### ISSUE TITLE
Reduce repetitive effort for common patterns

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1000]
Feature request from the UReport Global audit.

Flows they are authoring very frequently need to support many languages and have a lot of repetition. This pattern in particular is cumbersome:

```
Question, Quick replies, Yes, No
  => Save Response, Yes, No, Maybe
    => Other, Sorry I didn't get that, please say Yes or No.
```
Add this for every question, then localize in every language (the global account spans the world, so tons of languages). This results in hours of repetitive work they'd like to avoid.

Two ideas from the customer:
 * Node copy
 * Node library of preconfigured nodes

Creating this issue to solicit ideas and facilitate discussion.

**Comment by rowanseymour** [comment]
Copying a node sounds useful and relatively straightforward to add. 

Maybe support dragging with ⌥ ? 😎

**Comment by ericnewcomer** [comment]
Kind of hard to discover, but points for not introducing new ui elements!

**Comment by nicpottier** [comment]
Wonder whether node copy is actually enough, I mean if you are doing a whole other loop in there then that gets tedious.

Maybe a CTRL-C, CTRL-V that works when you have selected nodes? (IE, via drag?) That lets you copy whole blocks.

**Comment by ericnewcomer** [comment]
Don't hate the idea of a copied block. Agree the likely scenario is copying a bunch of neighboring nodes. Maybe it just needs a refactor menu `Push down into subflow` 😝

**Comment by nicpottier** [comment]
Ya, unintended consequence of this is monster flows for sure!

**Comment by ericnewcomer** [comment]
We discussed this a little bit on our call this week and I wanted to capture the sentiment here. Our discussion lead us to the thinking that the primary pain point sounds like localization. It may make more sense to build more robust localization tooling perhaps reusing common translations ala gettext inside of block copy.

**Comment by nicpottier** [comment]
Related: #1268

**Comment by ericnewcomer** [comment]
Added localization tooling. There's a separate issue for copy/paste
