### ISSUE TITLE
Add API endpoints to provision sub-orgs

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1002]
Would be useful for the whitelabel cases to allow the creation of a new sub-org via the API while also transferring a number of credits to it initially.

**Comment by rowanseymour** [comment]
What's the envisaged usage here? That a white-label has built their own management dashboard? Just wondering what white-label customers are asking for, and what might be missing in the UI we currently provide them.

**Comment by nicpottier** [comment]
Being able to provision accounts programmatically.. IE, automating this stuff instead of needing a person to go do it. Nothing new here except that it's an API.
