### ISSUE TITLE
Audit log of user activity

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1016]
Just looking at https://github.com/nyaruka/rapidpro/pull/2394 and wondering if it would be worth in the future moving to an audit log based approach for recording user activity. 

Obvious downsides of just having `modified_on`/`modified_by`:

- No record of what changed
- Record lost when db object deleted
- Sometimes we update `modified_on` but not `modified_by`

We'd replace that with something like...

| class | uuid | user | action |
|-------|-------|------|---|
| `contacts.Contact` | 2141-325325-23532 | bob@nyaruka.com | blocked |
| `contacts.ContactField` | 4262-3535351-35352 | jim@nyaruka.com | edited |

Trimmed in a celery task

**Comment by norkans7** [comment]
So we add a new model for this, that use the same event types as GoFlow for contact modifications?

**Comment by nicpottier** [comment]
Maybe, that could make sense. Note that this isn't something we have committed to doing which is why it has the "needs discussion" tag.

**Comment by norkans7** [comment]
Right, I was catching up on the goflow and mailroom just trying to understand how that could be done as you mentioned in https://github.com/nyaruka/rapidpro/pull/2545 and so far my assumption is that we focus only on contact changes only, i think this issue will consider more audit than that
