### ISSUE TITLE
Detect / Stop bot loops

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1018]
It is possible for RapidPro to get into a messaging loop with another bot (or even itself if you configure your channels just right).

We really want to detect these before they get out of hand as they can turn out to be costly to the customer (and not insignificant in server load either).

Problem is that it is slightly difficult to tell the difference between real behavior (especially with flow authors testing) and looped behavior. You really need to look at both sides of the conversation to know whether we are in a loop.

We also really want to avoid large DB queries looking at recent messages in the DB on every incoming message.

One idea is we could have an expiring redis set (named/expires every 5 minutes) with keys in it that were in the form: `contact_uuid:in_msg:out_msg` that we increment upon responding. In the case that the count is over 10 then we fail the message maybe? Feels like maybe we'd want to clear it in the case of sending something different too though which gets more complicated.

Need to think through various scenarios and solutions there.

**Comment by rowanseymour** [comment]
No solution but two additional thoughts:

1. I think most useful place to start here would be clearly defining what the signature of ping pong is. Maybe any back and forth of X messages in Y time is sufficient here regardless of message content? 
2. Thus far we've only experienced accidental ping-pong, do we need to also consider signatures of malicious ping-pong?

**Comment by nicpottier** [comment]
Ooh, I think 2) really frames the problem differently and in a useful way. In that we probably DO want to prevent malicious bots from just fucking with a RapidPro bot by sending different things over and over. That feels like more of a generic throttling infratructure or generic blocking functionality for contacts that are too damn chatty.

Problem is we've seen these loops be kinda slow in general terms, IE, 4 or 5 responses per minute. So we'd really want to be looking at total per hour or day? But then people are building even chattier bots with WhatsApp and the like (since messaging is free) so we may be running into that.

Maybe it is detecting when WE are being repetitive? IE, if WE are sending the same message over and over then it seems unlikely that anything useful is happening. Could still leave a door open for a malicious bot in a flow that is customizing say an error message but would cover the cases we've seen?

**Comment by nicpottier** [comment]
Ok, so a proposal:

In mailroom, before sending a message (in our `msg_created` hook) IF we are an interactive flow (IE, responding to something) THEN we use a redis function to look up in a 5 minute modulus map keyed by contact id the last message sent. If present AND the same message, then we increment the count on that record, if different then we reset it to 1. If the count we return from that is over 20 then fail the message immediately and never send it.

That hash should stay relatively small since it only lives up to five minutes, though in essence it will store every message reply we generate in five minute windows. I *think* that's ok. Say we handle 1M messages in 5 minutes, then in raw data that's say average 160 bytes for the message body, 10 bytes for a contact id plus 4 bytes for the count. So say 174 bytes per outgoing reply * 1M = 174,000,000 bytes, 175MB + overhead of the map. Say that is double then 350MB in Redis worst case. So not bad from that perspective. Guess worst case would be double that again since we generally store these in modulus named hashes so we store 9:59 minutes of data, not just 5 minutes.

This would catch most kinds of loops and spammy behaviors and is unlikely to trigger upon valid uses since it would require 20 identical messages to be generated in a five minute period with nothing else sent in between.

20 feels like a really low number but one of the examples we've seen of this was indeed a loop that was taking on the order of 15 seconds per loop. Again this would have to be the exact same message sent 20 times in a row with no other messages in between so I don't think normal behavior would trigger this often.

**Comment by rowanseymour** [comment]
Sounds good.. think we should try this and see how it goes. Ideally this functionality is well compartmentalised and easily tweaked without touching much of the msg sending code

**Comment by nicpottier** [comment]
Trying to think whether we could actually do this at the Courier level. I think the only missing piece for that would be Courier knowing it is a reply and I think it knows that since it has a `ResponseToID` on Msg.

Nice thing there is that it could create a channel log in the process saying why it failed that message.

**Comment by nicpottier** [comment]
So basically before sending a message that is a reply, it would do all the above and fail it automatically if it thinks its a loop.

**Comment by nicpottier** [comment]
Addressed in: https://github.com/nyaruka/courier/pull/254
