### ISSUE TITLE
Triggers are flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1023]
Recent ticket by Leah by someone who wanted a trigger keyword for people that weren't in a group, as well as any number of permutations of triggers around channels, words, group memberships and soon to be NLP classifiers had me wondering whether we could take a totally different approach.

What if we had two system flows that represented triggers for contacts active in flows and not active in flows?

The flow would have to have restrictions on it, basically couldn't send messages but could have a "start_session" action.

Mailroom would run the appropriate flow before handling any message and if the events that came back included a start_session event, then interrupt any other runs and start the contact in that session. We wouldn't necessarily record or start the sessions and runs created by these in the same way so as not to confuse things.

I think we would keep a similar UI as we have today for managing things for basic users but could let them opt in to instead having this kind of "trigger flow". Once they opt in then they are in charge of managing that flow, etc..

Advantages:

Allows for any kind of logic you want around interrupting a user out of a flow based on something they send. You can use NLP, webhooks, group or channel memberships etc..
As we add more things to flows triggers get more powerful too
Less logic, everything is a flow
Disadvantages:

Performance? I think if we limit the writing of these results then I'm not sure there's much of a performance hit, running a flow is very fast when you don't hit the DB
If we don't log due to performance, then figuring out why someone did something could get complicated. Perhaps we only log when we DO trigger which should be fewer times.

**Comment by johncordeiro** [comment]
That's a great idea! It's applicable in several use cases. I just can't visualize very well how it would work in the user perspective, if it would open flow when creating the trigger, or some other trigger types could be removed once we had this.

**Comment by ericnewcomer** [comment]
Really like the idea of everything is a flow! From a UI perspective, as @nicpottier said we can actually keep the same UI but with an escape hatch to edit the flow directly. We actually sort of already do that with the group join trigger. Abstracting triggers to a pre-flight flow feels pretty powerful and even jives with ideas around pre-flight flows for simulation.

**Comment by rowanseymour** [comment]
Ok well someone gonna have to be the pessimist here, can't have everyone being enthusiastic!

It is interesting that some orgs already do something like this - they have a very simplified trigger configuration and defer a lot of logic to a few "top-level" flows. So can't one sort of do all this already?

Is the limitation there that you can't refer a decision about interrupting contacts? Would we just need to add the idea of "passive" flows?

I think the complicated part here is that an entire org's trigger configuration is stored as a flow. That part feels fragile because any changes to that flow that we don't control result in a potentially unreadable configuration for the regular trigger UI. Are we thinking that once a user switches to manually editing the trigger flow.. there's no going back?

And if we're talking about this opening up new options on triggers.. do we mean adding those also to the regular trigger UI or forcing people to go the route of manually editing the trigger flow? If the regular trigger UI needs to keep up with everything the trigger flow can do.. the whole "everything is a flow" starts to feel like less of an actual win.

Worth noting that in the current case of a "group join" trigger, it's just a wizard that generates a regular flow and it becomes a regular trigger that points to that flow.

**Comment by ericnewcomer** [comment]
My understanding is that the entire trigger configuration is not stored as a single flow. Instead it would be a series of flows that are evaluated up until the point a start session is fired. The real change from what is happening today is that the keyword evaluation would be embedded in a flow as well.

**Comment by rowanseymour** [comment]
Ah ok that makes more sense - two flows for each trigger! I was taking the "everything is a flow" thing a little too far 😬

I guess I'm still stuck on the fundamental question... do we actually need/want triggers to be more complicated, or can we find ways to move complexity down to regular flows?

If we introduced the concept of passive flows, would that cover the possible use cases? Because at least then you could defer a decision about whether a contact is interrupted until a start_session action. 

@johncordeiro is there something stopping you from implementing the example in https://github.com/rapidpro/rapidpro/issues/832#issuecomment-523173150 as just a regular flow that then calls start_session actions?

**Comment by nicpottier** [comment]
So the idea here isn't fully formed but yes, I was actually thinking of this as a single flow. We would rebuild that flow (in the typical case) whenever a trigger is edited. It has a set of splits, likely one per trigger (though really may be closer to two splits for a group membership and keyword trigger case) and we run through the entire flow seeing if it spits out any flow starts.

In the case where the user opts into "advanced triggers" or whatever, then that flow becomes something they can see and edit and the normal trigger UI disappears.

That's just an idea though.

I fee like one flow per trigger is both a bit scary from a performance perspective (yes, flow running is fast and cheap but maybe not 100s per incoming message cheap) and it doesn't address the idea that you may have triggers that are co-dependent / ordering etc.. IE, I'm not sure the gain in functionality there is quite worth the cost of doing it all.

A single flow that is run to figure out if a trigger is fired is unambiguous in its ordering and execution, and can represent almost any logic the user may want.

To your question Rowan about how this isn't addressed with current functionality or why this isn't just a passive flow, I think the answer is that that's basically the same thing. Remember though this would have to be a passive flow that is run /for every incoming message/ even when a contact is already in a flow. That is after all one of the primary use cases for triggers is to spawn new flows regardless of whether someone is already in a flow.

Yes a current catch-all trigger could be used to implement all this, but that only works if the user is not already in a flow. We are trying to address the other use cases here.

I think the other aspect to consider is the pollution of the contact history that takes place if we are running these are normal flows, creating runs and sessions etc.. For every incoming message you would see the flow start and end etc, if we treated these as normal flows.

But really that idea is basically the same one I'm proposing, just that that flow is run for every message and that we store its results / history / logging differently.

Other gotchas we would have to solve:
  1. How does this work with channel events? IE, how does this concept map to incoming calls, facebook follows etc.. 
 2. What does this do to the current concept of triggers? Does `trigger.keyword` still exist? Does that just turn into a `parent.result` like item? Or do we map those over? In a way not having triggers at all and just having `parent` is appealing but not sure that always works.

**Comment by johncordeiro** [comment]
> Ah ok that makes more sense - two flows for each trigger! I was taking the "everything is **A** flow" thing a little too far 😬
> 
> I guess I'm still stuck on the fundamental question... do we actually need/want triggers to be more complicated, or can we find ways to move complexity down to regular flows?
> 
> If we introduced the concept of passive flows, would that cover the possible use cases? Because at least then you could defer a decision about whether a contact is interrupted until a start_session action.
> 
> @johncordeiro is there something stopping you from implementing the example in [#832 (comment)](https://github.com/rapidpro/rapidpro/issues/832#issuecomment-523173150) as just a regular flow that then calls start_session actions?

As Nic said the current functionality doesn't support that, as the main problem is when the user is already in a flow. The only way to do so in the current functionality is by setting up many rules in all `Wait for Response` nodes and then call a `start_session` action to move to a different flow.

A very simplified flow with no runs or sessions seems to be promising as the only way in the current functionality to know if a flow was triggered or not for a specific contact, is by looking to his conversation history. It wouldn't change.

For the Nic questions:

1) Don't you think that we could keep the existing triggers available (not editable), and this new one could be a kind of `Advanced Trigger`, which is a new type? (even if internally some other triggers are flows in the same way and some are not as `Incoming Calls` and `Facebook Follows`).

2) If we use the concept explained above, `trigger.keyword` would still live and for `Advanced Triggers` the `parent` can be used.

**Comment by rowanseymour** [comment]
Ok have thought about this a bit more.. and we really aren't arguing for very different things.. just how these things are surfaced.

Triggers internally could become internally very simple things which are essentially hooks for channel events (counting an incoming message as a kind of channel event here), i.e.

* incoming message
* incoming call
* missed call
* new conversation

NB. I'm pretty sure this is how Twilio Studio defines a trigger
NB. obviously you can only have one of each trigger type

Each trigger can be configured with two flows, started depending on whether the contact has a waiting session:

* Has session: a passive flow.. can do whatever besides send/receive messages
* No session: any regular flow

In the "has session" case, we complete a session for them in the passive flow. If it generates any `start_session` events we handle the last one and start them in a new session which interrupts their waiting session. If not, we resume their waiting session.

Users have two options, either:

1. Have a single "incoming message" trigger and you're in charge of triggering whatever way you want in those two associated flows. Note that besides one of these flows having to be "passive".. these are still regular flows.. edited only in the editor.
2. You continue using keyword and catchall triggers thru the trigger UI.. but behind the scenes we combine and save those as a single "incoming message" trigger with two system flows (regular flows, just not visible to the user).

Where it gets weird is that the `start_session` actions.. could start other contacts besides the contact from the trigger 🤔.. and right now doing a `start_session` for the current contact is kinda awkward.

**Comment by nicpottier** [comment]
This came up today on a call as a way to detect and deal with messages that may be asking for help / seeking assistance even if someone is already in a flow. Either using a split by and keywords or NLP could let people either open a ticket or start a flow to send a message about resources they could access for help. @ericnewcomer also brought up that maybe this is one way of dealing with "pausing" of contacts that have open tickets in that this flow could mark a message as handled and not needing handling within a flow based on either ticket state or group membership etc, to deal with "pausing" contacts. (I think that last bit probably requires more thought, campaigns are the constant wrinkle in that simple idea of pausing)

**Comment by ericnewcomer** [comment]
Quite a bit different since it isn't handling an inbound message, but what if campaign event flows also had a pre-flight flow? Not sure I like that, but just a thought. This could allow people to decide if they want to skip campaign events and adjust contact fields if necessary, etc.

**Comment by johncordeiro** [comment]
@nicpottier it's very powerful, and as you said has many hidden opportunities like the pause of contacts in tickets and other stuff like changing the subject of the conversation, or create AI-based shortcuts for the conversation.
