### ISSUE TITLE
Filter error 

### ISSUE THREAD

**Issue by dhamadou** [rapidpro/rapidpro#1024]
Hi Rapidpro family,

When i try to launch Rapidro from my browser (Mozilla) on my Debian 9 virtual machine, i have this issue:

![Filter_Error](https://user-images.githubusercontent.com/22197925/63649232-102aa300-c733-11e9-8e98-892c66841c14.jpeg)

**Comment by rowanseymour** [comment]
I would check your version of `lessc`. On our prod boxes we're currently using 3.9.0
