### ISSUE TITLE
FB related triggers order - problem with ads!

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#1026]
# Description

Once creating a Messenger ad on Facebook it requests to set a welcome message and a quick reply text.
The problem is the order that RapidPro is processing the parameters isn't the best shape! And it's interrupting the contact's flow.
![image](https://user-images.githubusercontent.com/35577716/63950633-bb4c9c80-ca52-11e9-950e-1e2f95f57c41.png)
In the example above there was a *referral ID trigger* set to one flow and a *Keyword trigger* to another, a new contact interacted with the ad by clicking the Send Message button. At this point, the referral ID set in the ad should have taken the trigger action set on RapidPro but it doesn't!
Then the user hits the quick reply (or send any message) that triggers the Keyword action, that's totally fine! The problem is that it gets interrupted by the referral ID trigger that was in some sort of "hold" status before and interrupts the current flow.

This also happens if no referral parameter is set in the ad. FB just sends an "empty" value ref.

# Suggestion

Making RapidPro understand once a FB triggers actions by referrals *or* keywords and prioritize accordingly to the presence of each parameter only.

Or making available to *ignore referrals* on flows as exists for keyword triggers.

**Comment by WilliamTales** [comment]
# Aditional info

Using the new flow editor also results in the same problem but instead of interrupting the contacts' flow it marks as completed and the order is the opposite.
![image](https://user-images.githubusercontent.com/35577716/64029599-514bfa00-cb1b-11e9-9796-c7a43fbbc418.png)

The scenario in the image above is the same - a contact clicked the **Send Message** button present on the ad, got no response from the referral and send the keyword trigger.
In this case, using the new Flow editor lead us to a patch - setting the target flow with the *ignore triggers* option.
![image](https://user-images.githubusercontent.com/35577716/64030672-688be700-cb1d-11e9-87c9-e292a5734843.png)

But would be great to enhance the referral trigger on RapidPro to reach a solution for that order issue.

**Comment by nicpottier** [comment]
Can you share the channel logs (and the time stamps) for this? Curious on what the order of events is and the exact payloads.
