### ISSUE TITLE
Codebase update to v5.1.28

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1027]
Hey guys, we're about to start the development of many features for this project and I see that it's a little behind the [nyaruka/rapidpro](https://github.com/nyaruka/rapidpro) version. I would like to ask you guys to update this repository with the recent and stable version of RapidPro. Thanks.

**Comment by rowanseymour** [comment]
So we made a decision before releasing 5.0 to switch to more predictable process of releasing and versioning, which @nicpottier explains in https://groups.google.com/forum/#!topic/rapidpro-dev/1yrzuHUCFvw

What is in rapidpro/rapidpro currently is the last patch version of 5.0.x. What is in nyaruka/rapidpro right now is 5.1.x and is our own development/unstable version.. which by November 1st will be released as 5.2 and become the next stable release.

Anyone is welcome to work off nyaruka/rapidpro but we can't make any promises about how stable/unstable it is.. and you also need to keep all the other components (mailroom, courier etc) up to date.
