### ISSUE TITLE
New Editor's problems                                                                   

### ISSUE THREAD

**Issue by evelynbarros** [rapidpro/rapidpro#1028]
- There is no more "Start another flow". Using just the "Enter a Flow" that works as a "run a flow" when the flow is finished, it comes back to the previous flow, "start another flow" is important because we have the option to choose when we want to come back to the previous flow or not.
- "Has a phone number" only works using the country code. When we need to ask the user's phone number is more usual the people send just the local code.
- When there is a \ in the "send message" the rapidpro replaces it for \ / on the webchat. 
![Captura de Tela 2019-08-30 às 16 27 49](https://user-images.githubusercontent.com/46901674/64046862-6dfc2800-cb43-11e9-9555-3566620c4423.png)
- The new editor's connections are not working very well, it is so difficult to keep the flow clean and easy to understand.
- On the "Call Webhook" the rapidpro is not replacing the blank spaces for %20, so the requests have been broken.

**Comment by rowanseymour** [comment]
Don't think all or most of these are problems with the editor itself but let's unpack each one and if they are bugs they can become individual issues. 

The last one.. you have to explicitly call `url_encode()` if you are putting expressions into a URL. This is intentional because we don't know where in the URL you might be putting an expression and whether you want things like `:` and `/` being escaped

**Comment by rowanseymour** [comment]
The first one.. it's a bit awkward but you can use a _Start Someone Else In a Flow_ with the expression `@contact.uuid`. I think maybe we want to make it easier to use that action with the current contact.

**Comment by periclesJ** [comment]
> The first one.. it's a bit awkward but you can use a _Start Someone Else In a Flow_ with the expression `@contact.uuid`. I think maybe we want to make it easier to use that action with the current contact.

I've tried to use this approach but it not works, the same user still returning to the previous flow.

**Comment by rowanseymour** [comment]
_Start Someone Else In a Flow_ is a `start_session` action which generates a `session_triggered` event. Flow execution continues in the current sprint until a wait is hit.

When mailroom is handling the `session_triggered` event, it should trigger a new session (in this case for the current contact) which will have the effect of interrupting the current session. So it shouldn't be possible to return to that session, and if that's not happening then there's a bug in how we handle `session_triggered` events.

**Comment by ericnewcomer** [comment]
Also, if you want to start somebody in a flow and not have them return, why not just make that a terminal action in the parent flow? I don't see the need for the distinction there.

**Comment by ericnewcomer** [comment]
Please file specific issues for each issue so we can address them appropriately.
