### ISSUE TITLE
Start another flow doesn't create / save result of status

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1029]
From a user ticket, some users would prefer that a result is created with the status of the subflow upon exit of a subflow. (IE, completed or expired)

One option is obviously for them to save that result manually after the split but we could also add an advanced option to save the result value as well.

Logging here so we can track if others request.

**Comment by rowanseymour** [comment]
Could see this being option on the split. Wouldn't want to force it on all subflow splits cuz it's not usually a particularly interesting result (just completed|expired).
