### ISSUE TITLE
Allow WA message template placeholder values to be translatable

### ISSUE THREAD

**Issue by smn** [rapidpro/rapidpro#1030]
The current implementation of WhatsApp templates automatically selects the correct message template depending on the Contact's `Language` preference. However it doesn't allow the values for the message template placeholders to be translated. This works fine if the assumption is that the message placeholders are not language specific, like say an integer unit or a voucher code. 

<img width="1045" alt="Image 2019-09-09 at 11 03 35 AM" src="https://user-images.githubusercontent.com/1065/64517916-83b2df80-d2f1-11e9-9491-6ddd2926f97c.png">

<img width="1057" alt="Image 2019-09-09 at 11 02 24 AM" src="https://user-images.githubusercontent.com/1065/64517831-5ebe6c80-d2f1-11e9-8274-f98438d71c24.png">

<img width="1077" alt="Image 2019-09-09 at 11 04 07 AM" src="https://user-images.githubusercontent.com/1065/64517984-9fb68100-d2f1-11e9-80eb-6838ac2d8eba.png">

For  message templates where the values for the placeholders are language specific this is a problem. Currently the only work around I see is to duplicate the message flow for each language which is quite a burden.

**Comment by smn** [comment]
@nicpottier Any chance of getting this on to the roadmap for the next release?

**Comment by nicpottier** [comment]
@rowanseymour @ericnewcomer whats the LEO on this guy? We've heard this from other people as well and I think it may become more of an issue as WhatsApp ramps up again.

**Comment by rowanseymour** [comment]
@nicpottier not high on the engine side.. just need to side how `variables` are identified in the localization section. Everything we've localized thus far is a named property of thing with a UUID - e.g. the `text` property of a `send_msg` action which has a UUID

```json
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "send_msg",
  "text": "Hi {1} of {2}, are you ready to complete today's survey?",
  "templating": {
    "template": {
      "uuid": "3ce100b7-a734-4b4e-891b-350b1279ade2",
      "name": "revive_issue"
    },
    "variables": ["@contact.name", "@fields.state"]
  }
}
```

so for that to continue `templating` would need a `UUID`... or we try to make a "path" of the property

```json
"8eebd020-1af5-431c-b943-aa670fc74da9",: {
  "text": [ "Hi {1} of {2}, are you ready to complete today's survey?" ],
  "templating.variables": ["@contact.name", "@fields.state"]
}
```

**Comment by nicpottier** [comment]
We hand out UUIDs like they are candy so I think either would work. Maybe whatever is easiest / most consistent on the editor side?

**Comment by rowanseymour** [comment]
( easier on engine side to give `templating` its own UUID )

**Comment by rowanseymour** [comment]
( although that also feels like it warrants a migration so UUID always exists... )

**Comment by smn** [comment]
Thanks for looking into this. I'm happy to help but would need some pointers as I'm fairly out of my depth in these parts of the code. Let me know!

**Comment by ericnewcomer** [comment]
I think saying anything that is localizable must also have a uuid is a good line to draw. Given that, this shouldn't be a huge lift on the editor side. A migration framework for the new stuff is probably a prerequisite.

**Comment by rowanseymour** [comment]
Do feel like it would be less than ideal to do this without a migration.. seems like a nice simple candidate for our first new-engine migration... 13.1 🤷‍♂

**Comment by nicpottier** [comment]
Sounds like this isn't a 5.2 feature but something we can look at first thing after that release though.

**Comment by rowanseymour** [comment]
This is ready on the engine side.. just need to figure out #1091 first

**Comment by ericnewcomer** [comment]
See: https://github.com/nyaruka/rapidpro/pull/2648

**Comment by smn** [comment]
thanks all!
