### ISSUE TITLE
Support Facebook stickers (thumbs up) in flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1033]
Right now these get converted into images, but the raw payload is a sticker:

```json
{"object":"page","entry":[{"id":"arts","time":1568205260068,"messaging":[{"sender":{"id":"arst"},"recipient":{"id":"arst"},"timestamp":1568205259578,"message":{"mid":"arst","attachments":[{"type":"image","payload":{"url":"https://scontent.xx.fbcdn.net/v/t39.1997-6/arst.png?_nc_cat=1&_nc_oc=arst-arts-arts&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=arst&oe=5DF3C875","sticker_id":arts}}],"sticker_id":`}}]}]}
```

The sticker id for thumbs up seems to be consistently `369239263222822` and seems to be consistent:
  https://github.com/restfb/restfb/issues/666

Easiest way to deal with this may be to just convert it to a thumbs up emoji on the Courier side and them let people do what they want from there?

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/courier/pull/256
