### ISSUE TITLE
Add NLP models and connection flow (Django)

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1034]
Building on https://github.com/rapidpro/rapidpro/issues/832#issuecomment-512581458

This issue covers the following work:
 * Create `nlp` package. Add `NLPProvider` model which should be similar to `Channel` (IE, they are a generic model per provider, just have a config and type)
 * Add Django view pipeline do add NLPProviders for BotHub and Wit.ai to start. This should be accessible from account page and let you enter credentials for each, verify credentials then create the `NLPProvider` instance on your org. You can view previously connected providers and see the classifiers which have been synced with it by clicking through a connected provider. 
 * Add way of representing a `Classifier` asset. This is likely pretty high level and mostly contains a foreign key to a NLPProvider and a generic config dict. This is similar to the concept of `templates` in RapidPro. (https://github.com/rapidpro/rapidpro/blob/master/temba/templates/models.py#L10) Mailroom / Goflow / Editor will use these to show a list of available classifiers in a flow and to run the classifier during execution. `NLPProviders` should be in charge of syncing these on their own. (similar to how WhatsApp syncs templates: https://github.com/rapidpro/rapidpro/blob/master/temba/channels/types/whatsapp/tasks.py#L107)
 * Add API calls to get available Classifiers for the editor. Again, very similar to templates: https://github.com/rapidpro/rapidpro/blob/master/temba/api/v2/views.py#L3143

Note this issue does not encompass Mailroom / Goflow or Editor work, @rapidpro/nyaruka will take care of that.

This needs to be ready October first, at that point @rapidpro/nyaruka will take over so we can meet release schedule.

@matmsa27 is lead on Ihlasoft for this work.

@rowanseymour any additional comments?

**Comment by nicpottier** [comment]
@matmsa27 can you give us an update. We are going to have to take over this work starting tomorrow, if you can open a PR with any work you have completed thus far that would be appreciated, otherwise we'll start from scratch.

**Comment by matmsa27** [comment]
Hi @nicpottier , I still couldn't finish our part here on the Ilhasoft for this feature to be able to add NLP Providers to RapidPro. I have done a kind of introduction in the RapidPro code completing simples tasks, and started the development a few days ago with more consistency. Therefore, as we're starting in the project and we want to create regular code as this one, I would like to complete that until Friday (precisely 10/04/2019), to be able to finalize part of the feature, the structure to support the type of NLP Provider and viewing all NLP Providers.

**Comment by nicpottier** [comment]
Hi Mathes. Unfortunately we are already behind on this feature so we can't
lose another week. If you want to open a PR with what you have I'm happy to
start there but otherwise I will be beginning on this on Tuesday so we can
wrap this up on all sides by the 15th.

Hopefully you can help contribute on future features on 5.4

**Comment by matmsa27** [comment]
Hi @nicpottier , ok I got it. So, I'll open my PR until 12:00AM here on Brazil (UTC-03:00), it's ok? Thank you so much for you availability and transparency. Me and Platform team from Ilhasoft, we hope contribute a lot in the future with RapidPro.

Regards.

**Comment by nicpottier** [comment]
Sure, you can open a PR then and I'll see if there's anything to pull in but I've begun work on this.

**Comment by matmsa27** [comment]
Hi @nicpottier , I open my PR [here](https://github.com/rapidpro/rapidpro/pull/1045). If you can use something of what I did, I'll feel very grateful and happy to have contributed. Thanks a lot.

Regards.

**Comment by nicpottier** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/2550
