### ISSUE TITLE
Can't delete label used previously in message export

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1037]
Either need to change label deletion to be soft (set `is_active=False`) or clear labels on export objects.

https://sentry.io/organizations/nyaruka/issues/1232346248/?referrer=alert_email

**Comment by rowanseymour** [comment]
I think the fix here is making deletion soft.. @nicpottier @ericnewcomer ?

**Comment by nicpottier** [comment]
Agree that label deletion can be soft. May need some tweaking to label creation then to make sure that we are doing the right thing there.
