### ISSUE TITLE
Ignore common "utterances"

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1042]
User request / idea. Having a way to have a trigger be set up to basically "ignore" a message. Their idea is basically that some "utterances" are uninteresting alone `ok`, `uhuh` and therefore they want to configure their entire system to ignore them.

I'm not sure this is useful and sounds like a confusing thing for a user to figure out but logging here in case it comes up again.

**Comment by nicpottier** [comment]
Part of the desire here seems to be to perhaps ignore certain thing at particular rulesets, maybe not moving on because of them. Part of it also seems to be people growing tired of adding many repeat rules for things they see often. So answer may be something very different than "ignore keywords".

**Comment by rowanseymour** [comment]
I think if the intention here to allow more humanlike conversations... that is probably requires more than just ignoring some words to really get right. You can imagine exchanges like:

```
RapidPro: "what is your favorite color?"
Contact: "umm"
Contact: "mauve"
Contact: "no sorry red"
RapidPro: "red is a nice color"
```

Where actually you need RP to behave like a human and not respond until there's a pause in the input from the contact... and then act on all the input it has received to that point "umm; mauve; no sorry red" and understand that as red.

**Comment by nicpottier** [comment]
Right, almost makes you wonder if that could be made to work NLP models for everything. IE, you just wait 20 seconds after the last message you have received then shuttle everything off to a classifier.

**Comment by nicpottier** [comment]
Could very painfully make this happen with timeouts once we have NLP actually.

**Comment by rowanseymour** [comment]
Yeah you'd want something like a router that loops back into itself.. consuming multiple inputs until it gets a match... or activates its timeout after X seconds.
