### ISSUE TITLE
Single message deletion

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1048]
We offer a way to delete unhandled messages (by first archiving from the inbox), but there is no way to do this for messages that were handled by a flow.

The primary issue raised by a customer is that sometimes their contacts send sensitive information that they would like to remove from the system.

I understand that handled messages are part of flow runs (and sessions), so deletion of individual messages would change history. We already support deleting entire runs (which I think would have to be the prescription in this case), however the inbound message still can't be deleted since "Flow" messages on the messages pane can't be deleted.

**Comment by rowanseymour** [comment]
Assuming msg.visibility was set to deleted, then we could still show those in the contact history as "redacted" msgs.. so you know there was a msg there.
