### ISSUE TITLE
Server does not support Surveyor app

### ISSUE THREAD

**Issue by hamedsafari** [rapidpro/rapidpro#1049]
I have version of 5.0.9 of rapidpro. My surveyor app version is 13.1.0
When I want to submit a pending flow from surveyor app it tries to send a request to /mr/surveyor/submit but the problem is that rapidpro server gives 404 not found error.
How can I deal with this problem ?

**Comment by rowanseymour** [comment]
If you're running v5 of RapidPro then you need to be also running [mailroom](https://github.com/nyaruka/mailroom) and configure nginx or whatever web server you are using to forward /mr/* requests to mailroom.
