### ISSUE TITLE
Test SMTP settings when being set

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1053]
A common problem people have is that they set incorrect SMTP settings on their account. We don't do any validation of their settings when they set them up, so they don't know if they made a mistake. We should try to connect to the SMTP server to check credentials, perhaps even sending a test email to the admin to validate everything is right.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2574
