### ISSUE TITLE
Change Facebook Connection Model

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1054]
Currently we require new Facebook channels to essentially create a Facebook app to automate the messaging of pages etc.. We did it this way so that abusive pages wouldn't hurt the reputation of the master app.

Facebook seems to be cracking down on this, specifically in requiring apps that need all permissions (such as reconnecting a page's webhooks) to submit a login/password to the app so that they can validate how the app works.

This points to us instead creating a per-installation Facebook app which then uses standard Facebook authentication points to grant access to that app for the pages that want to automate messaging.

To start out with this would likely be an ADDITIONAL way of adding Facebook, not entirely replacing the old way, though probably makes sense to always keep the other for special cases.

**Comment by IanLawrence** [comment]
I assume this would allow for the automated creation of bots for clients which is interesting for us. Is this being actively worked on?
