### ISSUE TITLE
Classifier dependency not honored on delete

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1057]
1) Create a classifier
2) Reference that classifier in a flow using split by intent
3) Delete classifier

Expected behavior would be to list the existing dependency and disallow deletion until that reference is removed.

**Comment by nicpottier** [comment]
I'm not sure Goflow is actually returning classifier dependencies yet, @rowanseymour ?

**Comment by rowanseymour** [comment]
Well darn almost.. let me fix that...

**Comment by rowanseymour** [comment]
Ok fixed in latest mailroom!

**Comment by rowanseymour** [comment]
Have verified this was fixed via https://github.com/nyaruka/goflow/pull/783
