### ISSUE TITLE
Email Details on Simulator Breaks with large inputs

### ISSUE THREAD

**Issue by mattcrum** [rapidpro/rapidpro#1061]
I think there's an outlier case I found that may be a bug.
I was testing to see if the send email feature would work with formatted HTML. I clicked the simulator then went to check the contents of the email that was going to be sent and it is so long that you can't scroll down or click off the window or anything. The only solution is to reload the page. I'm assuming this isn't an expected response and figured I'd share it here.

Reproduce: 
- Create an action that sends an email
- Fill the response with a large amount of text
- Run simulator and click the link of the expected email output.

![Photo-a-Day](https://user-images.githubusercontent.com/1972117/67316962-fc9b7e80-f4ce-11e9-9b72-a4bdaf81e167.jpg)

**Comment by rudigiesler** [comment]
Probably related: https://github.com/nyaruka/floweditor/issues/15
