### ISSUE TITLE
Entity-only NLU classifiers

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1064]
We can wait and see if this becomes a thing people need, but I wanted to add this wit app...

<img width="711" alt="Captura de Pantalla 2019-10-25 a la(s) 09 16 21" src="https://user-images.githubusercontent.com/675558/67578532-3d320c80-f708-11e9-8879-42741bc61732.png">

But no dice...

<img width="615" alt="Captura de Pantalla 2019-10-25 a la(s) 09 17 46" src="https://user-images.githubusercontent.com/675558/67578576-56d35400-f708-11e9-8459-31e4d9d729ea.png">

On an engine level.. it theory it would work fine with the existing `call_classifier` action/router.. but you'd have just _Other_ and _Failure_ exits, and then you'd have to access the entities as expressions

**Comment by nicpottier** [comment]
Ya, this was an explicit decision. Don't know if it is the right one necessarily but seemed to make more sense given how we talk about intents in flows etc.. It could probably use some documentation though.

**Comment by rowanseymour** [comment]
Yeah I remember us saying we should get intents working working first - just seems like something people could want at some point. Especially coming from wit.ai where the intent is just special entity.

And I thought it could work as is - but no - you would need a different rule.. cuz currently `has_intent` is what creates the result with the entities, so if you don't match an intent, you don't get entities.

**Comment by rowanseymour** [comment]
Also seems you can make it work by just adding an intent called _None_ and then a rule like `has_intent("None", 0)` in case anyone really needs to do this.

**Comment by NelsonGNP** [comment]
Hi @rowanseymour, I'm trying to add the wit classifier but I'm facing the same issue that you reported. I tried to add None as an intent but it didn't work. Could you explain where should I add it? Thanks in advance

**Comment by rowanseymour** [comment]
@NelsonGNP you should be able to add it to the wit app no?

**Comment by NelsonGNP** [comment]
That's what I currently have:
![Intents](https://user-images.githubusercontent.com/39569804/87482037-02119980-c607-11ea-981c-21bdf411e3ef.JPG)
![Entities](https://user-images.githubusercontent.com/39569804/87482045-063db700-c607-11ea-89b4-299402374afe.JPG)

**Comment by NelsonGNP** [comment]
appreciate it.

**Comment by rowanseymour** [comment]
@NelsonGNP I've updated RapidPro to match the latest wit.ai API.. please confirm you can now add your wit app. You will still have to add an intent.. but you can just add one called None

**Comment by NelsonGNP** [comment]
Thanks @rowanseymour !! I'll test and get back here asap

**Comment by NelsonGNP** [comment]
Just tested, all good now @rowanseymour!! Really appreciate your help.
