### ISSUE TITLE
Schedule trigger update form broken after contacts validation failure

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1070]
<img width="361" alt="Captura de Pantalla 2019-10-28 a la(s) 15 57 41" src="https://user-images.githubusercontent.com/675558/67717447-b8f7b780-f99b-11e9-9aaf-151377145783.png">

Can't enter anything in the omnibox and have to re-load the modal. Also if I set the repeat period to _Never_ at the same time, the week day selection widget re-appears

**Comment by nicpottier** [comment]
if easy while you are in there @ericnewcomer
