### ISSUE TITLE
Per contact timezone support

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1074]
Contacts should have a timezone field which can be set within a flow (or in the UI).

That timezone should be used when calculating campaigns and scheduled events. (the latter is rather complicated sadly)

**Comment by nicpottier** [comment]
Maybe we could simplify this by not supporting per contact timezones for schedules, but that seems likely to be confusing. Not sure how we would handle this short of creating 1 schedule per contact in a group for the exact time that contact should be fired. Could try grouping by timezone (maybe leveraging starts via queries?) but that sounds even more complicated.

**Comment by rowanseymour** [comment]
Oddly the engine is a bit ahead itself here. Contact has always had a timezone field accessible in expressions:

```
@contact.timezone
```

And there's an action to change the timezone:

```json
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "set_contact_timezone",
  "timezone": "Africa/Kigali"
}
```

**Comment by nicpottier** [comment]
Ya, we knew this was something we wanted to do. Sadly that's the simplest part. :(

**Comment by rowanseymour** [comment]
Does feel like a scheduled trigger and a campaign event.. are very similar things. Can we make `EventFire` work for both?
