### ISSUE TITLE
Infer URN contact searches

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1081]
Currently if you do a search for something like `tel:12065551212` that won't end up matching anything because we turn that into a search against the name.

Would be nice to detect things that look like URNs and convert them into the appropriate URN query. IE: `tel = "12065551212"`

This would be especially nice as some people use `@contact.tel` as a query in a Start Flow action based on a query and that doesn't work.

**Comment by rowanseymour** [comment]
Side note: any change to contact queries does get one wondering if we can have mailroom do all the contact query stuff so we don't have to keep two implementations in sync. I think that would just mean mailroom having a search http endpoint and a redis task to re-evaluate groups for a set contacts.

**Comment by nicpottier** [comment]
Ya I think that makes sense in general, added as a separate issue here:
  https://github.com/rapidpro/rapidpro/issues/1085
