### ISSUE TITLE
Two factor login

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1083]
Various people have asked about having two factor logins for RapidPro. Wouldn't be super hard to implement TOTP tokens I don't think.

**Comment by rowanseymour** [comment]
But it has to be implemented as a flow 😄

**Comment by matmsa27** [comment]
Hi @nicpottier and @rowanseymour , I have an idea and solution to implements this issue.

We think of two-factor authentication for Rapidpro using google authentication for example. The operation would be simple:

- The user performs the login;
- After login, Rapidpro asks for a two-factor authentication code using google authentication;
- The user enters a 6-digit code, so the Rapidpro backend validates and releases access for the user.

Of course, this two-factor authentication via google authentication, for example, would only be used if an org administrator or a super admin enable two-factor authentication for the user. It can be an option on the user at the endpoint of `org / manage_accounts /`

There is a [library](https://github.com/Bouke/django-two-factor-auth) to use two-factor authentication with google authentication, and we would need to adapt Rapidpro for that. We can configure whether authentication can be via QR code or a 6 or 8 digit.

We can discuss more it, if you think it's ok, we can develop it, just give us permission.

Regards.

**Comment by nicpottier** [comment]
Sure if this is something you want to tackle that would be useful. Make sure it works with any TOTP token generator, not just authenticator. (IE, Authy and the like)

**Comment by matmsa27** [comment]
Yes, I agree with the terms. With this [lib](https://django-two-factor-auth.readthedocs.io/en/stable/) we need to configure on the project, and overwrite some views from the lib. These views are responsible to enable with the user will login with two factor login or not.

We have tested the lib with these all applications to make login with TOTP protocol.
- https://play.google.com/store/apps/details?id=com.salesforce.authenticator
- https://play.google.com/store/apps/details?id=oracle.idm.mobile.authenticator
- https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2
- https://play.google.com/store/apps/details?id=com.azure.authenticator

There is a point to discuss:

1) Maybe are interesting set a value to SESSION_COOKIE_AGE on settings_common with two factor login

Thanks, for all.

**Comment by rowanseymour** [comment]
@matmsa27 can you clarify about your discussion point? You mean like having a longer cookie age for 2FA logins?

**Comment by matmsa27** [comment]
No, I think for more security is recommend to set the short cookie age for 2FA login, what do you think?

**Comment by rowanseymour** [comment]
The default for `SESSION_COOKIE_AGE` is 2 weeks.. which seems reasonable to me. I think it's probably best to let each deployment decide if they want to override that.

**Comment by rowanseymour** [comment]
I'm not a security expert and I'm not aware of the argument for 2FA logins having shorter expiration, but if there's a way to override it on a per-org basis, maybe org's could have the option to enable `SESSION_EXPIRE_AT_BROWSER_CLOSE` alongside 2FA.

**Comment by matmsa27** [comment]
Good idea, I think that point is a way to explore and bring more security.

Can we implement these steps and open a PR coming soon?

**Comment by rowanseymour** [comment]
Yeah let's get the 2FA stuff done and then we can discuss further ways to offer enhanced security. Looking forward to that PR

**Comment by nicpottier** [comment]
Just to add in here, session expiration times and two factor seemed pretty unrelated to me. Maybe shorter sessions make sense, but 2FA basically is just protecting fishing and other forms of password loss. There's no reason a 2FA session would have a shorter session than a normal session or vice-versa.

**Comment by matmsa27** [comment]
Yeah, two factor login and session expiration login are unrelated. I thought and suggested with two factor login a short expiration session bring more security, follow other platforms. In fact, to develop, they are not related, it was just an observation point.

After two factor implemented, I thought that is interesting we discuss the session expiration if you agree.

**Comment by hudsonbrendon** [comment]
Trying to implement two factor authentication in rapidpro, we verified that all the users' login and logout part comes from the django-smartmin app. In view of this, we need to change the login view of the app to check users and orgs that have two factor authentication enabled.

We also need a flag in the org and user model that will indicate whether both have two factor authentication enabled.

In summary, the steps are:

- In rapidpro, we will add a Boolean field in the org model and smartmin, we will add a Boolean field in the user model to enable two factor authentication in both;

- In rapidpro we will add a user list view for the org administrator to enable two factor authentication for specific users;

- Change the login view in the smartmin app to check if the user's org and whether the user has the two factor authentication flags enabled and redirect to the corresponding views after login.

**Comment by nicpottier** [comment]
So broadly I think `UserSettings` is probably where this configuration option belongs: 
  https://github.com/nyaruka/rapidpro/blob/master/temba/orgs/models.py#L2341

RapidPro users kinda predate custom users in Django but not sure it is worth switching at this point.

Smartmin could use some kind of callback / hook configured in settings to get required two factor information for a user object which RapidPro could implement using the settings object. That way no custom model is needed on the Smartmin side.

Note that there's a whole pipeline required for setup as well that needs to be addressed. We need to figure out how strict we want to be with these as well. IE, can you reset your password without OTP? (attacker with access to email has access to your account?) Or do we want to say even in that case you need OTP? What is the policy for people losing access to their OTP device? Do we hand out one time codes during set up?

If our primary goal is preventing phishing / key logging then allowing password resets via email without OTP is probably good enough.

I do not think we should tackle turning this on for other users but the logged in one to start. There's a whole set of crud that will have to be solved for that and it should be tackled afterwards. (IE, redirecting the user to a page after login, forcing them to set up OTP, etc..)

**Comment by rowanseymour** [comment]
We have two issues open for Two Factor but seems recent discussion has moved to https://github.com/rapidpro/rapidpro/issues/1207
