### ISSUE TITLE
Syntax for searching by group membership

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1086]
We don't currently have a way to use group membership within a search, searches can only be on attributes or fields of a contact.

This is a shame for a few reasons:
 * there are plenty of use cases where someone may want to say something like: "all peeps in this group who are female"
 * the target contacts for starts and broadcasts could all be represented as searches, which would be nice. (suppose there are downsides here too we would have to reassure ourselves of, such as possible drift or overall dependence on elastic)

Now one possible approach here is to say there is no such thing as a manually managed group, people should create fields to represent group membership, which then obviously lets you do this. Not sure that is user friendly but should be considered.

For the record, our elastic index already has the information needed on this front.

**Comment by nicpottier** [comment]
(one use cases here is targeting say all U-Reporters that have a WhatsApp URN)

**Comment by nicpottier** [comment]
I think we should try to target this for 5.4, as it is pretty compelling. It also would help address problems of excluding whatsapp contacts from a flow start which we know is a needed feature.

**Comment by nicpottier** [comment]
@rowanseymour any thoughts on syntax?

**Comment by rowanseymour** [comment]
One thought is that we've kept `groups` as a reserved word all this time - you can't have a contact field called `groups`. So that gives the option to introduce it as a lefthand side value.. and maybe re-use the `has`/`~` comparator, e.g..

```
name ~ "Bob" and age = 12 and groups ~ "U-Reporters"
```

**Comment by nicpottier** [comment]
Ya, I like that.

**Comment by nicpottier** [comment]
Do we allow `!~`?

**Comment by rowanseymour** [comment]
No but no reason we couldn't if that can work in ES

Maybe time to start moving on https://github.com/rapidpro/rapidpro/issues/1085

**Comment by rowanseymour** [comment]
Having just added support for `urn` in queries, it does make me wonder now if the syntax should match that, i.e. we have...

`urn = XYZ` → the path of any URN is equal to "XYZ"
`urn ~ XYZ` → the path of any URN contains "XYZ"

so the equivalent would be...

`group = XYZ` → the name of any group is equal to "XYZ"
`group ~ XYZ` → the name of any group contains "XYZ"

`urn` represents "any URN" and `group` would represent "any group". This is different to what I proposed above where `groups` means all groups and `~` becomes an array operator.

**Comment by nicpottier** [comment]
Not sure how we plan on expanding these, but one thing to note is that our indexes know only group UUIDs, not names. So we would have to do the expansion of name to group(s) before we get to ES.

**Comment by nicpottier** [comment]
Just revisiting this as we do want to get this into 5.4. I do think we should start with the minimal thing here. And I don't really see great utility in allowing substring group searching in general. So I would definitely lobby towards supporting `=` only by name.

Note that there is some fragility to this in that the group has to exist at query time, but I suppose that's no different than the fragility around field keys currently.

Since this is top of mind, we also will want to disallow creation of dynamic groups in queries that use `group` otherwise we could get ourselves in trouble. People that want compound groups like that can do so using fields anyways. 

This syntax's utility is mostly useful for specifying subqueries for flow starts. (IE, `all ureporters with an age > 18 in this district`)

**Comment by rowanseymour** [comment]
Yeah no worries about the `~`, I wrote that thinking we were doing that for all texty fields

One place this gets weird or cool depending on how you look at it, is that searching in the UI is always based on a "base group", so a group is already implicitly part of the query. If you are viewing the page for the U-Reporters group, and you're implicitly including `group = "U-Reporters"` in your query when you search from that page. So you could.. make that an explicit part of the query. When you go to that page, the search box already includes `group = "U-Reporters"`. That would certainly teach users about filtering by groups.

**Comment by nicpottier** [comment]
Right. I think the other neat / terrifying bit here would be that all flow starts could be represented as a query. Which is nice from a single code path perspective. Same usual apprehension about Elastic staying in sync, but I guess in truth we haven't seen that be a problem yet.

**Comment by rowanseymour** [comment]
Just thinking about groups based on groups and that's such a non-starter since you could create group `A`   with query `group = B` and group `B` with query `group = A`... or you create group `C` with query `group = D` and then rename group `C` to `D`... and BOOM!

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/goflow/pull/870
