### ISSUE TITLE
Trim FlowRevisions

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1088]
We save flow revisions on every flow save, this can be in cases as simple as a user moving a box a few pixels to the right or be something like them adding a whole series of steps. That's great but we never prune them, and that table is a bit out of hand since it is pretty big. (a full flow definition per row)

There may be some need to have all revisions that have unique schemas for #1041 / FLOIP results, but at the very least we should be able to trim revisions that don't differ in schema that are say more than 3 months back or whatnot.

Needs exploration but this is something we need to address sooner rather than later.

**Comment by nicpottier** [comment]
So going to start tackling this.

Some thoughts:
 1. At a minimum it would probably be nice to save revisions for every unique schema. That is for every version that has a specific set of results returned. Perhaps these should be marked specially when created to make trimming / not trimming easier.
 2. Additionally, perhaps we treat this like DB backups of a sort. IE, for anything older than a week, we store one revision per day, but keep all revisions for the past week. This basically gives you "roll back in time" for a week but "daily backups" older than that.

1) implies walking every revision and figuring out the schemas.

TextIt currently has 2,921,872 revisions. 892,248 in the past 365 days. 105,000 in the past 90 days. 

So approach I'd like to propose:
 1. We trim to last 90 days / 25 more recent, whichever is smallest
 2. Add a `results_changed` flag to FlowRevision, populate for all remaining revisions. (basically are the results the same as they were in the previous? If not, then true)
 3. Trim all `results_changed=FALSE` revisions to the first of the day. 

How does that sound @rowanseymour @ericnewcomer @norkans7 ?

**Comment by rowanseymour** [comment]
Thinking back to previous discussions about FLOIP and wondering should we also store the results schema on the revision as well as the `results_changed` flag? Just thinking you're going to need a migration to call mailroom inspect endpoint and get the schema.. maybe it's worth keeping that around?

Could the editor indicate whether revisions are solely changes to `_ui` ?

**Comment by ericnewcomer** [comment]
My gut feeling is any annotation to the revision based on the diff would be best handled by the saving endpoint. Saves can backup at the UI level and they can fail as well. Having that annotation being part of the atomic save sounds less error prone.

As for which ones to prune out the gate, by date sounds a lot better than by number. One thing I do use revisions for is to check on what happened when I'm sleuthing. Missing what happened a week or two ago because somebody loves moving nodes around sounds unfortunate.

**Comment by rowanseymour** [comment]
Yeah inclined to agree with that. So then results changing sounds like a good proxy of is this change significant, but wouldn't the most useful measure be - did something outside of `_ui` change?

**Comment by nicpottier** [comment]
For sure, but I think that's probably too many revisions kept around. We do create revisions when moving nodes around, but most revisions are indeed just small tweaks to the flow or the creation of the flow that creates a zillion revisions as you create all the nodes etc..

The only real reason to look at anything beyond "1 per day" is the idea that we may want to understand the schema at that point in time. Honestly I'm kind of moving away from even that (see FLOIP comment) because I'm just not sure it matters that much in reality. Also unless people are adding / removing nodes that collect data at a crazy rate it is unlikely that we wouldn't catch a relevant revision in the "1 per day" windows
.

**Comment by rowanseymour** [comment]
> Honestly I'm kind of moving away from even that (see FLOIP comment) because I'm just not sure it matters that much in reality

Yeah I think keeping 1 per day (the last) for anything older than X days would be a nice simple place to start here. We can always tweak in future if we want to be more aggressive or smarter.
