### ISSUE TITLE
Unit Testing of Flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1090]
It would be valuable in large systems to have a way of automating testing of flows.

Perhaps something like you running a flow to completion and saving the resulting results and messages as a "test case" that gets automatically run after every edit. Lots of different ways to take that.

**Comment by rowanseymour** [comment]
On the similar theme to part of the discussion in #963..  I do wonder if the priority for testing shouldn't be something more system level. 

You could have org-level test cases which users create by providing:

1. A list of message inputs
2. A set of checks to be applied to the final contact state (has group, has field value, has sent message)

You could in theory implement the entire test as a flow.. where I/O is flipped... i.e. `send_msg` means _the test contact is sending this to RP_.

There's no initial state.. just messages similar to what we do for high-level runner tests in goflow. Could be good or bad.. every test is dealing with a virgin contact.. and has to go thru all the signup/registration flows. 

It includes triggers so users can discover where keyword triggers might be pulling contacts out of flows.
