### ISSUE TITLE
Flow migrations for version 13+ flows

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1091]
We currently have Python migrations which migrate a legacy flow up to 11.12 and separate functionality provided via mailroom endpoint to migrate a 11.x flow to 13.0.

However https://github.com/rapidpro/rapidpro/issues/1030 requires the introduction of a migration from 13.0 to 13.1.

As soon as https://github.com/nyaruka/goflow/pull/729 gets pulled into mailroom, its migrate endpoint will start returning 13.1 flows... but RP doesn't know about 13.1.. so I think maybe it needs to take a `max_version` param so we can get mailroom ready to migrate to 13.1.. but not before RP has been updated.

On the RP side, we need to update the definitions endpoint to migrate definitions to 13.1 at the same time as updating the editor to write 13.1 flows.

**Comment by nicpottier** [comment]
Just to be clear, when you say RP above we are really talking about the editor ya? Is there anything else in RapidPro that cares about 13.0 vs 13.1?

Agree that a max version is probably the only sane way of dealing with this and sounds sane enough.

**Comment by rowanseymour** [comment]
Well RP has to serve the editor a flow in 13.1 format so.. I think anywhere we're calling `Flow.ensure_current_version` needs to migrate new flows as well as old flows (API, exports)

**Comment by nicpottier** [comment]
Understood, just making sure there's nowhere in RapidPro that we are actually dependent on flow versions at all since we don't introspect in any way. (save for metadata and dependencies I suppose)

**Comment by rowanseymour** [comment]
We now edit, save and run 13.1 flows
