### ISSUE TITLE
Share channel across sub orgs

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1092]
A common problem for UNICEF country offices is to have only one shortcode available but many different programs that want to use it. Currently the only way to do this is to grant many people to the same account, then try share a single organization across them. Obviously this doesn't scale well.

This is a common enough thing we should see if there is anything we could do that would allow say a channel a parent org to be conditionally shared / exposed on child orgs.

We tried doing this a bit using clover, which sat in front of RapidPro and routed traffic but it really doesn't know enough to do a good job of it, to do this right it needs to exist within RapidPro.

One super fast shwag at how we could do this:
 * a parent org could expose a channel to a sub org, that channel then appears on the sub org
 * keyword triggers then have to be unique across orgs that share channels
 * incoming messages are routed first by keyword if appropriate (if not in session ignoring), then by active session, then to parent org.. that is all out of-flow message gets delivered to parent org
 * when starting a flow, same rules apply about interruptions, active flows etc, except that applies across all shared channel orgs. That is, if you don't say interrupt when starting this flow and another sub org sharing that channel has that contact active in a flow, then the contact won't be started. (don't see any other way of doing this)

Challenges:
 * the flow starting behavior especially may be confusing. This can already be confusing for users though, so maybe having more of a flow start pipeline that summarizes active contacts, contacts who have already been in flows, etc.. could address this.
 * how does this interplay with orgs being anon? do all sub orgs also need to be anon if the parent is anon? (feels like they would? is this still useful if that's the case?)
 * from a technical perspective there's a million pitfalls and challenges, everything we have always done has been org centered.

@rowanseymour @ericnewcomer @norkans7 thoughts?

**Comment by rowanseymour** [comment]
Best I can offer thus far is this jumble of thoughts... from an implementation POV, I wonder if it wouldn't be easier to say 1) parent org adds a regular channel 2) sub orgs add a ??? (can't think of a name) channel which is child channel to that parent.. with a new role.  

 * Might make it easier to be selective about which suborgs are really sharing the channel
 * Let's us finish up with a message object which only references stuff in its own org (for some reason data spanning orgs makes me nervous)
 * Separate channel stats and logs...

The tricky part seems to be having courier allocate a message to a suborg without courier having to know about mailroom things like sessions and triggers. 

 * Could courier create a message with a null org and then mailroom knows that part of its routing job for that message is setting the org?
 * Should this routing be separate thing which courier does understand.. like just a start of keywords configured on each child channel (arguably annoying to have to configure the same keywords in two places.. channels and triggers)

**Comment by nicpottier** [comment]
Do agree that ya, maybe having the channel / channel log belong ONLY to the parent org but then have some new type of channel thingamabob may make more sense.

I like where you are going with the msg not having an org, though msgs are tied to channels, which are in turn tied to orgs so I wonder how that would work. Maybe the message always comes in the parent org/channel, so totally normal courier behavior there, but then mailroom dupes the message somehow from the parent to a child (and then handling is as normal?). Would be a duplication of every incoming message but maybe that's not so bad? Complexity of handling would be centralized to a single mailroom path where it does the check, duplication and task queueing.. Question is whether the original message on the parent org/channel appears there still..

Outgoing is another thing of course and even just the msg side of that is complicated. Does courier know about the suborg channels and send using them? Or do we duplicate outgoing messages the same way as incoming and hand them off to the parent instead? (that sounds yucky)

Whatever we decide we should also prioritize a method that lets us have logs visible to users so there is some way to reason about what has happened.

Not simple.

**Comment by nicpottier** [comment]
Having courier not know about any of this would be nice, or to put it another way, it would be nice if we could focus the complexity either on courier or mailroom, but hopefully not both. Seems like mailroom has to know about this stuff no matter what from a flow starting perspective so a solution that leaves courier totally out of this would be nice.

**Comment by nicpottier** [comment]
More spitballing..
 * sub org channels have a parent (across org boundaries) to the "real" channel
 * incoming messages are handled by courier at the parent channel level
 * mailroom when handling a message from a parent channel, figures out if it needs to be reassigned to a child channel instead and updates org / channel if so. (creating channel log that it did that in the process)
 * maybe courier understands parent channels? so whens ending from a child channel does the right thing? (trying to avoid having msgs in one org tied to a channel in another)

Are we willing to say a message belongs to one org but has a channel in another? Would that simplify things?

**Comment by rowanseymour** [comment]
I don't hate the idea of mailroom just cloning the message.. no weird orphan messages. So if mailroom decides the message should go to a sub-org, it just marks the parent-org msg as handled, creates and handles a new message for the child. Courier wouldn't do anything differently.

Re-assigning org/channel could also work.. but I think we'd want to get strict at a db level around when that is allowed, e.g. it's only for PENDING messages, and those never appear in the UI, exports, API endpoints.

Every time I think about data being shared across orgs I do think `CASCADE`! but.. I dunno.. does seem useful to minimize that.

**Comment by norkans7** [comment]
As I heard for the user saying it is for organizational purposes,

I think in that setup we can enforce somethings like the channel are on the parent only, contacts and messages can be entirely on the parent too
I think all messages on the channel, contacts  can be seen from the parent org

Flows, groups, campaigns can be in the sub org(some type of org) ONLY
users can be added on the sub-org

Contact can be borrowed by sub org when interacting with it, messages have a way to be mirrored on the sub org

**Comment by norkans7** [comment]
May be the new type is called "Workspace" and each org can have a workspace by default, so in this case we are adding new workspaces to be able to share a channel from the org

**Comment by nicpottier** [comment]
Ya, so to Norbert's point it is useful to explore / decide what we are doing here.

One possible approach is to not change the org model at all, but instead try to create per-flow permissions. That assumes a shared contact then obviously, so shared fields / groups etc, but maybe only certain groups of people can edit certain flows etc.. Kinda introduces a whole user management structure that sounds a bit nuts but maybe that's less nuts than shuffling messages around orgs?

The downside there is that obviously fields and groups are then shared and it is easy to see people walking over each other, and possibly destructively. IE, remove from all groups is no bueno. The contact history also becomes a view into everyone's data, exports are across everything etc as well.

I guess I'm not *positive* that is undesirable but it sure seems like it would be. Perhaps we need more input to know for sure. We do know that say for the one case we have done this (U-Report Nigeria and U-Report 24/7) they very much wanted things separate, not for the least reason that they wanted two U-Report dashboards, so org level API access across a single org wouldn't have really worked. (well I suppose it could have if they had prefixed all fields / groups etc, but still would have been confusing)

If generally feels to me like having a totally separate sandbox is the more correct approach, IE, contacts, fields, groups are never shared. (and maybe not messages either)

**Comment by norkans7** [comment]
In this case I thought contact history could have "contact moved to other sub org" everyone knows they share the channel so that is okay to see on the contact history I guess, the groups can be per workspace and not 

triggers, channels are the things that can be shared on the parent org 

Or may be we need a new model that can contain orgs, channels and triggers and manage 
It can manage triggers assigning them to org (guess that is 'clover' move to Rapidpro)

This way user management stays as is

**Comment by ericnewcomer** [comment]
My gut says a new channel to represent this feels like the most natural fit. So, the sub-org sub-channel that is linked in some way to the parent channel. We should endeavor to not break the wall between orgs (save for org.parent_id and now perhaps channel.parent_id). This implies all inbound is sent to the parent channel (which is then duplicated on the appropriate child) and outbound is sent by the child channel.

For another fun thought experiment, we discussed the inbound trigger system being a flow, with the appropriate (perhaps specialty) actions, could we address this as a component to that feature?

**Comment by nicpottier** [comment]
Other random thoughts that may guide our decision:
  * channel rate limiting on the sending likely wouldn't work unless we had the parent channel send. IE, if you are limited to 10 msgs/s then having children coordinate sending would be difficult
 * related would be prioritizing reply messages appropriately in the same scenario. IE, child channels should have their replies go before bulk messages of a sibling or parent

Both of those suggest that physical message receipts and sends happening at the parent channel.

**Comment by nicpottier** [comment]
So one thing is maybe there is no way to really have courier not know about this. Problem is that courier is not only dealing with messages but also with contacts. IE, when receiving a message, courier has to look up the contact by URN to assign a contact id to that message (or create the contact entirely). 

In the approaches that have mailroom do the assignment (or copying) of an incoming message to the appropriate org we would already be too late in the process, the contact would have been created on the parent org and assigned to the message, that seems like that wouldn't work.

So maybe courier **does** need to know about this stuff. Really all it needs to know is what sessions are currently active across the orgs and if there is an active session for the contact with the URN it is receiving then it needs to assign the message to that org.

I think another open question is are we sharing ALL the channels from the parent org to the sub orgs or selectively doing that? I can't see anything but all being reasonable because otherwise behavior gets super weird due to routing being session based. IE, say you had a parent org that had two kannel channels and one whatsapp channel. If a child org was only sharing the whatsapp channel then on incoming msgs we would have to determine if that whatsapp URN (not contact) was active in a session and only then route to the child org. But potentially that contact also has a phone number URN and because Kannel channels aren't shared the contact then could be active in a flow on the parent org? Just thinking about reasoning about that hurts my head.

So maybe an assertion here is that these types of sub-orgs share ALL channels, it isn't something you pick. You don't get to add channels to a sub org either, you are either using all the parents channels or operating totally independently.

**Comment by rudigiesler** [comment]
Just in case this helps, our solution to this is that we currently do this in Junebug, using what we call `routers`: https://junebug.readthedocs.io/en/latest/routers.html#built-in-router-types . Currently we only have a from-address regex based router (we use this to split different longcodes that are on a single SMPP bind, or to split one USSD line into multiple apps, `*120*1#`, `*120*2#`, etc.), but it's easily extensible to add more router types, if we wanted to do something like keyword /session based routing.

**Comment by nicpottier** [comment]
Thanks @rudigiesler, ya that's something we have done before as well. It really isn't enough to only do routing from the outside however, internally RapidPro really needs to know who is in what session etc in order to make decisions about who should be started in a flow etc.. So it needs to be more integrated than just routing from the msg level.

**Comment by nicpottier** [comment]
@ewheeler would be interesting to hear some more concrete use cases here.

Part of me wonders whether the most logical way to do this is just to have slightly more granular levels of permissions with the current Org representation. IE, would it be enough to say, have some kind of group permissions around flows that would prevent users in different groups from editing flows / triggers that belong to a group they are not part of?

The more I think through trying to do copying or routing the more it sounds like it would be a nightmare both from an implementation view but also from an understanding view for administrators. (knowing why a contact didn't receive a message in their sub org, or was kicked out of a flow)

So maybe the right way to do this is really having a single org but making sure people can't muck up other people's use cases. I don't cherish adding group permissions at all, but it does sound more reasonable than the alternative honestly.
