### ISSUE TITLE
Option to hide Flow Events in Contact History page

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1095]
Some users find it overwhelming to see all the detailed flow events, having a way to filter these would probably be a nice to have. (perhaps even storing that setting as a cookie so they don't have to do it on every contact)

**Comment by rowanseymour** [comment]
Seems reasonable.. maybe have a checkbox for "Messages only" ?

**Comment by nicpottier** [comment]
Ya, was thinking more like it's a radio button with like "full", "summary" in the upper right above the table:
  https://getbootstrap.com/docs/4.0/components/buttons/

Where "summary" is what we used to have and "full" is what we have now.

@johncordeiro is this something your team would be interested in doing for 5.4?

**Comment by rowanseymour** [comment]
@johncordeiro we want to include this before code freeze for 5.4 on Feb 17th. Can you confirm whether someone from your team is going to tackle it?

**Comment by nicpottier** [comment]
Added.
