### ISSUE TITLE
Send to node is not localized

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1099]
From feedback from U-Report Haiti: you can click on the blue number badge on a node to send a message to contacts currently on that node, but it can't be localized and doesn't consider current contact language.

**Comment by rowanseymour** [comment]
This could match the UI for campaign events which are localizable...

<img width="576" alt="Captura de Pantalla 2019-11-20 a la(s) 16 35 49" src="https://user-images.githubusercontent.com/675558/69280192-d4796b00-0bb3-11ea-886f-65020d68fcb0.png">

**Comment by norkans7** [comment]
We need to consider ways this behaves for channels like Facebook that prevents to send to contact that are out of the allowed window too
