### ISSUE TITLE
Updates to webhooks in a flow aren't saved, once a flow has been started.

### ISSUE THREAD

**Issue by knightsamar** [rapidpro/rapidpro#110]
Whenever a Webhook's URL is changed, the change is not saved.

This happens when a flow has been "started". And I can't figure out a way to "stop/restart" a flow.

**Comment by knightsamar** [comment]
The only solution seems to be deleting a webhook and creating it again.

**Comment by ericnewcomer** [comment]
It sounds like the flow is just not getting marked dirty on webhook URL change which should be an easy fix if you wanted to open a pull request. A workaround would just be triggering a save by any other means (such as moving a node).

**Comment by ericnewcomer** [comment]
Fixed in #115
