### ISSUE TITLE
Allow selection of Facebook message Tags in flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1103]
See: https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags

In the past messages that are not replies have had to be tagged as a non-promotional message. We did this automatically in Courier and that was a catch-all.

Facebook is moving to these having to be explicit based on the above set, currently one of: CONFIRMED_EVENT_UPDATE, POST_PURCHASE_UPDATE and ACCOUNT_UPDATE

We need to allow flow authors to select the appropriate one similarly to how they select WhatsApp templates. Likely an advanced tab that appears if you have a Facebook channel connected and a similar set of warnings if you try to start a flow on a set of contacts without selecting it etc.. 

Steps:
 1. Update Goflow, add something like `facebook_tag` to the `send_msg` action
 2. Update FlowEditor, show tab and allow selecting tag based on whether Facebook channel is connected
 3. Update Mailroom to pass through tag in msg metadata to Courier
 4. Update Courier to tag outgoing message based on metadata

**Comment by rowanseymour** [comment]
Trying to think ahead to more channel types adding their own special requirements... we've always tried to keep channel specific stuff out of actions, and even Whatsapp templates are surfaced with generic language like `templating` so they could conceivably be made to work with other channel types... can we do the same here? 

Or should we go the opposite direction and explicitly call these things out as being channel specific?

The former approach would add something like this to the spec...

```
"topic": "purchase" | "event" | "account"
````

And it's up to courier to map that to a channel specific thing.

The latter approach would be more like..

```
"channel_params": {
  "whatsapp": { "template": "asfsa" }
  "facebook": { "topic": "CONFIRMED_EVENT_UPDATE" }
}
```

I think I lean toward the former as it would be more robust to channel specific changes

**Comment by ericnewcomer** [comment]
I think the strongest argument for the former is I could see a scenario where a future channel says, hey, I have templating, and can implement that. Maybe a bit more of a stretch to see additional channels implementing this tagged bit, but don't see the harm in it being a generic decoration that channels can chose to use or discard.

**Comment by nicpottier** [comment]
I agree it is nice to try to make things generic, but these feel pretty darn specific to Facebook. For templates I think we saw the writing on the wall that these may be generic (it looks like Facebook Messenger may adopt something similar) so went that route, but for tagging I'm not sure that's the case.

That said, there's no huge downside to making these generic and mapping them over. 

I'd say the only big downside to going the generic route is what happens down the line if we then see something else that is similar but slightly different (IE, their tagging approach is different enough that it doesn't map cleanly to this) and we have to come up with some other name for what these things are. Us having picked a generic name for "topic" becomes more of a burden than anything.

Other question is what is the set of tags available in a flow? If it is generic then we need to come up with a universal mapping of tags that can map back to the limited set supported by channels. That could get tricky / impossible in the case of having supersets or just different concepts entirely where there is no unifying mapping that is possible.

Meh, I don't know. I don't like specific stuff either so I'm fine doing the mapping but somehow doubt that is going to work long term. (but happy to be proven wrong!)

**Comment by rowanseymour** [comment]
I'd vote generic with mapping and we'll see how it goes.. just seems weird to make the editor know about something specific to the Facebook API like `CONFIRMED_EVENT_UPDATE`.

And worth mentioning... nothing is forever.. we can do flow migrations now!

**Comment by rowanseymour** [comment]
Unrelated question - should this be available on `send_broadcast` actions too? And should WhatsApp `templating` as well?

**Comment by nicpottier** [comment]
Or for that matter quick replies? .. We seem to currently be saying broadcasts are plain things and if you want more then you use a flow to send a message. If we went the other way then we'd probably want to support everything. Haven't heard many requests for those though so I would say until we do priority is pretty low there.

**Comment by rowanseymour** [comment]
@nicpottier yeah think it's fair to limit it until we hear a demand for it. One thing I did hear a demand for tho was localization of "Send To node" broadcasts which is a UI change https://github.com/rapidpro/rapidpro/issues/1099

**Comment by rowanseymour** [comment]
Well huh seems engine _does_ support attachments and quick replies on `send_broadcast` actions but that's not surfaced in the editor... inclined to say that's ok.. maybe it's something we add in the future.. attachments definitely seems reasonable.

**Comment by paradoxxjm** [comment]
A couple questions/ideas on this feature request:
* Would it be possible to set the message type at the flow level, rather for each message?
* Is is possible to set a "default" message type. One of the worries that I have is that if a user forgets to set a message type for the Messenger channel, then the Facebook messenger API may reject the message all together.

Setting a default or global option may prevent issue in the second bullet. It would also have the advantage of removing the busy work of setting this for every message (if we assume the multiple messages in the same flow are likely to be of the same type).

**Comment by nicpottier** [comment]
Like WhatsApp, the only messages that need tags are those that are the first in a flow that is being broadcast. So not every message needs a tag set on it, only the first in a flow.

And like WhatsApp, you will be warned when starting a flow that doesn't have said tag set if you have a Facebook channel connected.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/floweditor/pull/770
