### ISSUE TITLE
Migration of start flow action

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1104]
In the old editor, we have three different ways to start flows.

Enter a subflow and route based on completion or expiration
Start a flow (enforced as a terminal action)
Trigger somebody (or perhaps yourself) in a flow

In the new editor we don't allow option 2. However, it's possible to get the editor in a state it doesn't recognize by migrating an old definition with such an action. I believe in your discussions this was meant to migrate forward to be like option 1 (this would need to break into its own node if it is in a node with more actions).

Alternatively, we could patch the editor to recognize these types of nodes and handle all the splicing and route manipulation the next time that action is edited. This wouldn't be a hard change on the editor side, but want to pose this question since it feels maybe more right (but more annoying) to fix this in the migration.

Moved. See additional comments here:
https://github.com/nyaruka/goflow/issues/802

**Comment by rowanseymour** [comment]
Well re my last comments about fixing this via a legacy migration.. fair point re migrated flows like this already having been saved.. so maybe that ship has sailed. Or at least fixing would mean having both a legacy and a new migration.. no?

The `terminal=true` conversion the engine currently uses was really just about getting legacy flows to run the same in the new engine as the old.

**Comment by rowanseymour** [comment]
@ericnewcomer this doesn't require any further action right? The editor converts these as they're edited?
