### ISSUE TITLE
WhatsApp template syncing should write to ChannelLog

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1106]
We sync WhatsApp templates every five minutes or so. Sometimes these have errors (usually due to invalid credentials). Right now these get logged to sentry only, we should write an HTTPLog instead for them, cleaning up our sentry logs and allowing us to see what's going on more easily.

**Comment by norkans7** [comment]
Do we add a Foreign key on the HTTPLog to a channel for this?

**Comment by norkans7** [comment]
And are the logs only for the errors cases only here or we log the success cases too

**Comment by rowanseymour** [comment]
HTTP logs are for all HTTP interactions and yeah I think we need a channel FK cuz assume we'd want to able to list these for a given channel

**Comment by norkans7** [comment]
I am adding that
