### ISSUE TITLE
Documentation Request for NLP / Intent action

### ISSUE THREAD

**Issue by paradoxxjm** [rapidpro/rapidpro#1107]
User Request:
I wasn't able to find RapidPro documentation explaining how to connect an NLP engine to the platform in v5.2. Related to this, added documentation/explanations for how the new "split by intent" action works.

**Comment by nicpottier** [comment]
Documentation is a hosting specific thing. We are working on one on the nyaruka front though that should be available in the next few days.

**Comment by nicpottier** [comment]
Our docs are here FWIW: https://help.nyaruka.com/en/articles/3525463-adding-classifiers-to-a-flow
