### ISSUE TITLE
Switch modals and forms to use components

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1110]
hashtag regerts?

#### Messages
- [x] Send message
- [x] Create Label
- [x] Create Folder
- [x] Message export
- [x] Schedule broadcast formax

#### Campaigns
- [x] Campaign create / update
- [x] Campaign event create / update

#### Contacts
- [x] Contact export
- [x] Create contact
- [x] Create group
- [x] Send message
- [x] Edit
- [x] Edit custom fields
- [x] Delete

#### Flows
- [x] Create
- [x] Start Flow
- [x] Edit
- [x] Delete

#### Triggers
- [x] Creation formax

#### Home
- [x] Account formax
- [x] Manage users
- [x] Transfer credits
- [x] Create sub org
- [x] Update global value

#### Channels
- [x] Edit

#### Classifiers
- [x] Delete

#### Controls
- [ ] Gear menu
- [x] Arbitrary tag support in multi select
- [x] Omnibox urn support
- [x] Date/time repeat picker
- [x] Checkbox

**Comment by nicpottier** [comment]
Ya, oh my gosh, do you think it still makes sense? What's the cost/benefit here? I guess you will know after you do a few more but don't be afraid to pull the plug, let's not get caught in some investor's dilemma.

**Comment by ericnewcomer** [comment]
I've been going after the hardest ones first, but maybe reducing this stress cloud would make more sense to get a better feel of the overall effort level remaining.

**Comment by ericnewcomer** [comment]
This work was completed as part of the refresh.
