### ISSUE TITLE
Add Pipeline to add WhatsApp channel

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1112]
I think we are at a point where we should add / advertise us supporting WhatsApp.

Idea would be that WhatsApp shows up as an option on the Claim Channel page in the Social Section. Clicking there then takes you to a similar looking page that lets you pick your "WhatsApp provider" where we currently just show Twilio and "Native WhatsApp". 

The Twilio case walks them through connecting their channel. The "Native WhatsApp" is the current docker implementation. (the claim page should outline that they probably don't have access to this, I could be convinced we continue to hide that)

**Comment by rowanseymour** [comment]
For simplicity can these be separate channels? Twilio Whatsapp vs Docker Whatsapp. For hosters who aren't going to offer docker hosted whatsapp, they can just exclude that from the list of channel types in the settings.

**Comment by norkans7** [comment]
So far to me it looks like a Twilio channel can support both schemes, just that the `from` and `to` have `whatsapp:` prepended on them

**Comment by nicpottier** [comment]
Yes, the only change needed on our side is to allow creation of a WhatsApp Twilio channel with scheme. Also the pipeline on the WhatsApp side doesn't allow for setting endpoints automatically for WhatsApp so they also need to be given what the receive URL is so they can set that up.

**Comment by norkans7** [comment]
From https://www.twilio.com/whatsapp/request-access I think any Twilio number can request to support Whatsapp.

Also aren't the MO URLs saved as the normal Twilio channel?

**Comment by smn** [comment]
Are you open to including Turn in that listing?

**Comment by nicpottier** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/2638
