### ISSUE TITLE
WhatsApp templates out of sync between flow editor & listing

### ISSUE THREAD

**Issue by smn** [rapidpro/rapidpro#1114]
We're seeing an issue where a WhatsApp template in the flow editor is out of sync with what's listed in the channel template list:

Channel Template List (correct):

<img width="761" alt="Image 2019-12-19 at 12 03 47 PM" src="https://user-images.githubusercontent.com/1065/71168811-d5a3c380-2257-11ea-919a-0c0257c9ca3b.png">

Flow Editor (incorrect, old value):

<img width="669" alt="Image 2019-12-19 at 12 04 51 PM" src="https://user-images.githubusercontent.com/1065/71168819-d9cfe100-2257-11ea-9ef3-8b3d84595427.png">

This seems to happen after a channel's deleted and recreated to force a clean sync of all templates. Happy to help with a PR to address this but would appreciate some pointers on how these things are synced across.

**Comment by nicpottier** [comment]
What's the exact repro here? Is it you connect the channel, create a flow that uses a template, then delete the channel and go back in the flow and the template text is still the old one?

Templates are normal Django models with UUIDs as I recall, so the editor is referencing one of those UUIDs which is probably stale at that point. So may just be a question of having the template syncing code update the old template with the same UUID instead of creating a new one. That gets slightly tricky though in that it would have to know the old channel is the same as the present one. Should be possible because the old channel isn't hard deleted though.

So ya, would dig into the template syncing code on the WhatsApp channel in RapidPro to figure out what approach makes the most sense.

**Comment by smn** [comment]
Yeah, that's pretty much it. Create a channel, create a flow, disconnect the channel and connect a new one, the flow still refers to the old templates.

**Comment by nicpottier** [comment]
So looks like when a WhatsApp channel is deactivated, its translations are trimmed (but the templates themselves stick around):
  https://github.com/nyaruka/rapidpro/blob/master/temba/channels/types/whatsapp/type.py#L139

When templates are next synced they SHOULD match the old template though (unless the name has changed):
  https://github.com/nyaruka/rapidpro/blob/master/temba/templates/models.py#L105

So I would think the template UUID would match. So would start there to figure out why they aren't.

**Comment by smn** [comment]
@nicpottier thanks for your help on this.

We're seeing this behaviour on a client's account hosted on textit.in and so low level visibility is limited for us unfortunately. 

From what I can see the TemplateTranslation's are being synced across fine as the message templates + translations listed at `https://textit.in/channels/types/whatsapp/<channel-uuid>/templates` are all correct and so I don't think the issue is at the Template or TemplateTranslation model level but something there after.

Where does the Flow Editor load its canonical list of all available message templates from?

**Comment by smn** [comment]
rubber duck debugging ftw, I spotted that the templates are being loaded via the `/api/v2/templates.json` endpoint and that seems to be listing old template translations that I suspect have been trimmed.

<img width="990" alt="Image 2020-01-13 at 10 49 22 AM" src="https://user-images.githubusercontent.com/1065/72246189-1a6a1280-35ea-11ea-9a8c-bcd3a6c0641a.png">

**Comment by smn** [comment]
No, it seems like the these translations are still active somehow even though their channels have been disconnected / deactivated.

**Comment by smn** [comment]
If the database manages to get in this state, the Flow Editor seems to just [pick the first translation](https://github.com/nyaruka/floweditor/blob/6033b4e08c8f9fb7f285865e38cc4d939f6f9640/src/components/flow/actions/sendmsg/SendMsgForm.tsx#L381) and go with that.

I'm a bit stuck at this point, not sure if this is a Flow Editor issue (how to deal with translations across channels) or a sync issue (TemplateTranslations somewhere not being trimmed properly).

**Comment by smn** [comment]
@nicpottier pls have a look at https://github.com/nyaruka/rapidpro/pull/2650 which is an attempt at resolving this issue.

**Comment by smn** [comment]
This has been resolved in https://github.com/nyaruka/rapidpro/pull/2650
