### ISSUE TITLE
Confusing that date format for Created On and Date Time fields different on Contact Page

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1115]
Should both be displayed in same format.

<img width="299" alt="Screen Shot 2019-12-25 at 10 57 52 AM" src="https://user-images.githubusercontent.com/168067/71449191-6f122000-2705-11ea-906e-1dea3cbb9dc2.png">

**Comment by rowanseymour** [comment]
Similar issue on contact list pages...

<img width="501" alt="Captura de Pantalla 2020-01-10 a la(s) 12 37 34" src="https://user-images.githubusercontent.com/675558/72173633-00d88900-33a6-11ea-94a8-cc9f81dff547.png">

**Comment by norkans7** [comment]
Fix on the read page https://github.com/nyaruka/rapidpro/pull/2689 to use the same format

<img width="1746" alt="Hallie Lopez 2020-02-14 12-49-13" src="https://user-images.githubusercontent.com/1040571/74524924-a4c6ce80-4f28-11ea-8475-eb4758945f79.png">

**Comment by norkans7** [comment]
For the list page we use `short_datetime` that never show the time, we show HH:MM in the last 12 hours and DD:MM  in the current year then the date for older time than a year

Do we switch that to have the same format? 20-11-2017 10:49

**Comment by nicpottier** [comment]
I think we should show the same format wherever we should a contact field date (and that includes `created_on`). That should use the org formatting with date. (IE, month / day first depending)

I think we should only use the one that shorterns for things like messages, flow change dates, campaign events etc..

**Comment by norkans7** [comment]
I just updated that to make sure created_on is always displayed as the datetime fields
