### ISSUE TITLE
VK Social Network Channel on RapidPro

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1125]
Hi everyone, the UNICEF requested a new channel on Rapidpro for the region [ECARO](https://www.unicef.org/eca/topics/ecaro). This channel is for [VK Social Network](https://vk.com/). 

The platform team from Ilhasoft is developing this channel. We will open a PR with VK channel coming soon.

**Comment by nicpottier** [comment]
Sounds good! 👍
