### ISSUE TITLE
Can't import flow definition with a smaller revision than existing flow

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1126]
If you export a flow at revision 3 and import it into the same system after making some edits to that flow, import will fail because the revision in the import is smaller than the revision of the current flow.

See:
  https://github.com/nyaruka/rapidpro/blob/master/temba/flows/models.py#L779

To:
  https://github.com/nyaruka/rapidpro/blob/master/temba/flows/models.py#L1308

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2658
