### ISSUE TITLE
Performance issues with JSON syntax highlighting in API explorer

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1129]
Any large JSON response causes the user's browser to freeze.

**Comment by rowanseymour** [comment]
Playing around with this and on my api.rapidpro.io test account and if I request contacts the textarea ends up with 409750 spans and the browser becomes unresponsive.

Should we just switch off syntax highlighting for the explorer? The JSON returned by the API is already formatted/indented. Seems like is pretty enough...

**Comment by nicpottier** [comment]
Ya, I'm totally for that.

**Comment by rowanseymour** [comment]
We're also using CodeMirror with the inputs which creates a noticeable and annoying lag when trying to edit the query string or body... so I think we ditch that too
