### ISSUE TITLE
Test contact can be displayed in group view and included in group count

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#113]
If you have a flow which adds a contact to a group, and run the flow in the simulator, the test contact will be added to that group. The test contact is then visible in the group view, and included in the cached group member count.
- `ContactCRUDL.Filter` needs updated to filter out test contacts
- `ContactGroup.update_contacts(...)` needs updated to handle test contacts appropriately

**Comment by ericnewcomer** [comment]
I believe this is addressed in nyaruka/rapidpro/pull/54
