### ISSUE TITLE
Add Bulk Delete Function 

### ISSUE THREAD

**Issue by Richaela26** [rapidpro/rapidpro#1130]
When a user tries to delete a contact, message, flow, campaign or trigger, they must delete it individually:

- Deleting multiple contacts involves a two-step process: (1) block the contact and (2) then delete
- Messages must be archived before they can be deleted 
- No option to delete triggers 
- No bulk delete option for Campaigns, however separate events can be deleted
- Flows can only be deleted once opened in the flow editor

Suggestion
Include a bulk delete function, whereby a user can delete more than one item (flows, messages, campaigns, etc).

**Comment by ericnewcomer** [comment]
https://github.com/rapidpro/rapidpro/issues/136

**Comment by rowanseymour** [comment]
One possible solution here is that we show dependencies in the confirmation dialog and offer to delete those, e.g. you try to delete a contact field, and we offer to delete an associated campaign event as well
