### ISSUE TITLE
Improve query performance

### ISSUE THREAD

**Issue by hudsonbrendon** [rapidpro/rapidpro#1139]
I'm having performance issues on the message inbox page, we currently have 33 million messages categorized as outgoing flows and 9 million.

![Screen Shot 2020-01-28 at 21 32 23](https://user-images.githubusercontent.com/5201888/73317700-bbc1ad00-4215-11ea-907c-a3865bc2ae74.png)

We use varnish to store as requisitions, but it does not solve the problem.
using the Django Debug Toolbar, note that when accessing the inbox page, about 120 queries are executed, somehow or the large number of queries may be burdening a request.

![Screen Shot 2020-01-28 at 19 33 04](https://user-images.githubusercontent.com/5201888/73317617-700f0380-4215-11ea-8da5-8e6e2971a521.png)

Study how queries are implemented in the view, and it will be implemented as ORM best practices. Try using or selecting_related available in InboxView, but it still had no effect on the relationship with query performance.
I wonder if anyone has had a similar problem, and has a solution for that?
We will get the archiver up and running soon. But I would like to know the same with him running, how answers to questions fall apart that way?

**Comment by rowanseymour** [comment]
@hudsonbrendon we tried a lot of stuff over the years to improve the performance of those views, but in the end, with the current architecture, the only real fix was reducing the number of messages. That's why we introduced archives and rp-archiver to make them.

Having said that, if you're just looking at a view like Inbox, the view should be fairly performant as it should be hitting a perfect index. It's when you start doing things like searching or filtering by label that things fall apart.

**Comment by matmsa27** [comment]
Hi @rowanseymour , really the archiver can help the large database to have the best performance. We will run the archiver with rapidpro.

You can help us with a question about the archiver? There some references to the archiver on the database that can break the Rapidpro application with the archiver not running? For example, there is some information on the database that can break Rapidpro and didn't return the specific error about the information corrupted?

To improve the queries on django ORM, have you used some tool to works with ORM cache on django or indexed some queries on the database? I think this solution can be an alternative to improve the return time on the database. 

Regards.

**Comment by rowanseymour** [comment]
Not sure I follow your question about rp-archiver. Best place for that discussion would be the RapidPro developers mailing list.

We've done plenty of trying to optimize our Django ORM queries - which usually means remembering to prefetch things, careful use of `only`, trying to avoid unnecessary joins, etc. And we've also tried to ensure big reads from the database are always supported by perfect or nearly perfect indexes.

If you can identify any missing indexes or any further optimizations we need in the ORM calls, then please make PRs for those.

**Comment by matmsa27** [comment]
Hmm ok, I got it. You can share with us the developers mailing list? You have another place to discuss subjects like this? Like slack for example.

Thanks a lot @rowanseymour for your attention.

**Comment by rowanseymour** [comment]
See https://groups.google.com/forum/#!forum/rapidpro-dev
