### ISSUE TITLE
Fields API endpoint write explorer is wrong

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#114]
Read explorer says that `key` is required, but that is only for updating an existing field. To create a new field, one must omit `key`

**Comment by nicpottier** [comment]
Read explorer is to get a current field isn't it? Key seems right there.

**Comment by rowanseymour** [comment]
Doh meant write explorer

**Comment by nicpottier** [comment]
For write explorer it is there to update fields..  (though it is indeed not required for creating new ones)

I'll try to tweak the wording there.

**Comment by rowanseymour** [comment]
Yeah not a big deal. I basically forgot how it worked and tried a few times creating a new field with the key included
