### ISSUE TITLE
cc.is_test column doesn't exist

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#1140]
Hi!
Upgrading from the previous stable release to the latest stable release and running the migrations has resulted in this error showing up:

`pq: column cc.is_test does not exist`

Any ideas?

**Comment by rowanseymour** [comment]
That would be the `Contact.is_test` field.. this is going from 5.0 to 5.2 right?

**Comment by rowanseymour** [comment]
Which migration is blowing up?

**Comment by cromulus** [comment]
Migrations all pass.
—————————————
At one point, the bits and bytes of this message were modulated wavelengths of light.

(he/him/his)

**Comment by cromulus** [comment]
Correct, from 5.0 to 5.2

**Comment by rowanseymour** [comment]
`pq: column cc.is_test does not exist` actually looks like a Go error - is this coming from mailroom? If so you probably just need to update it. Make sure all your components are the versions listed at https://github.com/rapidpro/rapidpro#stable-versions
