### ISSUE TITLE
Prevent message sends to tel channels in different countries

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1146]
Right now while we use prefixing of channel addresses to figure out what the best channel to use is when sending a message, and while this does generally take into account country codes, in the end we always default to assigning SOME channel to an outgoing message.

That has worked well enough, but it does open the window for users to incur significant charges if they erroneously end up generating messages to numbers in countries they don't mean to (and the channel sends them, but at a high cost).

Seems the safest ways to prevent sending messages to channels that are on different countries are either:
 1. Change our channel affinity logic so that we (optionally) don't assign a tel URN to a channel in a different country than the telephone number. I think the message would still get created here, it would just be failed immediately along the way. Basically the same as sending a message with a scheme that is not supported by any channel.
 2. Change courier to fail a message permanently at the sending stage if the URN country is different than the channel country.

Both of these would have to be options on the channel themselves, perhaps `local_only` or `fail_international`.

Option 1) has a nice symmetry to the `scheme` case so is appealing to me in that way. It also keeps affinity clean, in that we aren't assigning the contact URN to a channel that we cannot send to. I suppose one open question there is do we perform the same kind of check during manual channel assignment in a flow? (I think again, we are doing this with regards to scheme so makes sense there)

Option 2) is probably a bit easier to implement but comes with the baggage of us actually trying to send the message in Courier, changing it's status etc, as well as the international URN actually having affinity with a channel that can never be sent to.

@rowanseymour any thoughts?

**Comment by rowanseymour** [comment]
I like 1. `send_msg` actions in goflow always start by trying to find all possible "destinations" (URN/channel pairs). In the case where it can't find any valid destinations, it still creates a msg event with nil URN/channel and it's up to the caller to handle that as it wants.

Seems logical to say that a Rwandan tel URN doesn't get paired with a Australian tel channel.. in same way URNs/channels of different schemes don't pair.

Are there many cases where users want international SMS sending? Feels like the default there could be to disallow, and have an option on the channel (`allow_international` ?) that they explicitly enable.

**Comment by nicpottier** [comment]
Ya, agree that this should probably be the default going forward. I don't think it is super uncommon for people to use Twilio numbers internationally.

**Comment by nicpottier** [comment]
added in nyaruka/rapidpro#2679
