### ISSUE TITLE
Omnibox should require longer number before "creating" URN

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1149]
The omnibox supports a user typing in a phone number in a send message dialog. (and creating it)

That's fine, but the minimum length seems a bit short here. Perhaps we should require this to be at least 7 characters? Or even better only do it if parsing of that number comes back successful? (realize this might be happening client side so that could be more complicated)

But 3 is definitely too short / confusing.

![Screen Shot 2020-02-07 at 12 35 20 PM](https://user-images.githubusercontent.com/168067/74063891-4f2d7780-49a6-11ea-9c62-f1d6987f7701.png)

**Comment by ericnewcomer** [comment]
What about 4 digit short codes? I think I'm fine saying you can't message them adhoc. They could always create a contact for them first if they absolutely had to anyways.

**Comment by nicpottier** [comment]
Ya, I had the exact same thought. In the very rare event when someone wants to send a message to a shortcode they can manually create a contact.
