### ISSUE TITLE
FreshChat connection instructions 

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1154]
Need better docs on the connection page for FreshChat to explain what the various parameters are and where to get them on your FreshChat page.

@tybritten Any chance you could help on this front? We aren't sure what these are either.

**Comment by tybritten** [comment]
Yes, absolutely.

**Comment by tybritten** [comment]
Oh you mean on the actually page itself. Got it, I'll get a PR going

**Comment by tybritten** [comment]
Ok, I'm losing my mind. I can't seem to find where the channel claim pages pull their instruction text from. A little help?

**Comment by nicpottier** [comment]
Just create a `claim.html` template in the appropriate dir. 

Example:
  https://github.com/nyaruka/rapidpro/blob/master/templates/channels/types/dmark/claim.haml
