### ISSUE TITLE
Set language request on Bothub classifier.

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1155]
Hi everybody, I want to show you the bothub languages. The bots on bothub accept internationalization, and the endpoint "https://nlp.bothub.it/info/" have a list `available_languages` that all languages the bot support.

![languages_bothub](https://user-images.githubusercontent.com/10725273/74195617-6a181a00-4c3a-11ea-811f-15b5d7c92b6f.png)

So, internationalization is most important to treat situations when people with many languages can interact with rapidpro and bothub together.

We can discuss implementation for this? First, I thought of a solution and can present to you.

1) Create the model Language to associate the languages to the classifier, an object for each language on classifier
2) On method, sync_intents can get the field available_languages on JSON
3) On flow editor when the user selects the split by intent and selects a bothub classifier, the flow editor can open a field "Language" and the field listing the available languages to select. The user can select a language that the contact keeps conversation.
![language_request_flow_editor](https://user-images.githubusercontent.com/10725273/74195512-21f8f780-4c3a-11ea-87c5-3cda1afcea6c.png)

4) After get a language on flow editor, the gocommon send the parameter language to bothub, and the gocommon get a response.

I see a point to discuss:

On step 3, how can we get the language used on flow? For example, the flows have support to internationalization, and you can add translations to the flows. My idea is to get the language selected by contact in a conversation and the language sent to bothub if this option is enabled.

We are ready to implement this Nic and Rowan, you can discuss with us about how to improve this. If this okay, can we implement this?
 
Thanks for all.

**Comment by rowanseymour** [comment]
I would imagine users would almost always want to send the language that the flow is being run in, which we calculate from contact language, flow base language and supported org languages. Should we maybe just be passing that in to Bothub API calls?

**Comment by nicpottier** [comment]
Agreed that it seems this should just be the contact language no? Is there some reason we wouldn't always pass that through?

**Comment by matmsa27** [comment]
hmmm I got it, yes I agree that pass the contact language should resolve this. If the contact doesn't have a language the parameter language on bothub requisition must be empty like is today.

So, just to align, step 3 and step 4 must be a unique step modified to: Get contact language and send to bothub, if contact doesn't have a language, the behavior must be the same as today.

Steps 1 and 2 are ok?

Thanks for support @nicpottier and @rowanseymour

**Comment by nicpottier** [comment]
Feels a bit goofy that Bothub requires us to manage that. The other platforms just let you pass in the locale or language and it will do the best given that data. That then doesn't require any syncing or keeping track of supported languages on an intent etc.. Is that something that isn't possible?

**Comment by rowanseymour** [comment]
To be clear we're not specifically talking about `@contact.language` - we're talking about the language that the flow is being run in which is calculated from the contact language, the flow language, etc. So it always resolves to something. But yeah I think that's what we should be sending to Bothub.

What ISO standard does Bothub use for language codes?

**Comment by koallann** [comment]
Bothub uses the `iso2_country2`... [Environment.DefaultCountry()](https://github.com/nyaruka/goflow/blob/master/envs/environment.go#L36) is enough for `country2`?

**Comment by rowanseymour** [comment]
Yes `Environment.DefaultCountry` is the country of the org in RapidPro.. but will be overridden where the contact has a preferred channel with a country set.

We don't accept PRs on the goflow repository so I'll make that. Tho it doesn't seem http://docs.bothub.it is working... 

- whats the name of the parameter to pass to bothub?
- what happens if/when we pass a language that isn't supported?

**Comment by koallann** [comment]
Sorry, I mistook the iso standard, in fact it uses iso639-1, but when a new language variation needs to be added, the standard moves to `iso2_country2` (`country2` in lowercase), for example, we have `pt` and `pt_br`, so for a specific US english, we would have en_us (currently we only have the `en`).

That's, we should pass language to Bothub in `iso2_country2` if the org/contact have a country, right?

- The parameter is `language`;
- Returns `400 Bad Request`:
```json
{
    "detail": "Language '{{lang}}' not supported by now."
}
```
https://nlp.bothub.it/#/v1/parse_handler_parse_%3F_post

**Comment by rowanseymour** [comment]
Ok so take a look at https://github.com/nyaruka/goflow/pull/916. If we have language AND country, it will send them like `en_us`, `pt_br`, etc.

**Comment by koallann** [comment]
Nice! But that way we will to support `pt_br` only, because the other languages are in iso639-1 (en, es, pt, it, etc.)

So, we should get language (calculated from contact lang, flow lang, etc.) and if we have a country setted on org, add it to param, in other words, concatenate `"_cc"` to language param.

`por` -> `pt`

We have a country? What country? Yes, for example, `BR`.

`BR` -> `br`
`pt` + `_br` = `pt_br`

**Comment by rowanseymour** [comment]
I think it's doing what you describe in https://github.com/nyaruka/goflow/pull/916/files#diff-b37ba0ac301fc3fca21676616cfa50a7R31-R35, no?

**Comment by koallann** [comment]
It only sets `language` if there a country setted on org, right? But we should send if no have country too, with parameter in iso639-1, like "en", "es", "pt", etc.

`por` -> `pt`

We have a country? No.

So send it as `pt`.

**Comment by koallann** [comment]
Just to complement... Bothub has languages in `iso639-1` standard primarily (en, es, pt, it, etc.), but when a new specific country language need to be added, the standard goes to `iso639-1_country2` (en_us, pt_br) for that new language.

**Comment by rowanseymour** [comment]
Ah ok sorry I misunderstood... I thought you only wanted to send if there's a country. Will adjust.

If a user has something like `es_ec` setup in bothub.. will it match with `es`? And vice-versa if a user has setup `en` in bothub and it sends `en_gb`.. will it match?

**Comment by koallann** [comment]
Unfortunately, it will not match, the parameter passed in the request must be the same of Bothub.

**Comment by koallann** [comment]
Do you need that mapping?

**Comment by rowanseymour** [comment]
Yes.. I think we need something like..

```go
var languages = map[string]string{
	"en":    "en",
	"es":    "es",
	"pt":    "pt",
	"pt-BR": "pt_br",
}
```

so if we calculate the session is using `pt-MZ` (Mozambique) we can first try to look that up, then look up just `pt` if that fails. If a user has `en-US` we'll look up that, not find a match but then look up `en` and find a match.

**Comment by koallann** [comment]
Just to be clear... The recommended way is the Bothub handle that mapping, alright? That's, Bothub should have a languages map on incoming requests:

`pt` -> `pt`
`pt_br` -> `pt_br`
`pt_pt` -> `pt`
...

That way we have 1 request, no retry.

I'm requesting that handling to be implemented as soon as possible.

Many thanks for your attention, Rowan!

**Comment by rowanseymour** [comment]
It's debatable who's responsibility it should be. 

Where things get tricky is if someone requests `pt` and bothub has `pt_br`, `pt_mz` and `pt_pt`.. how do you pick one?

To clarify my previous comment - I'm not suggesting that goflow call bothub with a language (e.g. `es_ec`), and then retry with another (`es`) and then again with no language if all of that fails - I'm saying goflow would have that mapping, and end up making a single call with `es` to bothub.

**Comment by koallann** [comment]
I think the responsibility should be in Bothub so that we don't have to update the goflow whenever a new language gains support... What do you think?

But here's the supported languages currently:
- `en`: English
- `de`: German
- `es`: Spanish
- `pt`: Portuguese
- `fr`: French
- `it`: Italian
- `nl`: Dutch
- `pt_br`: Brazilian Portuguese
- `id`: Indonesian
- `mn`: Mongolian
- `ar`: Arabic
- `bn`: Bengali
- `hi`: Hindi
- `ru`: Russian
- `th`: Thai
- `fi`: Finnish
- `ga`: Irish
- `he`: Hebrew
- `hr`: Croatian
- `hu`: Hungarian
- `nb`: Norwegian
- `pl`: Polish
- `ro`: Romanian
- `si`: Sinhala
- `sv`: Swedish
- `te`: Telugu
- `tr`: Turkish
- `tt`: Tatar
- `ha`: Hausa
- `el`: Greek
- `ka`: Georgian
- `sw`: Swahili
- `kk`: Kazakh

So in case of mapping on goflow:
- Get language and country, like `es_ec`;
- Try to find on the map: not found;
- Try with the first part: `es`;
- Found, make request.

**Comment by rowanseymour** [comment]
Ok let's make it so bothub is responsible for this. Conveniently the language used is already returned in the response, so the caller (goflow in this case) can already check whether their requested language was used or not.

In which case goflow will send `es_ec`, `en_us`, `ar` etc and it's up to bothub to decide what the best match for that is.

**Comment by rowanseymour** [comment]
The changes on the goflow side are https://github.com/nyaruka/goflow/pull/916 but won't merge that until you've updated bothub.

**Comment by koallann** [comment]
Ok, we schedule that feature development for next week. Thanks!

**Comment by johncordeiro** [comment]
hey @rowanseymour , BotHub was updated with proper changes to make it work in the way is requested for this issue.

**Comment by nicpottier** [comment]
Closing as I believe this has been updated.
