### ISSUE TITLE
Strange behavior when deleting active groups

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#1157]
# Issue description
When trying to delete a group that's being used in a flow the proper warning pops-up.
![image](https://user-images.githubusercontent.com/35577716/74865699-4e92ca80-5330-11ea-8809-5f909d02f787.png)
It processes...
![image](https://user-images.githubusercontent.com/35577716/74865745-65392180-5330-11ea-9dc5-b032dca10809.png)
Then it does this awkward behavior...
![image](https://user-images.githubusercontent.com/35577716/74865837-8568e080-5330-11ea-93c9-7398dc47b298.png)

# Current functionality status
When the group isn't active in any flow, it can be deleted with no problem. BTW, this was the required pipeline, as long as I remember the behavior was similar to the one we got now when trying to delete a group that's associated with a campaign - Warn message *It cannot be deleted until it is removed from the foo campaign.*

**Comment by rowanseymour** [comment]
This was fixed in https://github.com/nyaruka/rapidpro/pull/2680
