### ISSUE TITLE
Softer dependencies for campaigns and triggers

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1159]
Now that we can better support it in flow design and execution, we should allow users to break flows with dependencies and instead warn them about it. This goes for contacts, groups, fields, etc. 

Dependencies from triggers and campaigns might be a bit different. Perhaps for consistency we allow them to go through with it there too but warn them that those will be modified or removed accordingly? Should we maybe allow campaigns to exist without a group assigned to it?

**Comment by nicpottier** [comment]
My vote would be not to allow triggers and campaigns on groups that don't exist, that feels much weirder to me than an action on a flow. It is also a lot easier for the user to fix if they really want that group gone.

**Comment by ericnewcomer** [comment]
So, do you prefer blocking the deletion of a group until then, or should we warn them and do it for them?

I feel for triggers I'd want it to be handled for me. In the case of campaigns, probably not.

**Comment by nicpottier** [comment]
Ya I think I agree with that. (warning on the triggers case and you can confirm to remove, campaigns is blocking)

**Comment by rowanseymour** [comment]
Closing in favor of https://github.com/rapidpro/rapidpro/issues/1480
