### ISSUE TITLE
WhatsApp Opt Ins

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1160]
WhatsApp requires users you contact via WhatsApp to explicitly opt in to receive messages: https://developers.facebook.com/docs/whatsapp/guides/opt-in/

This is something that is pretty doable via the current RapidPro APIs for organizations that aren't anonymous, but not possible for those where we don't allow getting the phone number for a contact.

Since this has high utility for both use cases, we should make this easier for user on both normal and anon accounts. This pretty much needs to be a minimal mobile-friendly web page that shows org-specific messaging, a checkbox and the phone number for the contact with a button to "opt in".

This form should be accessible in two ways:
 1. By just a generic link you can go to to type in a phone number to "opt in" to an orgs WhatsApp channel. After clicking submit you get a confirmation message to your WhatsApp message and if you reply "yes" or whatever, you are then marked as opted in.
 2. By a specific link that can be generated and used in a flow which takes the user to a page with the number pre-filled in. Once you click submit you receive the same confirmation message, and once you confirm you are marked as opted in and the WhatsApp URN is added to your contact.

This has quite a few tricky bits in implementation for the anonymous case:
1. For case 1), we can't generate traffic on the contact until they confirm they own that number. Otherwise anyone could type in a target's number and break anonymity.
2. We can't have the link displayed in the message history or channel log for case 2) above, as clicking on that would break anonymity and let you see the contact's phone number.
3. .. all sorts of other things I'm not thinking of.

**Comment by nicpottier** [comment]
@smn curious how you guys are dealing with this

**Comment by nicpottier** [comment]
Note that we need to think about whether we support different levels of consent.. ie subscribing to some things and not others.

**Comment by rudigiesler** [comment]
This explicit opt in is only required for sending template messages, not normal replies.

The way we're currently solving this is either having a registration mechanism on another channel (like USSD or a website), or sending the user a link, and once they've clicked the button to confirm, doing a redirect to https://faq.whatsapp.com/en/android/26000030/ , which will take them straight back to whatsapp with the conversation open.

**Comment by smn** [comment]
@nicpottier for Turn we'll likely be going the number 2 route, a unique URL automatically generated per WA contact with a TTL or something.

**Comment by cbunicef** [comment]
Good to note that although the wa.me links are convenient, there can be issues with captive browsers and differences in function between operating systems. As an example, at one time it was not possible on Android to click through a wa.me link in Facebook's captive browser to the WhatsApp application.

**Comment by johncordeiro** [comment]
hey guys, what about if we have a kind of `Subscription URL` on WhatsApp channels that would enable for 3rd-party apps or websites to input their phone number on RapidPro, it would be available in the WA Settings page:

<img width="1280" alt="1_attachment" src="https://user-images.githubusercontent.com/6073075/76643168-501c7080-6533-11ea-98e3-ffea8403e631.png">

and a new trigger type called `Start a flow when a contact subscribes to a channel` that would make flexible for users to send a template message in the flow:

<img width="478" alt="2_attachment" src="https://user-images.githubusercontent.com/6073075/76643316-9245b200-6533-11ea-8881-9882876ed0f4.png">

**Comment by cbunicef** [comment]
FYI or for posterity, WhatsApp has just made a significant change to their opt-in policy (July 7 2020):

> Opt-in:
> In order to initiate a WhatsApp message to a person, you must first receive opt-in permission confirming that they wish to receive future messages from you on WhatsApp. The opt-in must (a) clearly state that the person is opting in to receive messages from you over WhatsApp and (b) clearly state your business’ name.
> **You are solely responsible for determining the method of opt-in**, that you have obtained opt-in in a manner that complies with laws applicable to your communications, and that you have otherwise provided notices and obtained permissions that are required under applicable law.

Emphasis mine. I think this issue may no longer be relevant.

**Comment by nicpottier** [comment]
Yes, thanks. Looks like opt-in can be collected via normal messaging now without all their previous requirements, which are all possible within RapidPro already.

Win for procrastination! :) Closing.
