### ISSUE TITLE
Consider adding `trim_left` and `trim_right` to Excellent

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1162]
These come in really handy for a lot of use cases. Just had one with a customer wanting the telephone path without the leading `+` which turns into the quite verbose (and imprecise):
  `@(replace(urn_parts(urns.tel).path, "+", ""))`

Which would be a bit more correct as:
  `@(trim_left(urn_parts(urns.tel).path, "+"))`

**Comment by rowanseymour** [comment]
I was convinced we had a `trim` function but apparently not!

For this specific case, another approach would be letting users customize `format_urn` like.. 
```
@(format_urn(urns.tel)) => (415) 555-2671
@(format_urn(urns.tel, "e164")) => +14155552671
@(format_urn(urns.tel, "foo")) => 14155552671
```

**Comment by nicpottier** [comment]
We could indeed add options to `format_urn` but seems we could address more use cases by adding `trim_`

**Comment by rowanseymour** [comment]
Not disagreeing with adding trim functions, just saying for this particular case `@(trim_left(urn_parts(urns.tel).path, "+"))` is a pretty un-obvious solution.

**Comment by nicpottier** [comment]
Yep, though as a datapoint the user was looking for it!

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/goflow/pull/877
