### ISSUE TITLE
Orgs with channels with different countries can't resolve non-international phone numbers

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1166]
US and CA both use `+1` but `Org.calculate_country_code` won't return a country code if it sees channels for more than one country. This means simulation environments passed to goflow don't have `default_country` set, and thus we can't infer a default country code for phone numbers. 

Mailroom does this differently - it 1) doesn't look at location data 2) picks the lexically first country code.

Need to make mailroom and RP's logic for what an org's country is match.

We could make US/CA an exception and just return 'US' ?

**Comment by rowanseymour** [comment]
Tho I guess that wouldn't work - if we pick one of US or CA, `has_phone` would still reject numbers that are from the other one...

**Comment by rowanseymour** [comment]
On further thought.. maybe best to move away from the idea of an org having a single country and make country selection explicit in places like `has_phone`. Can still default to a country when a org really does have a single country.

I.e. stick a country drop down beside the rule..

<img width="639" alt="Captura de Pantalla 2020-03-03 a la(s) 13 08 36" src="https://user-images.githubusercontent.com/675558/75805696-4daa6180-5d50-11ea-95fe-8863e06f03df.png">

**Comment by ewheeler** [comment]
many Caribbean nations also share the `+1` international dialing prefix: AG, AI, AS, BB, BM, BS, DM, DO, GD, GU, JM, KN, KY, LC, MP, MS, PR, SX, TC, TT, VC, VG, VI, UM

**Comment by rowanseymour** [comment]
From playing around with numbers I can find online, looks like the phonenumbers library is ok with being passed the wrong country code, e.g (https://libphonenumber.appspot.com/phonenumberparser?number=613-941-6900&country=US), `isValidNumberForRegion()` will return false but `isPossibleNumber()` returns true.

So we can fix this specific case by returning either of US/CA.

To fix this more generally, for orgs with multiple countries that don't share the calling code we can change the engine to use the country of the current channel.

**Comment by rowanseymour** [comment]
One place we still need the concept of a single org country is contact queries - we allow local numbers in queries and rewrite them as international.
