### ISSUE TITLE
Refresh WhatsApp Contacts on CELERYBEAT_SCHEDULE

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1169]
Hi everyone,

I had a problem with WhatsApp channel when sending message templates to whats app contacts. Sometimes the WhatsApp API return the problem:
```{"meta":{"api_status":"stable","version":"2.27.8"},"errors":[{"code":1006,"title":"Resource not found","details":"unknown contact"}]}```

If I click on Refresh Contacts on channel configuration, the message sent successfully to the contact that presents the error "unknown contact".

The task `refresh_whatsapp_contacts` should be on the CELERYBEAT_SCHEDULE list on settings_common to avoid this problem? What do you think?

Regards.

**Comment by rudigiesler** [comment]
Hi

Calling the contacts endpoint for all contacts regularly might have some
issues.

Firstly, WhatsApp is quite strict on the ratio between calls to the
contacts endpoint and the number of contacts you send messages to, to avoid
you scraping their contact data, and so they might ban/block your number if
you're doing this often, but aren't messaging all of your contacts often.

Secondly, it's quite a slow endpoint on the API, and so for large amounts
of contacts (especially for large installations with many organisations
that have many contacts each), this task might take too long to do on a
regular basis for all orgs.

The way we solved this in our previous system is, we tried to send the
template, if it failed with that specific error message, then we called the
contact endpoint, and then tried to send the message again after that.
Maybe that is something that can be done in courier?

Regards,
Rudi.

**Comment by matmsa27** [comment]
Hi @rudigiesler , thanks for the observation.

So, always that the whatsapp return this message, we need the send the refresh_contact sending only the contact that receive the error to whatsapp instance endpoint?

@nicpottier can we implement this on courier?

Thanks a lot.

**Comment by nicpottier** [comment]
Ya, so to be clear, the WhatsApp implementation in RapidPro is made to work with people who opt in as opposed to initiating contact with users who haven't contacted a number before. The "Refresh" is used when you have "reset" a WhatsApp docker instance and need to populate contacts that had previously existed in the WhatsApp's docker address book previously.

We could call the add case when we know it isn't present, but note this isn't a synchronous call, it only initiates a fetch, it takes some amount of time for that contact to actually be added. Could try sleeping for say five seconds and try sending again and erroring the second time (to be retried in 5 minutes) if we wanted though.

I'm fine with that being added.

**Comment by rudigiesler** [comment]
With our experience, even if the user has opted in to messaging (we've done
a contact check for them before, or they've messaged us), and the docker
instance hasn't been "reset", we still run into this issue where contacts
seem to have been "forgotten" and requires the additional contact check.
This happens to random contacts, not all contacts at the same time.

**Comment by koallann** [comment]
Hey @nicpottier, the WhatsApp docs says the following about sending messages to contacts:

> Best practice is to check contacts before each message send, however you do not need to check contacts to respond to an incoming customer message, you can immediately respond using the wa_id. There is no additional cost as results are cached. If you check too many phone numbers without sending to them, you will be banned. Take care to check only phone numbers critical to your business that you have already received opt-in for.

(https://developers.facebook.com/docs/whatsapp/api/contacts?locale=en_US#contacts)

So, wouldn't the recommended behavior to send each message on Courier be as follows?

- Check the contact validity by `POST /v1/contacts` with the following body:
```json
{
    "blocking": "wait",
    "contacts": ["{{only message contact}}"],
    "force": true
}
```
- If `valid`, proceed by `POST /v1/messages`; sending message fails, otherwise.

That's, the contact check occurs synchronously with `"blocking": "wait"`.

(https://developers.facebook.com/docs/whatsapp/api/contacts?locale=en_US#blocking)

**Comment by rudigiesler** [comment]
I would take that one step further, and only do the first step if we get an error message. ie.

1. Try do a `POST /v1/messages`.
2. If it fails with the specific contact error, then do a contact check by `POST /v1/contacts`
3. If the contact check is valid, do the `POST /v1/messages` again.

The contact check endpoint, especially with `wait` blocking, can be very slow, so we could run into performance issues (and API limits) if we do it before every message send. This way allows us to only do it when necessary.

The above docs also suggest that we only need to do this before sending template messages, so we can save on API calls by also only having this functionality for templates, not for normal messages.

**Comment by nicpottier** [comment]
Ya, that feels more right @rudigiesler  Though I think you do need to add the contact even for non-template messages before you can send, so seems you have to deal with the missing contact case there as well.

**Comment by matmsa27** [comment]
Thanks a lot, @rudigiesler and @nicpottier . PR coming soon.
