### ISSUE TITLE
Create Message Feature Is Missing On The Flow 

### ISSUE THREAD

**Issue by Lemmynjash** [rapidpro/rapidpro#1173]
Hello Guys 

I have followed every steps from this link [This Link](https://rapidpro.github.io/rapidpro/docs/development/)

I have successffully followed evey step on my localhost machine, but when i create a new Flow the new flow has a missing Create New Message feature.

This is how it looks like this find the attached Image link below:
[Image of how it looks like ](https://drive.google.com/open?id=1Nlp9LXNhdrf-ne5njt7Ov5O8Y3lzIBUg
)

If i inspect i get this error 
```
Failed to load resource: the server responded with a status of 404 (Not Found)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:59)
```

Is there something i am missing 

I am stuck kindly assist 

Thank you

**Comment by ericnewcomer** [comment]
Hi Lemmy,

I would check the network tab of your browser console. It looks like you
are getting 404s which suggests you don’t have endpoints/proxies configured
to work properly. Knowing which urls are failing will help you track that
down. My guess without seeing that is it’s failing to reach your mailroom
instance.

**Comment by Lemmynjash** [comment]
Hello @ericnewcomer 

Thank you for taking your time to reply,
I appreciate

I navigated to the Network tab and found where the 404 Error comes from Kindly view the Image Below 
[Network Tab Inspect Error on completion.json](https://drive.google.com/open?id=18zL3aCWNo9FQl31ksaXu0LvmkwF_5Ibr
)

For a clear view please see the image below:

[completion.json Error](https://drive.google.com/open?id=1D_Z50ZgJqnInlOgIG0t3011tudY7uT-P)

Below shows the error am getting 

Kindly assist thank you

```
Request Method: | GET
-- | --
http://127.0.0.1:8000/mr/docs/completion.json
Using the URLconf defined in temba.urls, Django tried these URL patterns, in this order:

^ ^airtimetransfer/$ [name='airtime.airtimetransfer_list']
^ ^airtimetransfer/read/(?P<pk>\d+)/$ [name='airtime.airtimetransfer_read']
^ ^api/$ [name='api']
^ ^api/v2/
^ ^api/apitoken/refresh/$ [name='api.apitoken_refresh']
^ ^api/resthooks/
^ ^webhookresult/$ [name='api.webhookresult_list']
^ ^webhookresult/read/(?P<pk>\d+)/$ [name='api.webhookresult_read']
^ ^apk/create/$ [name='apks.apk_create']
^ ^apk/update/(?P<pk>\d+)/$ [name='apks.apk_update']
^ ^apk/$ [name='apks.apk_list']
^ ^archive/read/(?P<pk>\d+)/$ [name='archives.archive_read']
^ ^archive/run/$ [name='archives.archive_run']
^ ^archive/message/$ [name='archives.archive_message']
^ ^campaign/create/$ [name='campaigns.campaign_create']
^ ^campaign/read/(?P<pk>\d+)/$ [name='campaigns.campaign_read']
^ ^campaign/update/(?P<pk>\d+)/$ [name='campaigns.campaign_update']
^ ^campaign/$ [name='campaigns.campaign_list']
^ ^campaign/archived/$ [name='campaigns.campaign_archived']
^ ^campaign/archive/(?P<pk>\d+)/$ [name='campaigns.campaign_archive']
^ ^campaign/activate/(?P<pk>\d+)/$ [name='campaigns.campaign_activate']
^ ^campaignevent/create/$ [name='campaigns.campaignevent_create']
^ ^campaignevent/delete/(?P<pk>\d+)/$ [name='campaigns.campaignevent_delete']
^ ^campaignevent/read/(?P<pk>\d+)/$ [name='campaigns.campaignevent_read']
^ ^campaignevent/update/(?P<pk>\d+)/$ [name='campaigns.campaignevent_update']
^ ^ ^calls/$ [name='channels.channelevent_calls']
^ ^channels/
^ ^c/
^ ^channels/types/
```

**Comment by rudigiesler** [comment]
Hi @Lemmynjash 

That looks like requests to Mailroom are going to RapidPro instead of Mailroom.

It seems like the mailroom URL is set correctly in the local dev settings file `settings.py.dev`, so please ensure that you are using those settings (the command is in the "Clone RapidPro" step of the development server setup).

The setting is `MAILROOM_URL`, and defaults to http://localhost:8090, so ensure that it is set to that, and that mailroom is running on that port.

**Comment by Lemmynjash** [comment]
Hello @rudigiesler @ericnewcomer 

Thank you for your reply 

I appreciate your quick response 

When I looked closely on the settings.py the **MAILROOM_URL** has already been setup to the default  **http://localhost:8090** 
take a look below 

![Settings.py](https://user-images.githubusercontent.com/11975890/76512573-f601a980-6465-11ea-93ee-9e9ccac39a58.png)

 when i run the mailroom it runs perfectly

 kindly have a look at the below image its running with the default **http://localhost:8090**

![MailRoom](https://user-images.githubusercontent.com/11975890/76512420-ade28700-6465-11ea-870c-1047936651c9.png)

But still am getting the same error is there something i am missing

**Comment by rudigiesler** [comment]
Looks like the front end just looks for mailroom in a relative but hardcoded `/mr/` path on the current host, so using different ports for mailroom won't work with the React front end: https://github.com/rapidpro/rapidpro/blob/master/templates/flows/flow_editor_next.haml#L211-L212

**Comment by Lemmynjash** [comment]
Any solutions so far? @rudigiesler

**Comment by rudigiesler** [comment]
No, I have no experience with the RapidPro front end. We'll have to wait for someone from Nyaruka to see if my suspicion is correct, and how to work around it.

**Comment by Lemmynjash** [comment]
Okay thank you for your quick response 
I hope the Nyaruka team will respond to the matter quickly

**Comment by ericnewcomer** [comment]
That’s exactly what I suspected. To run rapidpro on localhost I use nginx
on my machine  and proxy the /mr path to mailroom. This is also needed by
things other than the editor, such as completion in the send message modal.

Hope that helps!

**Comment by Lemmynjash** [comment]
![Reverse Proxy](https://user-images.githubusercontent.com/11975890/76698415-b29c7a80-66b3-11ea-8e3d-a0271a8a6913.png)

Hello @ericnewcomer  i hope you are well

I tried using a reverse proxy using nginx i have attached an Image above kindly take a closer look.
On the Left side shows the inspected error i am getting and the status of the mailroom running without a problem.

On the right side shows the nginx config file that i created to enable reverse proxy on mailroom.
I even changed the **MAILROOM_URL**

When i tested it it run swiftly kindly take a closer look at the below Image
![this image](https://user-images.githubusercontent.com/11975890/76698513-ce545080-66b4-11ea-86e3-e14c0952607a.png)

I ran rapidpro but am still getting the same error

Did i do it wrongly kindly assist.

How did you run rapidpro on localhost to use nginx on your machine mapping proxy the /mr path to mailroom?

I will appreciate your assistance.

**Comment by rudigiesler** [comment]
Hi @Lemmynjash 

Looks like you're only using nginx to route only your mailroom traffic, and you're not directing the /mr/ paths to your mailroom instance. So when rapidpro is looking at `localhost:8000/mr/...` , it's still going to django, and not to mailroom.

You want everything to go through nginx, and route `/mr/..` to mailroom, `/c/...` to courier, and everything else to django.

Here's an example nginx config:
https://github.com/praekeltfoundation/rapidpro-docker/blob/master/nginx/nginx.conf

Regards,
Rudi.

**Comment by Lemmynjash** [comment]
Awesooooome!!! @rudigiesler 

Thank you for your assist,
I just found out the mistake that I did and rectified it
Thank you so much its working now 

![Awesome](https://user-images.githubusercontent.com/11975890/76752671-3e380900-6791-11ea-9517-04f8ba45943f.png)
