### ISSUE TITLE
Better Flow Translation Pipeline

### ISSUE THREAD

**Issue by paradoxxjm** [rapidpro/rapidpro#1176]
**Problem Description**
There is no simple way to confirm that a flow is fully translated. U-Report programme managers experience this when creating a flow or when adapting an imported flow. The yellow boxes in the flow view communicate when items are un-translated, but do not cover all elements (eg Rule Translations, Quick Reply Translations). Similarly, there is no way to mark items as "not requiring translation" (eg Wait for Response category names) and turn them from yellow to white, so yellow vs white loses meaning.

**User Story**
As a RapidPro user, I want to easily be able to see which elements of my flow still require translation, so that I can complete translation more quickly and accurately. I want to be able to mark elements as "translated" or "no translation" if they do not need translation.

**Comment by nicpottier** [comment]
Renaming this to just better translation support as I think that is the root issue. I think we think in general a dedicated translation page for a flow that is more a series of text boxes is better suited for the general case rather than having people translate from within a flow, especially when wanting to share flows with less technical users and have them translate them.

**Comment by rowanseymour** [comment]
Related: https://github.com/rapidpro/rapidpro/issues/841

**Comment by cbunicef** [comment]
It would be useful for this function to facilitate translation outside the platform. Referencing Roawn's issue above, that spreadsheet that is exported could be shared with translators who shouldn't be given access to RapidPro itself.

**Comment by nicpottier** [comment]
Yes of course, actually the thing that probably makes the most sense is to expose these as PO files as there are lots of tools (transifex among them) that are built to deal with those, deal with merging new entries, manage teams etc..

I'm actually going to say trying to build that all into RapidPro (again) is the wrong way about things. Our current editor native translation should remain for the simple use cases, but when teams start becoming involved or flows start getting very large we should be generating PO files and importing the translations.

I'm going to close this issue and add to #841 instead.

**Comment by cbunicef** [comment]
Just circling back on the core original issue - that it's now harder than before in the New Editor to confirm exactly what translation still needs to be done, and also not possible to mark something as "doesn't need translation". I think it's important for users to actually be able to see eg "100% translated" on a flow to know they are finished and have reviewed everything. It doesn't seem like that will be covered by #841.

**Comment by rudigiesler** [comment]
There are many tools to manage PO files, like POEdit, which make it very easy to see what is and isn't translated, so I think it solves that issue:
![image](https://user-images.githubusercontent.com/8234653/77287645-b6955180-6cde-11ea-9aba-ffbf910b96b6.png)

In terms of marking something as not needing translation, this is something that RapidPro would need to do, although you can probably work around it by pasting the content in the base language as the "translations".

One thing that isn't mentioned is translator notes, which is probably something else to consider.

I think for knowing when something is translated, exporting and importing PO files is the industry standard, and solves that problem well.

For marking not needing translation, and translator notes, I would consider those separate issues, and if they're important to create separate issues to discuss each one.

**Comment by rowanseymour** [comment]
Let's talk about PO files on https://github.com/rapidpro/rapidpro/issues/841
