### ISSUE TITLE
Flow JPEG Export

### ISSUE THREAD

**Issue by paradoxxjm** [rapidpro/rapidpro#1177]
**Problem Description**
RapidPro users in a UNICEF country office spend enormous amounts of time translating the flows into PowerPoint or Word in order to better present ideas to programme colleagues.  As easy as it is to mock-up a quick flow and demo it, could we not also add an option for downloading the Flow Editor into a JPG or other format that could be used in a presentation for programme colleagues?

**User Story**
As a UNICEF RapidPro power user, I want to be able to download a flow that I've made in the flow editor to a JPG or other file format, so that I can use it in a presentation to programme colleagues to obtain their buy-in.

**Comment by rowanseymour** [comment]
In theory this isn't so difficult to do, an HTML canvas can be rendered to an image. The only advantage this gives over a screen capture is that you can capture the entire canvas without scrolling.. tho that also then has the potential to create really really big jpegs.. I can't help thinking the best solution for this particular use-case is using the browser zoom out feature and taking a screenshot...

**Comment by nicpottier** [comment]
Note that a lot of people use various browser plugins to accomplish this:
  https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en

Main downside here is that the grid background is still present, as are other superfluous items.
