### ISSUE TITLE
Question randomization

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1185]
Two ways to approach this. 

1. Randomized paths in the flow:

<img width="945" alt="Captura de Pantalla 2020-03-18 a la(s) 11 16 08" src="https://user-images.githubusercontent.com/675558/76982464-effa4580-6909-11ea-9b36-8079c03a7605.png">

Small downside is onus is on user to connect *everything* back to router.. but at least there's no magic.

2. Randomized data accessible in the flow:

Maybe list of questions that can be shuffled.. and then those are used as templates for nodes that ask a question.. little harder to think how this might work when responses look different between questions.

**Comment by rudigiesler** [comment]
When we've done this in the past, one of the requirements was to have both the question order, and the order of the options, randomised (they weren't just yes/no options).

We ended up building an external tool to randomise this and keep track of questions and answers, but it would be great to have this sort of thing built in: https://github.com/praekeltfoundation/lebombo

**Comment by nicpottier** [comment]
Ya the randomizing of options is definitely another important bit (may belong in another issue). The rough bit there is the categorization if using A/B/C .. though even that should be possible since I'm pretty sure we allow variables in rules.

So it is conceivable that we could have a special node type that is hiding an action/ruleset that basically allows multiple choice that is randomized.

**Comment by nicpottier** [comment]
(for the record I think the "random once" router makes the most sense from a randomized question perspective)

**Comment by rowanseymour** [comment]
Created https://github.com/rapidpro/rapidpro/issues/1186 to brainstorm answer randomization which is a harder nut to crack. So question is should we move forward with this regardless of what we decide for #1186 ? I think so.

**Comment by nicpottier** [comment]
I think so, especially since it is low hanging fruit.

**Comment by rowanseymour** [comment]
This is ready to go in the engine via https://github.com/nyaruka/goflow/pull/888
