### ISSUE TITLE
Answer randomization

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1186]
Following on from #1185... brainstorming how randomization of answers could be implemented.. trying to rely on low-level primitives as much as possible..

Say you have a question like...

```
Favorite breed of dog:

A. Jack Russell
B. Schnauzer
C. Sheepdog
```

If we make some simplifications and say that only the category of results matter, and answers will be input as A-Z characters..

We need to generate a message body that lists the answers in random order. If there was a magic function `C` which could return nth shuffled category name, with a shuffling that is consistent for each call within the scope of this question to this contact, then we could do...

```
Favorite breed of dog:

A. @(C(0))
B. @(C(1))
C. @(C(2))
```

For example `C(0) => Schnauzer`, `C(1) => Sheepdog` and `C(2) => Jack Russell`

```
Favorite breed of dog:

A. Schnauzer
B. Sheepdog
C. Jack Russell
```

and if there was another magic function `M` that could return a similarly shuffled value to match on, then we could build a set of rules like...

Test | Args | Category
--------------|-------------------|--------
has_any_word | `@(M(0))` => `c` | Jack Russell
has_any_word | `@(M(1))` => `a` | Schnauzer
has_any_word | `@(M(2))` => `b` | Sheepdog

Then the question is if we can find a sane way to implement `C` and `M`. We could say that nodes get to provide context to expressions, and that maybe on a node with categories, you can access those as a list, so then `C(N)` becomes:

```
@(S(node.categories, N))
```

And maybe `M(N)` becomes.. something that can return the same shuffling but on a set of input values:

```
@(S(array("a", "b", "c"), N))
```

And now we just need to implement `S` which provides the same shuffling of a list of items, within the scope of asking this question to a contact.

Could set a result to RAND() and use that as a seed? 

Probably a much simpler way of approaching this that I'm missing..

**Comment by rowanseymour** [comment]
Tho the whole `node.categories` thing assumes that we've merged the question and router into the same node.. so I dunno... maybe it should be a bit higher level and have a function/context that provides the whole formatted list of options

**Comment by rudigiesler** [comment]
For the randomisation functions, what about a function that consistently randomises given an input? Then you could use something like the run UUID to randomise.

eg. `@(S(run.uuid, node.categories))`, which will always output the same ordering for the same `run.uuid`?

Similar to how you use hashing to split traffic where each user needs to be directed to the same node.
