### ISSUE TITLE
Website SSL Certificate Expired 

### ISSUE THREAD

**Issue by billyrrr** [rapidpro/rapidpro#1191]
<img width="671" alt="Screen Shot 2020-04-02 at 9 37 51 AM" src="https://user-images.githubusercontent.com/24789156/78274818-a131db80-74c5-11ea-908b-d40fa489b1c0.png">
Errors encountered when visiting rapidpro.io, https://community.rapidpro.io/ or http://rapidpro.io/.

Although this error can be skipped in some browsers, an official website with the valid SSL Certificate can attract more developers to help. 

Thanks!

**Comment by nicpottier** [comment]
@ewheeler is working on this I believe.

**Comment by paradoxxjm** [comment]
This issue has now been resolved. Apologies for the delay!
