### ISSUE TITLE
Prevent automatic flow element shifting that changes Flow Start

### ISSUE THREAD

**Issue by cbunicef** [rapidpro/rapidpro#1192]
Flow elements automatically shift to make space. This can happen when adding or moving flow elements, or sometimes when changing browser zoom levels.

Sometimes this automatic shift changes the Flow Start element, which causes problems. Quick video here: https://unicef-my.sharepoint.com/:v:/g/personal/cbrooks_unicef_org/ETP2Vgly9ZhLhG2AEriXbcQBqxeRdw6dO2V4QtmM8jzzfA?e=h23gH6

**Comment by cbunicef** [comment]
I don't really work with RapidPro anymore, but I would still advocate for this enhancement if it hasn't been incorporated yet.

**Comment by ericnewcomer** [comment]
I agree. Going to open an issue on the floweditor for this.

**Comment by ericnewcomer** [comment]
Added here: https://github.com/nyaruka/floweditor/discussions/1170
