### ISSUE TITLE
Change Graph API Version on Facebook 

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1193]
Facebook raising warnings to applications that are using **Graph API v2.12**. The API still available until 5 May 2020. 

We need to migrate the API requisitions to **Graph API v3.0** or **higher**.

![facebook](https://user-images.githubusercontent.com/10725273/78561758-a907bd80-77ee-11ea-835e-bbc79df5a76d.png)

Beyond make changes on requisitions localized on channels.fcabebook.type, there are any other modifications to change Graph API Facebook? Does Wich risk to do this modification?

Regards.

**Comment by nicpottier** [comment]
Ya, we have to investigate all the places where we are using the graph API and evaluate what makes the most sense there.

**Comment by nicpottier** [comment]
Their tools say we wouldn't need any changes to upgrade to the latest v6, but that never seems to actually be the case with Facebook. :)

**Comment by matmsa27** [comment]
Yes, the fear is to update to a long different version, and requisitions will be broken. There is an easy way or process that we can help to validate this?

**Comment by nicpottier** [comment]
You can try moving some over to v6 to see and let us know.. I checked our and it *looks* like it should be fine but we won't know until someone runs it for a while. This is definitely on our plate but we have so many other things to look at it may be a bit before we can look at it.
