### ISSUE TITLE
ZenDesk Integration

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1194]
Some notes from exploring this a bunch..

ZenDesk provides a way of creating what they call Channel Integrations:
  https://developer.zendesk.com/apps/docs/channels-framework/introduction

By default, once packaged these allow a user to add a new "Channel" to ZenDesk for incoming and outgoing messages. Incoming messages come in via ZenDesk polling a URL for new messages (from RapidPro) and they push outgoing messages back to us.

This works reasonably well but the polling period is 2 minutes, so not very interactive. There are ways of making it faster but it is more complicated (but seems doable):
  https://developer.zendesk.com/apps/docs/channels-framework/push

One missing piece though is that we really want tickets being marked as closed on the ZenDesk side to make the contact "active" again and able to interact with flows etc.. The channel integration doesn't provide any way to do that.

A query to their support has them pointing us to configure an external target and corresponding rule to be notified on ticket changes:
  https://support.zendesk.com/hc/en-us/articles/203662136-Notifying-external-targets

So that could be configured with a URL to notify RapidPro when someone closes a ticket. I played with this a little and wasn't able to get the ticket ID out but I'm sure it is possible.

So the workflow for a user for the integration would be:
 1. Add a new "channel" on the ZenDesk side (in theory we could get our app "approved" so it appears by default). They enter in their RapidPro credentials and that's all tied in automatically.
 2. Give the user instructions to set up an external target and trigger on the ZenDesk side that point to RapidPro so that when tickets are closed we can reactivate the contact. This is sadly also a multistep process.

Not seeing any simpler strategy right now that lets us close the loop on having a contact be "paused" and human handled.

One note here is that we've had some feedback that maybe it is desirable to have people both human handled and rapidpro-handled, but we really haven't wrapped our head around how that could work. (if you broadcast a poll out, how do you know the response belongs to the poll or a ticket that is opened for that user)

Related: #1127

**Comment by nicpottier** [comment]
As an aside, I also did some mild exploration of trying to hack this into email forwarding. The idea being that we generate a unique email address for a contact, then send that on to ZenDesk. That would open a ticket and replies would route back to us via email which would send a message out etc..

A ZenDesk text/plain email looks like:

```
##- Please type your reply above this line -##

Your request (5) has been updated. To add additional comments, reply to thi=
s email.
----------------------------------------------

Service Agent, Apr 10, 09:01 MST

What is your problem exactly, can you elaborate?

----------------------------------------------

Nic Pottier, Apr 10, 09:00 MST

I have a problem.

--------------------------------
This email is a service from Nyaruka.
```

So would be reasonably easy / 99% correct with some easy parsing rules. Sadly it doesn't look like ZenDesk sends anything about tickets being closed to the requestor, so it doesn't solve the problem above about being notified about ticket closures, so that still remains a big problem.

I also wonder how well it would scale, but I suppose email is pretty scalable!

**Comment by nicpottier** [comment]
(a bit more digging and being notified of tickets being closed is basically the same configuration as above in that you can set up a trigger to notify the requester that their ticket was closed)

**Comment by ericnewcomer** [comment]
Just to capture an internal conversation we just had publicly.

* Creating a ticket opens up forwarding to an external service (so messages co-exist) but does not change message handling behavior in the system.
* Later we should add in "Pause" and "Unpause" actions that correlate with ignoring triggers, flows, and campaigns. Should also add a "Close Ticket" action that removes them from any existing ticket (ie, create a campaign to close open tickets for contacts after a week of inactivity, etc)
* Later we should add "Ticket Opened" and "Ticket Closed" event triggers allowing users to model pausing without using pause actions (ie, removing from groups, trapping in a flow)
