### ISSUE TITLE
Escaping dialogues in flow editor with long lists

### ISSUE THREAD

**Issue by paradoxxjm** [rapidpro/rapidpro#1197]
I came across an interesting UI challenge for dialogues (e.g "Split by expression") that have many entries. As you'll see in the image, the number of variable/expression options pushes the "cancel" and "ok" buttons off the screen. The dialogue isn't movable and the "esc"  key doesn't close the dialogue on a Mac (Chrome browser). Initially, when I came across the issue I used the browser "back" button to return to the Flows window. When it happened again, I realized what had happened and I "zoomed" out further to enable me to see the buttons and press cancel.

This is certainly an edge case user interface bug. However, a few potential solutions include could be (1) have the "esc" key close the dialogue, (2) enable the user to "move" the dialogue, (3) add a close ("X) button to the top right-hand of the dialogue.

<img width="1440" alt="Screen Shot 2020-04-11 at 6 22 14 PM" src="https://user-images.githubusercontent.com/406181/79056333-56316a00-7c23-11ea-84e5-6dcb9aea75a1.png">

**Comment by nicpottier** [comment]
Ya, this is known and something we are looking at.
