### ISSUE TITLE
Message Templates not syncing across

### ISSUE THREAD

**Issue by smn** [rapidpro/rapidpro#1199]
We're seeing some issues with a Turn.io client trying to sync WhatsApp message templates between Turn.io and TextIt and they're not pulling through. According to our logs these message templates are not being polled every 15 minutes for the number in question by TextIt. Last I saw in our logs was around noon GMT on the 14th of April 2020. It has not been polled since.

What could cause this? In the past we removed the channel and added it again which made this problem go away for a while. I'm happy to help make this problem go away more permanently. 

Any pointers on where to start?

**Comment by nicpottier** [comment]
Hrmm, indeed. @norkans7 should be able to help. Can you remind us which accounts these would be under?

**Comment by smn** [comment]
The channel uuid in question ends with `0b933f5c7c72`

**Comment by norkans7** [comment]
There is a template that has content very long content than what we support and that was breaking the template syncing , the fix is in https://github.com/nyaruka/rapidpro/pull/2776

We'll log the error for the channel to Sentry but let the other channel continue to sync
