### ISSUE TITLE
Completion on flow variables isn't intuitive

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#12]
Our completion of @ variables doesn't do a great job when you want to stop at a subvariable.

IE, if you just want to do ```@flow.name``` if you first type @flow.name and press enter then the followng is inserted ```@flow.name.``` which won't evaluate correctly.

Need to fix our completion to do the right thing for sub-variables. (probably at the same time we switch everything to =() )

**Comment by ericnewcomer** [comment]
This behavior is now much better thanks to @norkans7.
