### ISSUE TITLE
Order of result columns in exports should match flow order

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1200]
This is a request from UNICEF Malawi. Makes sense, especially for linear questionnaires.

**Comment by rowanseymour** [comment]
I think this actually works for new editor flows since the editor always saves nodes by Y order

**Comment by ericnewcomer** [comment]
Can confirm the new editor saves in y order.

**Comment by rowanseymour** [comment]
OK so then solution for users here is stop using the legacy editor 😎
