### ISSUE TITLE
Send WhatsApp message templates with the correct language

### ISSUE THREAD

**Issue by koallann** [rapidpro/rapidpro#1206]
We need send message templates in pt-BR language, but we can see [here](https://github.com/nyaruka/rapidpro/blob/master/temba/channels/types/whatsapp/type.py#L67), on templates syncing, that both the codes `"pt-BR"` (is ignored, actually) and `"pt-PT"` are mapped to internal code `"por"`, and in Courier the language is mapped back to WhatsApp standard, how we can see [here](https://github.com/nyaruka/courier/blob/master/handlers/whatsapp/whatsapp.go#L781). Thus, a customer of ours was recently flagged by Facebook, because we are sending message templates with text in `pt-BR`, but language in `pt-PT`.

WhatsApp languages: https://developers.facebook.com/docs/whatsapp/message-templates/creation#translations.

So, we wish to submit a PR soon and we want to confirm that right way to fix this is just by mapping languages from more than one country based on the country code, like `"por"` to `"pt-BR"` (+55) and `"pt-PT"` (+351), in other words, with URN path, get the country code and map to the ISO 639_2 code:

[envs.DeriveCountryFromTel(number string)](https://github.com/nyaruka/goflow/blob/master/envs/country.go#L19)
[envs.ToISO639_2(country Country)](https://github.com/nyaruka/goflow/blob/master/envs/language.go#L35)

**Comment by nicpottier** [comment]
Ya, I think this is the right approach and I wish we had thought of it at the time. As long as WhatsApp channels always have country codes then yes we should be able to do a one way mapping from the `iso2_country2` format to `iso639` back to `iso2_country2` when we need it.

So +1 from me at least.

**Comment by nicpottier** [comment]
Actually thinking about this more I see the challenge.

If you have a single WhatsApp channel that is syncing both `pt-BR` and `pt-PT` templates then we have no way of storing these currently in a way that lets us differentiate the two, which is the rub. So no matter what we do on the courier/mailroom side we wouldn't be able to say which of the Template objects we saved actually is the `BR` one vs the `PT` one.

Maybe we need to add a country code to templates and use that as well? Then we could accurately map those over?

**Comment by koallann** [comment]
I thought about why the WhatsApp language is not saved directly, why to convert from `iso2_country2` to `iso639` before is needed.

What the purpose of [TemplateTranslation.STATUS_UNSUPPORTED_LANGUAGE](https://github.com/nyaruka/rapidpro/blob/master/temba/channels/types/whatsapp/tasks.py#L206)?

**Comment by koallann** [comment]
I got a better understanding about the templates now...

A country code field like `django_countries.fields.CountryField` seems to work well here, thanks @nicpottier :+1:

**Comment by nicpottier** [comment]
Merged / fixed. Thansk.
