### ISSUE TITLE
MaxRequestBytes of Mailrooom web server as environment variable

### ISSUE THREAD

**Issue by koallann** [rapidpro/rapidpro#1208]
We've experienced a problem opening a big flow because Mailroom endpoint `"/mr/flow/migrate"` limits the request body in 1 MB and to fix this temporarily we increase the [MaxRequestBytes](https://github.com/nyaruka/mailroom/blob/master/web/server.go#L33) variable. We think about request our customer to break that big flow in another subflows, but it will break U-Report integration, since a poll is associated to a flow would be necessary to create a new poll to each subflow.

We would like to know if it's preferable to make `MaxRequestBytes` an environment variable and then submit a PR, as this `MaxRequestBytes` is limiting the request body for the Mailroom web server.

**Comment by rowanseymour** [comment]
Wow that must be a big flow.. is there anything weird about that flow that makes it so big? Lot's of translations? 

We used to have a "flow server" that was intended to be open to the public and I think that's where that limit came from, but now we only really need to worry about things like user webhooks which are limited via `config.WebhooksMaxBodyBytes`... so 

 1. we could just get rid of it
 2. we could bump it to 100MB
 3. we could make it a config variable (which makes it set-able as an env var)

I'd be fine with any of those... @nicpottier ?

**Comment by koallann** [comment]
That flow is of the quiz type and has 20 translations.

**Comment by nicpottier** [comment]
Some limit is better than no limit.. 32 MB ought to be enough for anyone? That is kinda massive though even with that many translations. Are we gzipping on the wire when we send that over I wonder?

**Comment by rowanseymour** [comment]
The issue is that we let golang do gzip compression internally, and that limit is just applied to the uncompressed bytes that we read from the request body.

32MB also sounds fine.

**Comment by rowanseymour** [comment]
(Python requests library also handles gzip compression internally so that should be happening)

**Comment by nicpottier** [comment]
Cool, ya was just making sure that wasn't missed but see the same.

**Comment by rowanseymour** [comment]
@koallann so let's just bump the limit to 32MB.. if your users are making flows that are bigger than 32MB you might start having problems elsewhere

**Comment by koallann** [comment]
Okay, I agree. Thank you everyone!
