### ISSUE TITLE
Documentation issue on developer instructions

### ISSUE THREAD

**Issue by litlfred** [rapidpro/rapidpro#121]
The documentation here
 http://rapidpro.github.io/rapidpro/docs/development/
could use a bit more explanation for those that are new to some of the tools.

For example this is what I had to do to get postgres configured with Peer authentication:
  sudo apt-get install postgresql-client  postgis*
  sudo -u  postgres createuser temba --pwprompt -d
  sudo adduser temba
  sudo -u temba  psql --user=temba postgres
    postgres=> create database temba;
    CREATE DATABASE
    \q

To get lessc and coffee-script installed:
   sudo apt-get install node node-less coffee-script
   

For building the virual environment
   sudo apt-get install python-virtualenv  postgresql-server-dev-9.3 python-dev ncurses-dev

Not sure what level of detail you want in the install instructions.

**Comment by nicpottier** [comment]
Cool, can you give us a pull request? (all the docs are on the gh-pages branch)

**Comment by litlfred** [comment]
Will try to (once I make sure everything is working).   in the meantime i will keep updating the orignial comment where there are gaps.

**Comment by allyshaban5** [comment]
The added command "sudo adduser temba" is of help.
Thank you Carl.

**Comment by litlfred** [comment]
See more here:
   https://github.com/rapidpro/rapidpro/issues/121

**Comment by litlfred** [comment]
@nicpottier it would be helpful to put directions for changing the port.   can you give me a hint?

**Comment by nicpottier** [comment]
Changing what port? RapidPro is a start Django app, so the same startup options are available:
  https://docs.djangoproject.com/en/1.7/ref/django-admin/#runserver-port-or-address-port

**Comment by litlfred** [comment]
OK.  thanks - I haven't done any Django development, so didn't know.

**Comment by litlfred** [comment]
OK to put a disclaimer that these directions ar for Ubuntu 14.04?

**Comment by nicpottier** [comment]
We actually run on 12.04, but I can double check that things aren't too specific.

**Comment by litlfred** [comment]
One last hint to get through the install (hopefully) if you don't mind -- getting the error below.  Any suggestions?

(env)litlfred@masala:~/rapidpro$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'temba.settings' (Is it on sys.path? Is there an import error in the settings file?): Could not import settings 'temba.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named settings

**Comment by nicpottier** [comment]
Sounds like you forgot to link in the settings:
  ```ln -s temba/settings.py.dev temba/settings.py```

**Comment by litlfred** [comment]
You may run into a Ubuntu 14.04 specific thing on the package: postgresql-server-dev-9.3 

I can indicate the correct version for 12.04 (do you happen to know)?

**Comment by nicpottier** [comment]
I think that package will work on either.

**Comment by litlfred** [comment]
No, it's there:
(env)litlfred@masala:~/rapidpro$ ln -s temba/settings.py.dev temba/settings.py
ln: failed to create symbolic link ‘temba/settings.py’: File exists

(env)litlfred@masala:~/rapidpro$ ls -l temba/settings*
-rw-rw-r-- 1 litlfred litlfred 29860 Jan 23 14:34 temba/settings_common.py
lrwxrwxrwx 1 litlfred litlfred    21 Jan 23 15:11 temba/settings.py -> temba/settings.py.dev
-rw-rw-r-- 1 litlfred litlfred  3874 Jan 23 14:34 temba/settings.py.dev

**Comment by litlfred** [comment]
I updated the documentation here:
  https://github.com/litlfred/rapidpro/commit/3a7a92643161f5dbe26fbeb9f8dc10fbdcb6dfc4
will initiate the PR once the settings.py issue is resolved (not sure how to do it myself)

**Comment by litlfred** [comment]
ping.  any suggestions on the python manage.py syncdb issue?  Ally has the same problem.

**Comment by nicpottier** [comment]
Sorry, busy Monday. :)

Looks like the problem is just the symlink isn't properly set up.

This should fix it (from the /rapidpro dir)
```
cd temba
rm settings.py
ln -s settings.py.dev settings.py
```
Then go back out to /rapidpro and do the manage commands.

**Comment by litlfred** [comment]
Oops.  Should have caught that.  

Now, I have rapidpro listening, but when I point my browser to it, I get:
<pre>
Unable to apply CompilerFilter (lessc --include-path="/home/litlfred/rapidpro/temba/../static/less" {infile} {outfile})
Request Method:	GET
Request URL:	http://masala:8000/
Django Version:	1.7.1
Exception Type:	FilterError
Exception Value:	
Unable to apply CompilerFilter (lessc --include-path="/home/litlfred/rapidpro/temba/../static/less" {infile} {outfile})
Exception Location:	/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages/compressor/filters/base.py in input, line 173
Python Executable:	/home/litlfred/rapidpro/env/bin/python
Python Version:	2.7.6
Python Path:	
['/home/litlfred/rapidpro',
 '/home/litlfred/rapidpro/env/src/smartmin',
 '/home/litlfred/rapidpro/env/src/django-modeltranslation-master',
 '/home/litlfred/rapidpro/env/src/django-quickblocks-master',
 '/home/litlfred/rapidpro/env/src/django-celery-transactions-master',
 '/home/litlfred/rapidpro/env/lib/python2.7',
 '/home/litlfred/rapidpro/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/litlfred/rapidpro/env/lib/python2.7/lib-tk',
 '/home/litlfred/rapidpro/env/lib/python2.7/lib-old',
 '/home/litlfred/rapidpro/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/litlfred/rapidpro/env/local/lib/python2.7/site-packages',
 '/home/litlfred/rapidpro']
</pre>

Full screenshot is here:
http://awesomescreenshot.com/0fe49ttsdf

**Comment by ericnewcomer** [comment]
Do you have lessc (Compiler for Less) installed on your machine?

**Comment by litlfred** [comment]
Yes, but maybe it want installed correctly.  See the way I installed it at the top of this issue (via npm)

Cheers,
-carl

On Jan 26, 2015 4:08 PM, Eric Newcomer <notifications@github.com> wrote:

Do you have lessc (Compiler for Less) installed on your machine?

**Comment by litlfred** [comment]
Yep, that was it -- installing via npm is a no go.  I switched to using the node-less package and that fixed it.

**Comment by litlfred** [comment]
BTW now that I got it up and running, is there a default admin account / password?

**Comment by ericnewcomer** [comment]
Oops, missed that, great that you've got it working.

You'll want to create your own superuser using standard django methods.

https://docs.djangoproject.com/en/1.7/ref/django-admin/#django-admin-createsuperuser

**Comment by allyshaban5** [comment]
It worked for me too.
Thank you guys.
