### ISSUE TITLE
Feature request: Message Delivery Smoothing/Throttling

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#1210]
Hi!
It would be really fantastic if we could smooth out delivery of a flow to a group of contacts across a specific time period, and/or throttle delivery to N#/hour. 

Use Case: a survey sent to 10k people turns into a [thundering herd problem ](https://en.wikipedia.org/wiki/Thundering_herd_problem) when all are sent at once. A number of elements are impacted, but most importantly, the amount of potential customer service requests are deeply front loaded. 

Thanks!

**Comment by nicpottier** [comment]
So Courier definitely does some throttling, you can set the max messages per second per channel and it will only deliver messages that fast. In many cases that's enough to accomplish what you want. Note that that only affects message delivery though, flows and such will be started as fast as possible.

Throttling is a surprisingly difficult thing to do well/right, so this likely isn't something we would add in addition to the throttling Courier already does. Depending on your use case you can also randomly assign contacts to groups and meter them out that way. (ie, 3 cohorts that you start on different days etc) Short term that is probably your best option if you want the throttling to happen at the run level.

**Comment by cromulus** [comment]
We essentially do the randomized group assignment trick.

I think throttle/rate limit is perhaps the wrong term.... I think it's more akin to the delay between popping contacts off a queue to start the flow. 

Would also substantially help with avoiding hitting the twilio queue as well when starting a bunch of contacts in a flow.

**Comment by nicpottier** [comment]
Twilio queue should be handled by setting max TPS on your channel, if you set that to match your speed there you should never queue.

**Comment by cromulus** [comment]
Didn't know that was a thing. Will look into it.

Still, though, for the humans running supports, the thundering herd is a thing. Starting contacts in a flow at a smooth, consistent rate would be delightful. Thanks!
