### ISSUE TITLE
Dragging out of Message Compose dialog cancels it

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1212]
If you select text in a message compose box and let go of your drag outside the dialog, then the dialog gets hidden. People who copy/paste with speed seem to be triggering this. Guessing we are reacting on mouse-up here as a "cancel" of the dialog without taking into account the mouse-down.

**Comment by rowanseymour** [comment]
Can't reproduce.. so maybe fixed

**Comment by ericnewcomer** [comment]
Can't reproduce with new components.
