### ISSUE TITLE
Enhanced Sentry Error Reporting

### ISSUE THREAD

**Issue by tybritten** [rapidpro/rapidpro#1217]
One of our biggest issues is debugging and troubleshooting errors. We've recently started to move all our error reporting to Sentry already, and have some ideas about extending the current sentry error reporting in RP.

Not sure if the best approach is to make the logging handler more pluggable/configurable so we could pass more stuff in (and maybe others want to plug in support for stuff other than sentry?) or if it's just finding common, sane things to add to sentry.

The high level wants we have is:
* more context around errors - tagging errors with the flow and flow run IDs, maybe include not just the failing error but the offending input/result. Contact UUID is nice, but many of our contact interactions might trigger dozens of flows so traversing the logs on the contact detail page can be difficult.
* support for releases. the components should mark their release `mailroom@x.y.z` in sentry.

Beyond that, what would be really great is an integrated flow feature of "report error" or "log error" to capture relevant bits when flows fail. For example, right now we have a bunch of webhook calls to report a webhook call has failed. 

Not sure if global (per org) settings for something like that make sense, or just another flow node that you configure once.

I'll let @chris-erickson chime in with anything else he can think of.

**Comment by chris-erickson** [comment]
Yeah to clarify a bit it's two things, we can split discussion as you see fit.

- Improve Sentry usage on current apps and setups (adding more context to existing error calls, releases)
- Expand ability to interface with error and logging tools in ways that don't necessarily generate more web hooks and corresponding DB load (do it async, or externally with a log parser).

**Comment by rudigiesler** [comment]
Just want to add a :+1: here for adding error reporting in flows (the second point). Currently we're adding webhooks to flows on error paths, and trying to include as much information in the webhook to allow us to debug (these webhooks are currently just going to a slack channel). This has the added complexity that those webhooks themselves may fail.

Would be great to be able to have a "report error" action, (eg. for webhook failure branch), as well as just general errors in flows (eg. unable to calculate expression), go to something like sentry, where it's more easily manageable.

**Comment by chris-erickson** [comment]
Yep that's what we do!  It's fine until it's _really_ unhelpful (ie. failing webhook at a really high rate).

<img width="676" alt="Screen Shot 2020-05-13 at 9 44 51 AM" src="https://user-images.githubusercontent.com/3322287/81827750-b22b2f00-94fe-11ea-88f3-da6a980dcc14.png">

**Comment by nicpottier** [comment]
So to be clear, the feature request here is not about better error reporting for actual RapidPro errors but easier reporting of runtime flow errors due to invalid expressions or failed webhooks etc.. is that right?

**Comment by tybritten** [comment]
its actually two separate requests I think. the first smaller ask is improved error reporting of actual RP errors, then the larger vision is exactly that- enhanced runtime error reporting. 

At a 10,000 foot view an error is an error. If mailroom trips on flow or if the webhook fails the outcome of the user's experience is the same.

**Comment by rowanseymour** [comment]
Well I would say we still want to segregate errors by who potentially needs to fix something. We have error events in sessions which are usually indicative of flow design issues, e.g. an expression referencing a field that doesn't exist.

And we have errors which we send to sentry which are usually indicative of something gone wrong at a code level.. things we as developers need to address.

Yours is a bit of a special case where you're both a developer and flow designer!

I think the biggest problem currently is that sentry errors coming from mailroom/courier have very little context which is a limitation of the go libraries we're using there.

**Comment by tybritten** [comment]
Yes, that's a great description, which is why sentry might not be the answer for both problems in a hard coded fashion.

As far a sentry currently in mailroom/courier, I think we could add a few minor handling things to it add some context

**Comment by tybritten** [comment]
On the sentry front, might be a good time to move to sentry-go from raven-go too.

**Comment by nicpottier** [comment]
So to be clear this issue is about making golang error reporting have more context. (some concrete examples of where this isn't as good as you want would be super helpful)

Note that golang sentry errors will never measure up to python sentry just due to Python being dynamic and being able to dump the stack etc.. But we can certainly see about adding specific fields that are missing.

"flow errors" (webhook, expressions) should be a separate issue if people want to chat about that.

**Comment by tybritten** [comment]
Sure, I'll create an issue for that and mention those that chimed in there.

A perfect example is when we had that slice issue in mailroom.
`panic handling task: runtime error: slice bounds out of range [8:7]`
we get that message, the stack trace, and very limited context:
```
org_id queue | "handler"
runtime.GOMAXPROCS | 8
runtime.NumCPU | 8
runtime.NumGoroutine | 65
runtime.Version | "go1.13.9"
task | "{\"contact_id\":REDACTED}"
task_type | "handle_contact_event"
worker_id
```
So basically the contact's ID number and the time/date is the only useful information I have to go on, and nothing else to correlate it.

**Comment by tybritten** [comment]
I'm thinking of a new logrus hook for `sentry-go` that can take logrus fields and use them to add user scope and tags to sentry.

**Comment by nicpottier** [comment]
> A perfect example is when we had that slice issue in mailroom.
panic handling task: runtime error: slice bounds out of range [8:7]

Panic's are a special case because we don't have the normal context in our logrus context to annotate the sentry error as we usually do.

In that specific case it would be easy enough to put the task body in the context as well which would likely have given you a bit more clue. (though `contact_id` should have gotten you pretty far honestly)

Any fields added to an Error event in logrus is already added to Sentry, so don't think anything needs to change there. Which is why concrete examples are useful because it is more a matter of throwing in a few extra fields if they aren't providing enough context, not some rethinking of how error logging is working.

**Comment by tybritten** [comment]
So the same goes for that UTF8 error. The error had more context (run/session ids, etc) but was missing the body of that pg insert that caused the error. 
And on the context stuff what we were thinking about was using some of the sentry scope features like tags and users, which allow searching and grouping of errors. so feeding the contact id into the sentry user id scope.

**Comment by rowanseymour** [comment]
FYI we have a few issues in mailroom on this topic: https://github.com/nyaruka/mailroom/issues/220 https://github.com/nyaruka/mailroom/issues/190

**Comment by tybritten** [comment]
One other place that would be great would be archiver. Since all errors are logged as `error.ErrorString` sentry lumps them all together
