### ISSUE TITLE
New flow action: Merge contacts

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1218]
I would like to raise a discussion here. Did you need to merge contacts from different channels based in some contact fields at any point in using RapidPro for collecting data?

I tried to find a related issue here but, as I didn't find, I would like to start a thread here. I think that we can have a new action in the flow that could be called "Merge contact", and it would request the user to add a query (as they do for Start somebody else in a flow) and the result of this action will merge the original contact with URNs, contact groups, contact fields and message history from the contact that was selected in the query.

**Comment by nicpottier** [comment]
There's a lot of very difficult to solve edge cases around true merging. They could be in a flow independently, contact_ids are immutable on messages, archiving, etc..

Generally the way this is done is that the URN is "stolen" from one contact to another and this seems to satisfy the use cases we have seen. You just add the URN(s) from the other contact and that will bring them over.

Would that not work in your use case?
