### ISSUE TITLE
Problem Setting up RapidPro with Kannel

### ISSUE THREAD

**Issue by elovia** [rapidpro/rapidpro#122]
If anyone can help provide a way  configuration Kannel to connect a GSM modem with RapidPro?

Really hope of help from the experts.

**Comment by nicpottier** [comment]
Do you already have the GSM Modem working with Kannel?

**Comment by elovia** [comment]
yeah gsm modem is running as a sms gateway with kannel. My only difficulty to make the backend for RapidPro. Do I need to edit the file setting.py? Like what syntax should be written to the file?

Expect an answer from you Mr. nicpottier

**Comment by nicpottier** [comment]
Sounds like you just need to create a Kannel channel in your organization. Nothing needs to change in your settings.
