### ISSUE TITLE
Add GPS support for Facebook

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1223]
While not a thing in the SMS world, sending GPS coordinates is a pretty common thing in Facebook / WhatsApp / etc.. Would be nice to at the very least handle those types of attachments when receiving those messages (and making those available in flows).

Next would be to add a GPS field type so we could store these in a logical manner, allowing querying / grouping etc..

**Comment by nicpottier** [comment]
We could maintain our current "attachment" format of URLs using a `geo` scheme like `geo:37.786971,-122.399677`:
  https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by rowanseymour** [comment]
We already have support for `geo:` attachments no? Or at least we parse them from incoming messages on some channel types like whatsapp and we render them in the inbox views. Surveyor also allows collecting them from the phone itself.

**Comment by nicpottier** [comment]
Oh well, maybe this is just a Facebook attachment bug then! Will update.
