### ISSUE TITLE
Support protocol MQTT

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1229]
Some people commented on the possibility of Rapidpro making requests to terminals with MQTT protocols in addition to the requests it already has for the https protocol. Is it possible to make/implement requests to the MQTT protocols in Rapidpro?

**Comment by rowanseymour** [comment]
I'm skeptical there is enough demand for such a thing to warrant making it a first class thing in RapidPro.. I would try using a proxy for now, e.g. https://github.com/petkov/http_to_mqtt

**Comment by matmsa27** [comment]
Thanks a lot, @rowanseymour for the suggestion.
