### ISSUE TITLE
Return to the ability of setting the default flow language

### ISSUE THREAD

**Issue by odanielduarte** [rapidpro/rapidpro#1230]
Hi,

On the former flow editor it was possible to change the flow's default language once its translation reached the 100% translated mark:

![image001](https://user-images.githubusercontent.com/64784188/83421010-d2fbeb80-a3fd-11ea-82ec-558281cd2598.png)

This is not possible anymore on the current flow editor, making an impact on some user cases. 

For example, the U-Report website uses the flow's default language to set the labels on the poll page on the U-Report website. 

Since the Rapidpro users from the U-Report project are increasing the use of multi-language flows, the absence of this resource is impacting greatly on their usage of the system (eg. making the polls show the incorrect language on the labels).

It would be greatly appreciated if this function could return on the new flow editor.

Warm regards,
Daniel Duarte

**Comment by rowanseymour** [comment]
Hi Daniel, this is something we plan on bringing to the new editor soon but it's going to be a bit more complex given how translation is done in new flows. I'm going to be starting on the engine changes soon, see https://github.com/nyaruka/goflow/issues/917

**Comment by rowanseymour** [comment]
Hi @odanielduarte this is now an option in the new editor too. Select a language, open the translation drawer and hit the expand button beside the progress bar - you should see a button to switch the flow language.

**Comment by odanielduarte** [comment]
Hey @rowanseymour, thank you for your help, this is much appreciated.

Warm regards,
Daniel Duarte
