### ISSUE TITLE
Bug when clearing a field after filling it out in the same flow

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1239]
### Description

Contact fields that are filled out and after that cleared, in the same flow, behaves differently when validated at some expression.

### Steps to reproduce:

1. Simply clear any contact field and use it in the body of a webhook call:

![image](https://user-images.githubusercontent.com/6073075/84327691-68158780-ab56-11ea-9f85-1321d8e1ff09.png)

2. It works as expected, `null` is the value for the field that's sent:

![image](https://user-images.githubusercontent.com/6073075/84327900-ef62fb00-ab56-11ea-8546-148d7cbad1fb.png)

3. Now, just fill out the same field before clearing it up:

![image](https://user-images.githubusercontent.com/6073075/84328197-aeb7b180-ab57-11ea-89aa-2281bd41d6c2.png)

4. At the end, you'll see a validation error in the expression:

![image](https://user-images.githubusercontent.com/6073075/84328237-ce4eda00-ab57-11ea-86a9-a86789cc1dd6.png)

Depending on the way how the flow is designed, users can easily manage this contact field in many ways and get this unexpected behavior.

If someone know what project handles it (goflow or mailroom), please let us know if we can send a PR to solve.

**Comment by nicpottier** [comment]
Thanks for reporting, this looks valid and I can reproduce with a simple "Send Message" after the set/clear. We'll get a fix out ASAP

**Comment by rowanseymour** [comment]
@johncordeiro this is fixed in mailroom v5.5.27
