### ISSUE TITLE
APP_URLS setting does not register urls

### ISSUE THREAD

**Issue by DavisRayM** [rapidpro/rapidpro#1245]
The `APP_URLS` setting used [here](https://github.com/rapidpro/rapidpro/blob/ab1596268d7b257ad10ad198a44dbb1580549dd6/temba/urls.py#L51-L53) doesn't seem to register urls from applications/modules in the list.

Steps to reproduce:

i. Install a package of your choice that has urls to import. _Something like [this](http://github.com/onaio/ona-oidc)_
ii. Add urls module path to `APP_URLS`. _"oidc.urls" for the package above^_
iii. Try to access a url from the package or use [django-extensions](https://django-extensions.readthedocs.io/en/latest/) `show_urls` function to see if the link is registered

**Comment by rowanseymour** [comment]
You're right that this is broken.. curious what you need this for? If you want to add new views it might be better to create a new django app and add it to INSTALLED_APPS

**Comment by DavisRayM** [comment]
> You're right that this is broken.. curious what you need this for? If you want to add new views it might be better to create a new django app and add it to INSTALLED_APPS

Need this feature for a pluggable django app that implements Open ID Connect(Basically just a plug and use package)... This packages main trait is for it to be useable in any project with minimal changes to the project(Just need to add it to INSTALLED_APPS, register urls and set configurations in settings)

**Comment by rowanseymour** [comment]
Ok sorry I found an example of where we use this and it's not broken. It's not supposed to be a list of django URLs, but rather a list of modules that define URLs, e.g.

```python
APP_URLS = ('mymodule.urls',)
```

**Comment by DavisRayM** [comment]
Yes, I've set `APP_URLS` to a list of url modules but the urls are still not registered..... weirdly enough. Is the example of the usage public ? I might be doing something weird here... _Is import_module picky about how urls are defined ?_

# Changes made locally:

- Add the app to the `INSTALLED_APPS`
- Added `oidc.urls` to the APP_URLS. Expecting [three urls](https://github.com/onaio/ona-oidc/blob/master/oidc/urls.py#L9-L25) to be registered

**Comment by DavisRayM** [comment]
> Ok sorry I found an example of where we use this and it's not broken. It's not supposed to be a list of django URLs, but rather a list of modules that define URLs, e.g.
> 
> ```python
> APP_URLS = ('mymodule.urls',)
> ```

Mhhm, yes I've added the module to the `APP_URLS` list not entirely sure why it's still not picking it up. _Might just be a small mistake on my side, let me test this out further. Thanks_

_Is the example of the usage of this feature public/shareable ?_

**Comment by rowanseymour** [comment]
We have an internal app which has a `urls.py` which looks something like..

```python
from temba.urls import urlpatterns
from django.conf.urls import include, url

urlpatterns += [
    url(r'^', include('myapp.mymodule.urls')),
]
```

and then that app is added to INSTALLED_APPS

**Comment by DavisRayM** [comment]
> We have an internal app which has a `urls.py` which looks something like..
> 
> ```python
> from temba.urls import urlpatterns
> from django.conf.urls import include, url
> 
> urlpatterns += [
>     url(r'^', include('myapp.mymodule.urls')),
> ]
> ```
> 
> and then that app is added to INSTALLED_APPS

Ahh I see, from the snippet it kinda seems like the urls aren't really imported using the `APP_URLS` feature but by urls being added onto temba's urlpatterns.

_Also works on my end after importing and appending. But, Importing the `temba.urls.urlpatterns` directory seems like a hard dependency still...._

**Comment by rowanseymour** [comment]
Yeah.. I don't disagree and your solution in https://github.com/rapidpro/rapidpro/pull/1246 would be better. I think it would be simple enough for us to update our app.. 

@nicpottier thoughts?

**Comment by nicpottier** [comment]
Don't see any reason why that wouldn't be fine to change as per 1246

**Comment by DavisRayM** [comment]
Awesome, let me work on fixing the failing tests on #1246

**Comment by rowanseymour** [comment]
@DavisRayM that's merged now, thanks!
