### ISSUE TITLE
Stable Versions on ReadMe file

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#1247]
Hey, quick question, some days ago the `rapidpro/rapidpro` repository received some updates from `nyaruka/rapidpro`, so are the stable versions on readme file on `rapidpro/rapidpro` correct or should be updated as well?

Thanks

**Comment by ericnewcomer** [comment]
The stable versions are updated on a release cycle. We regularly push to
the head as progress is made, but the head should not be considered the
stable release.

Hope that helps,

Cheers,

Eric

**Comment by teehamaral** [comment]
Hi Eric, that's super helpful, thank you for the quick answer.
