### ISSUE TITLE
the android gateway does not synchronize itself

### ISSUE THREAD

**Issue by FlorentinCONGO** [rapidpro/rapidpro#1248]
Hi everybody. I deployed my own Rapidpro instance and i connected it with gateway android. When i send message, it is not send automatically. If i want that the android gateway send my message i must touch it for it synchronize. Could you tell me where is problem? 
Thanks

**Comment by rowanseymour** [comment]
Sounds like you might be running into a problem with some models of phones not allowing background syncing. You should use the mailing list https://groups.google.com/g/rapidpro-dev for problems like that.
