### ISSUE TITLE
Problem Connect Kannel with RapidPro

### ISSUE THREAD

**Issue by elovia** [rapidpro/rapidpro#125]
#askforhelp

I still have not been able to connect kannel with RapidPro. 

I've added a syntax BACKENDS in settings.py file like the example below:

INSTALLED_BACKENDS = {
    "message_tester" : {
        "ENGINE":  "rapidsms.backends.bucket",
        },
        # other backends, if any
        "kannel-usb0-smsc" : {
        "ENGINE":  "rapidsms.backends.kannel",
        "HOST": "127.0.0.1",
        "PORT": 8000,
        "sendsms_url": "http://127.0.0.1:13013/cgi-bin/sendsms",
        "sendsms_params": {"smsc": "rapidpro",
                           "from": "+SIMphonenumber", # not set automatical$
                           "username": "elovia",
                           "password": "elovia"}, # or set in localsettings$
        "coding": 0,
        "charset": "ascii",
        "encode_errors": "ignore", # strip out unknown (unicode) characters
    }
}
-------------------------------------------------------------------------------------------------

and this sample configuration file kannel.conf:

group = core
admin-port = 13000
smsbox-port = 13001
admin-password = elovia
status-password = elovia
admin-deny-ip = "*.*.*.*"
admin-allow-ip = "127.0.0.1"
box-deny-ip = "*.*.*.*"
box-allow-ip = "127.0.0.1"
log-level = 0
log-file = "/var/log/kannel/kannel.log"

group = smsc
smsc = at
modemtype = auto
smsc-id = rapidpro
host = 127.0.0.1
device = /dev/ttyUSB1

group = sms-service
keyword = default
catch-all = yes
accepted-smsc = rapidpro
max-messages = 0

-------------------------------------------------------------------------------------------------

In the Channels option I have the following configuration:

Number: +67078xxxxxx
Country: Timor-Leste
Send URL: http://127.0.0.1:13013/cgi-bin/sendsms
Username: elovia
Password: elovia

Are there parameters that need to be added to the file settings.py or need to create a new file.py?

hope experts can help

[Greetings from Timor-Leste]

**Comment by nicpottier** [comment]
Not sure where your are getting the INSTALLED_BACKENDS stuff, but that isn't required.

When you added the Kannel channel, you should have been given a stanza to use in your Kannel configuration, I don't see that included in your kannel.conf. That would be where I'd start.

**Comment by elovia** [comment]
The following configuration file that I created on kannel.conf...

#---------------------------------------------
include = "/etc/kannel/modems.conf" 

#---------------------------------------------
# CORE

group = core
admin-port = 13000
smsbox-port = 13001
admin-password = elovia
status-password = elovia
admin-deny-ip = "*.*.*.*"
admin-allow-ip = "127.0.0.1"
box-deny-ip = "*.*.*.*"
box-allow-ip = "127.0.0.1"
log-level = 0
log-file = "/var/log/kannel/kannel.log"

#---------------------------------------------
# SMSC CONNECTIONS

group = smsc
smsc = at
modemtype = auto
smsc-id = rapidpro
host = 127.0.0.1
device = /dev/ttyUSB1
#speed = 19200
my-number = +67078339240

#---------------------------------------------
# MODEM SETUP

group = modems
id = huawei
name = "huawei ei60"
detect-string = "ei60"
init-string = "ATZ"
init-string = "ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0"
init-string = "AT+CNMI=1,2,0,1,0"

#---------------------------------------------
# SMSBOX SETUP

group = smsbox
bearerbox-host = 127.0.0.1
sendsms-port = 13013
global-sender = 13013
sendsms-chars = "0123456789 +-"
log-file = "/var/log/kannel/kannel.log"
log-level = 0
access-log = "/var/log/kannel/kannel.log"
global-sender = +67077201133

#---------------------------------------------
# SEND-SMS USERS

group = sendsms-user
username = elovia
password = elovia
concatenation = true
max-messages = 10
user-allow-ip = "*.*.*.*"
faked-sender = 78339240
forced-smsc = rapidpro
default-smsc = rapidpro

#---------------------------------------------
# SERVICES

group = sms-service
keyword = default
accepted-smsc = rapidpro
allowed-receiver-prefix = +67078339240
max-messages = 0
get-url = "http://127.0.0.1:8000/?id=%p&text=%a&charset=%C&coding=%c"
concatenation = true
assume-plain-text = true
accept-x-kannel-headers = true
omit-empty = true

**Comment by nicpottier** [comment]
As I said, you are missing the stanza that RapidPro gave you after you configured the Kannel channel.

Maybe remove that Channel and re-add it, then insert that in this configuration.
