### ISSUE TITLE
Discord channel

### ISSUE THREAD

**Issue by IanLawrence** [rapidpro/rapidpro#1252]
Are there any plans/ideas to add a discord channel (https://discord.com/developers/docs/intro) into rapid pro?

**Comment by nicpottier** [comment]
No plans but if you want to give it a go, implementing a new channel type usually isn't too difficult. This would be the type of thing we would accept a PR for.

**Comment by IanLawrence** [comment]
Great! Will have a go then

**Comment by IanLawrence** [comment]
So we have had a look at Discord in more detail. There are some things we need to think about/discuss before going ahead with the work.

-  We believe Courier will need to be updated to support Discord. Maybe this could be done using the discordgo library (https://github.com/bwmarrin/discordgo) but maybe not (see below)
- A channel type will need to be written for RapidPro which encapsulates the config for a Discord bot (API keys etc)
- A URN scheme will need to be added to RapidPro so that the application understands Discord usernames
- Tests will need to be written for all of the above, and the PRs will need to be merged

Was wondering about your resistance to getting any courier work merged? The other channels all seem to use REST APIs but the Discord messaging API uses WebSockets. Implementing this might not be what you want for Courier. 

There is an alternative to the Courier change which would allow us to send messages (but not receive them) via Discord's webhooks, this implementation is much simpler but maybe not as useful.

Questions then are:
1. How are we expecting to use discord with RapidPro:
    a. to only send direct messages
    b. to only send messages to channels
    c. for bidirectional communication with users through direct messages
    d. for bidirectional communication through channels

We assume d in this scenario. Let me know your thoughts

**Comment by nicpottier** [comment]
Thanks, looks like you have a good handle on what work would be required there.

To be honest we haven't had much demand for Discord support up to this point, so it is hard to say how we see Discord being used by users, but certainly d) would have been our direction all things being equal.

Shame about WebSockets, that definitely complicates things a good bit, as you said thus far we have managed to avoid having a single persistent connection for channels which greatly simplifies scaling / high availability.

Does the Discord ecosystem have any REST wedge services out there perhaps? Maybe that could be a middle ground, at least as an MVP?

**Comment by IanLawrence** [comment]
We did some more digging and found [this whitepaper](https://gist.github.com/DasWolke/c9d7dfe6a78445011162a12abd32091d) about a microservices bot framework

The idea this inspired is to spin the discord functionality into a separate proxy service. The proxy could handle the gateway events and long-lived connection and forward the relevant ones to Courier over REST (or put the messages directly into whatever caching/storage system such as Redis or Postgres that Courier/RapidPro is using). Courier could send messages directly, as that’s just done over the Discord REST api.
This way the long-lived connections will be handled outside of Courier/RapidPro, and deployed as a sort of sidecar service 

If you think this might be OK we will start work and aim to ship an MVP of it when 6.0 is ready

**Comment by IanLawrence** [comment]
This work has now started. Will share a link to the proxy part of the implementation soon

**Comment by IanLawrence** [comment]
can you take a look when you have a minute @nicpottier

**Comment by nicpottier** [comment]
What you have so far looks reasonable, definitely prefer the proxy approach.

**Comment by IanLawrence** [comment]
@nicpottier we just [published the proxy itself](https://github.com/Jozian/RapidPro-Discord-Proxy)
