### ISSUE TITLE
Can't install cffi and psycopg2-binary from pip-freeze.txt

### ISSUE THREAD

**Issue by douglaschalegre** [rapidpro/rapidpro#1257]
Hi there! Im following the [docs](url)

I'm having trouble to install those specific versions that are required on the project. I've tried to install manually from pip install cffi and it works but when i go https://pastebin.com/Vh5pHcxE

**Comment by rowanseymour** [comment]
Duplicate of https://github.com/rapidpro/rapidpro/issues/1258
