### ISSUE TITLE
Python 3.8 incompatibilities

### ISSUE THREAD

**Issue by douglaschalegre** [rapidpro/rapidpro#1258]
Hi there! Im following the [development docs](https://rapidpro.github.io/rapidpro/docs/development/)

I'm having trouble to install those specific versions that are required on the project. I've tried to install manually from pip install cffi and it installs but when i execute manage.py migrate it it shows that 'temba.settings' is not found.

This is my error output from `pip install -r pip-freeze.txt`, since it's too long i put it on a pastebin
https://pastebin.com/Vh5pHcxE

Im running Manjaro and Python 3.8

**Comment by rowanseymour** [comment]
Sounds like you're hitting this incompatibility with Python 3.8 https://github.com/psycopg/psycopg2/issues/858

All of our testing and deployments are still on 3.6 so I'd recommend sticking to that until we've had a chance to update dependencies.

**Comment by Lemmynjash** [comment]
What I did is I upgraded the packages to the latest version.
Kindly @douglaschalegre try that.

Go to your  pip-freeze.txt and update the package versions.

**Comment by rowanseymour** [comment]
Closing this for now. We'll get to Python 3.8 one day

**Comment by rowanseymour** [comment]
On second thoughts.. made a PR for this https://github.com/nyaruka/rapidpro/pull/2872

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2872
