### ISSUE TITLE
In IVR flows, actions before the first Play do not take place until call is answered

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#126]
Brought up by Asch.

In a IVR flow, if you have actions leading off your flow (say, updating a contact field) these are not executed until the user actually picks up.

We should execute these right away (when the flow is first started) up to the first Play action. Conversely, actions after the Play action should only execute after the call is picked up.

**Comment by ericnewcomer** [comment]
Duplicate #13
