### ISSUE TITLE
Org selector not working when editing a flow

### ISSUE THREAD

**Issue by paulobernardoaf** [rapidpro/rapidpro#1261]
Hi everyone! This behavior can be reproduced simply by:
- Have access to more than one org
- Try to change orgs when inside a flow editor page.

After an investigation on the page, I've discovered that [this](https://github.com/rapidpro/rapidpro/blob/2d601abf237cba37805579e9d5d8f6e647bec593/templates/flows/flow_editor_next.haml#L41) CSS property is causing it.

Removing the property seems to fix the issue, but I'm intrigued if this was made on purpose or is a bug.

Anyone can confirm if this behavior is supposed to be like that?

**Comment by matmsa27** [comment]
A gif to presents the behavior 

![2020-07-15 17 35 08](https://user-images.githubusercontent.com/10725273/87593874-7eb57e00-c6c2-11ea-8ff7-dc452432be96.gif)

**Comment by ericnewcomer** [comment]
Reproduced. Likely to be the z-index and position is affecting the stacking context.

**Comment by rowanseymour** [comment]
Actually it seems font styling in the rest of the UI is slightly different when the editor is open. It's pretty subtle but you notice it if you switch between tabs, e.g.

<img width="580" alt="Captura de Pantalla 2020-07-16 a la(s) 16 55 48" src="https://user-images.githubusercontent.com/675558/87726762-4b87f300-c785-11ea-9d36-c88962e212af.png">

<img width="572" alt="Captura de Pantalla 2020-07-16 a la(s) 16 56 05" src="https://user-images.githubusercontent.com/675558/87726767-4d51b680-c785-11ea-8667-dee3880b1980.png">

**Comment by ericnewcomer** [comment]
Yup, noticed this too.

**Comment by matmsa27** [comment]
Hi @ericnewcomer, we can open a PR changing the `position` to fix it?

**Comment by ericnewcomer** [comment]
Sure!
