### ISSUE TITLE
Flow counts in Prometheus endpoint

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1263]
The prometheus endpoint is a really nice feature and seems to be promissing in terms of data analysis of RapidPro, a point that's always remembered in user feedbacks, really nice work team. 

I would like to propose adding simple flow counts in the prometheus endpoint, initially the same data we see in the flow overview inside RapidPro:

- Count of completed flow runs;
- Count of active flow runs;
- Count of interrupted flow runs;
- Count of messages in that flow;

Let me know if a PR is welcome here.

**Comment by rowanseymour** [comment]
What's an interrupted message vs an interrupted flow?

This seems feasible.. little nervous about orgs with hundreds of flows, but they can also have hundreds of groups 🤷

**Comment by nicpottier** [comment]
The key with all these metrics is they can't be expensive in any way. So they need to be things we already do squashable counts on. Any query which is actually doing a `COUNT(*)` is going to be problematic.

It seems we can probably calculate the items above with a single query against FlowRunCount with a join into the flow table for the uuid/name.  That would give you # of started runs, # of completed runs, # of interrupted runs, # of expired runs for each flow which should be scalable.

So ya, on that front I think we'd take a PR for that in Mailroom.

**Comment by johncordeiro** [comment]
@rowanseymour I've copied and paste the previous bullet point with the "interrupted" term, actually it's related just to "messages in a flow". 

And yes @nicpottier , all these are already available in flow overview page:

![image](https://user-images.githubusercontent.com/6073075/87605591-70ba2a00-c6cf-11ea-877e-f2e8455e0341.png)

**Comment by rowanseymour** [comment]
Maybe we worry about messages in flow later. 

As @nicpottier said you want to pull this data from `FlowRunCount`. I think it would be nice to have these correspond to run statuses in the engine, since exit_type does't currently capture things like failed status. So something like..

```
rapidpro_run_status_count{flow_name="Foo", status="active"} 34      // exit_type IS NULL
rapidpro_run_status_count{flow_name="Foo", status="completed"} 23   // exit_type = 'C'
rapidpro_run_status_count{flow_name="Foo", status="expired"} 1      // exit_type = 'E'
rapidpro_run_status_count{flow_name="Foo", status="interrupted"} 2  // exit_type = 'I'

rapidpro_run_status_count{flow_name="Bar", status="active"} 123     // exit_type IS NULL
...
```
