### ISSUE TITLE
Editor improvements to manage complexity

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1265]
Various users have brought up that it starts becoming difficult to manage large and complex flows. Arrows start becoming overwhelming, logic becomes difficult to comprehend etc..

There are various proposed solutions to this:
 * have some kind of simplified view of the flow that pares down details. It isn't totally clear what this is and whether enough detail is preserved for it to be useful generically, so we aren't super eager to head that direction
 * make improvements to our arrow rendering, this is captured here https://github.com/nyaruka/floweditor/issues/829 among other places. This seems broadly useful to all users.
 * explore other reasons flows are getting so big. Are subflows not appropriate for some reason? Are users not discovering these or are they just too difficult to use?

**Comment by IanLawrence** [comment]
Perhaps allowing flows to be designed in excel a la [xlsforms](https://xlsform.org/) and then imported?

**Comment by cromulus** [comment]
Composability is what I would go for. 

[Node-Red](https://nodered.org), [Integromat](https://integromat.com) and the O.G. pipe programming platform [Quartz Composer](https://en.wikipedia.org/wiki/Quartz_Composer) allow you to encapsulate your own flows and utilize them in other flows. You define inputs and outputs, and they become components in your "main" flow.

There already is a "start user in another flow" but there isn't a way to "start a user at a specific place in the flow that they left earlier", instead, to send back to the "main" flow, the user has to start at the top.

**Comment by nicpottier** [comment]
Not sure I follow @cromulus. You can start users in subflows and return from them (at the position you entered them, just like a function call) and even access the results in the sub flow (procedure style return values). The RapidPro engine is turing complete for all practical purposes.

**Comment by cromulus** [comment]
Yes, and we use subflows exactly like that. But those subflows can't be first class objects in the UI, plus in order for subflows to access the parent variables, you have to have precisely the right structure in the subflow. Instead, if a subflow could define its inputs and outputs (accessible as flow.{{subflow_instance_name}}.results), heck, even a generated UI (the name, type and default value of inputs is known), and be available as a first class object in the flow editor, then we have a whole new world. 

Additionally, sometimes, returning from a subflow, I don't want to return at the same place I entered the subflow. Defining subflow outputs would enable that.

**Comment by norkans7** [comment]
For defaults, you can use https://app.rapidpro.io/mr/docs/expressions.html#function:default

**Comment by nicpottier** [comment]
I'm having a hard time understanding this, maybe a concrete example would help?

> But those subflows can't be first class objects in the UI

What do you have in mind here over what already exists?

> plus in order for subflows to access the parent variables, you have to use the parent data structure precisely in the subflow, which means that reusability is limited.

Have you seen the parameters tab when entering flows? That basically is explicit named parameters. What do you have in mind that would be better there?

<img width="727" alt="Screen Shot 2021-03-11 at 7 34 37 AM" src="https://user-images.githubusercontent.com/168067/110812184-43148900-823c-11eb-8eb3-3710b7d60d5c.png">

> If my parent flow changes, then I have to edit the subflow, which in turn breaks other parent flows that depend on the subflow.

I guess I'm just missing what the alternatives are here. Do you want the above parameters to be stricter, is that it?

> Instead, if a subflow could define its inputs and outputs (accessible as flow.{{subflow_instance_name}}.results), heck, even a generated UI (the name, type and default value of inputs is known), and be available as a first class object in the flow editor, then we have a whole new world.

The parameters to subflows can be set in the UI as above, is there something else you are thinking there? We toyed with doing the reverse as well (once the flow returns, map the results back this way) but it seemed like more work for the typical case vs just using `@child.results.foo` or whatever.

> Additionally, sometimes, returning from a subflow, I don't want to return at the same place I entered the subflow. Defining subflow outputs would enable that. (yes, I know I can add a split)

I'm not understanding this. You want a goto of some kind? Or are you saying you want the flow to define built in splits when it is called? Maybe we just need a napkin sketch to grok what you are suggesting?

**Comment by cromulus** [comment]
Nic, Wow! I was not aware of that functionality. Rad! Thanks!
