### ISSUE TITLE
Special Event Logging for Facebook Apps

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1267]
There is no way to communicate critical actions from RapidPro to the Facebook ecosystem. Normally this is good, that RapidPro data stays in RapidPro – but in one case we would want to share data back to Facebook.

Currently there is no way in Facebook to see that a user has opted-out of U-Report or any other programme. It’s important that this information can be viewed so that Facebook Sponsored Message Ads, which appear as messages, are not sent to users who have opted out already.

As a RapidPro admin, I want to be able to send information to Facebook that a user has opted-out of receiving further messages from my programme.

As a Facebook Advertising campaign manager, I want to be able to exclude users that have opted-out from receiving my advertisements, particularly Sponsored Message Ads.

As a U-Reporter, I don’t want to receive further messages from U-Report after I opt-out of messages.

https://developers.facebook.com/docs/messenger-platform/analytics/app-events/

Requires some internal privacy and protection evaluation from outside the U-Report programme

**Comment by nicpottier** [comment]
Some initial thoughts here:
 * Can this be captured with a webhook? I imagine the main complication here being that U-Report is anonymous so we don't have the required Facebook ID to post to a webhook with the data we need
 * Can the idea of an "event" be combined with the idea of a Prometheus event from an action perspective? IE, if we build an action for a "Event Logging" of some kind, could that mean syncing to Facebook if you have such a channel?
 * Can this be automatic / universal? IE, what if we just sent flow start events to Facebook automatically for all contacts? Has some scalability concerns but could that make sense if Facebook is ok with us sending / recording that many events.

**Comment by rowanseymour** [comment]
Isn't opting-out an odd example since that is something the user would do from Messenger? I.e. it's not something we need to tell Messenger about, it's something they tell us about.

So more likely we're talking about sending custom events.. which does sound like what we've discussed previously about a "Log Event" action which creates arbitrary events which can be sent off to Prometheus if connected... and/or the Facebook channel if the contact is using one.

**Comment by nicpottier** [comment]
Right, ya, gotcha is that a Prometheus "event" is probably basically incrementing (maybe decrementing?) a counter with a particular name, while Facebook events seem to be more key/value pairs. But perhaps the imagined use cases could be satisfied with just different named event types? (without values)

**Comment by rowanseymour** [comment]
Yeah and if we let flow designers define arbitrary JSON payloads to send as events.. you start to wonder why these aren't just webhook calls. So maybe it's just event name.. or name plus zero or more key/value pairs.

I.e. engine producing events like...

```json
{
  "type": "custom",
  "name": "new_signup",
  "params": {"tel": "+12343526", "language": "eng"}
}
```

And from that we can send off just the `name` to Prometheus, or make the JSON with the `name` + `params` to send to Facebook. But I think until someone provides a clearer usecase that involves parameters, I'd opt for just having event names for now.
