### ISSUE TITLE
Copy / Paste nodes within Flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1268]
Some users want the ability to copy/paste nodes in a flow (and possibly across flows). We already support select/drag for a set of nodes, so this isn't a huge lift necessarily.

The big concern we have always had here is in what flows will be created with that ability. We really want to encourage people to build smaller flows with distinct purposes, ie, generally pushing towards subflows rather than megaflows.

Better understanding the use cases here would be helpful to determine whether this makes sense or whether we should be instead focusing on figuring out who subflows aren't used more.

**Comment by jacobmodel** [comment]
@nicpottier 
Let me provide a few use cases:

1) An example use case is if you are fielding a multiple-choice survey. For example, if you are writing a scale that uses that sample response rules for 5 Likert scale, for example:

E.g., 
How satisfied are you with your service provider:
A Very Satisfied
B Satisified
C Neither Satisfied/Unsatisfied
D Unsatisfied
E Very Unsatisfied

Creating and testing the regex response rules -- especially with translations -- can be tedious and error-prone. It'd be way easier to have a copy/paste feature here to reduce mistakes and create surveys faster.  SurveyMonkey, Google Forms, and Qualtrics all have some version of pre-populated or custom response rules (in their case, answer choices) that you can save and reuse in some way. Or at least copy/paste.

In an ideal world, I think you'd be able to save response rules and re-use them. In many respects, this might actually solve the problem w/o a copy/paste feature per se.

The other use case for us is for webhooks. Often times, we have to do a bunch of testing for integration with 3rd-party products, e.g., geocoding an address with Google Maps. Recreating these steps similarly can be time-consuming and you can imagine a bunch of cases where you wouldn't want to copy an entire flow just to get a geocoding step.

I hope this is helpful

**Comment by nicpottier** [comment]
Thanks, definitely useful. For the sake of completeness, let me offer why we pause before implementing copy/paste widely. In the case you call out above of reusing a 1-5 scale across questions, what happens after you copy/paste that node 10 times and then decide you want to change one of the rules for consistency?

In our opinion it probably leads to you forgetting to update some of them, which then leads to inconsistent results in your flow.

We would say we'd prefer you to use a subflow for this. We've made this a bit easier with the ability now to define parameters in the parent flow more easily, but retrieving the result isn't as easy as we'd like. So maybe one thing for us to think about before implementing copy/paste is whether we can make the link between parent and child flows stronger in such a way that they can be used more like functions. As in, you would build a subflow for your Likert scale question and then call that subflow repeatedly, assigning the result you get from the child flow.

<img width="720" alt="Screen Shot 2020-07-20 at 1 43 16 PM" src="https://user-images.githubusercontent.com/168067/87984569-00285a00-ca8f-11ea-95a8-f11a36f47c70.png">
<img width="676" alt="Screen Shot 2020-07-20 at 1 41 19 PM" src="https://user-images.githubusercontent.com/168067/87984573-028ab400-ca8f-11ea-9072-8ed8779b6be4.png">

**Comment by jacobmodel** [comment]
So I totally agree with the updating issue - I think that's actually the
crux of the issue.

For example, if you had something where you could save the rules set
"satisfaction", I think it would accomplish the same thing without the
extra subflow/save as overhead. Basically, the subflow route would make you
standardize a bunch of other stuff - name of the variable, continue when
there's no response, incorrect validation text - that you may not want to.

Here's some more detail on that:
1) I think the subflow management could quickly become an issue
(folders/subfolders), which I know you all are thinking about if you have
even a moderate number of subflows.
2) Flow step expiration becomes tricky - for example if you had a "continue
when there's no response" option, it'd have to be the same across all flows
that use the subflow. You could imagine wanting that to vary based on
parent flow.
3) Besides timing, you could image behavior varying as well. For example,
sometimes you may want to re-send the message. Other times, you may want to
just pause there.
4) Testing the subflow structure is somewhat more cumbersome. The subflow
would have to be tested from the parent flow, so if there were a type,
let's say, that you catch in the Simulator in the parent flow, you then
would have to click through to the subflow to make changes. Also, counting
characters for SMS length is trickier with the variable structure in the
subflow - it's doable with some copy/pasting, but it's annoying.
5) The subflow would also result in the question being standardized. So if
you named it "satisfaction question", that would have to be the
standardized name of the variable across all flows.

Other considerations
1) Data reporting for the subflows. I'd be curious what the export looks
like of the flow you posted. My hunch would be that it wouldn't be very
compatible with the Excel results or API. You'd have to do some funky
merging, I'm guessing, to make that work.
2) Analytics. - not sure how the subflow approach would work - particularly
if you're re-using it within the same parent flow

Thanks for your thoughts!
-Jacob

**Comment by ericnewcomer** [comment]
It is true, sharing components cuts both ways. It's great when you want things to behave consistently, but when you want small differences, you may need to be clever in how variables are passed down. I'd still venture to say building reusable components that are clever in handling a handful of cases is better than copy/pasting.

One thing to keep in mind is that a subflow can be as much as as little as you want it to be. It could even be as simple as a single wait for response node. Think of it as anything you want to repeat, if you break it down to the smallest reusable pieces, you might be surprised at how much you can push down into reusable building blocks for what could be cumbersome to build manually (even with copy/paste). So, if the question pre-amble is different, then put that part in the parent and have the child only deal with the response. If the handling is different for some cases, perhaps split on a variable in the subflow to handle those. You could even have subflows call subflows. Go nuts.

One quick thing to point out in @nicpottier's example: In the parent flow, to create results with different names, you can use the Save a Result action and then put the result from the child flow.  Also, notice that you can choose to create results for each of these questions in the parent flow, so there is no difference with respect to data reporting / analytics.

**Comment by nicpottier** [comment]
These are great Jacob, let's think through each of these together because I think you are absolutely right but I still say the solution is probably investing in making subflows better / more natural for this rather than adding copy/paste.

> 1) I think the subflow management could quickly become an issue
(folders/subfolders), which I know you all are thinking about if you have
even a moderate number of subflows.

I mean sure, that's a possibility, but this is definitely going to be better to manage than copy/paste by the time it becomes problematic. At least you can name / organize components in the subflow case, whereby in the copy/paste you just have blocks all over the place. In any case, I think this is one of the easier things to solve via folders or association of flows with parent flows etc..

> 2) Flow step expiration becomes tricky - for example if you had a "continue
when there's no response" option, it'd have to be the same across all flows
that use the subflow. You could imagine wanting that to vary based on
parent flow.

This is an interesting one as I don't think we've seen this requirement but that may be because subflows aren't used in this way as often. I think it is pretty easy to imagine having a subflow expiration be "inherited" by a parent flow if it isn't set. Basically to have setting for a flow that allows for either expiration to be explicit or for it to be based on the parent.

> 3) Besides timing, you could image behavior varying as well. For example,
sometimes you may want to re-send the message. Other times, you may want to
just pause there.

Sure, but this seems totally possible with subflows and parameters. IE, you can build your subflow to be as flexible as you want it to be and just require different parameters to be passed in to control that behavior from the parent. Since they are just flows you can split right at the start and implement those different behaviors based on the parameters the parent passes down.

> 4) Testing the subflow structure is somewhat more cumbersome. The subflow
would have to be tested from the parent flow, so if there were a type,
let's say, that you catch in the Simulator in the parent flow, you then
would have to click through to the subflow to make changes. Also, counting
characters for SMS length is trickier with the variable structure in the
subflow - it's doable with some copy/pasting, but it's annoying.

We've talked about this here: https://github.com/rapidpro/rapidpro/issues/963  But yes, this would have to be solved.

> 5) The subflow would also result in the question being standardized. So if
you named it "satisfaction question", that would have to be the
standardized name of the variable across all flows.

I think just like function calling in programming languages the name of the result in the parent flow should be something the parent decides, not the subflow. This isn't super easy today, but I don't see any reason why it couldn't be something in the "enter flow" dialog where you pick the result names you want to assign and we show you what results the subflow is exposing.

IE, maybe we could get the enter flow dialog to look something like:

<img width="483" alt="Screen Shot 2020-07-21 at 8 42 34 AM" src="https://user-images.githubusercontent.com/168067/88075824-2bae5180-cb2e-11ea-98ed-9ff80623cdd5.png">

I think the other piece here may be how do you simplify splitting on one of those results coming back so that a new node doesn't have to be built.

**Comment by jacobmodel** [comment]
I like having the explainer text for the subflows, regardless. I think
that's a nice touch there for sure.

I'm not 100% sure how the "save response as" would work with the response
rules in the subflow from the mockup (per Eric's comment). That's where I
think having some ability to save the response rules could be useful (same
thing with other flow steps, like webhooks, emails, etc).
