### ISSUE TITLE
More Administrative User Logging

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1273]
As an administrator of a regional platform, I would like to keep track of changes to flows and contact management.

**Comment by nicpottier** [comment]
Note that we currently provide good logging for the following:
 * flow starts via the flow start log available from the flow list page. This is new in 5.6 and shows all the manual flow starts and who started them. IE: `Matthew started all U-Reporters in the flow: July Poll`
 * flow edits are all captured in the revision history and show a full history of what changes were made on a flow and by whom.

Would be good to understand what other requirements exist here.

**Comment by rowanseymour** [comment]
Maybe some overlap with https://github.com/rapidpro/rapidpro/issues/1016
