### ISSUE TITLE
Contact Deletion From Archives

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1275]
With GDPR it becomes more important for flow authors to give contacts the ability to delete their data. Currently this can be done manually, we've recommended building an opt-out flow that adds a contact to a group which an admin then goes through and deletes the contacts in periodically. (you have 90 days per GDPR to remove that data)

Allowing this to be automated would be useful. Our first instinct here is to add a "Delete Contact" action in a flow. You could then either build a manual opt out / delete flow or use campaigns to do so automatically for contacts that haven't had recent activity.

**Comment by nicpottier** [comment]
Related: we either need to enhance contact deletion to rewrite archives with deleted contacts or disable archiving for those workspaces that need to comply with GDPR. (which has other less desirable implications)

**Comment by rowanseymour** [comment]
Related https://github.com/rapidpro/rapidpro/issues/1241

**Comment by rowanseymour** [comment]
Updated this issue to be specifically about cleaning contacts from archives since that's the last remaining piece.
