### ISSUE TITLE
New WhatsApp BSP channel: 360dialog

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1278]
hey team, today we've available in RapidPro 2 options to integrate with WhatsApp, the first one is the self-hosted WhatsApp installation and the other one Twilio WhatsApp. In order to give the flexibility for the users to choose among different fee rates, we have developed a great partnership with a German company called 360dialog.  They are a WhatsApp BSP and has a flat fee for integrating to WhatsApp, it sounds like a good alternative for the two available options.

By looking at their [API docs](https://docs.360dialog.com/api/wa-pipe-api/sandbox), it would be a new channel type but registered as a handler for the WhatsApp channel in courier.

**Comment by nicpottier** [comment]
Thanks, ya, always good to have other WhatsApp options. What is their story on templates?

**Comment by johncordeiro** [comment]
hey @nicpottier their templates API is not available yet, they're kind of creating a template API inspired on the FB one that we use, so it could be reused the WA channel templates as well. I'm contacting their support team to check.

**Comment by jcbalmeida** [comment]
Hey guys, we opened the PR [#3083](https://github.com/nyaruka/rapidpro/pull/3083) to refresh and populate the message templates, since the template API is now available.
