### ISSUE TITLE
Document advanced search options

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#128]
More complex search options for contacts (searching against fields other than name/phone number, comparisons, etc) are available, but are not documented in http://docs.rapidpro.io or made apparent in the UI.

https://github.com/rapidpro/rapidpro/blob/master/temba/contacts/search.py#L103

**Comment by ericnewcomer** [comment]
Nice find ;)

This is just us intentionally not documenting (releasing) it until we are sure we are happy with the language / syntax.

**Comment by ewheeler** [comment]
ahh ok gotcha. 
i think it is a bit awkward in its current form, since you've got to replace spaces with underscores for multi-word field names. and i think most users would benefit from the `=` operator defaulting to the behavior of `~` instead of exact matching

**Comment by rowanseymour** [comment]
We have some better documentation for this now like https://help.nyaruka.com/en/articles/3104762-searching-for-contacts
