### ISSUE TITLE
Unable to start IVR flows to contacts who interact with the bot

### ISSUE THREAD

**Issue by Leo25a** [rapidpro/rapidpro#1290]
Starting IVR flows to contacts created manually and imported to RapidPro works perfectly. However, sometimes, when trying to start IVR flows to contacts who interacted with the platform first, nothing is shown in the channel's logs and the message isn't delivered. Here's an example:

1 - This user first interacted with the bot via SMS:

![image (2)](https://user-images.githubusercontent.com/39038327/88392392-4aad1d80-cd92-11ea-90f9-cddd1d0ba038.png)

2 - We start an IVR flow to the user above

![IVR](https://user-images.githubusercontent.com/39038327/88392588-9f509880-cd92-11ea-9955-555ca23f5bac.PNG)

3 - Nothing is shown in the channel's logs

![image (4)](https://user-images.githubusercontent.com/39038327/88392918-36b5eb80-cd93-11ea-80e0-e4103558ae60.png)

The same contact was created manually and the sending was fine.

**Comment by nicpottier** [comment]
Anything of interest in the Mailroom log when this happens? What IVR channel are you using? Not sure why a contact that war created from messaging would be different from one that created manually but perhaps there is some channel affinity at play or the like.
