### ISSUE TITLE
Add `last_seen_on` on Contacts table

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1294]
A common request is to know which contacts have been "active" in a given period, either to clean up a contact database of people who aren't using the system anymore or perhaps to target only the most active users.

Propose adding a `last_seen_on` column that is updated on any incoming message from a contact and adding that column to the Elastic indexes so it can be queried upon.

Mailroom can take care of updating that column as needed.

Performance implications:
 * it is possible that for very high frequency accounts this could cause significant load that wouldn't otherwise exist on Elastic and Postgres, though the Resist use case updates the contact row very very often at high scale and that seems to work reasonably well. We should be able to add this to the same translation that is updating all rows at once and this is only on incoming messages so hopefully should be doable.

**Comment by rowanseymour** [comment]
- [x] Add db column (https://github.com/nyaruka/rapidpro/pull/2891)
- [ ] populate for new msg_received events and non-flow messages
- [ ] backfill
