### ISSUE TITLE
USSD channel - Last Message in  a Conversation 

### ISSUE THREAD

**Issue by kitandara** [rapidpro/rapidpro#1298]
We are implementing a USSD channel for a UNICEF task. One of the requirements is to indicate to the end user when a conversation has ended. To that end, we are proposing changes to the flows module to pass on additional information in the MsgOut structure (which can then be passed along via mailroom to courier and then on to the channel module) as we couldn't see any other way to pass on that information. 
 Our changes are here: https://github.com/dsmagicug/goflow
We would welcome comments.

**Comment by rowanseymour** [comment]
We don't think you need any changes to goflow. If you look at how mailroom handles `msg_created` events, it has access to the session, so it would just need to include a new field like `SessionStatus` when creating the `Msg` instance, and then make sure that is included in the msg JSON which gets queued for sending by courier. 

Mailroom's `Msg` struct already has some fields from the engine session - see https://github.com/nyaruka/mailroom/blob/eb7fdefb2356588a03b674b1de13c4e67d783514/models/msgs.go#L130-L132

**Comment by kitandara** [comment]
Thanks for this.
 I took another look and found that we can achieve the same thing using just the session. This is the new proposal: 
https://github.com/dsmagicug/mailroom/commit/f8632b5552de07575c7da28a5c8bee2b64015830#diff-f036ff0e1fd085a3bc107b430d11fc35
 It still uses the meta data to pass the flag along to courier.

**Comment by rowanseymour** [comment]
That still seems more complicated than it needs to be - the engine session status (`waiting`|`completed`|`failed`) should be enough to tell you if the engine session is waiting for input, so I think we just pass that to courier.

**Comment by kitandara** [comment]
Apologies for the delay. Have looked at it again and this is indeed much better. I shall make the changes accordingly on our end.

**Comment by kitandara** [comment]
As per your advice, we've narrowed it down further: mailroom will pass on the sessionstatus to courier, which will then determine if a response is required. See here for the new diff:
https://github.com/nyaruka/mailroom/compare/master...dsmagicug:master?diff=unified

Note that we choose to pass the session status in the meta data as we thought this least intrusive.

**Comment by rowanseymour** [comment]
We already have 3 fields related to the session on the message struct so it seems confusing to put this one in metadata, no?

Just add it at https://github.com/nyaruka/mailroom/blob/eb7fdefb2356588a03b674b1de13c4e67d783514/models/msgs.go#L130-L132 and make a PR

**Comment by kitandara** [comment]
Done. Thanks

**Comment by kitandara** [comment]
Thanks,
 In addition I believe we need:
- To add session_status to the rapidpro Msg model and do a migrate: https://github.com/rapidpro/rapidpro/compare/master...dsmagicug:master 
- Update mailroom to write the field: https://github.com/nyaruka/mailroom/compare/master...dsmagicug:master
- Update courier to read the field and pass it on in the call to the external channel api as field "session_status": https://github.com/nyaruka/courier/compare/master...dsmagicug:master

**Comment by rowanseymour** [comment]
Hi @kitandara I'm not quite following why those changes are necessary. We've now added `session_status` to the msg JSON that courier receives from mailroom when mailroom needs to queue messages for sending. Why isn't that enough?

**Comment by kitandara** [comment]
Hi @rowanseymour 
So there are a few design decisions re the USSD channel we had to make:
 1. We can implement it using the external channel API, or 
 2. We can implement it as a channel inside courier.
 Option #1 is now preferred by the UNICEF Uganda technical team. Which is why we need to change the external channel api.

We may very well have misunderstood the way courier receives messages from mailroom, hence our changes to the Msgs model of RapidPro, but of course we defer to you knowledge here.   What's key is passing the session status in the MT  the external channel api call.

**Comment by rowanseymour** [comment]
You will need to update courier to parse the `session_status` field on messages that have been sent to it from mailroom but you don't need any database changes.

Can I ask what the reasons were that the Uganda technical team have opted to use the external channel API instead of a custom channel type?

**Comment by nicpottier** [comment]
As @rowanseymour points out there shouldn't be any changes needed to the Msg model as mailroom should be passing that in the JSON passed to Courier. Courier doesn't load outgoing messages from the DB, only from Redis.

Also agree with Rowan that this should be a new channel type, if simply from the perspective that configuring this thing is going to be very custom and it's behavior is very different.

**Comment by kitandara** [comment]
Thanks @nicpottier and @rowanseymour  
I'll have to ask the UNICEF Uganda technical team to weigh in directly on their preference for an external channel api implementation. They provided historical maintainability reasons, rather than technical ones.  Which is why we had taken the route of adding to the external channel api code. 

On the db changes, this makes sense now, thank you for the clarification.

**Comment by asseym** [comment]
Hi Nic and Rowan,

Allow me to come in and please feel free to guide me if I have any of the below misaligned.

Last year we had a discussion about this when Uganda MoH and Rwanda MoH were seeking support on RapidPro USSD support/enhancements. Our understanding of the discussion and general guidance from the community was to implement the next iteration of support for USSD leveraging the generic external channel API. This recommendation informed the ToRs upon which this work by DSL & GC is based. 

From my recollection, the strongest reason given for taking this approach was to keep the RapidPro core codebase lean enough for quality assurance. We heard that the USSD channel support codebase was becoming too complex and a burden to maintain as part of core.

The other obstacle mentioned during the discussions was the difficulty in easily accessing real-life USSD services for USSD enhancements/channel testing or to certify delivery/functionality of work. It was understood that when previous enhancements were done neither the vendor nor the contract manager was truly able to confirm whether the work done achieved desired functionality

Of course we are happy to hear and would support any approach that addresses the current technical issues blighting the USSD functionality in RapidPro (including bringing back RapidPro-support for USSD/session-based channels long-term). With support from DSL &GC, we are happy to move ahead to re-implement USSD channel support as a custom channel in RapidPro as guided above. As you are aware and also appreciate, we are eager to not repeat the past mistakes when a vendor was engaged to make enhancements to USSD channel support but we were unable to merge those changes back into subsequent versions of RapidPro.

You will be happy to learn that this time the vendors (DSL & GC) are under contractual obligation (and proactive supervision) to ensure they engage the RapidPro community and follow guidelines for contributions (eg. Presenting proposed implementation approaches as Github PR and discussion on dev mailing lists). We are eager to prevent past mistakes of opening PRs after months of work based on un-sound/un-agreed approaches. We also hope that whatever approach we take, give us some level of assurance of continuity of support for robust USSD functionality/features/channel in the long-term.

Thank you.

**Comment by rowanseymour** [comment]
Hi, so I think we would agree with everything you've said here. The previous implementation of USSD was a very different approach - we had USSD specific flows and USSD specific code to handle them all over the code base. We didn't have a lot of customers wanting to use USSD or any easy way of testing it ourselves so that code always had issues.

In contrast the idea of making USSD something we handle in the channel is something we feel good about. USSD interactions will be possible with regular flows - we don't see the need to making any USSD specific changes to the engine.

But there's the question of whether to implement this as just an "external API channel" in courier vs a new channel type. I think we had assumed the latter but now it seems it's the former? I personally don't have a great understanding of how USSD works at a provider level so I'll defer to @nicpottier, but it would be useful to hear the reasons for using the external API vs a new channel type.

**Comment by nicpottier** [comment]
Yes, as Rowan said, the approach you are undertaking looks good to us.

I think the comments on the PR and the confusion is around this idea
of an external channel vs a custom one.

It may be possible to make this work entirely as an external channel,
it just isn't a great experience for users. IE, the configuration of
that external channel will require a lot of copy/pasting of settings
that you must document somewhere to talk to whatever layer is below
RapidPro and interfacing with the USSD interfaces. If you are fine
with that then I guess we are fine with that too. But it may just be
easier to have a channel type that encapsulates what the request body
is for both incoming and outgoing messages instead of expecting the
user to define that via the external channel interface.

To be clear, either approach is low effort in general and satisfies
our requirements of USSD not being intimately tied to the RapidPro
engine. It is mostly a question of how friendly the user interface is
when first connecting this new USSD type to a workspace. We are really
fine with either if you decide you want to stick to using an external
channel and user configuration.

Cheers,

Nic

**Comment by asseym** [comment]
Thanks Nic and Rowan for the clarification.

Glad to hear that both approaches are acceptable and lean/light enough to be maintainable long-term.

Obviously we will prefer the approach that is most user-friendly. @kitandara lets go with the approach that provides the most straight forward/user-friendly steps to implementation.

--
Alfred.

**Comment by kitandara** [comment]
Thanks gents.

 In terms of configuration, any USSD implementation will likely have some configuration effort and/or extra coding (outside of RapidPro). This is because as we discussed with @asseym USSD APIs, unlike SMS, are not generally standardised: Each aggregator tends to have a slightly different API mostly based on HTTP REST.  With SMS generally you can expect SMPP, typically being translated into HTTP.

 In terms of least amount of changes to RapidPro, external channel api wins (slightly), since all we add is the session_status CGI variable.  In terms of reduced duplication of the core configurations custom channel wins.  If you are ok with it, we can use the latter, but either works just fine.

**Comment by asseym** [comment]
I'd go with the approach with reduced duplication of the core configurations. I.e lets just go with the custom channel approach since Nic and Rowan have confirmed that both approaches are low effort, are fairly maitainable and meet the community design guidelines.

**Comment by kitandara** [comment]
Thanks.

 Updated proposal: https://github.com/nyaruka/courier/compare/master...dsmagicug:master

**Comment by rowanseymour** [comment]
@kitandara please just create that as a PR - it can even be a draft PR if you don't feel it's ready for review.

**Comment by kitandara** [comment]
Regarding your comments on the pull request, it seems to me we would do best to go back to the external channel option. The added coordination outside courier will add even more code.  

 The PR in this case would add only a few lines to the external channel code: To pass the session status in the CGI call to the external API

**Comment by kitandara** [comment]
@rowanseymour Kindly look at the last PR. We now have the coordination using REDIS but entirely outside courier. All that's needed from courier is the session status, which is passed as a CGI variable.
