### ISSUE TITLE
WhatsApp Media Management

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1310]
hey team,

I would like to share an experience that we're having by sending media in RapidPro flows through WhatsApp channel to hundreds of thousands of contacts. 

What's happening is that in the way as the WhatsApp channel handle media in RapidPro is that when you attach a video (or any other media) in the flow, it sends to WhatsApp API the link of the media for every message leading to several uploads for the same file. It incurs in high Data Transfer that consequently can leverage the costs of your cloud infrastructure (a lot).

That said, I would like to discuss the better solution for that, once WhatsApp already supports receiving this media in advance and sending just the ID of the media in each message, which would avoid uploading the same file several times. On the other hand, it creates a level of complexity, once messages that are sent through courier have a "loose" relationship with the flow.

I would like to know what you guys think about that and we can work in a PR with the best approach agreed.

**Comment by nicpottier** [comment]
Ya, I think this could be pretty easily handled by having a cache in redis of attachments that have already been uploaded and their IDs. Perhaps with a one hour expiration on it so it automatically gets cleaned up. Then you may duplicate that upload once an hour but on high message sends it would be massively reducted.

**Comment by johncordeiro** [comment]
hey, thanks for the response @nicpottier . WA keeps the media for 15 days, do you think we can use something close to that for keeping the media ID in Redis instead of 1 hour? The impact on data transfer is also huge for media on-demand.

**Comment by nicpottier** [comment]
Sure, can do per day if you want. I can't imagine one transfer per day is going to add up in any way that you would notice.

**Comment by smn** [comment]
Additionally, this also increases the transfer speed on WA's side since if the media_id is already present, the throughput is similar to sending a text message vs the documented throughputs for media messages as the encryption + upload of media  doesn't have to be repeated.
