### ISSUE TITLE
API access to tickets

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1319]
Requested by user

**Comment by rowanseymour** [comment]
Now have a tickets endpoint tho not publicized and not optimized https://github.com/nyaruka/rapidpro/pull/3250

**Comment by ericnewcomer** [comment]
Also added a non-published post endpoint to update status

**Comment by nicpottier** [comment]
We probably don't want to start exposing this to users (or rather advertising it) until we really figure out the details.

**Comment by rowanseymour** [comment]
it's currently not exposed in the API explorer

**Comment by rowanseymour** [comment]
Last release made these public
