### ISSUE TITLE
Archived contacts included in flow starts by query

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1324]

**Comment by nicpottier** [comment]
oopsie

**Comment by rowanseymour** [comment]
So problem here is that query evaluation for a flow start doesn't have a base group, so it leans on `is_blocked` and `is_stopped` to exclude those contacts. 

Currently rp-indexer isn't indexing a `status` field - it's deriving `is_blocked` and `is_stopped` from status

I think tho we could switch this in mailroom to use "Active" system group as that is indexed...

**Comment by nicpottier** [comment]
Adding status shouldn't take long, I can do that now.

**Comment by rowanseymour** [comment]
Is there an easy way to re-index everyone ?

**Comment by nicpottier** [comment]
Ya, can rebuild index in parallel once I ship.

**Comment by rowanseymour** [comment]
Fixed in latest mailroom
