### ISSUE TITLE
RapidPro UI nav items event listeners problem

### ISSUE THREAD

**Issue by ekeeya** [rapidpro/rapidpro#1335]
As illustrated in the .gif below,   event listeners for the nav items seem to be active all the way to the section below the nav section
Could some one kindly help?
Thank you
![rapidpro-issue](https://user-images.githubusercontent.com/40180598/92350201-ec898f00-f0e0-11ea-83f9-f2c12c3828e4.gif)

**Comment by rowanseymour** [comment]
Assuming this has been fixed in master because I can't reproduce it (there's a pretty significant UI refresh in master) and that'll be part of the 6.0 release at the start of November.

**Comment by ekeeya** [comment]
Alright thanks @rowanseymour
