### ISSUE TITLE
IVR: Need to able to enter a series of digits

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#134]
IVR appears to have three options for responses:

1. Record a digit and assign the digit a category, e.g. 1=yes, 2=no
2. Record any input before # and then assign it to a category
3. Record the voice response

We need the ability for someone to call in and input a raw numeric number, e.g. 999, without a forced categorization, just pure numeric.

**Comment by nicpottier** [comment]
You should be able to use the keypad option on the dialog to just set a rule for "number between ... "

Is that not working?

**Comment by citizenrich** [comment]
Does not appear to be working. When I call, and put in digits, if I hit # after then it hangs me up, or if I don't put a hash it doesn't move to the next step in the flow. On the screen shot, if I change the category to simply 'numeric' or '0 - 999' it is the same outcome.

![ivr_error](https://cloud.githubusercontent.com/assets/2528387/6413095/4fd749f0-bea9-11e4-8b9a-3c0b34bd6212.jpg)

**Comment by ericnewcomer** [comment]
Hey @citizenrich can you give this a try again? We pushed some changes out recently that might have addressed the premature hangup you were seeing on keypad entry.

**Comment by citizenrich** [comment]
Thanks all. Working great now after the hiccup.
Close issue please.
Sent from my mobile device
+93 798507153, twitter.com/ict4dr




On Tue, Mar 3, 2015 at 8:30 AM -0800, "Eric Newcomer" <notifications@github.com> wrote:












Hey @citizenrich can you give this a try again? We pushed some changes out recently that might have addressed the premature hangup you were seeing on keypad entry.
