### ISSUE TITLE
Allow language to be set via a variable

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1341]
Right now language is selected from a dropdown, so it isn't possible to say use the category result as the value when setting the language on a contact in a flow.

For flows that are in many languages (say a dozen) this causes a pretty ugly flow. The user already has to categorize the user response into a recognized language so it would be nice for them to use that result category to set the contact's language in a single shared action instead of having to branch for each category.

**Comment by rowanseymour** [comment]
The awkwardness here is that unlike setting name or a field etc, we expect language to be a valid ISO code.. but there's no error case for that action, so we'd have to just silently ignore invalid languages if that action took any expression.

Given that most users are probably not familiar with ISO language codes.. does make me wonder if there could be a node type that encapsulates matching text and selecting languages by name from a dropdown.
