### ISSUE TITLE
Login page no longer works with password managers

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1342]
User reported they can no longer use 1password.. which does seem to be the case.

**Comment by nicpottier** [comment]
Did someone fix this manually? WFM.

**Comment by rowanseymour** [comment]
Hmm I can't use fill fields in 1Password

**Comment by nicpottier** [comment]
How are you accessing that? In the field itself? When I'm on a login page I can click "autofill" and it does the right thing for me.

**Comment by rowanseymour** [comment]
The blue button..

<img width="339" alt="Captura de Pantalla 2020-09-22 a la(s) 13 53 22" src="https://user-images.githubusercontent.com/675558/93924911-fe6f5280-fcda-11ea-9355-5e87714504a3.png">

**Comment by nicpottier** [comment]
Weird, ya that works for me on the login page.

<img width="826" alt="Screen Shot 2020-09-22 at 11 54 53 AM" src="https://user-images.githubusercontent.com/168067/93925106-7b460080-fcca-11ea-99b7-a7bb3c3997c9.png">

**Comment by rowanseymour** [comment]
that's the chrome extension? I see you have a pending Chrome update.. maybe that'll break it 😁

**Comment by nicpottier** [comment]
Ya.. still works after restart. I think I'm running the native app so I have fingerprint support not the pure JS one.

<img width="695" alt="Screen Shot 2020-09-22 at 12 02 02 PM" src="https://user-images.githubusercontent.com/168067/93925765-73d32700-fccb-11ea-8ceb-7c5a7950a361.png">

**Comment by ericnewcomer** [comment]
I'm pretty sure this changed when the login page switched to shadowed inputs. Should probably just switch that back but perhaps there's some cue we can give it.

**Comment by chris-erickson** [comment]
Wanted to note that all of us hit this after updating RP recently, so it's not just you.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/3661
