### ISSUE TITLE
Archives page missing header, wrapping issues

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1349]
* No title or menu
* Wrapping on date and size

<img width="792" alt="Screen Shot 2020-09-16 at 12 41 03 PM" src="https://user-images.githubusercontent.com/211652/93384696-08e0a680-f81a-11ea-8684-9722d8107a31.png">

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/3053
