### ISSUE TITLE
Make it easier to delete flows once archived

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#135]
We are cleaning up a lot of old flows (~90). Once they are archived they can only be deleted by going into the flow itself to delete them, the can't be deleted from the archive folder. Once deleted, you are sent back to the main active flows page, instead of back to the archived page.

**Comment by ericnewcomer** [comment]
Agreed, this is very cumbersome. The initial thinking was that deleting was an infrequent operation and should be somewhat laborious to make sure it was intentional. I agree we should allow deletion a level up with confirmation to make this easier.

**Comment by citizenrich** [comment]
Closing as stale.
