### ISSUE TITLE
Allow contacts to be added to a flow from the contact page

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1350]
(from a customer)

When viewing a contact, it would be useful to be able to add a contact to a flow quickly, say to trigger a follow up survey, or maybe initiate a cleanup flow easily etc..

One thought is to introduce an idea of "pinning" a flow the same way that contact fields could be "pinned" and those pinned flows would appear on the contact page to be started.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/3237
