### ISSUE TITLE
Courier wrong SQL string making it fail

### ISSUE THREAD

**Issue by ekeeya** [rapidpro/rapidpro#1356]
Hello,
In https://github.com/nyaruka/courier/blob/c5bd19cfa24bb7a3c993c99f501bbc32aadbfa0f/backends/rapidpro/contact.go#L59, courier tries to write to contacts_contact with a non existing field _`status`_. In the same SQL string it misses a  `not null` boolean fields `is_blocked` and `is_stopped` which makes courier fail.

Since `status` is not defined in the models https://github.com/nyaruka/rapidpro/blob/166463e34333f80069dfc5273640a8139a390f16/temba/contacts/models.py#L700 , courier returns the following error:

![Screen Shot 2020-10-01 at 10 23 36 AM (2)](https://user-images.githubusercontent.com/40180598/94783520-79202800-03d5-11eb-9ab7-e5aa4370ead5.png)

When status is added to the models, then courier returns this error due to the fact that a mandatory `is_blocked` field is not included in the SQL string yet during table creation at the database level, `is_blocked` has no default value:

![Screen Shot 2020-10-01 at 10 19 40 AM (2)](https://user-images.githubusercontent.com/40180598/94783818-ecc23500-03d5-11eb-945f-59d15424e465.png)

The suggestion is adding `status` field in the contacts model definition and adding `is_blocked` in the SQL string with a corresponding value as shown below

modifications to https://github.com/nyaruka/courier/blob/c5bd19cfa24bb7a3c993c99f501bbc32aadbfa0f/backends/rapidpro/contact.go#L59
```
const insertContactSQL = `
INSERT INTO 
	contacts_contact(org_id, is_active, is_blocked, is_stopped ,status, uuid, created_on, modified_on, created_by_id, modified_by_id, name) 
              VALUES(:org_id, TRUE, FALSE ,FALSE, 'A', :uuid, :created_on, :modified_on, :created_by_id, :modified_by_id, :name)
RETURNING id
`
```

then add 
```
status = models.CharField(
        verbose_name=_("Status"), 
        max_length=5, 
        blank=True, 
        null=True
    )
```
to https://github.com/nyaruka/rapidpro/blob/166463e34333f80069dfc5273640a8139a390f16/temba/contacts/models.py#L700

**Comment by rowanseymour** [comment]
Hi @ekeeya, you're running a newer version of Courier than is supported by the version of RapidPro that you're running. The versions you should be running are listed at https://github.com/rapidpro/rapidpro/blob/master/README.md
