### ISSUE TITLE
Easier to select all contacts

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#136]
Contacts can only be selected one at a time. When there are several thousand to manage this is problematic when changes need to be applied to hundreds of them.

**Comment by Happs80** [comment]
Hi guys,

Is there any chance this will ever be added?

**Comment by nicpottier** [comment]
Likely not, as we sometimes deal with a few million contacts and those kinds of operations couldn't be done at once.

**Comment by Happs80** [comment]
Thanks for the quick reply.

Even a 'Select All' check box at the top of the Contacts Page? To select all 50 contacts on the page, Instead of having to individually select each one? (And equally for the Flows Page).

**Comment by ericnewcomer** [comment]
Another option is to group your contacts with a dynamic group and start them in a flow to do your update depending on what you are trying to do.

**Comment by Happs80** [comment]
Thanks Eric, but I don't know if that would help.

For example. we have 90,000+ users. If we want to add a selection of users to a group or block a selection of users for deletion, we have to individually click on each user. Very time consuming, as you can imagine.

**Comment by citizenrich** [comment]
Closing as stale
