### ISSUE TITLE
Viewer role broken

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1364]
Viewer role has a bunch of issues:
 * can't click on flows
 * triggers tab is visible but clicking on it asks for login (seems they should be able to view)
 * pages look a little odd without buttons (see screenshot)
 * empty contact page looks wrong

<img width="778" alt="Screen Shot 2020-10-19 at 10 22 18 AM" src="https://user-images.githubusercontent.com/168067/96489931-f977c300-11f4-11eb-8b63-4ee9afa01868.png">

**Comment by nicpottier** [comment]
![Uploading Screen Shot 2020-10-19 at 10.21.32 AM.png…]()

**Comment by nicpottier** [comment]
![Uploading Screen Shot 2020-10-19 at 10.21.48 AM.png…]()

**Comment by rowanseymour** [comment]
empty contact page fix in https://github.com/nyaruka/rapidpro/pull/3062

**Comment by ericnewcomer** [comment]
Looks like all of these points have been addressed except for the pages looking different without the primary button. Does that sound right?

**Comment by ericnewcomer** [comment]
Not sure what we want to do about no buttons for the viewer case, but I don't find it particularly offensive.

**Comment by rowanseymour** [comment]
I think fair to say viewer role isn't used that much and we can revisit what to do with list pages in UX refresh.. so closing for 6.0
