### ISSUE TITLE
Display Last Seen On on contact read page

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1366]
Users can query on this, access it in flows but it can't be found anywhere in the UI. Could go below created on:

<img width="362" alt="Captura de Pantalla 2020-10-21 a la(s) 14 08 10" src="https://user-images.githubusercontent.com/675558/96771240-03d9be80-13a7-11eb-96f0-9a9b49cdd94b.png">

**Comment by norkans7** [comment]
Do we want that on the list page too?
including sorting?
