### ISSUE TITLE
Importing of contacts with multiple URNs of same type no longer works

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1367]
In our recent rewrite of contact imports, we try to move away from an approach where the user complies with a specific format, to an approach where they can upload whatever they want and map columns to fields and URN types as they wish.

Insisting that every column header be unique seemed like a nice simplification, but I forgot this breaks the usecase of importing more than one URN of the same type. For example our exports can look like this..

| Name | URN:Tel | URN:Tel
|-|-|-
|Bob| +1234567001 | +1234567002

Two ways we can fix this.

1. Continue with the requirement that headers be unique:
   - In the case of exports, those headers become something like `URN:Tel:1`, `URN:Tel:2`
   - For backward compatibility with exports not written like that, convert URN columns to the above on import
   - On preview page, users see 

| Column | Mapping |
|-|-|
| Name | [Name] |
| URN:Tel:1 | [Tel URN] |
| URN:Tel:2 | [Tel URN] |

2. Drop the requirement that headers be unique:
   - Instead of using a dict to represent mappings on `ContactImport`, use a list etc
   - On preview page, users see 

| Column | Mapping |
|-|-|
| Name | [Name] |
| URN:Tel | [Tel URN] |
| URN:Tel | [Tel URN] |

**Comment by nicpottier** [comment]
2) feels most correct to me

**Comment by rowanseymour** [comment]
That's how I'm leaning but it's a more complicated fix 😐
