### ISSUE TITLE
Update Redis version in pip-freeze.txt

### ISSUE THREAD

**Issue by nomulex** [rapidpro/rapidpro#1375]
The Redis version set [here](https://github.com/rapidpro/rapidpro/blob/master/pip-freeze.txt#L91) is lower than the one required by the application.  
```
Request Method: | POST
-- | --
https://rapidpro.dev.medicmobile.org/contact/customize/1/
2.2.4
VersionMismatch
Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.5
/home/django/.virtualenvs/django/lib/python3.6/site-packages/kombu/transport/redis.py in _get_client, line 980
/home/django/.virtualenvs/django/bin/uwsgi
3.6.9
['/home/django/app-versioned/1604414889',  '.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/django/.virtualenvs/django/lib/python3.6/site-packages']
```
![image](https://user-images.githubusercontent.com/3070004/98116988-28ab5700-1eba-11eb-8c92-5b5927d12009.png)

**Comment by rowanseymour** [comment]
It seems you're running a newer version of kombu than we support. The version listed in pip-freeze.txt is 4.2.1 which works with redis-py 2.10.5.
