### ISSUE TITLE
Codify true length support for globals

### ISSUE THREAD

**Issue by chris-erickson** [rapidpro/rapidpro#1376]
Globals have field limits on them, which aren't really enforced by the API.  They're a text field in Postgres so have a pretty long limit (1 GB).  We're making great use of these so wondering if we could either remove the explicit field limits (which are essentially soft limits) or crank them up to match what Postgres supports.  It would be bad for us if these were to be [forced down to 640 chars](https://github.com/nyaruka/rapidpro/blob/master/temba/globals/models.py#L30).

**Comment by rowanseymour** [comment]
Not sure about 1GB because that would potentially create performance problems and UI issues, but there's definitely room to bump that 640 limit. We kinda suspected globals would end up being a way to expose static data to flows but wanted to see how users ended up using them first. And you have to draw the line somewhere - using the API to write big JSON blobs is never going to be replacement for having external data stores and pulling little bits of information into flows as needed through webhook calls.

Can I ask what sort of things you're putting in globals?

**Comment by chris-erickson** [comment]
Sure, I don't need 1GB 😃, but maybe allow a _lot_ and truncate/collapse it in the UI past some point?  With our petitions feature, we often have a torrent of users who are essentially all doing the same thing.  The trending data we have available (it updates every few hours internally) is added to RP via the API and flows will check to see if the relevant data for a petition is in the global before going out to the source of the data with a webhook.  So, we have a JSON blob there that's got the most recent 10 or so.  This alleviates the need to make many webhook calls when a particular petition is high traffic, reducing user waits, MR queues, backend load, db load for logging all the webhook results etc.

Essentially we're using it as a caching layer for the hottest data.  Other than maybe making that field collapsible so the view is less bad with so much data, it's really working well.

**Comment by rowanseymour** [comment]
I think we could say **10,000** for now. An org potentially has 250 of these. And we make it configurable so feel to experiment on your side.

**Comment by chris-erickson** [comment]
Finally had some time to check what we use, we have one right now wavering around 20k chars but I'm ok updating the settings to allow higher.  I'm not sure this is really enforced by the API (which we use for this) so maybe it's entirely inconsequential for us, and maybe a loophole.  Just would cause issues if for some reason you wanted to edit data that made it in that way.

Collapsible globals on the main screen though _would_ be useful, which you've also addressed 🎉

**Comment by rowanseymour** [comment]
Note that the PR above fixes that loophole that doesn't check global length in the API.. but the limit is configurable so 🤷
