### ISSUE TITLE
Improve contact field management by moving that to new page

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#138]
The manage fields dialog is counter-intuitive. Old fields show and fields cannot be removed.

**Comment by citizenrich** [comment]
Figured this out, as in the docs. Just clear the name. Maybe a little hint in the dialog.

**Comment by rowanseymour** [comment]
It's still counter intuitive - we should have manage fields be a separate list page. Then beside each field we can have options like "Delete" which is more obvious than clearing the label

**Comment by dodobas** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2328
