### ISSUE TITLE
Android channel moves message to status "sent" before sending

### ISSUE THREAD

**Issue by kennsippell** [rapidpro/rapidpro#1386]
1. Install the RapidPro android channel
1. Leave the phone idle. Phone goes to sleep.
1. Send a message via the channel.
1. Message is recieved by the channel and moved to status "sent", no message is on the network
1. Wake up the phone. Message is sent onto the network.

If too much time is spent between step 4 and step 5, the message is not even actually sent.

**Comment by nicpottier** [comment]
We don't mark a message as sent unless Android reports back it is sent. That said, Android does all sorts of weird things, especially on devices that aren't official Google ones, so not sure what is to be done there:
  https://github.com/rapidpro/android-channel/blob/d4a9aa8ed20c6eacc1e2d12ade6f3263871c41aa/app/src/main/java/io/rapidpro/androidchannel/SMSModem.java#L176

If you watch your log you should see something like:
```RapidPro.LOG.d("Sent to queue report, result code '" + resultCode	+ "', token '" + token + "' URI: " + intent.getData());```

Which is the Android intent telling us the message was sent. Only then do we mark the message as sent.

Closing as this belongs on the `android-channel` repo if you want to look into it further.
