### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by alvibd** [rapidpro/rapidpro#1398]
I am trying to setup docker container for rapidpro. While setting up varios services it's very hard to find what the environment variable are. where they are and how to override IP configurations for various docker services such postgis, elasticsearch, courier etc. Can someone help me?

**Comment by rudigiesler** [comment]
That depends on what docker image you're using. If you're using `praekeltfoundation/rapidpro-docker`, then https://github.com/praekeltfoundation/rapidpro-docker/blob/master/settings.py is a good place to see all of the django settings that we've converted into environment variables.
