### ISSUE TITLE
Facebook blocking messages, change over night

### ISSUE THREAD

**Issue by cathrinepauline** [rapidpro/rapidpro#1401]
We have had the same flows running for over a month, but all of a sudden this morning we saw that FB Messenger did not react to any of the triggerwords. 

None of the users that have tried starting the chat has blocked the FB page. If you use "guest mode" there is no problem with the bot.

Would very much appreciate any help regarding this issue.

<img width="1397" alt="Skjermbilde 2020-12-02 kl  16 14 51" src="https://user-images.githubusercontent.com/75379863/100891679-d1e56d00-34b9-11eb-9fa0-8c73376356a0.png">

**Comment by nicpottier** [comment]
Just to be clear, this is on an install you are managing?

**Comment by cathrinepauline** [comment]
Hi Nic, I'm not sure what you mean.. Have only been familiar with the program for a couple of months. It's RapidPro through an install on facebook messenger through developers.facebook - if that is what you mean?

**Comment by cathrinepauline** [comment]
> Just to be clear, this is on an install you are managing?

Hi Nic, I'm not sure what you mean.. Have only been familiar with the program for a couple of months. It's RapidPro through an install on facebook messenger through developers.facebook - if that is what you mean?

**Comment by nicpottier** [comment]
Where are you running RapidPro? This is probably a better question for whoever is hosting for you.

**Comment by cathrinepauline** [comment]
Ilhasoft Brazil is hosting :-) 

But.. have you experienced messages blocked with this error before?

**Comment by nicpottier** [comment]
Ilhasoft should be able provide you support. I can't really tell anything because the response log isn't shown there. Generally Facebook issues tend to be about auth tokens being invalid.
