### ISSUE TITLE
Language: Synced vs Synched

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1403]
While these are both acceptable, we should be consistent and we use both in places. I don't think it matters, but I believe sync/synced to be more common, so I say we go with that.

**Comment by rowanseymour** [comment]
"synched" looks weird to me..

**Comment by nicpottier** [comment]
Whoever wrote `synched` should get 10 demerits.

**Comment by ericnewcomer** [comment]
It was probably me.

**Comment by rowanseymour** [comment]
Not pointing fingers but it was @nicpottier
