### ISSUE TITLE
Update contact channel prior to IVR start?

### ISSUE THREAD

**Issue by jeremysteele** [rapidpro/rapidpro#1404]
When designing an IVR flow with an `Update Contact -> Channel` node at the very start, I was expecting that channel to be used  when the flow is started. Unfortunately it looks like the IVR connection occurs before the flow engine even sees that node - so the channel used for each contact seems to depend on their previous settings. 

For instance, if I have a contact that is tied to Twilio. They enter the flow (IVR starts), then encounter the update channel node - the URN will switch to Nexmo. However, since the connection was already initialized they are stuck on Twilio for that specific flow run. If I rerun the flow, they will go over Nexmo as expected. At least, that seems to be what is happening. 

Logically, that makes sense since you can't really jump between providers once the call starts, but from a user perspective it would be great if there was a way to set the channel within the IVR flow prior to it starting (is there a way that I am missing?). 

Is this expected behavior, and if so are there any known workarounds?  I am running the previous stable release (5.6.5).

**Comment by nicpottier** [comment]
Ya, this is a bit of an oddity as we consider an IVR flow as "started" only when it actually connects, so there's a bit of a chicken and egg.

I *think* you should be able to start a normal SMS flow that has a single step of first setting the preferred channel, then doing a "start session" for the contact you want to start with the IVR flow and that should work.

**Comment by jeremysteele** [comment]
Thanks @nicpottier , using two flows and switching contacts over seems to be working. I'll close this.
