### ISSUE TITLE
Tickets: Modeling and exposing contact ticket state

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1408]
We need ways to:

1. Display a list of contacts who have open tickets
2. Query for contacts with or without open tickets 
3. Expose ticket state in flows so for example users can avoid opening a new ticket if an open one already exists

Initially thought this might be a new status (like `ticketed`) but that gets weird because status is a thing that users control, where as this would be thing that's always set if there are open tickets. So probably need a boolean field on contact maintained by database triggers on tickets being opened and closed.

That makes it straight forward to build an index to list contacts with open tickets, but doesn't mean that what we expose in queries and flow expressions has to be a boolean.

For example in expressions we could expose a list of ticket objects

```
@tickets = [
  {
    "uuid": "b2c878bb-356c-4bc3-93ca-c4b5cfc0d3bc", 
    "subject": "Help",
    "ticketer": {"uuid": "47803fa3-e8f6-40a7-9e7d-25d7fc98b2b7", "name": "Zendesk"}
  },
  {
    "uuid": "b34b6708-e2c4-4424-b6ff-8772b6e9ec8e", 
    "subject": "Support",
    "ticketer": {"uuid": "cbd612d9-d41d-4e29-b151-c5a71856efd3", "name": "RapidPro"}
  },
]
```

In queries, it could be a count of tickets

```
gender = Male AND tickets > 0 
```

**Comment by nicpottier** [comment]
Before modeling this in models etc and committing ourselves to that, do we need any of this? Any reason we can't just query against the ticket model to and do a unique per contact? Just trying to think how we start exploring this problem without committing to particular directions in flows / queries etc..

**Comment by nicpottier** [comment]
IE: of the three things above, I think only 1. is necessary for an MVP.

**Comment by rowanseymour** [comment]
We now have `@contact.tickets` which is an array of all open tickets and `@ticket` which is a shortcut to the last ticket.
