### ISSUE TITLE
Tickets: Agent UI

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1409]
Similar to other ticketing systems, this would allow users to communicate in a more chat like manner with contacts without having to navigate to separate contact read pages.

```
══════════╦═══════════════╦═══════════════════════════════════╦═════════════════════════
Active    ║ Jim 078123111 ║ ╭───────────────────────╮         ║ Jim 
Stopped   ║---------------║ │ Thanks for replying!  │         ║ 078123111 
Blocked   ║ Bob 078123222 ║ ╰───────────────────────╯         ║ 
Archived  ║---------------║         ╭───────────────────────╮ ║ Age: 35
          ║ Eve 078123333 ║         │ Hi there.             │ ║ Gender: M
Tickets   ║---------------║         ╰───────────────────────╯ ║ State: WA
          ║               ║      <opened ticked: Support>     ║ Created On: 2020-12-25
Group 1   ║               ║ ╭───────────────────────╮         ║
Group 2   ║               ║ │ I need help!          │         ║ Tickets:
Group 3   ║               ║ ╰───────────────────────╯         ║ - Support
          ║               ║      <started flow: Catch all>    ║
          ║               ║                                   ║
          ║               ║                                   ║  
          ║               ║╭────────────────────────────┬────╮║       
          ║               ║│                            │send│║     
          ║               ║╰────────────────────────────┴────╯║         
```

**Comment by ericnewcomer** [comment]
I don't think this will live inside the contact list page though. Instead that left most column will not be there and it'll live under it's own top-level thing

**Comment by nicpottier** [comment]
Right, this is a different thing entirely (agent ticketing view)

I don't think we want the contact list page to look anything like this, people still want their columns of info etc..

**Comment by ericnewcomer** [comment]
There's nothing saying they couldn't coexist within the same section, but since agents are likely to only see this view and none of the other stuff, it really feels like it should live somewhere else at least to start out.

**Comment by rowanseymour** [comment]
Ok that makes more sense!

```
═══════════════╦═══════════════════════════════════╦═════════════════════════
 Jim 078123111 ║ ╭───────────────────────╮         ║ Jim 
---------------║ │ Thanks for replying!  │         ║ 078123111 
 Bob 078123222 ║ ╰───────────────────────╯         ║ 
---------------║         ╭───────────────────────╮ ║ Age: 35
 Eve 078123333 ║         │ Hi there.             │ ║ Gender: M
---------------║         ╰───────────────────────╯ ║ State: WA
               ║      <opened ticked: Support>     ║ Created On: 2020-12-25
               ║ ╭───────────────────────╮         ║
               ║ │ I need help!          │         ║ Tickets:
               ║ ╰───────────────────────╯         ║ - Support
               ║      <started flow: Catch all>    ║
               ║                                   ║
               ║                                   ║  
               ║╭────────────────────────────┬────╮║       
               ║│                            │send│║     
               ║╰────────────────────────────┴────╯║         
```

I think at some point it would need its own left pane to allow filtering by ticket state. Agents/users would naturally want to view open vs closed, assigned vs unassigned.

**Comment by nicpottier** [comment]
Ya, or that could be a drop down at the top of the left-most pane.

**Comment by matmsa27** [comment]
Hi everyone, we follow this discussion here, and we created a UI about this idea proposed by @rowanseymour on the first comment on this thread.

![TicketsAgentUI](https://user-images.githubusercontent.com/10725273/103183534-dec76780-4891-11eb-9406-495fc5660a0a.png)

We will update this UI with the suggestions by @nicpottier and @ericnewcomer , besides that we can create a UI with more details. What the way to get to this view? Inside the tickets or there will be an option like `chats` in the top options bar? We can create a UI with more screens and with the way to user get this view.

**Comment by rowanseymour** [comment]
Looks nice! To be clear @ericnewcomer already started on this so it's useful to hear your feedback and hear what ideas you have but we're not looking for development on this PR.
