### ISSUE TITLE
Feature Request-Create New group by removing a subset from a master group

### ISSUE THREAD

**Issue by AschHarwood** [rapidpro/rapidpro#141]
It would be great if we could remove groups of people from a larger group to create a subgroup.

For example, let's say I have a master group entitled "Group A." This group is supposed to report on a weekly basis. These members activate a flow using a trigger word. However, only a subset of group A successfully report, Group B. I want to send a follow up to just the subset of Group A that did NOT respond, Group C. So the feature I would like to do would be Group A - Group B = Group C.

Thanks!
Asch

**Comment by ericnewcomer** [comment]
Have you considered accomplishing this by adding and removing people from a group as they report using an action in your flow?

So for example, at the beginning of the week, add everybody to a "Not Responded" group. As they respond, remove them from the group with an action in your data collection flow. Then at any point during the week you have a group you can address of all those who have yet to respond.

**Comment by AschHarwood** [comment]
I think that will work!

Thanks!
Asch

On Wed, Mar 4, 2015 at 2:51 PM, Eric Newcomer <notifications@github.com>
wrote:

> Have you considered accomplishing this by adding and removing people from
> a group as they report using an action in your flow?
>
> So for example, at the beginning of the week, add everybody to a "Not
> Responded" group. As they respond, remove them from the group with an
> action in your data collection flow. Then at any point during the week you
> have a group you can address of all those who have yet to respond.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapidpro/rapidpro/issues/141#issuecomment-77232591>.
>



-- 
Asch Harwood
Mobile: 646.217.8843
Skype: Aschharwood
