### ISSUE TITLE
Passive flows

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1410]
Often users want to perform something via a flow, without interrupting the contacts currently in a flow session. This might be:

 - A maintenance operation like moving contacts between groups, setting fields (i.e. something that doesn't involve communication with the contact)
 - A message blast which isn't expecting responses

We could classify flows as "passive" if they meet certain criteria, and then on the flow start modal, provide the option to run without interrupting other flow sessions.

By including extra information in goflow's flow inspection, we can let RapidPro determine what is a passive flow without having to understand the flow definition (see https://github.com/nyaruka/goflow/issues/980)

**Comment by rowanseymour** [comment]
Mailroom is already in a good place to support this - it doesn't save a flow session until the first sprint is complete. A passive flow by definition would only have one sprint and be saved as completed. So contacts will still never have more than one _active_ flow session in the database and there shouldn't be any confusion when a message is received about what session to resume.

**Comment by rudigiesler** [comment]
This is something that we've previously had to create manual scripts to interact with the API for, so a 👍  from me, will be very useful.

**Comment by rowanseymour** [comment]
Finished in https://github.com/nyaruka/rapidpro/pull/3138. We went the route of adding a new flow type called _Background_ in the UI. Background flows can call background flows etc.
