### ISSUE TITLE
Join page problems

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1412]
What you see if you accept an invitation but you're already logged into that instance.

<img width="332" alt="Captura de Pantalla 2020-12-11 a la(s) 13 37 12" src="https://user-images.githubusercontent.com/675558/101946919-a6e7d100-3bbd-11eb-903c-4d60df4b35e7.png">

**Comment by nicpottier** [comment]
This is also a common source of confusion for people accepting invites while logged in as another user.

Almost feel like the "accept invite" page should force a logout when you first hit it or something. To make people explicitly choose to join as the logged in user.

**Comment by rowanseymour** [comment]
Yeah this page doesn't even show who you are currently logged in as.. so certainly simplest solution would be to end whatever sessions you currently have.
