### ISSUE TITLE
Archiving and restoring of triggers tied to channels should handle failures 

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1419]
Archiving or restoring a trigger that is tied to channel calls `activate_trigger` / `deactivate_trigger` on the channel type. That might make to an external API and might fail for lots of reasons, e.g. https://sentry.io/organizations/nyaruka/issues/2143785195/?project=21956&referrer=alert_email

We should at least show the user an error message, tho there are possibly also cases when it's better to ignore the remote error. For example seems like you should be able to locally archive a Facebook New Conversation trigger even if your credentials no longer work on the Facebook channel.

**Comment by ericnewcomer** [comment]
Ya, it seems to me a two-step process in the cases like losing FB permissions. First a dialog saying, we couldn't disable things on the facebook side because [remote error] with a button to remove it anyways, retry, or cancel. Perhaps we can even do this in all cases?
