### ISSUE TITLE
Send and receive message from different source

### ISSUE THREAD

**Issue by jeanfrancis** [rapidpro/rapidpro#142]
is it possible to reveice sms from the android app and have all the message sent go va the external API ?

**Comment by knightsamar** [comment]
Yes. I have tried with Kannel instead of External API. Use the Add Bulk
Sender option described in the docs. http://docs.rapidpro.io/#article_367582

**Comment by nicpottier** [comment]
Hi guys,

Bulk sending only works with Nexmo right now as they are the only provider
we have that lets you mask your sending number. (otherwise replies wouldn't
work)

Cheers,

-Nic

**Comment by jeanfrancis** [comment]
but a lot of SMPP provider allow that so we should be able to do that via the API
