### ISSUE TITLE
Flow Editor / Export Translation: Modal dialog does not close after download po file

### ISSUE THREAD

**Issue by jcbalmeida** [rapidpro/rapidpro#1420]
Steps to reproduce:

1. Open any flow in Flow Editor;
2. Open the toast menu and select "Export Translation";
3. The modal dialog will open, just click "Export".

Expected behavior:

- The file is downloaded and the modal closes automatically

Actual behavior:

- The file is downloaded, but the modal keeps open, and the OK button continues in the "loading" state.

https://user-images.githubusercontent.com/7980502/104375600-648a1a80-5502-11eb-8524-942cdc0c4774.mp4

**Comment by ericnewcomer** [comment]
Fixed in #1428
