### ISSUE TITLE
importing large number of contacts always fails

### ISSUE THREAD

**Issue by JesusEkie** [rapidpro/rapidpro#1426]
When we try to upload more than 1000 contacts it just fails or rather it will only import the first 1000, sometimes it will even import less than 1000 and stop there instead of the 25.000 contacts (either with CELERY_ALWAYS_EAGER set to True or False) 

Since the last message on this thread: https://groups.google.com/g/rapidpro-dev/c/gg06bSMdHcc/m/ioy_5xisAAAJ and the update made by the PraekeITFoundation team experiencing the same issue have someone found the cause of the issue ?.

PS: the upload of 25.000 contacts in one-time works like a charm on the app.rapidpro.io instance

**Comment by rowanseymour** [comment]
Closing this here as this is a deployment specific problem and you've already posted at https://groups.google.com/g/rapidpro-dev/c/Ym1InM2t78E
