### ISSUE TITLE
Creation of a new direct web channel

### ISSUE THREAD

**Issue by caioreix** [rapidpro/rapidpro#1429]
Nowadays our customers use a web channel that we create a lot, at the moment this channel integrates with rapidpro through the external channel, and we would like to discuss the possibility of making a direct connection between this channel and rapidpro. This channel is a websocket channel that communicates in real time on both sides, some features are: triggering push notifications, quick responses, sending images, audios, videos and all possible integrations currently existing in rapidpro in addition to having a frontend decoupled for easy configuration and modification. We would like to know and discuss where this channel fits best, in rapidpro, courier, external microservice or elsewhere.
The creation of this channel is something very important because many clients use it, and it would be a direct way for rapidpro to communicate with its contacts and at a better cost.
Example:
![webchat](https://user-images.githubusercontent.com/62818416/106903822-3fd82b80-66d9-11eb-9a39-e59d624a43b9.png)

**Comment by rowanseymour** [comment]
Definitely sounds interesting. Can you maybe sketch out in a bit more detail how this currently works and how you envisage it would work? 

I guess the things that I'm wondering right now are 1) security implications of direct channel communication in JS 2) what advantages this would give over your current solution.

**Comment by nicpottier** [comment]
This sounds like a great new channel to add, but I think the microservice part and client parts probably live outside RapidPro as external open source components. Happy to have those in the RapidPro repo but just like USSD support I don't think this should be in courier etc..

**Comment by caioreix** [comment]
We actually have a javascript websocket to do this integration, it works like any other channel, at the moment this integration is done from the "external channel". I expressed myself badly, my idea is to recreate or refactor this channel, because in fact it was not developed in the best way, the main idea is to make a USSD and a new exclusive channel in the courier. The advantages of this is to improve the current code, to make it easier to update and the new channel in the courier will make the configuration easier and more intuitive, and finally make this webchat part of rapidpro. Regarding security, we would like to discuss what would be the best way to develop this, and in what language golang, js, ts, node...

**Comment by nicpottier** [comment]
Just to be clear, USSD is a totally different thing. I was bringing that up because it also hard requirements about long lived connections and it was decided it was better to have that managed in an outside service rather than in Courier.

We don't want Courier to continue to grow its responsibilities, it is all about receiving and rending short lived requests. I think for this kind of channel if persistent connections are needed then that is another component in charge of that which then communicates to Courier much like you have already done. I think that's the right architecture for that, not trying to incorporate those websockets into Courier itself.

**Comment by matmsa27** [comment]
Hi @nicpottier , ya I agree with your points, I believe that a better way is outside of courier. We are defining some points about the external service in the web channel here and after that will open a PR to integrate with Rapidpro as new channel.

**Comment by matmsa27** [comment]
hey @nicpottier , we'd discussed and we will start the development of a new component outside RapidPRO that would manage socket connections securely, after that we'll send a PR to rapidpro and courier as a new channel with a simple token and the URL of this new microservice.

**Comment by nicpottier** [comment]
That sounds great. Would be awesome if that was in golang given the other pieces of RapidPro but it doesn't really matter if it is solid!
