### ISSUE TITLE
Whatsapp template quick replies support

### ISSUE THREAD

**Issue by caioreix** [rapidpro/rapidpro#1430]
A frequently requested feature is the quick responses in the whatsapp template messages, it consists of the addition of predefined buttons in the templates, actually rapidpro does not support this practice and is a fundamental feature for our customers, we would like to discuss the viability of developing that.
Facebook developer reference: 
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/
And other BSPs like 360dialg already support this:
https://docs.360dialog.com/api/whatsapp-api/message-templates-api#undefined-1

**Comment by rudigiesler** [comment]
Just to add in here, I was just looking through current support and approaches to adding support.

The latest version of RapidPro can support syncing and sending these templates.

It just cannot handle receiving the button responses.

Messenger also supports quick replies, but the webhook API there sends the content of the quick reply as the message text body.

With the WhatsApp webhook, a quick reply is a completely different message type.

What is the feasibility of adding the ability to interpret the `button` WhatsApp message type to courier, and just taking the button `text` that is received, and placing it as the body of the message, and letting the rest of RapidPro handle it just as a normal message, similar to how it's done on messenger, albeit that happens before it reaches us. Or is there another preferred way of handling this?

Unfortunately, docs are very light on this, all I was able to find was an example, not actual specifications of what the webhook will look like: 
https://developers.facebook.com/docs/whatsapp/api/webhooks/inbound#receiving 
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/#callback-from-a-quick-reply-button-click

**Comment by nicpottier** [comment]
I think adding the button text as a message definitely makes the most sense. Do you have some sample request bodies just to get a feel for what this looks like?

**Comment by rudigiesler** [comment]
Here's an example of a request body for clicking on the button:
```
{
    "contacts": [
        {
            "profile": {
                "name": "Rudi"
            },
            "wa_id": "27820001001"
        }
    ],
    "messages": [
        {
            "button": {
                "payload": null,
                "text": "NEVER"
            },
            "context": {
                "from": "+27600123456",
                "id": "gBGGJ3QZQiE_Agkkbc4qpLCyxYw",
                "mentions": []
            },
            "from": "27820001001",
            "id": "ABGGJ3QZQiE_AhAo75-yEIR-Uba1j9XWs713",
            "timestamp": "1613988405",
            "type": "button"
        }
    ]
}
```

**Comment by nicpottier** [comment]
Huh.. is `payload` ever non-null? Does seem we could convert that to a message pretty cleanly.

**Comment by rudigiesler** [comment]
Yes, so payload is set when you send the template.

For example, here's how rapidpro currently sends the template:
```
{
  "to": "27820001001",
  "type": "template",
  "template": {
    "namespace": "whatsapp:hsm:npo:praekeltpbc",
    "name": "opt_in_alert",
    "language": {
      "policy": "deterministic",
      "code": "en"
    },
    "components": [
      {
        "type": "body",
        "parameters": null
      }
    ]
  }
}
```

If we change that to:
```
{
  "to": "27820001001",
  "type": "template",
  "template": {
    "namespace": "whatsapp:hsm:npo:praekeltpbc",
    "name": "opt_in_alert",
    "language": {
      "policy": "deterministic",
      "code": "en"
    },
    "components": [
      {
        "type": "body",
        "parameters": null
      },
      {
        "type": "button",
        "sub_type" : "quick_reply",
        "index": "0", 
        "parameters": [
          {
            "type": "payload",
            "payload": "button0payload"
          }
        ]
      }
    ]
  }
}
```

Then, if the button in position 0 is pressed, we'll get a webhook that looks like:
```
{
    "contacts": [
        {
            "profile": {
                "name": "Rudi"
            },
            "wa_id": "27820001001"
        }
    ],
    "messages": [
        {
            "button": {
                "payload": "button0payload",
                "text": "NEVER"
            },
            "context": {
                "from": "+27600123456",
                "id": "gBGGJ3QZQiE_Agkkbc4qpLCyxYw",
                "mentions": []
            },
            "from": "27820001001",
            "id": "ABGGJ3QZQiE_AhAo75-yEIR-Uba1j9XWs713",
            "timestamp": "1613988405",
            "type": "button"
        }
    ]
}
```

But since RapidPro doesn't currently set the payloads for buttons in the outgoing requests, `payload` will always be `null`.

**Comment by nicpottier** [comment]
Makes sense. Ya, I'm down for having this in courier if you want to open a PR.

**Comment by rudigiesler** [comment]
Courier PR created: https://github.com/nyaruka/courier/pull/348
