### ISSUE TITLE
Whatsapp template not updating number of params in flows

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/rapidpro#1432]
Channel: WhatsApp
Issue related to: Templates / Flows

When switching templates with different parameters number, the block do not update it's value.

How to reproduce:
1. Create a flow
2. Add a _"Send Message"_ block
3. Configure it to send a template with a _n_ number of params (n > 0)
    - Optional: Test the flow to see if the template actually works
4. Now in this same block switch the template for one with _n - 1_ number of params
5. Test it

The expected behavior is to continue working, but in this case the number of params will no update/change, will maintain the same value, resulting in something like:
```json
{
    "errors":[
        {
            "code":2000,
            "title":"Number of parameters does not match the expected number of params",
            "details":"number of localizable_params (n) does not match the expected number of params (n-1)",
            "href":"https:\/\/developers.facebook.com\/docs\/whatsapp\/faq#faq_1612022582274564"
        }
    ]
}
```

This behavior does __not__ occur when the first template has __less__ parameters than the second one.

**Comment by matmsa27** [comment]
Hi @rowanseymour did you see any behavior like this? We can investigate a lot here to open a PR fixing this.

**Comment by rowanseymour** [comment]
I've not seen that tho to be frank the WhatsApp stuff isn't my area of expertise. Any chance it's related to caching of template assets in the engine? Remember all assets are cached for 10 seconds.
