### ISSUE TITLE
Not Able to log into https://rapidpro.moda.wfp.org/

### ISSUE THREAD

**Issue by samwata** [rapidpro/rapidpro#1434]
We are unable to log into https://rapidpro.moda.wfp.org/ when using the same credentials used to log into moda.wfp.org in Bitwarden
We are getting the following error after we Enter the password
![image](https://user-images.githubusercontent.com/23456184/108189712-1cbe6a80-7122-11eb-992e-30cd68f58fce.png)

**Comment by nicpottier** [comment]
Not sure why you are opening an issue in this Github repo. You should contact the host for that installation instead.
