### ISSUE TITLE
Global Webhooks

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1435]
There are a lot of users who need to use webhooks on flows. In the flows are common a lot of cards with call a webhook, sometimes for the same webhook or different webhooks, this can take a problem when the user needs to change a webhook that called in other cards, and for this, the user needs to change the webhook URL in many cards. This action takes more difficult to maintain the flows, especially webhooks URL, for this I suggest the idea for Global webhooks, a page when the user can create the webhooks for use in your flows, and then on flow called the global webhook created previously.

**Comment by ericnewcomer** [comment]
It seems like this use case is satisfied by the use of subflows. If you want to call the same webhook in many different places, a subflow that does only this could be used in all flows and managed in one place. This is also how you can address this same thing for non-webhook feature reuse.

**Comment by rowanseymour** [comment]
And also via globals - things like webhook URLs and payloads are expressions which can contain global variables.
