### ISSUE TITLE
When running Delete in OrgCRUDL the modified_by field is not updated.

### ISSUE THREAD

**Issue by Sandro-Meireles** [rapidpro/rapidpro#1436]
When running a Delete in `OrgCRUDL` the user who performed the action is put in `modified_by`:

-> https://github.com/nyaruka/smartmin/blob/master/smartmin/views.py#L482

```py
def pre_delete(self, obj):
    # auto populate modified_by if it is present
    if self.request.user.id and self.request.user.id > 0 and hasattr(obj, 'modified_by_id'):
        obj.modified_by = self.request.user
    #                           ↑  ↑  ↑
```

however, this change is never saved.
This could be resolved by adding `modified_by` as `update_fields` in `org.release ()`

-> https://github.com/rapidpro/rapidpro/blob/master/temba/orgs/models.py#L1819
```py
class Org(SmartModel):
    ...
    def release(self, *, release_users=True, immediately=False):
        ...
-       self.save(update_fields=("is_active", "modified_on"))
+       self.save(update_fields=("is_active", "modified_on", "modified_by"))
        ...
```
Would that be a bug, or is it behaving as expected?

**Comment by rowanseymour** [comment]
There's probably a few places where we don't set modified_by on models that have it, tho we haven't tended to worry about this so much since those fields aren't surfaced anywhere. One day we'd like to replace such fields with a proper audit log of user activity, but for now feel free to make a PR for this.

**Comment by rowanseymour** [comment]
`Org.release` sets `modified_by`
