### ISSUE TITLE
Regions not being correctly displayed

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/rapidpro#1441]
We have an org with a registered map(regions, states, etc), in the org's locations/aliases config there's the complete listing, but when consulting the [SQL in Mailroom.](https://github.com/nyaruka/mailroom/blob/master/core/models/locations.go#L117), some of those regions in the org's listing doesn't appear in the query result.

Some context, we have a flow that receives a message, and with this message using the "Has state" method it will iterate with all regions to find the same one(or an Alias), and some regions just don't work, even it being listed on org's map, the only regions that work are those listed by [this query on Mailroom.](https://github.com/nyaruka/mailroom/blob/master/core/models/locations.go#L117).

**Comment by rafaelbreno** [comment]
Before hand, we have updated this map, because was missing some regions, so before the update everything was working fine, after the update, those missing regions appeared on org's Aliases listing, but can't be found by "Wait for Response"'s "Has State" conditional.

**Comment by rowanseymour** [comment]
We've not noticed anything like this. I would identify one of the locations that you know should exist, and debug why it's not being returned by that SQL query. Maybe the location data didn't import correctly?
