### ISSUE TITLE
Parameters next in API Flow.json

### ISSUE THREAD

**Issue by nanopn** [rapidpro/rapidpro#1442]
How can I correct the url of the next parameter in the flow.json API, so that the next parameter is shown in  http and not in https. Also if someone can help me what is the parameter for the paging of the api in the flows since I have more than 300 flows and it does not work because the url is in http and not in https. I already check the settings and the api_link if you have the https. 
<img width="203" alt="Screen Shot 2021-02-26 at 15 43 12" src="https://user-images.githubusercontent.com/22599784/109358555-8f79c500-7849-11eb-8068-2c5d0e6fbb3f.png">
Thanks for your help.

**Comment by rudigiesler** [comment]
I think this is related to your django and load balancer setup. See the documentation here for how http/https is decided: https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.build_absolute_uri

Here's some more docs around how Django determines whether a request is http/https: https://docs.djangoproject.com/en/3.1/ref/settings/#secure-proxy-ssl-header

So it's possible that your loadbalancer is replacing the `https` with `http` in your requested URL. If that's the case, then you either need to configure your load balancer not to do that, or have the load balancer set a header if the request is https, and put that header in the config at `SECURE_PROXY_SSL_HEADER`

For the parameter used for paging, it is an opaque cursor used to go between pages, so you must use the `next` and `previous` URLs (or the query parameters in those URLs), to be able to go through pages.
