### ISSUE TITLE
Add a Vagrantfile for an easier dev environment setup

### ISSUE THREAD

**Issue by rodowi** [rapidpro/rapidpro#145]
It would be nice to provide a [Vagrantfile](https://www.vagrantup.com/) to make it easier to load a dev environment with all the tools set up (python version, postgresql, credentials, etc.).

If that makes sense, I'd be happy to open a PR and sign the [contributor agreement](https://github.com/rapidpro/rapidpro/blob/master/CONTRIBUTING.md).

**Comment by nicpottier** [comment]
Hi Rod!  We've never used Vagrant internally before, but that sounds like it would be super useful for people getting started, so would definitely welcome that. If you could write a quick 'howto' to put in the documentation with the usage of said file that'd be awesome.

**Comment by eduardo-g-silva** [comment]
Hi guys any news about the vagrant file?

**Comment by rodowi** [comment]
Sorry guys, I'm no longer working on this.

**Comment by javaguirre** [comment]
Hi! I have a working version with Vagrant, I'll make a PR if you people are interested. :-)

**Comment by eduardo-g-silva** [comment]
I am. Thank s

**Comment by ewheeler** [comment]
added by @javaguirre in https://github.com/rapidpro/rapidpro/pull/254
