### ISSUE TITLE
Facebook Channel Integration

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1452]
Hi guys, there are recommendations to integrate Rapidpro with Facebook? 

We created an app on Facebook to integrate with Rapidpro, but this app doesn't have all super permissions on Facebook. With this app the credentials were added on variables environment on Rapidpro, when a new channel is created, the pop up with Facebook is open, the user selects the page that has access, the user allows access, but after that, pages on the Facebook are listed on Rapidpro, but when to click to select the page, for Rapidpro the integration appears to have been completed normally. When making the test with page, the msgs didn't send from Facebook to Rapidpro. 

We have difficulties getting all permissions on our app on Facebook, we are in need of four permissions. We asked Facebook for these permissions, which was denied by Facebook. For the new integration between Rapidpro and Rapidpro-App on Facebook works, needs for all permissions to Rapidpro-App Facebook configuration?

**Comment by norkans7** [comment]
You need to configure the environment variables to courier too and make sure the Webhook URL is set on Facebook and verified

**Comment by rafaelbreno** [comment]
@norkans7 which URL?

**Comment by matmsa27** [comment]
thanks @norkans7

**Comment by dayures** [comment]
@norkans7 which file must be edited in courier for adding the environment variables ?

**Comment by norkans7** [comment]
No specific file, you can use linux `export` command or and the variable in a file and use linux `source` command

**Comment by avnavarretes** [comment]
I'm trying to connect Facebook as a channel in rapidPro but there's something wrong. Is there an updated version of the documentation for this? When I click on add channel- Facebook-add Facebook page it says that it's already connected but it doesn't really appear in the list of connected channels. I've checked the admin permissions in Facebook so it shouldn't be that
