### ISSUE TITLE
Portuguese translations on Transifex

### ISSUE THREAD

**Issue by paulobernardoaf** [rapidpro/rapidpro#1456]
Hey @rowanseymour , all the Portuguese translations for RapidPro, Flow Engine and Flow Editor are completed at Transifex, but the automatic PR from transifex-integration was not made in any of the repositories. Could those be added to each project?
Thanks!

**Comment by rowanseymour** [comment]
@paulobernardoaf I can update those manually.. tho having just tried that I noticed transifex is missing two strings for the engine - can you update those when you get a second https://www.transifex.com/rapidpro/flow-engine/translate/#pt_BR/flowspo/317787685?q=translated%3Ano

**Comment by paulobernardoaf** [comment]
Hey @rowanseymour , done!
Thanks!

**Comment by rowanseymour** [comment]
Ok those are all up to date now. If you have an account on textit.com you can check on them right now. One thing I'm noticing from a quick look at the site in Portuguese is that the translations don't always match the case of the original text, e.g. "flows" in the top nav menu becomes "Fluxos", or "Create Flow" becomes "Criar fluxo".

There are also some places where the translated string is longer than the UI allows for, e.g.

<img width="260" alt="Captura de Pantalla 2021-03-09 a la(s) 14 00 36" src="https://user-images.githubusercontent.com/675558/110523297-e56b2a00-80df-11eb-9150-84faf872f0d5.png">

I fixed similar issues with the Spanish translation by opting for less verbose translations. We're in code freeze this week.. but any changes you make in the next couple of days we'd be ok with merging.

**Comment by paulobernardoaf** [comment]
Hey, @rowanseymour we've changed this `Log de chamadas do Webhook` for a shorter one: `Chamadas do Webhook` on Transifex today.

**Comment by paulobernardoaf** [comment]
Also, we've now fixed the top nav menu items translations case mismatch.

**Comment by rowanseymour** [comment]
I'm afraid it's too late for that to be included in the 6.2 release but we plan to always use the code freeze period before a major release to get translations up to date. I'll get it pulled into the code in the next few days but not sure if that actually helps you.

**Comment by matmsa27** [comment]
Hi @rowanseymour, it is very important to us if you add the translation on the code, which can be on after 6.2 releases on `nyaruka/rapidpro` (like 6.3.5), and we update our code here. We work a lot to add these translations on the transifex in the last few days. Thank you so much for this.

**Comment by rowanseymour** [comment]
Have merged the translations tho they're not yet part of a tagged release. And obviously you use any 6.3.x release at your own risk. We've already gone and changed redis client and celery versions in the 6.3 code...
