### ISSUE TITLE
Inconsistent broadcast statuses across APIs

### ISSUE THREAD

**Issue by dianabarsan** [rapidpro/rapidpro#1457]
I'm using the `broadcasts` endpoint to add outgoing messages. I'm waiting for them to be delivered, and they are. Then, when polling to check for status updates, I'm getting inconsistent results for the same broadcast if I use `messages` vs `broadcasts` endpoint: 

![image](https://user-images.githubusercontent.com/35681649/110442433-84cdf400-80c3-11eb-9e48-803c63365a3b.png)
![image](https://user-images.githubusercontent.com/35681649/110442522-98795a80-80c3-11eb-9f3d-0c48d3769f8a.png)

`broadcasts` endpoint reports the status as `sent` while the `messages` endpoint reports the status as `delivered`. 
Can a broadcast have two statuses at the same time? 
Are there two actual entities here, one is a broadcast and one is a message, and they have different statuses? 
Which endpoint should I poll if I want to check the status of my outgoing messages, in an efficient way? 

Related issue: https://github.com/rapidpro/rapidpro/issues/1377

**Comment by rowanseymour** [comment]
The statuses mean different things - messages can be `sent` but then later `delivered` if the channel sends us a status update to confirm that message made it to a handset. Broadcasts are a set of messages to be sent to different contacts and thus have no concept of being delivered, only `sent` - which in that case just means that the messages have been created and handed to courier for sending.

The broadcast endpoint will tell you if all messages in that broadcast have been created - the messages endpoint will tell you the actual progress of sending each message.

**Comment by dianabarsan** [comment]
Thanks for clarifying!
