### ISSUE TITLE
Set the maximum limit of active objects by org.

### ISSUE THREAD

**Issue by Sandro-Meireles** [rapidpro/rapidpro#1458]
Some customers have felt the need to use more contact groups than 250, others more than 250 contact fields, we believe that a good way to serve these customers would be to add the possibility to modify the limit of these objects by org, instead of using values fixed within settings.

We thought about managing this limit using the `config` field in the `Org` model, thus limiting the permission to edit it only via the shell.

A modification on the `get_limit` method of the `Org` model also needs to be made:
```py
     def get_limit(self, limit_type):
 
+        if limit_type in self.config:
+            return self.config.get(limit_type)
+
         if limit_type == Org.LIMIT_FIELDS:
             return settings.MAX_ACTIVE_CONTACTFIELDS_PER_ORG
         if limit_type == Org.LIMIT_GROUPS:
```

We also need to make some test changes to `test_org_get_limit` by removing the value set there (`250`) by the value that comes from `self.org.config`

**Comment by rowanseymour** [comment]
The reason we added `Org.get_limit(limit_type)` was precisely to make it easier to make these limits org-specific in future.

I think my preference would be to have these be real integer fields rather than packing them into `Org.config`. Have them default to a setting when the org is created, but let deployments set them to whatever they want.

**Comment by Sandro-Meireles** [comment]
Thanks for the answer. Okay, you think it would be better to create the fields directly in the Org model.
Should we enable these fields on the form, where customers can view and edit?
Can we open a `Pull request` with these modifications?

**Comment by rowanseymour** [comment]
Yes these fields would be editable on the org update form used by superusers/staff.

I think it might be easier if we make the PRs because we have some specific requirements for migrations to allow us to deploy with zero downtime. It's also not that much work.

**Comment by nicpottier** [comment]
One thing to note here is that there are reasons for these limits,  mostly around performance and generally it is a sign of someone building out their system in the wrong way if they are hitting them. So while we can make these configurable I would caution that is not the same as saying that things will work correctly if you up the limits and I would encourage you to really look at the use cases and figure out other ways of modeling things. (oftentimes people lean on groups when instead they should be using fields and searches instead as an example)

**Comment by matmsa27** [comment]
Thanks for this support everyone.
