### ISSUE TITLE
Incorrect confirmation message when uploading contacts with Excel

### ISSUE THREAD

**Issue by George-Kamau** [rapidpro/rapidpro#1459]
When uploading or updating a contact list from an excel sheet or CSV, the confirmation message for newly created contacts and updated contacts is off. 

Steps to replicate the issue:
1. Create a contact list in excel of, say, 3 contacts.
2. Add them to an empty contact list in RapidPro, if not empty, you should be aware of the current number of contacts on the list.
3. Observe the confirmation message once done. For our case, it shows **`Created 0 new contacts`** and **`Updated 3 existing contacts`**

**Comment by rowanseymour** [comment]
This was fixed in mailroom and will be part of the 6.2 release https://github.com/nyaruka/mailroom/pull/389
