### ISSUE TITLE
V2 API Broadcasts to specified channel

### ISSUE THREAD

**Issue by rsdunya** [rapidpro/rapidpro#1465]
Hello team Rapidpro, I had a question about the V2 API's claim to support broadcasting to a specific channel:
https://github.com/rapidpro/rapidpro/blob/main/temba/api/v2/views.py#L631

The feature does not seem to be implemented as specifying a channel UUID to v2/broadcasts does result in a channel ID or UUID being sent to Redis:
```
curl -H "Content-Type: application/json" -H "Authorization: Token blah" -X POST  "localhost:8001/api/v2/broadcasts.json" -d '{"urns": ["tel:+14115991234"], "text": "Test @contact.name", "channel": "72c80c36-0deb-4d15-b1dd-e4a97cb7ce08"}'
```

Results in the following entry in Redis:
```
1616420541.513342 [1 172.18.0.1:64500] "ZADD" "batch:1" "1616410541484" "{\"type\": \"send_broadcast\", \"org_id\": 1, \"task\": {\"translations\": {\"base\": {\"text\": \"fantastic @contact.name\"}}, \"template_state\": \"unevaluated\", \"base_language\": \"base\", \"urns\": [\"tel:+14115991234\"], \"contact_ids\": [3], \"group_ids\": [], \"broadcast_id\": 91, \"org_id\": 1}, \"queued_on\": \"2021-03-22T13:42:21.484Z\"}"
```

If we were to modify Rapidpro by adding a channel uuid to task:
https://github.com/rapidpro/rapidpro/blob/18cab6ce7c8600ca1f8993cb6bbbefad6bc1fe95/temba/mailroom/queue.py#L85-L94
```
task = {
...
"org_id": broadcast.org_id,
"channel_uuid": broadcast.channel.uuid
}

```
We would be able to pass the channel uuid or channel id to Redis for mailroom's consumption:
```
1616420541.513342 [1 172.18.0.1:64500] "ZADD" "batch:1" "1616410541484" "{\"type\": \"send_broadcast\", \"org_id\": 1, \"task\": {\"translations\": {\"base\": {\"text\": \"fantastic @contact.name\"}}, \"template_state\": \"unevaluated\", \"base_language\": \"base\", \"urns\": [\"tel:+14115991234\"], \"contact_ids\": [3], \"group_ids\": [], \"broadcast_id\": 91, \"org_id\": 1, \"channel_uuid\": "72c80c36-0deb-4d15-b1dd-e4a97cb7ce08"}, \"queued_on\": \"2021-03-22T13:42:21.484Z\"}"
```

This leaves a bit of work to be done in mailroom and goflow.

**Is this feature deprecated?**

**Comment by rowanseymour** [comment]
Hi @rsdunya, it does appear in the great migration to mailroom, this feature got lost and since no-one was using it, no-one complained. Can you tell us more about what you're trying to do that requires this?

**Comment by rsdunya** [comment]
@rowanseymour Thank you for the response, one of our use cases involves orgs with multiple channels that have the same scheme. So we ran into this hiccup when we attempted to bypass the UI and use scripts to broadcast messages via the v2 API.

**Comment by rowanseymour** [comment]
Usually contacts have a single URN for a given scheme, for example your contacts have tel URNs - some for carrier 1 associated with channel 1, some for carrier 2 associated with channel 2. So then it's not clear what we're supposed to do if a user requests to send a message to a contact with a URN from carrier 1, using channel 2.

I think I lean toward dropping this feature and finding other ways to solve whatever usecases it was once solving.

**Comment by rsdunya** [comment]
> Usually contacts have a single URN for a given scheme, for example your contacts have tel URNs - some for carrier 1 associated with channel 1, some for carrier 2 associated with channel 2. So then it's not clear what we're supposed to do if a user requests to send a message to a contact with a URN from carrier 1, using channel 2.
> 
> I think I lean toward dropping this feature and finding other ways to solve whatever usecases it was once solving.

The way you've envisioned makes sense, I think we've got a workaround for our particular use case. Thanks again for taking the time respond.

**Comment by rowanseymour** [comment]
We've removed the field from the API endpoint
