### ISSUE TITLE
Errors with calls dropping when using twilio

### ISSUE THREAD

**Issue by ni-ka** [rapidpro/rapidpro#1466]
Hi,

We're using text.it + twilio for some tests in Mali and are having some trouble to identify the source of calls dropping. It seems to drop mostly after no selection is made after a prompt but sometimes drops after 4 or 8 seconds. When trying to research the calls we see some errors in the twilio logs which show some errors (which we could not actually hear as the call dropped before)

Any recommendations on how to figure out whether this is a problem on Twilio's end or textit?

Thx!

![Capture d’écran 2021-03-25 à 16 58 25](https://user-images.githubusercontent.com/1225776/112521291-422f3b80-8d94-11eb-9d90-bdaec9356730.png)

**Comment by nicpottier** [comment]
Hi there. Please open a ticket on TextIt and we can take a look at the logs there and see what may be happening. Twilio and the like definitely sometimes have issues with DTMF tones in some countries so it could be that, but it'll be a lot easier to tell what's happening from the TextIt side.
