### ISSUE TITLE
Rapidpro integration with WhatsApp Embedded Signup for Business Account

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1475]
Hi everyone, recently WhatsApp announced the WhatsApp Embedded for business accounts on new numbers. This improves the infrastructure configuration when will not necessary to have a WhatsApp docker instance running for each number. This new way to integrate the WhatsApp channel on Rapidpro to a number is a behavior like the new Facebook channel integration with Rapidpro, you must create an app on Facebook and integrate this app with Rapidpro, and then when you connect your Facebook page, you must have a login on Facebook and then select the page. This process to WhatsApp numbers is similar to Facebook pages, and you need to select the number that your Facebook account has access to. This process can be viewed on this [video](https://www.youtube.com/watch?v=ebjs9xBp8kE&feature=emb_imp_woyt&ab_channel=WhatsApp).

The documentation about WhatsApp Embedded Signup for Business Account can access [here](https://developers.facebook.com/docs/whatsapp/embedded-signup).

**Comment by nicpottier** [comment]
Yay, at last! I'm not sure this is something that belongs in RapidPro proper as this is still a BSP facing integration. The final thing that is on the horizon is Facebook letting users register etc, directly on the Facebook side and have their own line of credit etc, which is still coming down the line as I understand it. That's something that will naturally fit into being something RapidPro integrates with, but RapidPro isn't aimed at having BSP specific features in it like this.
