### ISSUE TITLE
Flow dependencies should be soft

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1480]
Soft in that when you try to remove a thing which is still used by a flow, you get a warning, but we let you remove it anyway. It then becomes a "Missing Dependency" issue in that flow.

Currently issues are just JSON in the flow metadata that we get back from asking mailroom to inspect a flow before saving it. If a dependency is being used by a large number of flows, it doesn't sound ideal to reinspect and re-save all of them. 

But as part of https://github.com/rapidpro/rapidpro/issues/1163 we would need to create database models on flow saves. If we did that, then we could avoid having to re-save all the flows that depend on the thing being deleted - and just manually create "missing dependency" issues in the database for each affected flow.

**Comment by rowanseymour** [comment]
I think I've talked myself out of having every flow issue being a db object.. or having RapidPro create these.

Maybe we have a mailroom task we can hit after we delete a dependency - which re-inspects all the dependent flows and updates their metadata from mailroom. That should be fast.

Could have a `issue_count` field on `Flow` to avoid having to count those on the fly in the flow list view.

**Comment by nicpottier** [comment]
We don't expose issues anywhere but the editor right now though right? Maybe issues should just always be dynamic when you enter a flow and evaluated at that time instead of always trying to keep them in sync?

**Comment by nicpottier** [comment]
(if we did choose to show them in the UI from the list page we could make it a binary thing (`has issues`) which would be easy to update in the "delete a dependency" case)

**Comment by nicpottier** [comment]
Then it would be up to you to click through to see the issues and that would then be dynamic.

**Comment by rowanseymour** [comment]
I don't hate the flow list page just showing something like `⚠️ has issues`.. but I don't love not being to say at any point in time what your workspace's issues are... I even kinda liked the idea of one day having a list page of all the issues in your workspace. Makes it easy for a user to go thru issues and clean them up.

In theory it shouldn't be too hard to keep issues up to date because the only external thing that can affect them is dependencies being deleted. The only real concern being a dependency delete that causes a very large number of flows to need re-inspecting.. but maybe I'm over-thinking that because workspaces don't tend to have that many flows tied to a single dependency *. 

(* would want to handle org releases as special case that doesn't trigger a bunch of flow re-inspects)

**Comment by nicpottier** [comment]
Even if we had a single page that showed all issues you'd still have to click through into the flows to resolve them so maybe that's not that big a win? I'm fine with either really but it feels like until we get to that day doing the simplest thing of just having a boolean of `has_issue` makes the most sense.

**Comment by rowanseymour** [comment]
I guess the thing I don't like is that we're leaving that inspection data on flows in a "sometimes correct" kinda state. Or maybe we stop saving issues on flows all together and always call out to mailroom to get the latest issues when a flow definition is loaded?

That doesn't feel much simpler than re-inspecting flows when a dependency is released.. It certainly feels potentially useful having that data around and up to date even if it's only for our tracking purposes. Currently we can do stuff like see how many active flows are still using `legacy_extra` etc.

**Comment by rowanseymour** [comment]
Ok I think I'm down with this. The thing I like about an editor like VSCode is I don't have to hit compile to see a list of errors. The files with errors are always red. I open them and I can see why they are red. But we can make that work with `has_issues` being the only state re issues that is actually saved.

**Comment by nicpottier** [comment]
I mean also we don't actually show issues anywhere in the UI so we can also punt on this until we decide to add that.

**Comment by rowanseymour** [comment]
This currently done for the following types that can be flow dependencies:

 - [x] channels
 - [x] classifiers
 - [ ] fields
 - [ ] flows
 - [x] globals
 - [ ] groups
 - [x] labels
 - [ ] templates
 - [x] ticketers
