### ISSUE TITLE
Facebook page listing should be flexible

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/rapidpro#1481]
In our platform there's some page administrators that manages a lot of pages, because of the limit of Page Listing(25 items) some users are reporting the need to increase the number and that they can't "uncheck" a page to "check" another(in the Facebook Popup), when doing this the "unchecked" page will stop working.

So, wouldn't be nice to add some another type of listing or increase the max number of pages?
![facebook_page_listing](https://user-images.githubusercontent.com/32229014/115760900-1fcf1480-a378-11eb-8c79-816803340a7b.png)

**Comment by rafaelbreno** [comment]
A solution would be adding a local variable into rapidpro called `FACEBOOK_PAGES_LIMIT`, and it would be implemented as a field in the Facebook Graph url, there's this field called limit, so it would be something like:
`https://graph.facebook.com/me/accounts?limit={FACEBOOK_PAGES_LIMIT}`

**Comment by matmsa27** [comment]
Hi @nicpottier and @rowanseymour , what do you think about this?

**Comment by rowanseymour** [comment]
Can we just pass `limit=100`? What's the maximum we can request?

**Comment by rafaelbreno** [comment]
Looking at the Facebook Graph API docs it does not show any limit, so in theory if my user administer 9999 pages I could fetch it using `https://graph.facebook.com/me/accounts?limit=9999` without any problem.
