### ISSUE TITLE
Rocket.Chat Ticketer improvements

### ISSUE THREAD

**Issue by paulobernardoaf** [rapidpro/rapidpro#1482]
Hey guys, opening this issue so we can discuss the Rocket.Chat Tickets integration.
We've successfully been using the current integration, but some features are missing and we would like to discuss them with you.

- [ ] Start a flow when the Ticket is closed
- [ ] Return the Ticket service opened response
- [ ] Send department and custom fields when opening a new Ticket 

#### A simple explanation of how and why these features are necessary:

- Start a flow when the Ticket is closed
    - The main goal for this feature is NPS research at the end of each Ticket, giving the option to start a customizable flow cease this requirement.

- Return the Ticket service opened response
    - When a new Ticket is opened, the Rocket.Chat response contains information that can later be used by clients, like send that information to a CRM.

- Send department and custom fields when opening a new Ticket
    - Rocket.Chat gives the possibility for agents to be grouped by department and open a new room for a specific department. 
    - Rocket.Chat allows the visitor to have custom fields, and the agent can view them to get an earlier look at the visitor and the case.
    - Both features are widely used by clients.
    - Both features are currently implemented but only on our fork, [as asked for](https://github.com/rapidpro/rapidpro/issues/1251#issuecomment-658360303). We're now looking for them to be merged into the source code in the best manner.
    - For them to be forwarded to Rocket.Chat, both are passed in the request body as: `department: string` and `customFields: map[string]string`
        - `department` will always be a string
        - `customFields` can only be a json/object of just strings.

**Comment by matmsa27** [comment]
Hi everyone, is there a way for Rapidpro in a flow execution to know when a ticket is closed on the ticketer platform side (Zendesk or rocketchat)? For example, I create a flow here to open a ticket on Zendesk, but when the ticket is closed on Zendesk, I need to start a flow for this contact to run an NPS research, is there a way to `flow run` know this action?

**Comment by rowanseymour** [comment]
Sorry for the delay! I had a bit of covid and I'm still catching up

- Start a flow when the Ticket is closed
    - Currently there is no way to know when a ticket is closed. We've chatted about this and I think the way we'd accomplish this is thru a new trigger type which handles ticket closures. Right now we're beta testing the new internal ticket handling UI with some customers but I think this trigger type could be added soon

- Return the Ticket service opened response
   - We create a result in the Open Ticket action so we could let services set `extra` on that result to whatever JSON they want... tho it would be nice if this was consistent between ticketer types. What's the sort of information you'd want to set?

- Send department and custom fields when opening a new Ticket
    - I don't love the solution of using the ticket body to pass a JSON payload to an external service, since that's not really what the body is for tickets in general. When people look at their list of tickets it's going to be odd to see a list of JSON blobs. 
    - Maybe there could be arbitrary fields on the Open Ticket action like webhook headers? Or maybe we agree on a set of common fields like "priority", "department" and then for external ticket services that use those we send them, for those that, we just ignore them.

**Comment by matmsa27** [comment]
No problem @rowanseymour I hope you are well and safe. Thank you for your reply.

1 - Do you have this mapped how to implement this solution? When a ticket is closed on RocketChat side, the RocketChat application can call an endpoint on the mailroom and the `mailroom` can start a trigger. For this, is necessary to create a new trigger type on the Rapidpro Django project to the user to set a flow to start when a ticket is closed on RocketChat. Do you agree with this approach?

2 - @paulobernardoaf can you add here more details about this point?

3 - I agree with you, I don't love to use the ticket body to configure a context when opening a ticket on RocketChat. I believe that the best solution is to define a list of main fields to configure when the user sets the flow to Opening a ticket service. The RockeChat can accept any other fields to improve the experience to the agent, but this is a specific context in how organizations are configured. To configure the list of main fields to opening a ticket is it necessary to implement on `floweditor` side and `mailroom` side?

If you give us a green signal, we are ready here to implement these points, with you agree or have any suggestions to discuss please let us know

**Comment by rowanseymour** [comment]
We've already started on adding "closed ticket" as a new trigger type (actually part of a bit of a re-factor of triggers in general) - all ticket closing whether from an external system on internally happens in mailroom so we'll have it create a new event for the handler, and that'll look for "closed ticket" type triggers and fire one if it finds one.

We're also adding a new trigger feature which maybe of interest to you - exclusion groups. Currently some of the trigger types support a list of groups which are "inclusion groups".. and this is the opposite of that. Could be used to keep contacts with tickets out of certain triggers etc.

I think I'd be ok with open ticket actions taking an arbitrary map of fields and values..  which ticket services can ignore or pass on. 

@nicpottier @ericnewcomer ?

**Comment by nicpottier** [comment]
This should be broken into separate issues tracking each proposal FWIW.

I don't personally think arbitrary fields on a ticket make sense. Do RocketChat / ZenDesk have tagging or labeling support? That feels like what we are trying to arrive at here, some way of tagging a ticket for a certain group. Also seems like most ticketing tools have ways of using rules based on ticket subjects etc, so feels like current ability to set ticket subject could be used to route tickets as well.

**Comment by rowanseymour** [comment]
FYI closed ticket triggers and trigger exclusion groups have been merged and will be part of the upcoming 6.4 release.

**Comment by rowanseymour** [comment]
Code freeze July 5th, final release July 19th
