### ISSUE TITLE
Stopping flow interactions when a ticket is open

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1484]
So one thing that is clear is that in most (all?) cases it is going to be really confusing to have contacts getting replies both from humans and from flows when interacting with a ticket. Right now we treat a ticket being opened as a side-effect which causes inbound messages to be forwarded to ticketers (or the native UI) while ALSO handling those inbound messages in flows if appropriate.

We have a few different ideas on how that should be accomplished, in order of increasing complexity:

1. Having any open ticket means your messages don't get sent for flow processing. I suppose we could further subdivide this into your messages don't get sent to active flows and/or your messages don't get evaluated against keyword triggers. Big pro here is that it is the simplest for users to grok. If a contact has an open ticket, no automation. Downsides (which apply to pausing as well) is campaigns may become broken (for recurring events). One possible workaround there would be that background flow campaign events still fire, so you could build something that updates them. Other downside is that this is pretty prescriptive, we are drawing a line in the sand, while in general we have instead said we will build the primitives to allow people to build anything they like (including flows catching messages with tickets open). But maybe that's ok. (or even desirable for a change!)

2. We introduce a contact status of "paused". This was what we originally talked about when thinking about tickets, that separate from tickets there would be a contact status that could be used to control whether a contact's messages are handled and we considered that contact to be in a "paused" state. Basically all the same pros and cons as above except we aren't being as prescriptive about it, users can choose to put the contact in a paused state when/if they choose (in the flow or manually via the UI) so they can manage things however they like.

3. We do something 🍌 🍌  like https://github.com/rapidpro/rapidpro/issues/1023 and have a "pre-flight" flow that then can determine whether an incoming message continues for processing by flows or is trapped. That lets people essentially use groups the same as "paused" in 2) but without any handling on the campaign front. (could say the same there that a properly built system should have campaign events fire but they can choose what to do in it by switching based on group or ticket status) Though groups are probably enough for this, it would probably be convenient to have some ticket state passed in with the contact in flow execution to allow splitting based on whether tickets are open against the contact. This has some appeal in that we have other use cases that a pre-flight flow would satisfy. (such as automatically opening a ticket based on some words in an incoming message "help" or NLP match "I have covid")

@ericnewcomer @rowanseymour @norkans7 @cromulus @ewheeler Thoughts?

**Comment by ericnewcomer** [comment]
While it may have the most 🍌 I keep gravitating to option three. An important distinction is that pre-flight flows would never wait, but they could trigger new flow sessions if the need arose. My primary concern with this option would be it co-existing with triggers which might be somewhat confusing because the utility would certainly overlap.

Another thought  is, in a pre-flight flow how would you distinguish from "stop handling this message" and "continue normal handling"? Seems you would need an action for one or the other which feels a bit weird.

**Comment by ewheeler** [comment]
Option 3 is attractive for its flexibility, but I expect might complicate the ability to export all of the bits of an overall "messaging intervention" as a single importable package.
As related inspiration, Rasa uses the concept of '[fallback policies](https://rasa.com/docs/rasa/fallback-handoff)' that can be defined with a [priority and confidence thresholds](https://github.com/RasaHQ/rasa/blob/main/rasa/core/policies/fallback.py#L48) that determine if/when these are triggered. The option 3 'pre-flight flow' seems kindof like a preemptive version of this mechanism

**Comment by nicpottier** [comment]
I think if we are just looking for easiest / surest next steps then adding
tickets to the contact context is the obvious win there. You can then
adjust your campaigns to do whatever you want based on ticket status. (and
same for triggered flows honestly)

Pre-flight (probably needs a better name) really is more about addressing
the different (but important) problem of how do you deal with catching
things that could be calls for help but are in the context of a flow.

One possibly and maybe better solution than the bananas is adding a trigger
type for NLP classification. IE if you match over this threshold then the
trigger fires. We have talked about this in the past. Bummer there is that
NLP is still a big lift for people to use or integrate but I suppose that's
a different problem.

Back to this specific issue, could we get away with adding tickets to
context and saying that's all? If you are concerned about your triggers
doing weird things then you can add a split for it. That sure feels
simplest as a first step for something we probably want anyways.

**Comment by rowanseymour** [comment]
Tickets obviously belong in the context (and probably also in queries so that having tickets can include/exclude a contact from a smart group).. so I think we can move forward with adding that regardless of what we decide here.

But that doesn't really help users with the problem of contacts *already* being in active flows, and as a solution for preventing contacts from starting new flows, places all the burden on users to start every flow with a split on tickets.

It's already a problem for users that if you have a contact stuck in a loop in a flow, and you want to talk to them, there's no easy way to get them out of that flow.

Maybe in the agent UI, you would see that the contact has an active session and there's an _Interrupt_ button?

**Comment by ericnewcomer** [comment]
So, in plain words, I think the goal is a default configuration that requires no setup that effectively pauses automation if they have an open ticket with ways to eject out of that if they know what they are doing and want/need to be clever.

Maybe we could add a system-level smart group for contacts with open tickets. We had touched on the idea of exclusion groups for triggers in the past. If open tickets is a system group, we could add it to an exclusion list on triggers by default. We could perhaps do the same for campaign events.

To @rowanseymour's point above, I don't hate the idea of forcing/strongly encouraging interruption if agents send a message to somebody active in a flow.

**Comment by norkans7** [comment]
I think we can have a way to configure a flow to handle different scenario, 
when to keep the contact in PAUSED state or reply the contact to set expectation that they will hear from an agent soon but can meanwhile keep interacting with other flows.
The default is probably to have the contact PAUSED.

For recurring events, I think we could add two options in addition to what we have when a contact is active in a flow, we can have one option to start a background flow so a way to allow users to reschedule the event.
And an option for when we have a ticket open, probably again start a background flow
