### ISSUE TITLE
Add Ticketing Status to Contact for Querying / Grouping

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1486]
I guess we have two ways we could go about this:

1. Add a "Ticketed Contacts" system group that adds/removes contacts based on whether a ticket is open on that contact or not.
2. Add a `has_open_tickets` or `ticket_count` or even just `tickets` attributes to our Elastic contact representation to allow for querying based on that state. That would let users build up queries and dynamic groups based on ticketing state.

Both of these have performance implications but as tickets are tied to human interventions generally I don't think they are as potentially painful as other additions. (such as `last_seen` for example) If we added `has_open_ticket` to the Contact model it would just be a matter of updating that state based on Ticket changes while also setting `modified_on` for the simplest case which is unlikely to be worse than `last_seen` is currently.

**Comment by rowanseymour** [comment]
Just brainstorming but `ticket` could work like other properties which have multiple values - for example when you query `tel = 12345` you're actually querying against a set of tel URN values and the query is true if any one of them matches `= 12345`. `tel != ""` matches if there are any tel URN values, and `tel = ""` matches if there are no tel URN values.

It could be the set of ticket subjects, so `ticket = "Urgent ticket"` matches if they have a ticket with that subject, `ticket != ""` matches if they have any ticket, and `ticket = ""` matches if they have no tickets.

**Comment by rowanseymour** [comment]
Having pondered on this a lot I now lean toward the simplicity of `tickets > 0` and `tickets = 0`

@nicpottier @ericnewcomer thoughts so I can get this moving?

**Comment by ericnewcomer** [comment]
I prefer the `tickets` attribute.

**Comment by nicpottier** [comment]
To your earlier point Rowan I don't think we allow `urns > 0` or `urns = 0` do we? And those do feel kinda similar. Doesn't seem THAT crazy to include ticket name, status, created_on, modified_on, and status in Elastic for open tickets. If we stick the entire ticket body in there (and maybe interactions from agents even?) then that would also solve the issues of searching across tickets which is something we know we will eventually need.

That said I don't feel strongly on this.

**Comment by rowanseymour** [comment]
I agree at some point we need ticket searching (and we've also needed better message searching for a long time) but I think that's a likely a new ES index kept in sync with `Ticket.modified_on` rather than a contact.

**Comment by rowanseymour** [comment]
This has been implemented for a while as `tickets > 0` etc
