### ISSUE TITLE
Make `next_attempt` nullable

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#1492]
Going to pick up: https://github.com/rapidpro/rapidpro/issues/1196 again and work through it.

Step 1 is making `next_attempt` nullable and only setting it when there is an error so we can build a partial index we use for queueing retries.

From the looks of it making `next_attempt` nullable should be a cheap operation but we need to update courier/mailroom/rapidpro to deal with null values. That's where I'm starting.

**Comment by rowanseymour** [comment]
Done
