### ISSUE TITLE
Maintenance page is sometimes displaying textit logo instead of RapidPro. 

### ISSUE THREAD

**Issue by scampo** [rapidpro/rapidpro#150]
This should always be RapidPro (as with ureport.in -- sometimes bad things happen to good people...)

![screen shot 2015-03-25 at 11 13 55 am](https://cloud.githubusercontent.com/assets/7856804/6820461/54284414-d2e0-11e4-9146-18039a5e28bb.png)

**Comment by nicpottier** [comment]
This should be fixed.
