### ISSUE TITLE
Referral links with new Facebook Integration not working properly

### ISSUE THREAD

**Issue by Leosantos25** [rapidpro/rapidpro#1501]
Hi everybody!

Is anyone else having difficulty using referral links with the new Facebook integration (the one that uses a single app on developer.facebook.com)?

Some of our costumers are complaining that people who get in contact with the bot for the first time via referral links are not receiving the message that the trigger word should start.

For instance, the referral link is **http://m.me/mypagezyz?ref=test** (this is not a real page). With our old bots, people would first see a "Get Started" button and then proceed to receive messages from the specific flow that the trigger word "test" starts. However, with this new integration, looks like it doesn't happen anymore and you see nothing but the following when getting in contact with the bot for the first time via referral links:

Before the single app:
![image](https://user-images.githubusercontent.com/81816212/119551130-aa3bd700-bd6f-11eb-97fa-ff5c41041512.png)

After the single app:

![2021_05_25_0qt_Kleki](https://user-images.githubusercontent.com/81816212/119554513-22f06280-bd73-11eb-9763-78dbc9a3e45e.png)

If you have already got in contact with the bot before, the link will work just fine with no "Get Started" button though, just the flow it should trigger.

Why does this matter? Well, some countries advertise those links so that people should click them and start the conversation straight away. If the trigger word doesn't start specific flows, the contact is likely to end up talking about something else.

Looking into [the official doc](https://developers.facebook.com/docs/messenger-platform/discovery/welcome-screen/?locale=pt_BR#set_postback) I see that this button returns a payload that seems to be handled [here](https://github.com/nyaruka/courier/blob/b3a8c19f2b7e5c925ef1805f0afae53ab8f4f5b9/handlers/facebook/facebook.go). However, does anyone know how to place that button there? It doesn't look like an option you check on your page.

So are you guys experiencing the same issue?

Note: for the examples above, we created trigger words "referred id" type.

Thanks in advance everyone!

**Comment by nicpottier** [comment]
Best way to debug this would be to attach logs for what Facebook *IS* sending when those links are clicked.

**Comment by Leosantos25** [comment]
Hi Nic. Thanks for the hint. The thing is, apparently, Facebook doesn't send anything in return unless this button is set up. Looks like the payload is attached to it. I've been trying to find a way to put it there in order to see what I can catch, no success yet. What baffles me is that some bots don't have it, some others do, which is weird since we never took any actions to enable  I'm trying to figure this out with Facebook support team too.
