### ISSUE TITLE
Add support for Google/Microsoft login

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1505]
Right now admin users need to use individual username/passwords, when many orgs will likely be using either Google or Microsoft single sign on for other systems. Would be great to either include out of the box support for these or the ability to configure the SSO option of choice.

**Comment by nicpottier** [comment]
This isn't the type of thing we would likely add on our own but could see the utility for some organizations for sure. Depending on how compartmentalized it is we would likely accept a PR.
