### ISSUE TITLE
Add support for latest Template Message UI features now being rolled out by WhatsApp BSPs

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1506]
e.g headers, images, buttons, footers. We've struggled to send template messages so far and had to strip out everything but the basics in order for the Template message to send.

**Comment by davidjcole** [comment]
Turn offers the ability to use the latest WhatsApp template message UI features which includes an option to have a text, image, media or PDF header, footer copy, and buttons or a call to action as well as the standard body copy. (see image below for how these render)

Template messages including these features can be successfully detected by our version of RapidPro when filling in the WhatsApp field of a message in a flow. However, these features then cause the message to fail to send with a variety of reasons logged (see below)

Stripping out all of the features (header, footer, buttons) enables the messages to send successfully again which led us to believe these features were causing the issue.

Plus, the language synch issue which I think you're already aware of (template message language and rapidPro default language need to match) is a pain.

Here are a couple of error log examples:

Format mismatch, expected Image, received Unknown [NB this happened even when an image was attached to the message in RapidPro and the image matched the one loaded in the approved Turn template)

{"errors":[{"code":2000,"details":"body: number of localizable_params (3) does not match the expected number of params (2)","title":"Number of parameters does not match the expected number of params"}],"meta":{"api_status":"stable","backend":{"name":"WhatsApp","version":"latest"},"version":"4.42.10"}}

errors":[{"code":1008,"details":"body: Parameter of type text is missing text value","title":"Required parameter is missing"}],"meta":{"api_status":"stable","backend":{"name":"WhatsApp","version":"latest"},"version":"4.42.2"}}

We're also seeing some errors where logs aren't available for some reason e.g. 

![HYoKBfhJ](https://user-images.githubusercontent.com/6450357/120655988-1eb2fc00-c47b-11eb-91f7-2f3feea2e227.png)

**Comment by nicpottier** [comment]
Thanks, those are useful. Do these templates work if you aren't templatizing say the image itself? (that part is a constant) My understanding was this is only an issue if you are substituting into the special parameters but maybe I'm wrong.
