### ISSUE TITLE
Add support for persistent menus in Messenger

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1507]
Messenger has the option of setting a persistent menu  - an always-on user interface element that helps people discover and more easily access your bot's functionality throughout the conversation - but right now we can't set these in RapidPro

https://developers.facebook.com/docs/messenger-platform/introduction/conversation-components#sender_actions

**Comment by nicpottier** [comment]
From what I gather this would be something set at the channel level, not in a flow. So this is more about augmenting the set of things people can edit on Facebook channels (like the current "Get Started" message).
