### ISSUE TITLE
Add ability to disable credits information

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1509]
For self hosted RapidPro deployments the credits information in the workspace settings screen may be irrelevant 

![d44i3TZX](https://user-images.githubusercontent.com/6450357/120335966-d3b5af00-c2e9-11eb-92aa-938997cb5105.png)

Would be great to have a setting to disable/hide these.

**Comment by nicpottier** [comment]
Credits are actually pretty useful even in self-hosted deployments as a way of making sure things don't run out of control in the worst case scenarios, but agreed this should be an option.

**Comment by davidjcole** [comment]
Yep, can see how they might be useful for folks. For orgs like ours who have other ways of monitoring usage they aren't relevant so the ability to turn them off would be super helpful.

**Comment by rowanseymour** [comment]
We're planning now to get rid of topups/credits as it adds a layer of complexity that most deployments don't need - and a deployment that wanted to model billing that way could implement their own tracking on top of RapidPro.
