### ISSUE TITLE
Feature Request: Edit Multiple Contacts at Once

### ISSUE THREAD

**Issue by AschHarwood** [rapidpro/rapidpro#151]
For example, I want to standardize a job title across more than one contact at a time.

**Comment by ericnewcomer** [comment]
Hi Asch, I understand the request. In the meantime, you might consider the following:

* Create a group with those you want to update the job title for
* Create a flow that sets the contact field to the value you want as the first action
* Run that group through that flow

Not ideal for this particular case, but pretty flexible and will let you do other bulk operations you can dream up.

**Comment by AschHarwood** [comment]
Genius!

On Wed, Mar 25, 2015 at 10:59 AM, Eric Newcomer <notifications@github.com>
wrote:

> Hi Asch, I understand the request. In the meantime, you might consider the
> following:
>
>    - Create a group with those you want to update the job title for
>    - Create a flow that sets the contact field to the value you want as
>    the first action
>    - Run that group through that flow
>
> Not ideal for this particular case, but pretty flexible and will let you
> do other bulk operations you can dream up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapidpro/rapidpro/issues/151#issuecomment-86121511>.
>



-- 
Asch Harwood
Mobile: 646.217.8843
Skype: Aschharwood
