### ISSUE TITLE
More advanced bulk message send functionality

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1511]
Existing bulk send functionalit is very limited:

![Y4PRE927](https://user-images.githubusercontent.com/6450357/120336616-6eae8900-c2ea-11eb-859f-ecb5e2588a41.png)

Are there plans to expand this so for example we could send a message to all users in a specific group AND who have a certain user field value?

**Comment by nicpottier** [comment]
Generally the answer here is use a flow for this. If you don't want to interrupt people you can use a background flow.
