### ISSUE TITLE
Improved relevance of flow completion data

### ISSUE THREAD

**Issue by davidjcole** [rapidpro/rapidpro#1512]
Right now the flow completition data isn't eliable in the way it’s interpreted, so we’ve had to use workarounds like labels and groups.

**Comment by nicpottier** [comment]
Can you expand on this a bit? This is what we mark as how many completed a flow by reaching the last step. How would this work for you ideally? I suspect the answer MAY just be that groups are the right thing here unless a new action is added that essentially "marks" a flow run as completed or having some outcome.

**Comment by davidjcole** [comment]
Hey Nic,

When our team assesses our own contact_ids in the database after testing our flows, one person’s flowrun status will be C, another colleague’s will be I, another’s would be X, and another’s would be W. And in reality we’d all communicated with the bot in the same way and all completed the flow. So it appears the flowrun statuses are not reporting consistently across contacts. Our understanding is that C should mean completed; I should mean interrupted; X should mean expired, W waiting etc. Thus we have resorted to adding contacts to a group once they reach the end of a flow so we do know they have indeed completed the flow. We would much prefer to utilise the flowrun statuses, as recording things such as a flowrun expiring/being interrupted/waiting etc would be very valuable, but we are not certain of this metric’s definition and why the statuses are so disparate.

Does that help?
