### ISSUE TITLE
Removing URN from contact via UI makes it unusable

### ISSUE THREAD

**Issue by tybritten** [rapidpro/rapidpro#1517]
On RP v6.0.7- if you remove a urn from a contact, it does not remove the urn from the contacturn table, just sets the contactid to null. Because it still exists in the contacturn table, you cannot add that urn to another contact.

From testing in the database, it cannot remove the contacturn row if there are messages in the messages table associated with that URN. I think the fix is allowing 'add urn to contact' to either add a fresh urn or to also claim a urn that has a null contactid

This only happens via the UI. If you remove a urn from a contact in a flow, it works fine.

**Comment by rowanseymour** [comment]
It's intentional that URN's are not deleted but just detached from contacts. That URN may still be associated with messages and connections etc. Adding a URN to a contact should allow you to claim a URN that has no attached contact. If that isn't happening, that's a bug.

**Comment by rowanseymour** [comment]
I'm not able to replicate this in 6.3.x tho I don't recall us changing this recently. Mailroom handles all contact updates and uses the same URNsModifier for flow actions as UI driven requests.. could it be a URN normalization issue? What is the error you see in the UI?

**Comment by tybritten** [comment]
from the UI perspective it just wont save and say an error has occurred. When i check the dev console, I can see the call to the contacts api endpoint is what's failing. Let me try to get a repro. The last few times theyve been ext urns which are apple ids (which are pretty long)
