### ISSUE TITLE
Scheduled Triggers (weekly) issue when creating new ones

### ISSUE THREAD

**Issue by moymoussan** [rapidpro/rapidpro#1518]
When you create a Scheduled Trigger trough the UI, when selecting "weekly" the option for "repeat days" does not appear. The option only appears after selecting "save changes" (shows an error and then the option appears).

When editing triggers theres no problem.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/3372
