### ISSUE TITLE
Add extra fields on "Enter a flow" action

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1523]
What do you guys think about a tab in the `Enter a flow` action, where the user can input Extra fields (the UI can be similar to Webhook headers with key and value) to start the flow?

For example:
![Captura de Tela 2021-06-30 às 17 32 35](https://user-images.githubusercontent.com/6073075/124027709-8e100300-d9c9-11eb-84ef-d09d2e41f66e.png)

It will help users organize how they send information to the sub-flow and expand the possibility of creating Flows that act as "modules" or "mini-apps". Do you guys agree that's a PR welcome here?

**Comment by rowanseymour** [comment]
We already have some functionality that tries to do this. We look for references to `@parent.results.*` in a flow when you save it, and when you select that flow in a Enter Flow action, we list those as parameters, e.g. the Test Child flow references `@parent.results.foo`, so..

<img width="670" alt="Captura de Pantalla 2021-06-30 a la(s) 15 52 57" src="https://user-images.githubusercontent.com/675558/124029918-45e9e400-d9bb-11eb-8dbe-f0d5f672be75.png">

<img width="672" alt="Captura de Pantalla 2021-06-30 a la(s) 15 53 04" src="https://user-images.githubusercontent.com/675558/124029937-497d6b00-d9bb-11eb-9e95-0be5cae0c7db.png">

**Comment by johncordeiro** [comment]
Hey @rowanseymour , that's incredible! We're thinking to build a kind of marketplace to share flows across users, and this is a big step forward.
