### ISSUE TITLE
Hubspot Ticket Service

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1527]
Hello everyone, we noted an interest in some customers in the integration of Rapidpro with Hubspot. These customers need integration on Hubspot for Hybrid conversation (Agent/Human), this integration can be a ticket service type like rocketchat, zendesk and mailgun. We starting our Q3 roadmap this month and we are planning to implement this integration and open a pull request. What do you think?

Refference:
* https://www.hubspot.com/
* https://legacydocs.hubspot.com/docs/methods/forms/submit_form_v3_authentication
* https://developers.hubspot.com/docs/api/overview

**Comment by nicpottier** [comment]
I think as long as it fits into the current ticketing model we are definitely fine with this.

**Comment by rowanseymour** [comment]
See https://github.com/rapidpro/rapidpro/issues/1612 for why this not something we're keen on now.
