### ISSUE TITLE
Deleting a contact by urns not working

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#153]
Sending a delete request to https://api.rapidpro.io/api/v1/contacts.json with a phone number or list of phone numbers does not seem to have any impact on rapidpro contacts data. 

An empty 204 response is returned as expected(from api reference) but the contact is never removed rapidpro.

**Comment by norkans7** [comment]
To delete contact you need to submit either its uuid or its urn, we do not support deleting contact by phone field.
