### ISSUE TITLE
Surfacing channel errors

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1538]
While we show channel errors, users aren't really made aware of significant issues with their channels without visiting the channel log. Customers wanting some kind of notification that a channel went off the rails at some point (see Facebook) has come up more frequently of late. This has long felt like a pretty important missing feature.

One way this could work is perhaps a scheduled task that checked all active channels' error rates and flagged them at some threshold until a human acknowledged it. We could then have an alert over the channel icon as long as it was present. We could send email alerts when that alert activates (but probably only if we require human intervention to clear it).

**Comment by ericnewcomer** [comment]
If we want to go crazy, another way to think about this could be a monitoring dashboard that showed flow activity, channel activity, error rate, etc though I'm inclined to do the simplest thing here.

**Comment by rowanseymour** [comment]
I noticed that we do currently try to do this for Android channels.. but the alerts never actually appear (they styled as `display: none`) and it's not particularly useful only doing this for Android channels

https://github.com/rapidpro/rapidpro/blob/1a7a83bd5333c7d96605249c7cc9afd51bcffaed/templates/includes/nav.haml#L261-L280

**Comment by ericnewcomer** [comment]
Ya, this used to be a thing back in the day when Android was the only channel type.

**Comment by nicpottier** [comment]
We've actually done this at various times and it wouldn't be hard. It probably is the right thing but I know that carrier connections are often so brittle and browning out that it isn't rare for us to get tons of errors before we retry to send everything out. But exposing it and then addressing that they will be retried etc probably is the right thing.
