### ISSUE TITLE
Feedback when entering invalid dates on contact fields

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1546]
Repro:
  * Create a contact field of type date
  * Update that field with text that doesn't conform to date format

Expected:
User should receive a form validation error informing them of the proper format for a date field

Actual:
User is brought back to the same form with an empty text box and no idea what happened or how to fix it.

**Comment by rowanseymour** [comment]
This is addressed in the new UI which adds datepicker widget for fields of that type
