### ISSUE TITLE
Support more than one header in External Channel

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1547]
Hello everyone, recently we identified a necessity to configure more than one header when configuring a channel for external API. For example, if need to integrate an API with an external API on Rapidpro, that doesn't have a native channel, and to use this API is necessary more than one header, it's not possible to configure with external API, is necessary to implement a channel to integrate with this API. 

We can use the same field for headers that have today on Rapidpro to configure the headers on external channel API, and this field can accept a JSON for example that you can add many keys (headers) and the respective values from headers (values from keys).

**Comment by rowanseymour** [comment]
You mean the `send_authorization` config field? I think better to add a new `headers` field and migrate existing channel configs to populate that as `{"Authorization": send_authorization}`.

Having control over headers seems reasonable tho the UI for adding external channels is already pretty insane so I'm a little apprehensive about making it even more complicated.

If this is a single customer we could leave the UI as is for now, but save to `headers` and update courier to use that. Then you can manually set that field...
