### ISSUE TITLE
User friendly channel log errors for common cases

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1548]
Populate an optional description on channel logs for common well structured channel logs. We direct users to inspect channel logs on sending errors. We can do a better job for common errors to surface on the contact history page. 

  * Twilio trial non validated errors
  * Twilio non SMS number
  * Twilio stopped contact
  * Facebook OAUTH
  * Facebook/WA outside 24 hours

And several others. We should audit then current set of channel errors and identify which ones to give this treatment. An optional help url to point to the appropriate help docs (on Twilio, FB dev, etc) could also be a consideration.

**Comment by rowanseymour** [comment]
Have made some improvements for Twilio and Vonage errors in https://github.com/nyaruka/courier/pull/543

**Comment by ericnewcomer** [comment]
Closing this, will create new discussion for Facebook
