### ISSUE TITLE
External API channels can have extra parameters submitted with MO messages requests

### ISSUE THREAD

**Issue by norkans7** [rapidpro/rapidpro#1550]
It could be useful to collect those and make them available in the flow on the `input` context in the flows

example 

https://HOST/c/ex/d7920b02-cd4e-46e9-973d-72b330274670/receive?from=PHONE&text=TEXT&user=NAME

currently we collect the text and phone but we could also collect the name in a way the the admin can use in a flow

**Comment by rowanseymour** [comment]
Definitely don't want to go the route of courier knowing about contact fields - I think the way these things should generally work is more like referral triggers - users can access additional data in a flow through `@trigger.*` and then they can decide in a flow if/how to turn that into contact field values.
