### ISSUE TITLE
Feature Request: Select Nodes to create sub-flow

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#1566]
Hi!
Refactoring flows would be much easier if it was possible to select nodes in a flow and create a sub-flow out of those nodes.

Thanks!

**Comment by ericnewcomer** [comment]
Agreed, I've often found myself in a similar situation. Perhaps this belongs in https://github.com/nyaruka/floweditor though.

**Comment by cromulus** [comment]
Moving to flow editor!
