### ISSUE TITLE
Better bot detection

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1575]
Saw a single contact in an "Other" loop fail to break out causing mailroom to back up. Need a way to eject bad contacts from flows instead of relying on dupe detection at the courier level to break out runaway contacts.

**Comment by rowanseymour** [comment]
We moved duplicate message detection into mailroom and added a limit on the maximum resumes per session. One last piece would be creating an incident and notifications so that users can deal with this and it not just be a thing we log as an error.
