### ISSUE TITLE
Delete, Archive and/or Manage Groups

### ISSUE THREAD

**Issue by AschHarwood** [rapidpro/rapidpro#158]
It would be great to have some tool to manage group clutter, either by nesting or deleting them

**Comment by nicpottier** [comment]
Hi Asch.

You can delete groups right now, just use the gear menu after you click on a group on the Contacts page.

**Comment by AschHarwood** [comment]
Brilliant!

On Wed, Apr 8, 2015 at 1:29 PM, Nic Pottier <notifications@github.com>
wrote:

> Hi Asch.
>
> You can delete groups right now, just use the gear menu after you click on
> a group on the Contacts page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapidpro/rapidpro/issues/158#issuecomment-90981426>.
>



-- 
Asch Harwood
Mobile: 646.217.8843
Skype: Aschharwood
