### ISSUE TITLE
Rapidpro with Twilio: Mailroom Url is not a valid URL

### ISSUE THREAD

**Issue by FlorentinCONGO** [rapidpro/rapidpro#1585]
Hello everyone. I deployed and configured rapidpro with mailroom, mail ... I then connected my rapidpro instance with a twilio channel. When I make a call I have the following error:
{"code": 21205, "message": "**Url is not a valid URL: https:///mr/ivr/c/620da070-98c7-4dc1-af81-f74899494bd8/handle?**action=start&connection=10&start=11&urn=tel%3A%2B22673211539%3Fchannel%3De78ffa38-c5fe-4e6f-9155-5cdbd4c00f39%26id%3D2%26priority%3D1000", "more_info": "https://www.twilio.com/docs/errors/21205", "status": 400}

I don't know where I should configure the mailroom url?

Could you help me?

**Comment by moymoussan** [comment]
Temba - settings

**Comment by FlorentinCONGO** [comment]
Thank you M. @moymoussan, 
Which settings file should I modify? between the settings.py or settings_common.py file?
and if possible could you tell me the location in the affected file?
Thanks in advance!

**Comment by rowanseymour** [comment]
`settings_common.py` is typically where we set default values and `settings.py` is where you override things as needed for your deployment. You need to set `MAILROOM_URL` and `MAILROOM_AUTH_TOKEN`.

In future please use the RapidPro developers list for these sorts of questions.
