### ISSUE TITLE
Filter httplog by Contact or Flows

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1592]
Hello everyone, I've seen the changes in version 6.5.51 about the WebHookResult drop and the use of HttpLogs instead. Before this drop, it was possible to filter WebHookResult by contact. I can see the necessity of filtering HttpLogs by flow or contact to be able to investigate issues more precisely.

Today how can we improve HttpLog to be able to filter by contact or flows?

**Comment by matmsa27** [comment]
Hey guys, are you available to discuss this point?

**Comment by rowanseymour** [comment]
Sorry I actually started work on making them filterable by flow at one point but got sidetracked. We'd be open to a PR making them filterable by flow. Less keen on contact since that requires adding yet another field/index.
