### ISSUE TITLE
Translating arguments for subflow router

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1598]
Ran into an issue where a user exported a PO file, translated everything and imported. During the import, it applied to the arguments in the subflow router causing contacts to route erroneously into the expiration route (the rules here are expecting to evaluate on the status of either `completed` or `expired`.

See video showing the issue here:
https://app.crisp.chat/website/2a810199-9469-490b-8be9-d3d994c3e788/inbox/session_f4bc7b47-1b11-4c7a-9400-965b9f629545/

**Comment by rowanseymour** [comment]
Removed option to include router arguments in PO files in https://github.com/nyaruka/rapidpro/pull/3644 and https://github.com/nyaruka/mailroom/pull/562
