### ISSUE TITLE
Email test not working as intended thank to missing comma 

### ISSUE THREAD

**Issue by code-review-doctor** [rapidpro/rapidpro#1599]
This test has missing comma on line 572
https://github.com/rapidpro/rapidpro/blob/44f12b8593231ecb33fc652a5766515fa474bd2f/temba/utils/tests.py#L570-L575

it's hard to spot so I will break it down a bit. Line 572:

'"()<>[]:,;@\\"!#$%&\'-/=?^_`{}| ~.a"@example.org' '" "@example.org',

should have a comma after `ple.org'` ie

'"()<>[]:,;@\\"!#$%&\'-/=?^_`{}| ~.a"@example.org', '" "@example.org',

The absence of this comma means the two strings are implicitly concatenated together.

This means the email test is not covering those two email addresses and instead uses '"()<>[]:,;@\\"!#$%&\'-/=?^_`{}| ~.a"@example.org" "@example.org',

I can make a PR to fix this for you?

**Comment by rowanseymour** [comment]
Good spot - I just fixed this now
