### ISSUE TITLE
Allow deletion without archiving for configured workspaces

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1601]
From a TextIt user. 

User has data sensitive in nature. They use the platform as a triage system of sorts. Once contacts meet some requirement, they are shuttled to another CMS system where they get followed up on.

They would like to disable archives. Instead of archiving, data would just be deleted after 90 days.

**Comment by rowanseymour** [comment]
Not archiving sounds great! I think I'd put a bool field on `Org` and have rp-archiver handle that accordingly

**Comment by ericnewcomer** [comment]
See: https://github.com/nyaruka/rapidpro/discussions/4226
