### ISSUE TITLE
Change `SESSION_ENGINE` from `cached_db` to `cache`

### ISSUE THREAD

**Issue by Sandro-Meireles** [rapidpro/rapidpro#1607]
In our fork we are using a custom login system which requires high speed when saving data in the session, using `django.contrib.sessions.backends.cached_db` is causing some errors. We would like to understand the reason behind using this engine and if we would take any risk in changing it to `django.contrib.sessions.backends.cache`.

**Comment by rowanseymour** [comment]
This has come up before (https://github.com/rapidpro/rapidpro/issues/708) and I'm not aware of any important reason to keep using db sessions, it just hasn't been a priority for us to switch. Feel free to make a PR for this.
