### ISSUE TITLE
Integration with Twilio Flex as ticket service

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1612]
Hey guys, I would like to purpose to you a new ticketer service on Rapidpro, which is about Twilio flex.

Twilio Flex has an API that you can open a chat directly with a human (Flex or Agent Desktop), to talk with a contact. So, this will work like other ticketer services on Rapidpro, the contact will start a chat with a channel on Rapidpro, the flow will run for this contact, and if necessary the flow will have a card to open a ticket on Twilio Flex, with this the attendant will receive a new chat and talk with the contact communicating with Rapidpro.

To make this integration pls see the documentation:
- https://www.twilio.com/docs/chat
- https://www.twilio.com/docs/flex
- https://www.twilio.com/docs/taskrouter

We are open to working on this and opening the PRs on the Rapidpro side and mailroom side.
Thanks a lot.

**Comment by rowanseymour** [comment]
Hey, so we've been chatting about this as a team and we feel everyone's time would be better spent working on the internal ticketing functionality. We added support for Zendesk etc at a time when we weren't even considering building ticketing into the platform, and we'd rather invest time in that, than take on the technical debt of another integration with an external system. I don't know if you guys have played much with what is there but there are definitely some low-hanging-fruit improvements we'd love to get your help with.

**Comment by matmsa27** [comment]
Hi @rowanseymour, thanks for your response. We go ahead with the integration here, and after we have feedback from our customers and the use for it, we will bring to here to improve the discussion about the internal ticketer and the service third tickets integrated (like zendesk, twilio flex, and rocketchat). Thanks.

**Comment by ericnewcomer** [comment]
Hey guys, I just wanted to say that this is probably a good candidate to live on a public fork as you expose that to your customers. Ticketers as third party services, while intended to be pluggable, is not something we necessarily see as a good direction for the platform at this juncture, so it is unlikely to be something we would merge and maintain.

I also just wanted to echo @rowanseymour 's comments that we very much would welcome contributions to build out the feature set for internal ticketing.  We have an established roadmap of features to collaborate on and see it as a pillar of the platform.

**Comment by matmsa27** [comment]
Hi Eric, ok, I agree with you. Is interesting for us and the community that the ticketed service keeps as a pluggable,  so I would like to ask you to keep this alive so that this Twilio flex integration will keep alive in our fork. 
Could you share with us the roadmap about the internal ticketing? We can contribute to the roadmap and improvements on the internal ticketer.

**Comment by rowanseymour** [comment]
We have this list of things we _think_ it needs https://github.com/orgs/nyaruka/projects/4/views/1 - tho I would say we're about to talk to some U-Partners users and that might alter our priorities.

**Comment by matmsa27** [comment]
Hi @rowanseymour , I believe that the project on GitHub that you shared with the roadmap about internal ticketer is a private project, and I haven't access to see.

**Comment by rowanseymour** [comment]
Ah oops try again now
