### ISSUE TITLE
Problem exporting contacts using Elasticsearch in AWS by Elastic Cache service

### ISSUE THREAD

**Issue by Sandro-Meireles** [rapidpro/rapidpro#1613]
Currently, we are using the Elasticsearch in AWS by Elastic Cache service, with this service we found a problem related with `contact_export` and `check_elasticsearch_lag` tasks on Rapidpro. The lib that are using in rapidpro to do connection with elasticsearch have a [condition](https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/transport.py#L655) that validate if the `build_flavor` is equal to `"default"`. In our case, `build_flavor` is returned like `"oss"` because of AWS Elastic Cache limitation.  

Causing a `UnsupportedProductError`, message:  "The client noticed that the server is not a supported distribution of Elasticsearch"
![image](https://user-images.githubusercontent.com/49874732/154370749-1f8fbd14-4aed-44bf-8dcd-cad4bd2bd294.png)

References:
Validate if the `build_flavor` is equal to `"default"` and returns `UNSUPPORTED_DISTRIBUTION`:   
https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/transport.py#L668

Call the `raise_error` method if `_verified_elasticsearch` does not equal `True`
https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/transport.py#L412

Validate that the passed state is equal to `UNSUPPORTED_DISTRIBUTION` and raise the exception
https://github.com/elastic/elasticsearch-py/blob/v7.15.2/elasticsearch/transport.py#L620

AWS Elasticache License Change Article(Stepping up for a truly open source Elasticsearch):  
 https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/

**Comment by rowanseymour** [comment]
From reading https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883587433 it seems this is intentional. For now I think you can revert the client version to anything pre 7.14 (it's on 7.15.2 in main). Long term if OSS diverges from official ES we'll need to pick one or the other.
