### ISSUE TITLE
Missing authentication error when adding Vonage channel

### ISSUE THREAD

**Issue by George-Kamau** [rapidpro/rapidpro#1619]
We have encountered an issue when trying to add the Vonage/Nexmo channel on textit.in. 
When attempting to connect to a phone number, we get the following missing authentication error:

`Missing Auth: Auth header is required (https://developer.nexmo.com/api-errors#missing-auth)`

![image](https://user-images.githubusercontent.com/49223522/155482973-b0a6cb0a-d5c6-42a4-8a4e-72dcbcf40cc2.png)

Kindly assist in troubleshooting this.

**Comment by eochieng-lab** [comment]
@rowanseymour , requesting your support with this issue.

**Comment by norkans7** [comment]
I believe that was fixed with https://github.com/nyaruka/rapidpro/pull/3711
So that is going to be available  in the next release soon.
Always pull requests are welcome for such issues

**Comment by George-Kamau** [comment]
@norkans7 

Any idea of a timeline for the deployment of the next release?

**Comment by norkans7** [comment]
7.2 release candidates that include the fix were released 3 days ago
And the final release will be available within the following 2 weeks
Follow the google group https://groups.google.com/g/rapidpro-dev for the release notes as well coming soon
