### ISSUE TITLE
No limit for reset password 

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1624]
Hey guys, recently we found a potential issue that can compromise the email server. When you will recover a password that you have forgotten about in your account, you can request the link for recovery password infinite time, this action can compromise the email server and it can suffer actions like being added to a black list for example.

Possible solutions for this:
1 - Implements a captcha when the user will recover the password, and with this can prevent attacks.
2 - Implements a limit for identifying that the user/email has requested to change the password before. Can define a limit, for example, a user/email can request to change their password 5 times in 12 hours for example.

**Comment by rowanseymour** [comment]
We only send to email addresses that are associated with a user in the system so it would seem safe to have a limit on the number of times we'll send the forgot password email to particular user in X amount of time.

**Comment by matmsa27** [comment]
Ya, I got it, I agree with you. What are your thoughts about this implementation @rowanseymour ? What is the number for the limit? What value for the amount of time?

**Comment by rowanseymour** [comment]
I think we can implement this by checking how many RecoveryToken's have been created for that user in the last X hours... I'm inclined to say you get 5 in 24 hours

**Comment by matmsa27** [comment]
Nice, thanks a lot for sharing your thoughts @rowanseymour , we will open a PR for this.
