### ISSUE TITLE
changed the parameter GLOBAL_VALUE_SIZE doesn't work

### ISSUE THREAD

**Issue by dayures** [rapidpro/rapidpro#1628]
Environment: rapidpro version 6.2.4

Assumption: the parameter GLOBAL_VALUE_SIZE set the max size of the value saved on each field of @ results.

Use Case: during the flow, there is a call to an API and it returns a JSON that it is saved in a field of @ results. The amount of characters returned in one case is ~11.000, and we need to deal with that scenario. Is GLOBAL_VALUE_SIZE the proper parameter to be changed?

It looks like changing the value of the parameter GLOBAL_VALUE_SIZE from 10_000 to 15000 in the file https://github.com/rapidpro/rapidpro/blob/main/temba/settings_common.py#L1249 is not working. Is it needed some restart ?

**Comment by rowanseymour** [comment]
`GLOBAL_VALUE_SIZE` determines the maximum size of `Global` values and has nothing to do with results or webhooks.

When a webhook response has been fetched, the entire response body is accessible at `@webhook`... for the duration of the current sprint. If the body is less than 10000 bytes (currently hardcoded in goflow at https://github.com/nyaruka/goflow/blob/main/flows/actions/base.go#L24) that is also stored as `.extra` on the result. That was done for backwards compatibility and isn't something we recommend users rely on.

We could make that configurable but obviously there's a cost to persisting and loading the session output, so you really don't want to be putting giant webhook responses in there too.

**Comment by dayures** [comment]
@rowanseymour thanks for the great feedback.
How can I deal, in the rapidpro workflow, with responses with more than 10000 bytes and responses with less bytes?
When you said "current sprint", what does it mean ?
Any recommendations on this use case (that I cannot change so much the size of the response fetched)?

**Comment by rowanseymour** [comment]
What we recommend to users is that they extract what they need from `@webhook` and store that in a result manually if they want it to be a result.

A _sprint_ in the engine is a contact moving thru a flow until they reach a wait or the end of the flow. Nothing is persisted in the database until the end of a sprint.

**Comment by dayures** [comment]
Thanks @rowanseymour 
And in our case, we are saving the JSON received from a service (using "Call Webhook"), in a result. But depending on the size of the JSON file, the payload is saved or not (amounts higher than 10.000 characters are not saved).
