### ISSUE TITLE
FB Messenger Not Going Through

### ISSUE THREAD

**Issue by ndomoika** [rapidpro/rapidpro#1639]
Hi, we seem to be having issue on FB messenger, trigger word is not going through and we are getting this error. 
![image](https://user-images.githubusercontent.com/103161929/162114797-fb89b42b-d083-4578-b595-ad6d3775fcf3.png)
 Any suggestions?

**Comment by ndomoika** [comment]
![image](https://user-images.githubusercontent.com/103161929/162126027-4c2da7a3-5efd-44b9-afbd-024d272ab333.png)

**Comment by rowanseymour** [comment]
Please use the developer mailing list for deployment questions like this https://groups.google.com/g/rapidpro-dev
