### ISSUE TITLE
Add Slack and Microsoft Teams as new channel types

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1661]
Hey guys, I am opening this issue to get your perspective about integration for Slack and Microsoft Teams on Rapidpro as channel communication.

We know that some companies need to integrate your slack workspace and their Microsoft Teams account into Rapidpro to improve the communication with their employee. For example, that is a use case that is interesting to share, some users shared with me an organization on Rapidpro to run an employee satisfaction survey, getting and send documents and process that related company and employee.

**Comment by matmsa27** [comment]
Hey guys @rowanseymour @ericnewcomer what do you think?

**Comment by rowanseymour** [comment]
Hi @matmsa27 , I'm not so familiar with Teams and haven't used Slack in years. They're both primarily group chat platforms, but do they both have a concept of private messages between users.. where one of those users can be a bot?

**Comment by matmsa27** [comment]
Ya, exactly. Slack and Teams have the support for a user can be a bot, like a role for example. When you set up the user with this role you can configure this user to be a bot connected to an external platform like Rapidpro, and with this, the user can talk with the bot, send messages and start flows to the user, and the same in another way, with the contact created on Rapidpro, Rapidpro can start the flow for the user on these platforms for example.

**Comment by rowanseymour** [comment]
Ok well if there's nothing inherently different about adding these as channel types then go ahead and make the PRs for Courier and RapidPro

**Comment by matmsa27** [comment]
Nice. First, we will open about slack and then about teams.
