### ISSUE TITLE
Start Somebody Else flow action should support excluding contacts already in a flow

### ISSUE THREAD

**Issue by tybritten** [rapidpro/rapidpro#1662]
Start a user in a flow works as expected, including removing them from an active flow to achieve it. An option to attempt to start a user on a flow, but abandon it if the user is currently active in a flow. 

Sometimes we want to start a user in a flow, but don't want to disturb their existing session if they're in one.

**Comment by ericnewcomer** [comment]
Is this different than the checkbox on the Start Flow dialog "Exclude contacts currently in a flow"?

**Comment by putorti** [comment]
Tyler means the flow step, "Start Somebody Else in Flow"

The fact that it will always boot someone from an active session makes it a dangerous step to use, it would be good to have the option to not do that, same as the manual flow starts have in the UI.

**Comment by ericnewcomer** [comment]
Ah, makes sense!

**Comment by rowanseymour** [comment]
@susanm74 can you look at the editor side of this?

[x] Skip contact if they're currently in a flow

```
exclusions: {"in_a_flow": true}
```

@ericnewcomer the complication here is that the engine currently only starts 1 contact.. _1 somebody else_, but the editor UI isn't explicit about that and you can still add multiple contacts etc.

<img width="678" alt="Captura de Pantalla 2022-10-24 a la(s) 11 24 32" src="https://user-images.githubusercontent.com/675558/197576685-0f371a91-44b2-4bf7-aab8-4a8acb3199bc.png">

**Comment by susanm74** [comment]
ok, so it sounds like 2 changes for this one:
- add checkbox to skip contact(s) if they're currently in a flow
- limit the selector to only allow adding 1 contact? OR continue to allow adding multiple contacts, but make the wording more clear?
@rowanseymour

**Comment by rowanseymour** [comment]
Need to discuss with @ericnewcomer if we are committed to this action being the Start Somebody Singular action.. I still wonder if it could be an advanced option to allow up to N contacts.

FYI it used to start an unlimited number of contacts but we found that more often that not caused users to shoot themselves in the foot and create explosions of flow starts.

**Comment by tybritten** [comment]
@putorti do we start multiple users this way today?

**Comment by rowanseymour** [comment]
Ahhhh I'm confused my bad it's only if you use a querry that we limit to one contact

<img width="465" alt="Captura de Pantalla 2022-10-25 a la(s) 08 52 39" src="https://user-images.githubusercontent.com/675558/197792276-d0014621-7dc7-41aa-a498-c55e7ebe78f6.png">

So the wording is fine - but for this checkbox wording needs to work for both multiple recipients and single contact query... I guess...

[x] Exclude contacts currently in a flow

**Comment by putorti** [comment]
> @putorti do we start multiple users this way today?

When for example, Rosie follows Jessica, Jessica will get a push notification because Rosie's action will start Jessica in the push flow. However, this is only because I forgot to remove it, apparently; as it could potentially interrupt someone in an active flow. This happened all the time with our most active organizer because she is always writing something and also always hitting petition goals, gaining followers, etc. So generally, we don't do this because of the inability to not interrupt people in active flows. We have to queue them up in campaigns, etc. I think maybe we can run them in a background flow, that seems new, but background flows aren't supposed to be able to message, and yet they can. If a background flow doesn't interrupt a user, then we could just use that, I just thought the entire premise of a background flow was that it couldn't message.

**Comment by rowanseymour** [comment]
> I think maybe we can run them in a background flow, that seems new, but background flows aren't supposed to be able to message, and yet they can

Background flows can send messages - what they can't do is wait for a response from a user - or wait for anything since that would require interrupting any existing session that is also waitingcuz we can't have two waiting sessions for a single contact.

**Comment by putorti** [comment]
@rowanseymour Can they be initiated from messaging flows though via a standard "enter a flow" step? Or is it only that messaging flows can't be initiated in background flows? I've had to create multiple versions of the same flow for this reason.

**Comment by rowanseymour** [comment]
@putorti for now _Enter flow_ actions only work with flows of the same type

**Comment by susanm74** [comment]
@rowanseymour just want to confirm that we want to mirror the "skip contacts in a flow" functionality, which i believe mostly lives in rapidpro, in the floweditor, yeah? ex. contacts -> click a contact -> click start flow - > and then here's a screenshot of the form that displays (they have a VERY similar look/feel as floweditor forms, but just want to sanity check, as i believe this form is a rapidpro form):
<img width="627" alt="Screen Shot 2022-10-26 at 2 38 06 PM" src="https://user-images.githubusercontent.com/854012/197964268-bc28ce44-b9bd-47f3-b068-cb6cb326e8b6.png">

**Comment by norkans7** [comment]
@susanm74 in the flow editor a contact can start other contact in a different flow, so for that action we want to allow configuring that to specify whether to skip active contacts in another flow at that time

**Comment by susanm74** [comment]
@norkans7 makes sense, just wanted to moreso confirm that this issue is meant to implement a duplicate feature in the floweditor repo that currently only exists in the rapidpro repo, yeah?

**Comment by norkans7** [comment]
The one that exits in rapidpro is when a wirkspace admin is manually starting a flow to contacts or a group.

Here we need the similar configuration when a flow start somebody else in another flow
So a contact A will be going in a flow and when the reach the start somebody(Contact B) else in a flow that action will have to check on the configuration to decide whether the contact B should be started and interrupted from other flows or should just ignore the start and keep the contact B in the same flow it was in at the time

**Comment by rowanseymour** [comment]
@susanm74 yeah I think you can copy the wording from the flow start dialog since it will mean the same thing

**Comment by ericnewcomer** [comment]
Fixed in nyaruka/floweditor#1061
