### ISSUE TITLE
Whatsapp channel token refresh should continue when one fails

### ISSUE THREAD

**Issue by morrismukiri** [rapidpro/rapidpro#1664]
Currently, if a token refresh fails in the task `refresh_whatsapp_tokens` (temba/channels/types/whatsapp/tasks.py) for one channel for a reason like a timeout, the rest of the channels will not be updated.

Related to https://github.com/rapidpro/rapidpro/issues/1654

**Comment by rowanseymour** [comment]
This was fixed a while back https://github.com/nyaruka/rapidpro/commit/b920d2ee1334c516fa793b3898405427425f59ed
