### ISSUE TITLE
Mailroom start preview query doesn't apply recency query correctly

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1669]
Note, the Start Flow dialog is not wired into the preview endpoint yet, so this screenshot is from local development.

<img width="576" alt="Screen Shot 2022-06-29 at 5 02 16 PM" src="https://user-images.githubusercontent.com/211652/176565520-f7f4cb15-112a-4b3a-9967-507722fb192d.png">

Expected a preview query akin to:
(name ~ "ben" OR name ~ "eric") AND last_seen_on > "01-04-2022"

But instead, the recency is grouped with the last item of the search:
name ~ "ben" OR (name ~ "eric" AND last_seen_on > "01-04-2022")

**Comment by rowanseymour** [comment]
The query generation code is definitely wrong.. but weirdly I can't replicate that result. I see `name ~ ben OR name ~ eric AND last_seen_on > 21-03-2022` which is still wrong because AND takes precedence over OR.
