### ISSUE TITLE
Either plug perf_tests into Travis or remove them

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#167]
Our current perf_tests.py in /temba are pretty old and I'm not sure relevant any more.

We should figure out if we want to keep these, and if so, then make them fail on some conditions and/or report useful metrics, then add them to Travis so they are built automatically.

**Comment by rowanseymour** [comment]
These were replaced with a perf_test command which benchmarks a list of URLs but same problem remains that we don't test it in Travis so it could easily end up broken.

**Comment by nicpottier** [comment]
Gone! Also not at all relevant anymore.
