### ISSUE TITLE
Add support for template messages on Facebook/Instagram channels

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/rapidpro#1670]
Hi Guys, I am opening this issue to get your thoughts about Rapidpro supporting template message on Messenger platforms (Instagram and Facebook channels). 

Reference: https://developers.facebook.com/docs/messenger-platform/send-messages/templates

**Comment by rowanseymour** [comment]
As with all channel specific features, you have to ask yourself what this would look like across the other channel types. I'm not convinced this isa sufficiently useful feature to justify introducing something specific to FB/IG.
