### ISSUE TITLE
Facebook recurring notifications

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#1673]
Facebook recently opened up their recurring notifications API. This is a way to get ongoing opt-in at regular intervals to allow outbound messages to be sent. This likely represents a replacement of the tag attribute / notification type.

This likely necessitates formalizing the concept of opt-in at the platform level with a way to configure opt-in requests and channels with a way to utilize it. Or maybe this all belongs at the Facebook channel level and the configuration exists therein. In any case, general flow is:

To send daily, you need to get weekly opt-in.
To send weekly, you need monthly opt-in.
To send monthly, you need yearly opt-in.

More here:
https://developers.facebook.com/products/messenger/recurring-notifications/

Additionally, the WhatsApp 24 hour messaging window requiring a template might fit into this recurring opt-in model.

The challenge here is how / where to abstract this functionality.

Additionally, this is likely a critical piece for U-Report going forward.

**Comment by norkans7** [comment]
Looking at the docs, It seems we need to store the token on the contact and not the channel 
And a contact can have more than one token; one for each frequency

**Comment by ericnewcomer** [comment]
Tracked here: https://github.com/nyaruka/rapidpro/discussions/4217
