### ISSUE TITLE
Performance issue in task `trim_http_logs_task`

### ISSUE THREAD

**Issue by Sandro-Meireles** [rapidpro/rapidpro#1680]
We are having problems with the `trim_http_logs_task` task, in our environment, this table has a large volume of data, 102.31 GiB to be exact. This causes the task to terminate without erasing any data, generating a "snowball effect". I discovered that the problem is precisely in the query, as it requires all data in the `trim_before` range to be returned.

I made an adjustment to the query that solves this problem inspired by the `trim_flow_sessions` task:

```py
...
    while True:
        http_log_ids = HTTPLog.objects.filter(created_on__lte=trim_before).values_list("id", flat=True)[:1000]

        if not http_log_ids:
            break

        HTTPLog.objects.filter(id__in=http_log_ids).delete()
        deleted_count += len(http_log_ids)

        logger.info(f"[ Trim HTTPLogs ] Deleted {deleted_count} HTTPLogs")
...
```
I would like to know if you have already noticed this problem and if this resolution makes sense.

**Comment by rowanseymour** [comment]
We haven't seen that but your change looks reasonable - make a PR
