### ISSUE TITLE
Channel Logs in S3

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1681]
Maybe instead of creating `channels_channelog` rows for HTTP calls and error messages that occur during message handling, we create a single JSON file in S3 for each courier "transaction".

The paths of the files contain the message UUID, so for a given message we can infer the S3 path prefix of its logs, and get them all back with a list request. Maybe each filename is a timestamp, e.g.

```
http://logs.s3.com/orgs/123/channel_logs/8eb2/8eb23e93-5ecb-45ba-b726-3b064e0c568c/12345678904.json
```
```json
{
   "type": "message_send",
   "message": {
     "id": 2354266762,
     "contact_id": 3245425,
     "urn_id": 56858448
   },
   "http_logs": [
      {
        "url": "https://api.cool.com/message?text=Hello",
        "status": "success",
        "request": "GET /message?text=hello HTTP/1.1",
        "response": "HTTP/1.1 200 OK\r\n\r\n",
        "created_on": "2006-01-02T15:04:05Z",
        "elapsed_ms": 123
      },
      {
        "url": "https://api.cool.com/message?image=23425",
        "status": "success",
        "request": "GET /message?text=hello HTTP/1.1",
        "response": "HTTP/1.1 200 OK\r\n\r\n",
        "created_on": "2006-01-02T15:04:05Z",
        "elapsed_ms": 123
      }
   ],
  "issues": [
    {"type": "attachment_too_big", "attachment": "http://big.jpg"}
  ]
}
```

```
http://logs.s3.com/orgs/123/channel_logs/8eb2/8eb23e93-5ecb-45ba-b726-3b064e0c568c/12345678906.json
```
```json
{
   "type": "delivery_report",
   "message": {
     "id": 2354266762,
     "contact_id": 3245425,
     "urn_id": 56858448
   },
   "http_logs": [
      {
        "url": "https://textit.com/c/23432532523/status",
        "status": "success",
        "request": "POST /message?text=hello HTTP/1.1",
        "response": "HTTP/1.1 200 OK\r\n\r\n",
        "created_on": "2006-01-02T15:04:05Z",
        "elapsed_ms": 123
      }
  ]
}
```

**Comment by rowanseymour** [comment]
If we don't write anything to the database it becomes harder to replicate the current view of channel logs per channel. When we brainstormed on this previously we settled on having the _Failed_ messages view be filterable by channel, which would effectively let users find all logs with errors.

**Comment by rowanseymour** [comment]
Having gotten a bit farther with this I think we also want to change how we link channel logs and msgs. We can give each log a UUID, and that's added to an array of UUIDs on the message.

 * Would mean we don't have to search in S3 to find the logs for a message
 * Allows us to have multiple messages per log (not sure if this happens but seems possible on some channel types) 
 * Would fix https://sentry.io/organizations/nyaruka/issues/2920869812/?project=205713&query=is%3Aunresolved

**Comment by ericnewcomer** [comment]
Tracked here: https://github.com/nyaruka/rapidpro/discussions/4214
