### ISSUE TITLE
Export of tickets

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#1687]
Like what we have for messages or runs but every row is a ticket. We can start simple with these columns...

 * UUID
 * Opened On
 * Closed On
 * Topic
 * Assigned To (email address of user)
 * Contact UUID
 * Contact ID (only include for anon orgs)
 * URN Scheme
 * URN Value (path of the URN, omit for anon orgs)

**Comment by rowanseymour** [comment]
@norkans7 @ericnewcomer it would be nice for the different export types to use consistent column headers so maybe `Contact UUID`, `Contact ID`, `URN Scheme`, `URN Value`, followed by user selected `Field:...` and `Group:...` columns can be consistent across the types. Open to suggestions on clarifying/simplfying those header names.

**Comment by norkans7** [comment]
I think we keep the format `URN:[SCHEME]` and the value be in the column on the row, I think we still want one contact to take one row 

and we still want contacts we be importable and backward compatible for the contacts exports we already sent

**Comment by rowanseymour** [comment]
To be clear I'm not including contact exports here - but contact info on msgs, tickets and flow results exports

**Comment by norkans7** [comment]
Yeah, I thought including `URN:..` as we include the `Field:..` and `Group:...` similarly to the contacts export is more consistent 

However it seems limiting to the URN that was used in the interaction is enough
