### ISSUE TITLE
RapidPro Development Server Installation Issue 

### ISSUE THREAD

**Issue by Mahamadi** [rapidpro/rapidpro#169]
Hello, 
First time here.
I'm facing an issue installing RapidPro Development Server.

$ virtualenv env
$ source env/bin/activate
(env) $ pip install -r pip-freeze.txt

where it shows this error:
compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with
 exit status 1

Command /home/mrouamba_ticanalyse_org/rapidpro/env/bin/python -c
 "import setuptools, tokenize;__file__='/home/mrouamba_ticanalys
e_org/rapidpro/env/build/gnureadline/setup.py';exec(compile(geta
ttr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record /tmp/pip-H2qnME-record/
install-record.txt --single-version-externally-managed --compile
 --install-headers /home/mrouamba_ticanalyse_org/rapidpro/env/in
clude/site/python2.7 failed with error code 1 in /home/mrouamba_
ticanalyse_org/rapidpro/env/build/gnureadline

**Comment by ewheeler** [comment]
@Mahamadi i believe you need to install the python development headers, which are required by some of the dependencies from `pip-freeze.txt`

on debian-based systems that would be `apt-get install python-dev`

more info here: https://docs.python.org/devguide/setup.html#build-dependencies

**Comment by ericnewcomer** [comment]
The folks at praekelt ran into this as well. The gnureadline package
probably isn't needed for your ubuntu install (though it is needed for
OSX). You might try commenting it out for now until we sort out what the
issue is there.
