### ISSUE TITLE
SMS Forms

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#17]
Allow users to define SMS "forms" that contain more than one field in one message, ie things like:

```reg Nicolas Pottier Kigali 25 M```

to mean: register, first name, last name, City, age, gender

This is on the roadmap but adding it here to track.

**Comment by ewheeler** [comment]
addressed in https://github.com/rapidpro/rapidpro/commit/722458b30ba95793ab0c910f50ff9fe96246f551
