### ISSUE TITLE
Facebook channel not working

### ISSUE THREAD

**Issue by dayures** [rapidpro/rapidpro#1700]
Working on RapidPro v 7.4.2

We are trying to use the Facebook Channel, but we are facing some issues:

In order to fill the variable FACEBOOK_WEBHOOK_SECRET in the settings.py, there is a text in the source code that says:

```
4. Generate a Random Secret to use as Facebook Webhook Secret as described
       on https://developers.facebook.com/docs/messenger-platform/webhook#setup
```
But the link doesn't point to a particular section on the page, and there is no reference to "secret" in that page.

Could somebody help in order to know how can we obtain the FACEBOOK_WEBHOOK_SECRET?

Also, where is the latest documentation about adding a facebook channel (including the generation of variables FACEBOOK_APPLICATION_ID, FACEBOOK_APPLICATION_SECRET, FACEBOOK_WEBHOOK_SECRET)?

We have found some old references that are outdated, like https://community.rapidpro.io/blog/adding-facebook-rapidpro-channel-part-1-2/

**Comment by ericnewcomer** [comment]
This question is more appropriate for the dev list.
https://groups.google.com/g/rapidpro-dev
