### ISSUE TITLE
RapidPro TypeError

### ISSUE THREAD

**Issue by honourm** [rapidpro/rapidpro#1708]
[TypeError.txt](https://github.com/rapidpro/rapidpro/files/10334559/TypeError.txt)

Good day

Please see the attached document showing the TypeError  I am getting on RapidPro after running the command below in the virtual environment.
python manage.py runserver.

Your assistance will be greatly appreciated.

Honour

**Comment by ericnewcomer** [comment]
This is not a support channel, please only file well defined bug reports here. Your can dissect these sorts of questions to the rapidpro-dev list linked from the new issue page.
