### ISSUE TITLE
Phone number on contact view should be international

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#172]
Currently on the contact read page we attempt to show locally dial-able numbers. There's two issues with this:

1) The phonenumbers library is not consistently good at producing a formatted locally dial-able number (it fails for NP for example.

2) There's not enough context on this page to know where this contact is. Take for example the case of using a US number to dial various countries in Africa. In this case, a visitor to this page will not know what country that number belongs, and currently there's no way to discover it.

My recommendation is we move the numbers to be internationally formatted. They don't have to be E164, but I think they need to show the country code everywhere for consistency, especially for multi-country campaigns.

**Comment by rowanseymour** [comment]
Sounds good

**Comment by norkans7** [comment]
I second this too

**Comment by ewheeler** [comment]
Agree. I think internationally formatted numbers are probably the safer option. If someone is familiar with the country whose phone number they are looking at, they'll likely know how to format it for local dialing (if not the international format will work locally too). Other viewers not familiar with this country's numbers probably will want the international format.

Nepal doesnt use a national trunk prefix (leading zero when dialing within the country), so the number displayed under the contact name is not a dial-able number

However, looks like this may just be a bug in `phonenumbers.format_number` method. -- the `PhoneNumber` object's `national_number` property is correct.
Doesn't seem to be tracked in the upstream repo: https://github.com/googlei18n/libphonenumber

    >>> x = phonenumbers.parse("+9779841061471", None)
    >>> x
    PhoneNumber(country_code=977, national_number=9841061471, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=None, preferred_domestic_carrier_code=None)

    >>> phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.NATIONAL)
    u'0984-1061471'

    >>> x.national_number
    9841061471L
