### ISSUE TITLE
AFRICA'S TALKING -RapidPro SMS AUTHENTICATION IS FAILING

### ISSUE THREAD

**Issue by SheilaAbby** [rapidpro/rapidpro#1739]
I'm working on configuring Africa's Talking Channel on RapidPro.  
I noticed the API token generated by Africa's Talking is truncated by RapidPro SMS because it expects the token length to be 64 characters. The API Token generated by Africa's Talking is 77 characters long.

This is the reason why authentication is failing when sending SMS. See attached screenshots. 

<img width="796" alt="Screenshot 2024-07-29 at 12 25 39" src="https://github.com/user-attachments/assets/74260570-1f5e-41f4-89d6-d175ca1efa4f">

<img width="812" alt="Screenshot 2024-07-26 at 09 48 32" src="https://github.com/user-attachments/assets/5403ace8-d903-45b1-9392-58231f121cc6">

Any support to remove 64 characters restriction for AT Channnel configs will be highly appreciated.

**Comment by norkans7** [comment]
That issue should be fixed once https://github.com/nyaruka/rapidpro/pull/5421 is merged

**Comment by SheilaAbby** [comment]
Super great!
Thanks a lot! Looking forward to the merge!

**Comment by SheilaAbby** [comment]
@norkans7 Thanks for the effort.
I see the code update was merged to the main branch.
As an application user, when do I expect the update to reflect on the RapidPro application? i.e when will this be deployed ?

**Comment by rowanseymour** [comment]
@SheilaAbby that change is already live at https://app.rapidpro.io but I can see from your screenshots that you are using a very old version of RapidPro. If that's not something you are hosting yourself, you need to talk to whoever is hosting it for you.
