### ISSUE TITLE
Unable to create action

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#174]
I keep getting the response box whenever I try to create an action or click on the + sing in the right bottom corner.
![bug in rp](https://cloud.githubusercontent.com/assets/1177423/7809923/866f35bc-03a6-11e5-98d1-b543c37329e5.png)

**Comment by ericnewcomer** [comment]
We are actively looking into this. This is a problem on Firefox and IE. You
can work around it in the meantime using Chrome.

**Comment by ericnewcomer** [comment]
This has been addressed on nyaruka/rapidpro and is live on rapidpro.io.

**Comment by xkmato** [comment]
Thank you
