### ISSUE TITLE
Data lost when importing contacts

### ISSUE THREAD

**Issue by kaleemcf** [rapidpro/rapidpro#176]
When I import contacts and try to add additional columns (e.g. gender and age), the contact fields are added but data are lost. 

When the contact fields were already defined in RapidPro, I was able to successfully import data in additional columns.

**Comment by ericnewcomer** [comment]
Can you provide a bit more information? Perhaps giving us the steps to reproduce it and the specific thing that has gone missing? You can perhaps link to import files we can reproduce it with.

**Comment by ericnewcomer** [comment]
I don't believe this repros anymore. If you are still seeing this, please reopen this or start a new issue.
