### ISSUE TITLE
django-compressor not setting absolute CSS image paths on uses the S3

### ISSUE THREAD

**Issue by fly2wind** [rapidpro/rapidpro#184]
need upgrade the django-compressor's version to 1.5

this issue like the follow links:
http://stackoverflow.com/questions/15532464/django-compressor-not-setting-absolute-css-image-paths-on-heroku

**Comment by nicpottier** [comment]
Huh, interesting, ya, we don't actually upload our files to S3, but host them locally.

Did updating to 1.5 work for you?

**Comment by fly2wind** [comment]
yes, 1.5 work well for S3.

**Comment by nicpottier** [comment]
Closing.
