### ISSUE TITLE
update advanced expressions documentation

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#186]
[Documentation](http://docs.rapidpro.io/) for "Using Advanced Expressions" is out of date.
Now, expressions begin with ```=(``` now, not just ```=```

So, many of the example expressions in the docs no longer work as written: ```WELCOME =UPPER(contact)!!```
This one, for example, should be ```WELCOME =(UPPER(contact)!!)```

**Comment by ewheeler** [comment]
"Using Advanced Expressions" docs should also explicitly call out that variables in expressions must not be preceded with '@' (e.g., should be ```=(UPPER(contact)!!)``` and not ```=(UPPER(@contact)!!)```

**Comment by nicpottier** [comment]
Both of those are currently correct, we haven't changed expressions yet.

The latter will actually remain correct long term, you won't have multiple @ in an expression. That case will just read @(UPPER(contact))!!

**Comment by ewheeler** [comment]
hmm. ```=(UPPER(@contact)!!)``` doesnt work for me.. ```@contact``` gets evaluated, but not the expression. so the output would be ```=(UPPER(evan)!!)```

![screen shot 2015-07-27 at 4 23 30 pm](https://cloud.githubusercontent.com/assets/15692/8907001/beadb790-347b-11e5-94e2-2379819fda09.png)

**Comment by nicpottier** [comment]
Oh, sorry, read your comment backwards, but yes, you can't have @'s in inner expressions. Will update the docs.

**Comment by nicpottier** [comment]
What docs are you talking about? Our version of using advanced expressions looks right to me.

**Comment by ewheeler** [comment]
doh! sorry you're right. i thought ```=``` didnt work now and had to be ```=(```
wasnt working for me bc of the ```@```
