### ISSUE TITLE
Connecting Rapidpro with Kannel

### ISSUE THREAD

**Issue by ashaban** [rapidpro/rapidpro#189]
I'm setting up Rapidpro to send SMS using a short code provided from the network operator. The connection between Kannel and the network operator is up and i can send sms from Kannel through http. But the problem is when i try to send SMS from Rapidpro,nothing is going to the Kannel.I have the Kannel channel up and running in Rapidpro. Below is the configuration that i have in Kannel.

group = sendsms-user
username = "rapidpro_26"
password = "rapidpro_26"
concatenation = true
max-messages = 10
faked-sender = 15205
forced-smsc = smpp
default-smsc = smpp

group = sms-service
keyword = default
allowed-receiver-prefix = 15205
max-messages = 0
post-url = "http://localhost:9000/api/v1/kannel/receive/5ddce626-b498-4a34-a2fd-78d323af464f/?backend=%i&sender=%p&message=%b&ts=%T&id=%I"
concatenation = true
assume-plain-text = true
accept-x-kannel-headers = true
omit-empty = true
accepted-smsc = smpp

Any help will be appreciated.

**Comment by ericnewcomer** [comment]
Do other channels work on your local rapidpro install? You want to check your configuration to make sure you are not running in development mode (which fakes sending of sms messages). I'm guessing since its on localhost, that might indeed be the case.

**Comment by ericnewcomer** [comment]
You might be better served carrying this forward on the mailing list until we know for sure there is an issue that needs to be addressed.

https://groups.google.com/forum/#!forum/rapidpro-dev
