### ISSUE TITLE
Add email scheme so that we can tie emails to Contacts

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#19]
One use case might be to add contacts to groups then allow sending of emails to that group.

If we do this it seems worthwhile to go whole hog and add an EmailChannel to send/receive emails for a particular SES connection or the like so we can automate interactions over Email.

**Comment by ericnewcomer** [comment]
We have an e-mail urn type.

Leaving this open. What we don't have is:
 - An EmailChannel to interact over email
 - A way to customize an SMTP server for an org

**Comment by nicpottier** [comment]
We have an email URN now.
