### ISSUE TITLE
French translations cause Javascript error in registration form

### ISSUE THREAD

**Issue by Signaldraht** [rapidpro/rapidpro#190]
After switching the interface to French I cannot use the registration form /org/signup/ anymore. The single Quotes in some of the terms ('S'il ...) cause a Javascript error that renders the form unusable.

SyntaxError: missing ) after argument list signup:1074:51

```
  $("#id_name").attr('placeholder','Quel est l'organisme appartient ce compte?');
  $("#id_email").attr('placeholder','name@domain.com');
  $("#id_password").attr('placeholder','S'il vous plaît entrer au moins 8 caractères');
```

Tested in Firefox 40 and Chrome 44. The RapidPro-Code was pulled from Github on July, 23rd 2015.

**Comment by Signaldraht** [comment]
I fixed the issue on my server with this change:

rapidpro/templates/orgs/org_signup.haml line 188-194
      {% trans "What organization is this account for?" as t_whatorga %}
      {% trans "Please enter at least 8 characters" as t_enteremail %}
      $("#id_name").attr('placeholder','{{ t_whatorga|escapejs }}');
      $("#id_password").attr('placeholder','{{ t_enteremail|escapejs }}');

Here is a patch.diff

**Comment by supportticanalyse** [comment]
Hi Signaldraht!
I deployed RapidPro and I also use it in French. Firstly thank you for  for agreeing to share your code to solve the problem "contunue" in French. Currently I found the same mistake with the "Modifier" button of the contacts.
Did you notice?
If so could you solve it?
If so can I have the code for fix this problem?
Thanks in advance!

**Comment by ericnewcomer** [comment]
Perhaps fix this and open a pull request?

**Comment by supportticanalyse** [comment]
Mr Eric Hi,
do you have any idea how to fix this problem?

**Comment by ericnewcomer** [comment]
There's an example in this ticket. Looks like they just added an escapejs filter in these cases.

**Comment by supportticanalyse** [comment]
OK! But can you solve the problem? and forget the code as Signaldraht did?
Thanks in advance!

**Comment by ericnewcomer** [comment]
I'm focused on other issues. Since you have a repro case, it seems best to have you tackle it.

**Comment by supportticanalyse** [comment]
Alright! can you just tell me where I have to go there to do it (the file)?
can you just give me the instructions for i make some research to solve the problem?
thanks!

**Comment by supportticanalyse** [comment]
I seach in /rapidpro/templates/contacts/contact_read.haml but I can not find the responsible line to changes a contact. 
can you help me?

**Comment by ericnewcomer** [comment]
I don't know which one is failing for you. But you can find the corresponding template since they follow the a consistent naming scheme.

**Comment by ericnewcomer** [comment]
I would start looking around here:
https://github.com/rapidpro/rapidpro/blob/master/templates/contacts/contact_read.haml#L555

**Comment by Signaldraht** [comment]
In my installation / version of Rapidpro it is working, so I cannot help you here directly. contact_read.haml is a good candidate for the error location. Look for a javascript error in your browsers console. Usually the problem arrises when a term that is fed into a Javascript contains the ' character. With that error the Javascript cannot initialize on the page and all the buttons won't work. 
After identiying the Javascript error, you can then find the line in the template and use my code as an example.

**Comment by supportticanalyse** [comment]
ok thank you I start immediately to work.

**Comment by nicpottier** [comment]
Closing due to age, believe this is fixed, please reopen if not.
