### ISSUE TITLE
no error message if password is not long enough

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#193]
when a user follows an invitation link to create a new account -- and enters a password that is shorter than 8 characters, there is no message or indication that the sign up was unsuccessful

**Comment by apabbi** [comment]
Hi, I would to contribute to this project. So I will start by fixing this issue as fast as possible. Thank You.

**Comment by nicpottier** [comment]
Sounds, great, looking forward to the pull request!

**Comment by pcardune** [comment]
This was the least invasive fix I could come up with.
