### ISSUE TITLE
Box SENT don't appear 

### ISSUE THREAD

**Issue by wwwnizar** [rapidpro/rapidpro#195]
in Textit platform we have 2 boxes : OUT and SENT,
but in local version of Rapidpro i have only OUT box,
how can i add SENT box on the left menu

**Comment by rowanseymour** [comment]
It used to be that _Outbox_ was all sent messages, but a while back we changed _Outbox_ to be queued outgoing messages, and _Sent_ to be sent outgoing messages. You need to update your local code base and run all migrations.

**Comment by wwwnizar** [comment]
thanks a lot
