### ISSUE TITLE
rules for webhook responses with null json values

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#197]
When using webhook responses in flows, rule evaluation treats 'None' as a string literal (presumably after json.loads converts json's `null` to python's `None`)

This means that if a webhook response includes `myJsonField: null`, then the condition 'is not empty' will match for `@extra.myJsonField`, which is unexpected (I would expect a null value to be considered empty)

So, in order to check for a webhook response value of `null`, one has to use the condition 'has any of these words' = none

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/1695
