### ISSUE TITLE
Hardware requirement for local intall

### ISSUE THREAD

**Issue by wwwnizar** [rapidpro/rapidpro#199]
i'd like to have specification for hardware ( servers numbers and configuration) to install RapidPro locally
please it's important to have that list to obtain found to bye them
i need requirements for project that use 300.000.000 messages text with kannel configuration as channel
i also need how much i need for network configuration ( router, switch and network speed)

**Comment by nicpottier** [comment]
We have some rough guidelines here:
  http://rapidpro.github.io/rapidpro/docs/hosting/

There aren't any installs with 300M messages on them yet, so you may be charting unknown territory. The largest installation we know about has about 120M messages and uses about 450gb of DB space, so you can plan accordingly.
