### ISSUE TITLE
import from textit to local

### ISSUE THREAD

**Issue by wwwnizar** [rapidpro/rapidpro#200]
j'essaie d'importer des flow et compain depuis l'export de textit vers l'import du serveur local, mais ca marche pas, la solution est de remplacer "base_language": "base", dans le fichier d'export .json par 
"base_language": "eng",
ca marche pour les flow mais pour le compaign ca marche pas en plus lors de l'export le fichier .json ne prenne pas l'apostrophe ou le "à" il affiche par exemple : le compte \u00e0 rebours a commenc\u00e9

ce problème n'etait pas présent avant la dernière mise a jour de rapidpro

**Comment by ericnewcomer** [comment]
The version running on TextIt is not fully compatible at the moment with rapidpro/rapidpro as it is running the tip of development that includes a new flow spec version. There's another big change coming there this week. Once things settle down, we'll pull things into rapidpro/rapidpro. If you provide the flow you are trying to import that would help confirm if there isn't something else fishy going on.
