### ISSUE TITLE
buckup rapidpro

### ISSUE THREAD

**Issue by wwwnizar** [rapidpro/rapidpro#201]
i'd like to have some script to backup all rapidpro application (without sync db) and database,
i use ubuntu server 12.04 without graphical interface

thank you!

**Comment by nicpottier** [comment]
Data is stored in two main places:
  - The PostgreSQL database, so use whatever method you'd like to back that up
  - The file backend store, though this is mostly used for saving recordings for IVR flows, so if you aren't using IVR you don't really need to backup those files (on our production boxes this all goes to S3)

All the data stored in Redis will get regenerated if lost.
