### ISSUE TITLE
extra variable not interpolating for particular name

### ISSUE THREAD

**Issue by chrisgeorge** [rapidpro/rapidpro#203]
Hello ... we recently started to see that one of our extra variable's values was not getting interpolated when making it into RapidPro. Currently we trigger a run for a flow for a particular user and pass in a payload. The payload looks like this:

{"phone": ["+123444555666"], "flow": 16995, "extra": {"product": "81029490", "sender": "Sender", "contactName": "John Doe"}}

On the RapidPro side, the action is a send message that looks like this:

Hi @extra.contactName, @extra.sender has sent you @extra.product. Have you received it? Please reply YES or NO.

Both the 'sender' and 'product' names get interpolated fine within the SMS. However, the contactName stays as '@extra.contactName' within the SMS. 

This was working before and we think it might have to do with something related to the recent RapidPro changes in order to improve the expressions (https://community.rapidpro.io/blog/changes-rapidpro-ui-and/).

Any ideas on how to resolve this?

**Comment by rowanseymour** [comment]
Hi Chris. I think the latest code makes an assumption that all keys in the context are lowercase.  Can you try changing `contactName` to `contactname` to confirm?

**Comment by chrisgeorge** [comment]
Sure, let me do that and get back to you ...

**Comment by chrisgeorge** [comment]
Hey Rowan, that was exactly it. So maybe we should start using underscores for our keys from now on? Thanks.

**Comment by rowanseymour** [comment]
@chrisgeorge we'll fix this so that it's backward compatible. Are you self-hosting?

**Comment by chrisgeorge** [comment]
Nope, this was for an account we have on app.rapidpro.io.

**Comment by rowanseymour** [comment]
This should be fixed on app.rapidpro.io now if you haven't already switched to underscores
