### ISSUE TITLE
Ability to choose special channel for sending messages within a flow

### ISSUE THREAD

**Issue by mshafiee** [rapidpro/rapidpro#208]
It's a necessary feature in some applications to have the ability to set a special channel for Sending Messages within a Flow.
It's good to add a combo box with these options: Default channel, Channel A, Channel B, ...

**Comment by nicpottier** [comment]
This is a good suggestion for sure. Ideally it would be implemented so that this would only show up on Organizations that have more than one channel.
This isn't likely to get done by Nyaruka soon, but happy to consider a pull request..

**Comment by ericnewcomer** [comment]
This is now included.
