### ISSUE TITLE
Building the readline extension module -c error at compilation 

### ISSUE THREAD

**Issue by Haythamamin** [rapidpro/rapidpro#212]
I get an error during compilation after (env) $ pip install -r pip-freeze.txt fetch depindancies:

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying readline.py -> build/lib.linux-x86_64-2.7

running egg_info

writing gnureadline.egg-info/PKG-INFO

writing top-level names to gnureadline.egg-info/top_level.txt

writing dependency_links to gnureadline.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'gnureadline.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'gnureadline.egg-info/SOURCES.txt'

running build_ext

building 'gnureadline' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/Modules

creating build/temp.linux-x86_64-2.7/Modules/2.x

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python2.7 -c Modules/2.x/readline.c -o build/temp.linux-x86_64-2.7/Modules/2.x/readline.o

In file included from Modules/2.x/readline.c:31:0:

./readline/readline.h:385:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 extern int rl_message ();

 ^

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/gnureadline.so

Thank you for your help.

**Comment by xkmato** [comment]
This is probably not the best fix for this but I would suggest you remove `gnureadline` from your `pip-freeze.txt` file. It is an optional requirement that will be installed by ipython anyway. Then run `pip install -r pip-freeze.txt` again

**Comment by Haythamamin** [comment]
it worked, thanks..
