### ISSUE TITLE
recompile django.po or django.mo

### ISSUE THREAD

**Issue by ticanalse** [rapidpro/rapidpro#213]
hi!
I contribute to the translation into transifex but i would like to know what command run to update the translation. I tried "python manage.py makemessages -l fr" but it does not.
can you help me?
thank you in advance!

**Comment by rowanseymour** [comment]
Please use the [rapidpro mailing list](https://groups.google.com/forum/#!forum/rapidpro-dev) or [rapidpro slack channel](https://rapidprodev.slack.com) for these kinds of questions.

**Comment by ticanalse** [comment]
ok thanks!
