### ISSUE TITLE
how to point the server to internal IP instead of 127.0.0.1?

### ISSUE THREAD

**Issue by Haythamamin** [rapidpro/rapidpro#214]
I have deployed Rapidpro locally "finally", now trying to connect an android phone using the app as specified on the rapidpro website.  when I point the app to the server machine IP it never connect and give me the nessesary code. I have noticed that the website work locally only on 127.0.0.1:8000 but I think for it to sync with the phone it need to point to the internal IP eg. 192.168.x.xx. how can I do that?

**Comment by ericnewcomer** [comment]
I see you also posted this to the discussion group which is the appropriate place.

**Comment by Haythamamin** [comment]
I did not, can you refer me to the disuccion group you are reffering to?

**Comment by ericnewcomer** [comment]
Ya, sorry, I realized that was a mistake, so I edited my comment above.

**Comment by Haythamamin** [comment]
no worries, thank you for you help.
