### ISSUE TITLE
MO response

### ISSUE THREAD

**Issue by ticanalse** [rapidpro/rapidpro#215]
Hello, I have a problem with the connection between RapidPro and my gateway (jasmin sms gateway). Jasmin requires that during an MO, RapidPro response "ACK/Jsamin" when it receives the message from MO. how to make RapidPro answer with "ACK/jasmin" when it receives an MO message?
 thank you in advance!

**Comment by ericnewcomer** [comment]
I see you found the rapidpro dev mailing list which is the appropriate place for this.
