### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by ticanalse** [rapidpro/rapidpro#216]
Hello,
I tried to customize error pages like textit. I have not been able to.
I would like to know which files (views.py, urls.py) do I edit  to customize these pages my RapidPro instance.
I put the files '404.html' and '500.html' in the "RapidPro / templates', but it's always the same.
Thanks in advance!

**Comment by norkans7** [comment]
make sure DEBUG setting is False for those template to be used

**Comment by ticanalse** [comment]
ok, could you tell me what setting file would i edit?

**Comment by norkans7** [comment]
The file pointed by settings.py
This is recommended by Django docs

**Comment by ticanalse** [comment]
yes i know but if i edit it i have this error: Bad Request (400) .
when i run my domaine_name in the browser.
