### ISSUE TITLE
Dynamic attributes on contacts (e.g., this year - birth year = age)

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#22]
Some interesting (and difficult) implications on this combined with dynamic groups.

IE:

Say you do the above to always keep age up to date, then also have a group that defines a group of contacts with an age in a particular age, then when do you reevaluate these equations.

A couple other approaches / arguments:
 - make Age a first class citizen in RapidPro, which might simplify all this
 - Use a campaign to calculate an age variable once a year for all contacts (or even per contact a year later)

**Comment by ewheeler** [comment]
The described use case for this issue is possible to accomplish using advanced expressions.
For example, a flow can ask for a contact's age and then calculate & save the estimated birth year:
```=(YEAR(NOW()) - flow.age)```

Then, the birth year can be used to calculate age when necessary

**Comment by nicpottier** [comment]
I don't see us adding this anytime soon, would require recalculating contact fields on a fairly constant basis which just doesn't work with the scale we have to operate on. (we need these always up to date because hey, you might create a group based on this value)
