### ISSUE TITLE
'Send an SMS to somebody else' hijacks @contact variable

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#245]
When you choose the option of 'Send an SMS to somebody else' - The @contact variable changes from the person currently participating in the flow to the 'somebody else'; Is this the intended behavior?

**Comment by nicpottier** [comment]
Yes, ```@contact``` always refers to the recipient of the message. If you want to reference the flow contact, you can always use ```@flow.contact```

**Comment by xkmato** [comment]
@flow.contact does not compile to anything 
![flow](https://cloud.githubusercontent.com/assets/1177423/14348997/ab1a3274-fcc8-11e5-9f86-b3e385bfd6a0.png)

**Comment by ycleptkellan** [comment]
@xkmato when using a 'Send an SMS to Somebody Else' action, you can use @step.contact to reference the active contact.

**Comment by nicpottier** [comment]
Yep, sorry, my bad on that.
