### ISSUE TITLE
Facebook Page access token size

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#252]
Rapidpro validates the facebook page access token and always expects a string of length 190. This does not seem to be accurate since, I just got an access token of a length less that that. 
![pageaccesstoken](https://cloud.githubusercontent.com/assets/1177423/14982852/221ce294-1142-11e6-92ff-310c21c13508.png)

**Comment by nicpottier** [comment]
This is fixed on our branch, just haven't pushed upstream yet.
