### ISSUE TITLE
Coding conventions is a 404 in the contribute page

### ISSUE THREAD

**Issue by javaguirre** [rapidpro/rapidpro#253]
Hi!

I wanted to know the coding conventions, but It's a 404 in the [contribute](https://rapidpro.github.io/rapidpro/contribute/) page, is It moved?

Thank you!

**Comment by norkans7** [comment]
Check https://rapidpro.github.io/rapidpro/docs/coding-conventions/

**Comment by javaguirre** [comment]
Thanks!

**Comment by ericnewcomer** [comment]
Fixed
