### ISSUE TITLE
Broken reports when removing rulesets

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#262]
There is no way to delete a report nor is there a way to remove a chart that references a missing ruleset. The fix should allow both of these.

Repro:
1) Create a flow with a ruleset
2) Gather some results through that ruleset
3) Create a report based on that ruleset (save)
4) Delete the ruleset in the flow editor
5) View the report

**Comment by ericnewcomer** [comment]
Related to https://github.com/rapidpro/rapidpro/issues/262

**Comment by ericnewcomer** [comment]
Related to https://github.com/rapidpro/rapidpro/issues/44

**Comment by nicpottier** [comment]
Reports aren't a thing anymore, closing.
