### ISSUE TITLE
TelegamBot Issues

### ISSUE THREAD

**Issue by tymiles003** [rapidpro/rapidpro#264]
Team,
I have setup a Telegam bot api key to create a webhook from rapidpro. When I attempt to add the channel via rapidpro with the generated key for telegram I get this error. Please assist, any help would be greatly appreciated.

TelegramError at /channels/channel/claim_telegram/
Bad webhook: getaddrinfo: Name or service not known
Request Method:	POST
Request URL:	http://192.168.1.207:3443/channels/channel/claim_telegram/
Django Version:	1.8.5
Exception Type:	TelegramError
Exception Value:	
Bad webhook: getaddrinfo: Name or service not known
Exception Location:	/root/.virtualenvs/rapidpro/local/lib/python2.7/site-packages/telegram/utils/request.py in decorator, line 79
Python Executable:	/root/.virtualenvs/rapidpro/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/rapidpro',
 '/root/.virtualenvs/rapidpro/src/django-modeltranslation-master',
 '/root/.virtualenvs/rapidpro/src/django-ttag',
 '/root/.virtualenvs/rapidpro/src/django-celery-transactions-master',
 '/root/.virtualenvs/rapidpro/src/librato-bg',
 '/root/.virtualenvs/rapidpro/src/dash-master',
 '/root/.virtualenvs/rapidpro/src/rapidpro-python-master',
 '/root/.virtualenvs/rapidpro/src/smartmin',
 '/root/.virtualenvs/rapidpro/lib/python2.7',
 '/root/.virtualenvs/rapidpro/lib/python2.7/plat-x86_64-linux-gnu',
 '/root/.virtualenvs/rapidpro/lib/python2.7/lib-tk',
 '/root/.virtualenvs/rapidpro/lib/python2.7/lib-old',
 '/root/.virtualenvs/rapidpro/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/root/.virtualenvs/rapidpro/local/lib/python2.7/site-packages',
 '/opt/rapidpro']
Server time:	Fri, 1 Jul 2016 03:06:46 -0400

**Comment by ericnewcomer** [comment]
This looks like you are trying to register with telegram and your server is not publicly addressable. You need to do this using a production server or use a development tool like ngrok.

**Comment by tymiles003** [comment]
Thanks
