### ISSUE TITLE
FilterError accessing the webpage at port 8000

### ISSUE THREAD

**Issue by tipen** [rapidpro/rapidpro#265]
Hi, I have done all the installation steps without any issue and started the server.

When I tried accessing the webpage, I got this FilterError page.

![screen shot 2016-07-01 at 3 59 59 pm](https://cloud.githubusercontent.com/assets/19336977/16515502/f0ee398e-3fa4-11e6-91bb-b325aedb2e86.png)

Could anyone kindly help advise what the issue here is?

Thanks!

**Comment by ericnewcomer** [comment]
this is a configuration issue. It looks like you are missing node in your environment. You will need that, coffee and lessc to compress your static files.

**Comment by tipen** [comment]
Hi @ericnewcomer, is there any guide that I could refer to in order for me to do what you mentioned? I was running the server in the virtual env as described in the installation guide, I have also installed coffee and lessc as mentioned here (http://rapidpro.github.io/rapidpro/docs/development/).

**Comment by ericnewcomer** [comment]
Yes, that is the guide for setting up a development server. For production hosting, there isn't a RapidPro specific guide. That falls on the documentation for the individual components in the stack (postgres, redis, django, celery, etc) for how to best accomplish that to meet your hosting requirements.

**Comment by tipen** [comment]
Hi @ericnewcomer, yes I was trying to setup a development server, could you elaborate more on the "compress your static files"? Thanks!

**Comment by supportticanalyse** [comment]
Hi @tipen could you say me how do you do to install correctly coffee? 
thanks!

**Comment by tipen** [comment]
Hi @supportticanalyse,

Do the following to install and then update the nodejs before installing coffee,

curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
apt-get install -y nodejs

npm install -g coffee-script
npm install --save coffee-script

Hope that helps.

Thanks!

**Comment by supportticanalyse** [comment]
Hi @tipen,
Thanks for you reply.

Best regards!
