### ISSUE TITLE
Relayer sync taking too long

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#267]
If an android channel has difficulty sending it can start to slow down the syncing process to the point of causing timeouts which can cause cascading badness. Need to investigate how to speed syncs up or handle some things async.

**Comment by nicpottier** [comment]
Relayer currently tries to deal with this by only sending so many events.. maybe we need to just turn that down further?

**Comment by ericnewcomer** [comment]
Believe this has been addressed with recent pending message changes.
