### ISSUE TITLE
Error updating welcome message on the Facebook Messenger configuration

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#269]
Hey guys. The action to set a welcome message Facebook Messenger channel is presenting the following error:

`We encountered an error updating your welcome message: {"error":{"message":"(#100) Invalid keys \"message\" were found in param \"call_to_actions[0]\".","type":"OAuthException","code":100,"fbtrace_id":"BY2zpPqjIEV"}}`

This error is caused, possibly because Facebook Messenger updated its API welcome messages by pressing the button "Get Started" (https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button).

**Comment by nicpottier** [comment]
This was fixed with:
  https://github.com/nyaruka/rapidpro/pull/712

Once that bakes a bit we'll merge with master.

**Comment by teehamaral** [comment]
Ok @nicpottier, thanks.
