### ISSUE TITLE
Error on Welcoming message on facebook configuration 

### ISSUE THREAD

**Issue by Mekdim** [rapidpro/rapidpro#271]
We encountered an error updating your welcome message: {"error":{"message":"(#100) Invalid keys \"message\" were found in param \"call_to_actions[0]\".","type":"OAuthException","code":100,"fbtrace_id":"EbKodV2oUXv"}}. 
It creates this error when ever, a new welcoming message has to be configured when hooking it up with facebook.

**Comment by ericnewcomer** [comment]
Believe this is fixed in https://github.com/nyaruka/rapidpro/pull/712
