### ISSUE TITLE
[API] /api/v1/messages.json with Uganda Ureport key returns 502

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#280]
`/api/v1/messages.json` endpoint with Uganda Ureport key returns 502.

**Comment by rowanseymour** [comment]
API v1 was created in the days when our databases were much smaller and all sorts of arbitrary queries were possible. [API v2](https://app.rapidpro.io/api/v2) is replacing that and provides a more restricted set of ways to query particular objects. That allows as to ensure that all queries are backed by appropriate database indexes, and don't timeout like this.

You can start using API v2 today and it's supported by the latest client versions, but if you do please talk to us about how you're using it, as it is not finalised and endpoints may change slightly in the future. UReport and CasePro are already using API v2.
