### ISSUE TITLE
MP3 audio files

### ISSUE THREAD

**Issue by jameshappell** [rapidpro/rapidpro#284]
Is it possible to support mp3 files as well as wav files in IVR audio? Uploading many files over slow connections is particularly problematic. (Also there seems to be a 1mb limit on the file size, which does not allow for a very long wav file).

**Comment by nicpottier** [comment]
Hi James, the main reason we don't have this is that for most people creating mp3s is more complicated than wav's and it greatly complicates being able to preview messages in the UI.

Where are you running into the size limit exactly?

**Comment by jameshappell** [comment]
Hi Nic,

Thanks for getting back to me so quickly.

It’s a question of both bandwidth and file size.

When we officially move to RapidPro/Textit we are going to need to upload over 140 audio files for our project (a maternal and child health project). We currently have a 3mbps connection here in Cambodia, shared by ~30 people. That upload would take a lot of time.

But yes, our messages are anywhere from around 500kb to 3mb. And these aren’t particularly long audio files either. And as I understand it, there it is a 1mb limit?

Regards,

James Happell
Technology for Development Manager
People in Need – Cambodia

[logo_en2]<http://www.peopleinneed.cz/>

[alliance2015]<http://www.alliance2015.org/>

mob.: +855 (0) 10 567 487
email: james.happell@peopleinneed.cz

People in Need, # 33 (4th floor), St 71, S/K Tonle Bassac, Khan Chamkar Morn, Phnom Penh, Cambodia

[fcb]<https://www.facebook.com/pages/People-in-Need-Official/244192865606024?fref=ts> Like us on Facebook <https://www.facebook.com/pages/People-in-Need-Official/244192865606024?fref=ts>  [twitter] <https://twitter.com/people_in_need>  Follow us on Twitter<https://twitter.com/people_in_need> [youtube] <http://www.youtube.com/user/peopleinneed>  Watch our videos<http://www.youtube.com/user/peopleinneed> [male_logo] <http://clovekvtisni.cz/klub>  Support us!<http://www.clovekvtisni.cz/en/want-to-help>

**Comment by nicpottier** [comment]
Ya, as I said due to browser compatibilities we aren't likely to change to support MP3 uploads. I am curious about the limits you have around file size limit though. Can you maybe attach one of your larger files?

What service as you working against? (TextIt, RapidPro or another one?)

**Comment by jameshappell** [comment]
Please see attached.

Working with TextIt currently.

Regards,

James Happell

**Comment by nicpottier** [comment]
Hi James, file didn't come through, can you send it to me directly at nicp@nyaruka.com? Thanks.

**Comment by nicpottier** [comment]
Hiya James, thanks for forwarding on the file.

I just tried uploading it to TextIt and it seemed to work, we may just recommend files less than 1 MB but that one certainly didn't have a problem.

**Comment by nicpottier** [comment]
The only thing I could think that might be happening is that requests can only be open for 60 seconds or so, so if you connection is super super slow it may be taking longer than that. Can you try that file again and see if it works for you and if not time how long it takes?

**Comment by nicpottier** [comment]
Followed up with James and thinks seem to look good now, closing.
