### ISSUE TITLE
Ability to process GPS points from messenger

### ISSUE THREAD

**Issue by mberg** [rapidpro/rapidpro#289]
If you use telegram and post your location via GPS it shows up in RapidPro.  If you try with messenger you don't receive the message.  It would be great if messages from messenger were handled in a similar way.

If you can point us towards the relevant code, I can potentially have someone from our team take a look.

**Comment by nicpottier** [comment]
Huh, interesting. Should be an easy change here:
  https://github.com/rapidpro/rapidpro/blob/master/temba/channels/handlers.py#L1634

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/courier/pull/305
