### ISSUE TITLE
Nested Groups

### ISSUE THREAD

**Issue by jameshappell** [rapidpro/rapidpro#290]
Hi,

One of our projects requires a large number of contact groups. Is it possible to build in the capacity for nested groups, so that we can reduce the total number required and to make administration quicker and more simple?

**Comment by nicpottier** [comment]
Ya, we've talked about this at various times. There are a lot of complications that come from any amount of nesting.. for example, are higher level groups the union of the groups below them? Can you assign to groups that have child groups? etc..

For labels, we used to have nesting and it got confusing for users, so we added folders as a way of organizing what is essentially a flat structure.  Would folders of groups be useful to you? How exactly would you use nested groups?

**Comment by jameshappell** [comment]
Hi,

Yes I can understand that it would create some significant questions about configuration.

To give you an idea of how we would use them. In Cambodia, there are Provinces, Districts and Communes, each of which is a subset of the other. If you were a member of a commune for example, you would atomically be a member of a particular district and province. So instead of having to add contacts to three groups, you would simply add them to the ‘Commune’ group and then add the commune group into the district group and then the district group into the province group. I’m sure similar governmental structures exist worldwide.

I think as a starting point, folders could certainly help with organising groups. At the moment, it is just one long list of groups.

Regards,

James Happell

**Comment by nicpottier** [comment]
Ya, so in your case I would say we'd be more inclined to add first-level support for grouping of contacts by the administrative boundary they are part of rather than doing nesting of groups. That would more precisely fit your use case and avoids all the confusion as to what the semantics are around "nesting" of groups.
