### ISSUE TITLE
Flow ordering in the UI is altered by flow migrations/exports

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#305]
On the flow list page, flows are ordered by `-modified_on`. If there is a new flow migration and a user exports several flows, the flow ordering becomes the order in which flows were migrated, which is confusing to users.

**Comment by ewheeler** [comment]
can confirm that i am confused.

**Comment by ericnewcomer** [comment]
Additionally, we probably shouldn't sort by something that is not shown in the list.
