### ISSUE TITLE
MMS Support

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#31]
Sending and receiving of images, sounds and videos.

Twilio has good support of this, and it seems like we should be able to do it over Android, but I'm not sure how integration works with carriers in developing markets, so this is low priority.

**Comment by gabrielgrant** [comment]
Has there been any movement on this? I'm in the process of implementing this manually with a webhook, but would obviously prefer to be doing it directly through the interface.

In terms of what that interface would look like, I'm thinking the two options are either to add a media field to the "Send Message" action, or add a new "Send Multimedia Message" action. Not sure if the distinction is important enough to be worth complicating things?

In terms of back-end implementation, certainly the Twilio side seems like it should be very straightforward (just adding 1-10 `MediaUrl` parameters onto the message post). Did you have a chance to look into the feasibility with the Android app?

**Comment by ericnewcomer** [comment]
There is multimedia support now for messages. Inbound MMS messages from Twilio (or for exmaple, media messages from Telegram) now show the media in the contact history. 

Leaving this open. What we don't have is:
 * The ability to author outbound MMS messages as a flow action
 * Receiving MMS messages via the android channel

**Comment by gabrielgrant** [comment]
@ericnewcomer is there some way to author outbound MMS messages that isn't a flow action?

**Comment by ericnewcomer** [comment]
As in authoring arbitrary MMS messages? Nope, there's no outbound MMS support of any kind as of yet.

**Comment by gabrielgrant** [comment]
Ok, cool, that's what I thought, but the way it you'd worded it sounded like there might be some other way to send MMS. Thanks for clarifying!

**Comment by norkans7** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/1165
