### ISSUE TITLE
Add UI improvements on Facebook Messenger channel

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#311]
Hey guys. Improve the user experience on Facebook channel could leave it a little more interesting, for example, the response options could come to the user to choose: https://developers.facebook.com/docs/messenger-platform/product-overview/conversation

Someone is already developing something related?

**Comment by ericnewcomer** [comment]
Yup, there's lots of potential for a richer integration here. It might imply some significant changes needed on the flow editor side. Happy to explore this further here. Feel free to share your ideas.

**Comment by citizenrich** [comment]
Hmm. Lots of potential here but what looks interesting are quick replies.
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

Seems to me that this is very similar to Telegram's custom keyboards though they have two types (but see the example below on the left).
https://core.telegram.org/bots#keyboards

I'd think that quick replies of this sort in either Telegram or Messenger can be done from a user perspective of calling them out with @, like a Send Message of the form "What's your favorite color? Please reply with @QuickReply(Red) or @QuickReply(Blue)." Then RapidPro parses these out. In the body of the Send Message, the @QuickReply() is stripped out. And then displayed as a quick reply depending on channel type.

Just my $.02

**Comment by ericnewcomer** [comment]
Why not send the category names from rulesets as buttons or quick replies?
That's closer to what we were thinking.

**Comment by citizenrich** [comment]
Yah, sounds good.

**Comment by teehamaral** [comment]
Exactly what I implemented this to test, it worked. But this way the rules should always also contain the category, it would not be a limitation?

**Comment by ericnewcomer** [comment]
Ya, rules should always contain category names. There's definitely some user awareness required so that they know those category names would be presented to the user, so that certainly requires some thinking on the UX (especially since the editor doesn't know what channel it will be deployed over). Also, the always true rule probably would be omitted in this case.

**Comment by teehamaral** [comment]
I developed some modifications to the Facebook Messaging channel and put here <https://github.com/udomobi/rapidpro/tree/feature/ui-improvements-fb-channel>. Do you could evaluate and give us a return about we can improve for we can send a PR?

**Comment by nicpottier** [comment]
Here's the PR:
  https://github.com/rapidpro/rapidpro/pull/321

**Comment by nicpottier** [comment]
Quick replies and such are supported now.
