### ISSUE TITLE
Add UI improvements on Telegram channel

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#312]
As the Facebook channel, the Telegram channel could also have the same user experience improvements, such as the response options could come to the user to choose: https://core.telegram.org/bots#keyboards

This is already being implemented?

**Comment by ericnewcomer** [comment]
It's not actively being developed, but it's definitely something that is being discussed. Happy to continue that discussion here.

**Comment by nicpottier** [comment]
Telegram now supports custom keyboards.
