### ISSUE TITLE
How to save values to a different contact than the current frow contact

### ISSUE THREAD

**Issue by Mukopaje** [rapidpro/rapidpro#316]
hi, I would like to know how i could save contacts and there respective results as a new contact, or simply update an existing contact with a unique field value equal to one of the results.
(eg. update contacts WHERE full Names = @extra.name with values age=@extra.age, votes=@extra.votes). How can i archieve this? thanks. (otherwise can i loop through group contacts with an equivalent of foreach function?)

**Comment by nicpottier** [comment]
Take a look at the start another user in a flow action.. you'll have the variables from the parent flow passed in as @parent and can do whatever you like with those in the child flow, including updating the contact.
