### ISSUE TITLE
Map @channel to @contact.channel

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#318]
...and surface it as a default field on the Contact Read page and 'Split by Contact Field' RuleSets. Would allow users to set channel preference manually as well as evaluate it within flows. Would also help audit accounts with multiple channels of the same type who aren't already mapping channel preference with custom fields.

**Comment by nicpottier** [comment]
It isn't quite so simple. The channel used is dependent on the URN type.. so there may be multiple preferred channels for a contact.
