### ISSUE TITLE
Surface failed broadcast messages on contact read page

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#319]
Failed messages resulting from broadcasts aren't currently visible from the contact read page.

**Comment by nicpottier** [comment]
Can't you click on the red message icon?

**Comment by ycleptkellan** [comment]
It some cases, when a broadcast is sent, it appears the failed message is
only visible if the user navigates to the failed messages folder. In this
case, the flow was triggered by a schedule trigger and is displayed in the
contact read page as a broadcast, though the message actually failed:

[image: 0.png]

**Comment by nicpottier** [comment]
Ah, ya, ok, broadcasts are indeed treated differently and agree we should link to think as well.
