### ISSUE TITLE
Viber Support

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#326]
Add support for Viber channels

**Comment by supportticanalyse** [comment]
Hi Mr Pottier! The Viber channel is it available now in latest repository of Rapidpro? 
Thanks

**Comment by nicpottier** [comment]
It is on our branch yes.

**Comment by supportticanalyse** [comment]
Ok thanks! can I have the link to your branch? because I just deploy RapidPro with this link https://github.com/rapidpro/rapidpro
but Viber is not in the list of Channels.

**Comment by nicpottier** [comment]
https://github.com/nyaruka/rapidpro

Use at your own risk.

**Comment by supportticanalyse** [comment]
ok Thanks!
