### ISSUE TITLE
FilterError at /

### ISSUE THREAD

**Issue by HolySamosa** [rapidpro/rapidpro#330]
I'm attempting to set up a RapidPro instance and am receiving a HTTP 500 error:

FilterError at /
[31mFileError: '../../style.less' wasn't found. Tried - /home/temba/rapidpro/static/brands/style.less,/home/temba/rapidpro/static/brands/style.less,/home/temba/rapidpro/style.less,../../style.less[39m[31m in [39m/home/temba/rapidpro/static/brands/rapidpro/less/style.less[90m on line 1, column 1:[39m
1 [7m[31m[1m@[22mimport "../../style.less";[39m[27m
[90m2 @import "../../../less/variables.less";[39m[0m[0m

![image](https://cloud.githubusercontent.com/assets/1156546/17870828/10218b84-6887-11e6-9d79-5f1e4921890a.png)

I've seen this similar issue:
https://github.com/rapidpro/rapidpro/issues/265

My error is a bit different, but I have installed lessc and coffee-script globally via npm and can execute both from the command line.

Any suggestions?  Thanks!

**Comment by ericnewcomer** [comment]
This actually looks like one of your less files is missing. What happens if
you collect your static files and run?

Best,

Eric

**Comment by supportticanalyse** [comment]
Hi @ericnewcomer! when i collect static files and run i have the same error.

**Comment by migscabral** [comment]
I'm also experiencing the same issue. I was comparing the files vs previous commits and it seems that `static/brands/style.less` was deleted.

It seems it was deleted at this commit: a7534b594523145f7012797ec226b51b8dd53cc9

**Comment by xkmato** [comment]
I am also getting the same error. Looks like `brands/style.less` does not exist any more

**Comment by nicpottier** [comment]
We'll have a fix merged for this today, sorry about that.

**Comment by ericnewcomer** [comment]
This should be fixed in the latest nyaruka upmerge
