### ISSUE TITLE
Rename Contact Field keys when changing Label

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#333]
Currently contact field keys remain the same forever more after you first create the contact, even if you change the contact label. This is nice in that flows that already exist and dynamic groups remain valid, but a bit ugly because they have stale keys which may be drastically different from the current label.

Ideal implementation might be to fire off a task that finds all references to the old key and replaces them with the new one across flows and dynamic groups.

**Comment by nicpottier** [comment]
We really need a better UI to manage contact fields that allows us to know the intent of the user (are they really renaming a field or are they deleting and adding a field?). We now know dependencies so should be able to rewrite flows which are using the field now as well.

**Comment by nicpottier** [comment]
We now have a UI that would allow us to be more explicit about this. Should reconsider what we want to do here. Main problem is references in flows. Perhaps having a way of renaming references in flows is the right way to deal with this?

**Comment by rowanseymour** [comment]
We could rename all the references in flows currently in the db.. but where this gets complicated.. is does that include older revisions? And what about re-importing of exported flows? 

Should fields be referenced by UUID in flows?

**Comment by nicpottier** [comment]
Well biggest problem is templates, not direct references that include UUID.

I suppose one idea would be that there is some kind of mapping that takes place from a flow def that contains dependencies and those are used to remap things. IE, if we store dependencies in the flow def somewhere, then when loading it we could say uuid5 used to be `age` but not it is `born` so we should remap all templates using `@fields.age` to `@fields.born`.

**Comment by rowanseymour** [comment]
FYI currently flows don't know about field UUIDs...

```json
{
  "uuid": "8eebd020-1af5-431c-b943-aa670fc74da9",
  "type": "set_contact_field",
  "field": {"key": "gender", "name": "Gender"},
  "value": "Female"
}
```

But that idea about a mapping sounds familiar. I think we talked before about referencing fields by UUID/Name in actions like above, and then having a mapping inside the flow definition that determines how each field will be referenced in expressions.
