### ISSUE TITLE
Removing or updating audio files in Call Flow

### ISSUE THREAD

**Issue by jameshappell** [rapidpro/rapidpro#340]
Once you have added an audio file to a message in the Phone Call call flow, it can't be removed without removing the step completely. Also, updating via drag-n-drop is not super clear to user.

**Comment by ericnewcomer** [comment]
You can just drag a file on top of that step in the flow to update the message. I'll update this to account for the confusion and keep it open.

**Comment by jameshappell** [comment]
Ah! Perfect! Thank you. From what I could see, it wasn't in the RapidPro Documentation online? Or I may have missed it.
