### ISSUE TITLE
Chikka channel triggers reply flow while msg is not yet fully written to database, causes bad request

### ISSUE THREAD

**Issue by migscabral** [rapidpro/rapidpro#341]
I'm setting up Rapidpro to use Chikka Channel, however I keep on getting `Bad Request` response from Chikka API:

`{"status": 400, "message": "BAD REQUEST", "description": "Invalid/Used Request ID"}`

Upon checking all replies sent to Chikka from Rapidpro has no `request_id`, which is a required field when sending replies to Chikka API. Here's a sample request from Rapidpro to Chikka API that causes errors:

```
POST https://post.chikka.com/smsapi/request

{u'request_cost': u'FREE', u'message_type': u'REPLY', u'request_id': None, u'message_id': 27, u'client_id': u'dfc39efebaf12b00b05c446a6b73df26b22902b198dc18ed82ff91f2b869fdd9', u'mobile_number': u'639178680631', u'secret_key': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'shortcode': u'29290130', u'message': u'PONG.'}
```

From my tests, `request_id` is always set to none; `request_id` is retrieved from the `external_id` field from `msgs_msg` table. Digging further I noticed that the reply is sent even before the  `external_id` field gets written to the database:

https://github.com/rapidpro/rapidpro/blob/eaa873c2063198c6e60724dcbfdcaa4895f535bb/temba/channels/handlers.py#L1484-L1487

The msg is saved into the database at line 1484 and then the `external_id` gets written at line 1487. However somewhere inside `Msg.create_incoming(...)` the reply from the flow already gets sent to the Chikka API while the `external_id` is still empty, thus causing the `Bad Request` response. 

Here's the pdb trace:

```
Pdb) > /srv/src/temba/channels/handlers.py(1509)post()
-> sms = Msg.create_incoming(channel, urn, request.REQUEST['message'], date=gmt_date) #Msg created at this point but no external ID yet
(Pdb) print sms.external_id
None
(Pdb) continue
(Pdb) M[000000040] Processing - Ping #Reply from flow is sent unexpectedly, external_id is not yet populated, resulting to bad request
[41] ERROR - POST https://post.chikka.com/smsapi/request "{u'request_cost': u'FREE', u'message_type': u'REPLY', u'request_id': None, u'message_id': 41, u'client_id': u'dfc39efebaf12b00b05c446a6b73df26b22902b198dc18ed82ff91f2b869fdd9', u'mobile_number': u'639178680631', u'secret_key': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', u'shortcode': u'29290130', u'message': u'PONG.'}" 400 "{"status": 400, "message": "BAD REQUEST", "description": "Missing Required Field/s: request_id"}, response_to: 40, None, None"
Traceback (most recent call last):
  File "/srv/src/temba/channels/models.py", line 2557, in send_message
    send_funcs[channel_type](channel, msg, part)
  File "/srv/src/temba/channels/models.py", line 1441, in send_chikka_message
    response_status=response.status_code)
SendException: Got non-200 response [400] from API
[0.43] triggers for 40
M[000000040] 0000.437 s - Ping
> /srv/src/temba/channels/handlers.py(1514)post()
-> Msg.all_messages.filter(pk=sms.id).update(external_id=request.REQUEST['request_id']) #external_id will only be populated here after
```

Digging deeper,  there are consecutive calls to `Msg.create_incoming(...)`,

https://github.com/rapidpro/rapidpro/blob/eaa873c2063198c6e60724dcbfdcaa4895f535bb/temba/channels/handlers.py#L1484

,`WebHookEvent.trigger_sms_event(SMS_RECEIVED, msg, date)`, 

https://github.com/rapidpro/rapidpro/blob/eaa873c2063198c6e60724dcbfdcaa4895f535bb/temba/msgs/models.py#L1243

, and `trigger_sms_event(SMS_RECEIVED, msg, date)`. However, I can't find in them any piece of code that would trigger the flow to send the reply message.

I just need the `external_id` populated before the reply flow is sent, however I can't find when the reply flow is triggered. Am I on the right track or am I missing something?

**Comment by nicpottier** [comment]
Hrmm, Chikka is a weird one in that it is the only one of our channels that likes having a reply id sometime. It is definitely possible this is just wrong, but my first guess would be that you are running with ALWAYS_EAGER set to True, ie, you aren't using Celery to run tasks in the background.

We do some magic to make sure tasks don't fire off until after the transaction is committed, which takes care of race conditions like this, but I'm guessing if you are running completely synchronously that's what is causing this.

**Comment by nicpottier** [comment]
Oh, and though things will likely break for you in various other ways if you run RapidPro synchronously in production we would accept a PR that added an external_id parameter to `create_incoming` to prevent this race in that case, just because it is kinda ugly.

**Comment by ericnewcomer** [comment]
Was in contact with Chikka this week and they recommended not using the reply field due to issues on their end regarding message rejection (one of which being that they purge reply ids causing erroneous message rejection for messages that include a since-purged id).

We since disabled the reply flag on our fork, but will update here as that situation progresses.

**Comment by migscabral** [comment]
We've been using Chikka for quite sometime and we always encounter challenges with their API. Here are some items we always consider when using Chikka:

1. There are two types of outgoing messages: `REPLY` and `SEND`, defined using the `message_type` request parameter. `REPLY` type outgoing messages, always requires `request_id`  (reply id), if `request_id` is not present your request will be rejected by the API. 
2. `REPLY` is used is replying to a previous incoming message. Also `request_id` is only usable once, which is very limiting. You can't send multiple replies to a single SMS.
3. `SEND` is used when you want to send an SMS to the subs (ala SMS broadcast). This does not require a 'request_id' (reply id).
4. Once the API receives an incoming SMS from the subs, it REQUIRES your system to send an outgoing  'REPLY' SMS. The subscriber can send up to 3 incoming SMS, without your system replying, but after the third time, the subscriber's mobile number will be blocked by the API. The mobile number will be unblocked after 24hours from the time the last incoming SMS was received.

**Comment by ericnewcomer** [comment]
This is useful information. The other tricky bit is reply ids are purged
from their system after 24 hrs. If you use it after that they reject the
message as well.

**Comment by migscabral** [comment]
I could  create a checker for the  validity of the last `request_id` based on the time it was created then switches between `REPLY` and `SEND` outgoing SMS types.

**Comment by ericnewcomer** [comment]
Ya, we actually started with that approach on our fork. Perhaps a
combination of that and also not using a reply id unless the most recent
message is inbound would be a combination that could work. And then finally
falling back to a send if a reply fails.

I'm planning to add this logic today.

**Comment by ericnewcomer** [comment]
FWIW, here's how we are now currently dealing with Chikka:
https://github.com/nyaruka/rapidpro/blob/ded8d602753777d3834294374dfd92dda0ca07c5/temba/channels/models.py#L1408

**Comment by migscabral** [comment]
Thanks for this! We'll update our server's repo to this.


Miguel Cabral
--

**Comment by nicpottier** [comment]
Fixed in courier.
