### ISSUE TITLE
Admin boundaries for island nations lead to confusing maps

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#342]
Using administrative boundaries for data visualization isn't great for island nations. We should investigate if there's a way to special case these to not include the waters in between small islands such as those in Indonesia (or perhaps some overlay of admin boundaries on a real map).

<img width="564" alt="screen shot 2016-09-12 at 9 17 49 am" src="https://cloud.githubusercontent.com/assets/211652/18439151/d54d43a6-78c9-11e6-9ddc-19207f40891f.png">

Using admin boundaries, the representation of the country becomes very confusing once extracted using POSM.

<img width="251" alt="screen shot 2016-09-12 at 9 17 26 am" src="https://cloud.githubusercontent.com/assets/211652/18439156/d98506c0-78c9-11e6-956f-a3fd94631fd9.png">

May not be a whole lot to be done considering with border smoothing, the administrative boundaries may be the only reasonable representation here.

**Comment by nicpottier** [comment]
Closing with chagrin as I don't think this is something we can reasonably address within RapidPro. Perhaps #763 would fix this for those that have painful maps?
