### ISSUE TITLE
Androïd Channel doesn't work with flows

### ISSUE THREAD

**Issue by supportticanalyse** [rapidpro/rapidpro#345]
Hi! i deployed the last version of Rapidpro but when i use Androïd Channel to run the flows it doesn't work. I can send keyword but there are not the return message. Could you help me please!
Thanks in advance!

**Comment by ericnewcomer** [comment]
We'd need a bit more information for this to be a bug report. Please direct questions to the mailing list rapidpro-dev and only open issues against the repo with a repro case.
