### ISSUE TITLE
Timeouts and the simulator

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#351]
When flows proceed beyond the simulator, timeouts are not reflected.

Repro
- Create a flow with a timeout
- Route that to a message and back to the timeout
- Run the flow in the simulator

The flow never proceeds, partly because the simulator doesn't poll for messages. It's possible these aren't proceeding for test contacts as well.

This also raises an interesting topic in what to do with test contact timeouts that loop indefinitely.

**Comment by nicpottier** [comment]
New simulator should have a button for this to allow full testing of flows.

**Comment by rowanseymour** [comment]
Should move this issue to floweditor repo..

**Comment by ericnewcomer** [comment]
Agreed, will open there.
