### ISSUE TITLE
seems the temba template tag was omitted in templates/includes/nav.haml

### ISSUE THREAD

**Issue by antsmc2** [rapidpro/rapidpro#358]
Hi,

Just cloned and tried to setup a fresh instance of rapidpro... whenever I try to add new user, the page explodes with reference to this template file:
https://github.com/rapidpro/rapidpro/blob/master/templates/includes/nav.haml

Seems the file is omitting to load your temba template_library. (I believe it's needed for the ssl_brand_url tags.)

After I included temba in the initial load statement everything works fine. I guess it is an omission?

**Comment by ericnewcomer** [comment]
Sounds like it. Want to open a PR?
