### ISSUE TITLE
Unordered messages sending on Facebook channel

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#362]
We are facing a problem when we are trying to send broadcast message through facebook channel.

The messages should be delivered as follows:
![screen shot 2016-10-05 at 14 48 39](https://cloud.githubusercontent.com/assets/5198870/19125185/772b04ca-8b0c-11e6-8b08-967f19b8e85a.png)

But it were delivered in reverse order:
![screen shot 2016-10-05 at 14 57 14](https://cloud.githubusercontent.com/assets/5198870/19125200/87d625ca-8b0c-11e6-89f3-e8b3313864f6.png)

It would be a problem in the RapidPro or in the Facebook Messenger?

**Comment by nicpottier** [comment]
RapidPro should be sending these in order, would recommend debugging to see which messages are sent when on the RapidPro side.

**Comment by teehamaral** [comment]
So possibly the problem is at the reception of messages on Facebook, because in the contact log page the messages are displayed in the correct order.

**Comment by teehamaral** [comment]
We did the debugging and the messages are shown in the RapidPRO correctly, but on `Celery` queue the messages are sent scrambled. For some contacts all messages are delivered correctly and others contacts it is delivered in wrong order. Could the problem be at the celery worker? Would you have another suggestion to debug this problem?
