### ISSUE TITLE
Validate/reconcile facility names against registry

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#37]
might make more sense to have a general noun reconciliation process? so users can define a type of entity (like districts, etc for locations) and then specify a URL for a reconciliation/validation service

would need to standardize around a reconciliation API like OpenRefine (maybe develop some tooling around https://github.com/okfn/reconcile-csv) or Nomenklatura (http://nomenklatura.okfnlabs.org/)

cc: @ewheeler

**Comment by ewheeler** [comment]
heres a writeup on how to accomplish this with rapidpro and nomenklatura: 
https://community.rapidpro.io/blog/easy-webhook-lookups/

**Comment by rowanseymour** [comment]
Closing this for now as it seems preferable to let users accomplish this via webhook calls if they want rather than automatically calling an external service when a field value is being parsed.
