### ISSUE TITLE
Contact field completion could have more accurate test

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#378]
The more fields exist in the account, the harder it is to create a new field from within the 'Update Contact' modal. 

<img width="400" alt="0" src="https://cloud.githubusercontent.com/assets/18295810/20137224/9d31f3e4-a679-11e6-8db2-3a0670083fb3.png">

For example, 'Age' matches 'Message'.

**Comment by nicpottier** [comment]
New editor does a better job of this, closing.
