### ISSUE TITLE
@extra is not working with "Start someone in a flow"

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#383]
Hi guys,

I was trying to add multiple users into my organization, however, when I tried to add them through a "Start someone in a flow" and update their information in another flow, it just didn't take the information from the first flow, even though I’m using the @extra.flow. See below:

![captura de tela 2016-11-17 as 15 44 48](https://cloud.githubusercontent.com/assets/23530401/20402865/3c65410a-acdd-11e6-83a1-669ec205a032.png)

![captura de tela 2016-11-17 as 15 43 45](https://cloud.githubusercontent.com/assets/23530401/20402875/45d8a45c-acdd-11e6-82f0-06317ccaa2db.png)

![captura de tela 2016-11-17 as 15 43 14 1](https://cloud.githubusercontent.com/assets/23530401/20402882/4da72424-acdd-11e6-91bd-deb3c30f1d95.png)

Let me know if I'm doing something wrong. Thanks in advance for your help.

**Comment by nicpottier** [comment]
Depending on the version you are running you may be looking for @parent.nome not @extra

**Comment by nelsonlapf** [comment]
Thanks @nicpottier, I did some tests at Textit environment also. I will try with @parent.nome and back here.

**Comment by nelsonlapf** [comment]
@nicpottier it's working with @parent. Thanks a lot. I would like to suggest you update the rapidpro documentation, with this change.

**Comment by nicpottier** [comment]
Great. Which documentation are you talking about?

**Comment by nelsonlapf** [comment]
This one here http://docs.rapidpro.io/

**Comment by johncordeiro** [comment]
@nicpottier this documentation is available at a repository that we could contribute?

**Comment by nicpottier** [comment]
@ycleptkellan Can you update these?

@johncordeiro No, these are all part of our support system (Nyaruka's) and our IP, not UNICEF's.

**Comment by ycleptkellan** [comment]
@nicpottier updated
@nelsonlapf apologies for the confusion

**Comment by nelsonlapf** [comment]
@ycleptkellan no problem at all!! thanks for the quick action.
