### ISSUE TITLE
A space at start or end of username prevents login

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#390]
When one adds a space before or after username(email) at login, usually by mistake. Rapidpro will not strip it automatically. It is extremely hard for someone to notice that space.

**Comment by dodobas** [comment]
this is simple to fix, but should we maybe create custom form fields that would `strip` raw input, for example: `CharFieldStripped` and `EmailFieldStripped` and then just use those where needed ?

**Comment by ericnewcomer** [comment]
Feels more like an attribute on a field than a field type.

**Comment by dodobas** [comment]
hmm, there is a `strip` attribute on CharField ... https://docs.djangoproject.com/en/1.11/ref/forms/fields/#charfield and EmailField extends the CharField ... so it should strip the extra spaces ... 

... after some digging ... this looks like a smartmin bug ... https://github.com/nyaruka/smartmin/blob/master/smartmin/users/views.py#L438 ... it is using a 'raw' form and we do not strip input values ... I will fix it there
