### ISSUE TITLE
Rulesets can't match Emojis

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#396]
Currently due to the regexes we use, there is no way to create a rule that matches a thumbs up, 👍, even if you explicitly put it in a ContainsTest.

Seeing as people use emojis more and more, we should allow this.

Doesn't look super simple but it seems we can call out particular character ranges as emoji's and make sure those are pulled out appropriately.

See:
http://stackoverflow.com/questions/39536390/match-unicode-emoji-in-python-regex

**Comment by norkans7** [comment]
Supported in https://github.com/nyaruka/rapidpro/pull/985
