### ISSUE TITLE
Allow sorting of contacts by contact fields

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#406]
We can't do this for yuge accounts but for smaller ones it sure would be convenient for users to sort by the columns they have made visible.

**Comment by nicpottier** [comment]
Would be interesting to know whether this is possible for arbitrary fields even when we have millions of contacts.

**Comment by rowanseymour** [comment]
This was added in https://github.com/nyaruka/rapidpro/pull/1864
