### ISSUE TITLE
Groups created in Simulator runs are actually added to the org

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#408]
- Add an 'Add to Group' action to a flow to add contacts to a group that doesn't yet exist. 
- Simulate that flow and pass through that step.

**Comment by rowanseymour** [comment]
Not an easy thing to change currently. Ideally we'd have a flow engine like what we use in surveyor which takes some state in JSON and outputs some new state in JSON. RapidPro would then update things in the database accordingly, or in the simulator case - not make any database changes. In that world, we could keep test contacts and test messages completely out of the database.

**Comment by nicpottier** [comment]
Groups and Contact Fields are now always present if they are references in a flow, so this is no longer an issue.
