### ISSUE TITLE
Allow users to programmatically build/edit flows

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#413]
Organizations want to be able to create and edit flows via the API. Seems these would be natural additions to the platform's flow management toolset, as it's already possible to request a flow's definition and start it via the API. Plus, the UI can be cumbersome when working with larger flows or making sweeping changes.

**Comment by nicpottier** [comment]
Some of the work we are doing around the FLOIP world should help in this regard. We have these APIs today but don't really expose them because the definitions of flows changes quite a bit, so making guarantees we can keep would slow us down.

**Comment by rowanseymour** [comment]
Closing this as I don't think there has been much demand, and it sort of runs counter to the point of the platform
