### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by iahmedani** [rapidpro/rapidpro#417]
can anyone tell me how to install on ubuntu 16.04 AMD64bit.

I tried but end up with error 

> x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/Modules/2.x/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-2.7/gnureadline.so /usr/bin/ld: cannot find -lncurses collect2: error: ld returned 1 exit status error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by rowanseymour** [comment]
Better to use the mailing list for installation questions like this which aren't issues with the code.

I think this answers your question http://stackoverflow.com/questions/32168379/usr-bin-ld-cannot-find-lncurses
