### ISSUE TITLE
Successfully delivered Messenger messages aren't marked delivered on the contact read page

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#420]
<img width="439" alt="fb_outbound" src="https://cloud.githubusercontent.com/assets/18295810/21650994/808ec220-d26c-11e6-8e74-8f6fbb96ee9a.png">

**Comment by nicpottier** [comment]
This is by design.. Facebook queues up all delivery reports so if there are large sends then it slows down all incoming messages, so we no longer register for delivery reports.
