### ISSUE TITLE
USSD Flows: Ability to 'Start someone else in a flow'

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#429]
We have a common requirement on our projects for a healthcare worker to capture a patient as a new contact over USSD. 

The Documentation (http://docs.rapidpro.io/#article_366849) describes how to achieve this on a Messaging flow (using the 'Start Someone in a Flow' action). However, this functionality is not available in 'USSD Messaging' flows. At present, it does not seem possible to register another Contract from within a USSD flow.

**Comment by SeanBlaschke** [comment]
Wanted to bump this and see if feature is expected to be included in any upcoming releases. Thanks!

**Comment by ewheeler** [comment]
@SeanBlaschke related mailing list discussion:  https://groups.google.com/forum/#!topic/rapidpro-dev/fBHwVplLpGM

**Comment by smn** [comment]
Pull request ready for review in #464 @nicpottier & @ewheeler

**Comment by nicpottier** [comment]
Believe this should be fixed now.
