### ISSUE TITLE
USSD Flows: Channel selection bugs

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#430]
Environment: RapidPro.io

We may have hit a few more USSD teething issues in terms of an account configured with both a USSD and SMS channel. On our account, we have added both the Vumi USSD channel and a Nexmo account (South African number - +27).

We have noticed:
1) In the Contact detail view, the 'Send Message' button causes the system to attempt to send the message over the USSD channel. We can see the attempted message send over USSD in the Message History.
2) If we build a Messaging flow and use a timer Trigger to start the flow, the system also attempts to send the messages over USSD. We can see the attempted message send (Broadcast) over USSD in the Message History.

**Comment by SeanBlaschke** [comment]
Has there been any progress adressing this bug? We are set to launch a national programme in 2 weeks with the Ministry of Health and this currently is one of 3 showstoppers.

**Comment by nicpottier** [comment]
Should be fixed now. You may need to remove/readd existing USSD channels for it to take effect.
