### ISSUE TITLE
USSD Flows: Ability to send SMS within a USSD Flow (bug/enhancement)

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#431]
On a USSD Flow, the system allows the user to specify a 'Send an SMS response' action. 

However, the system displays the content in the message field onscreen in the USSD session. In our current use case (post-signup notification SMS), we can work around this using a campaign with a zero-delay message rule. 

Preferred solution: support sending of SMS messages within a USSD Flow - the system correctly sends the message using an available SMS channel.

Alternatively: remove the SMS actions from the designer in USSD Flows.

A question: if the user has configured multiple SMS channels, how does the system select which SMS channel to use for outbound message sending?

**Comment by RichardHeslopZA** [comment]
Hi, 

I am currently designing flows for a USSD project needs to send SMS messages during/after flows. 

Is this on the radar for development in the short-term? i.e. should we expect this to be available in the near future, or do you advise us to launch using Campaigns as a workaround for sending SMS during/after a USSD Flow?

**Comment by nicpottier** [comment]
Don't USSD flows already allow sending SMS messages within them?

Anything delayed should be using campaigns though.

**Comment by nicpottier** [comment]
Should be fixed now. You may need to remove/readd existing USSD channels for it to take effect.
