### ISSUE TITLE
No Module Named Settings

### ISSUE THREAD

**Issue by Chelagat** [rapidpro/rapidpro#432]
I am setting up the environment. When I run `manage.py syncdb`, I get this error: "No module named settings" : and it's because of this line in temba.celery:  
`getattr(settings, 'CELERY_ALWAYS_EAGER', False):`

Did anyone get the same problem? I thought the module would be accessible because of the import statement: `from django.conf import settings`. Any help will be appreciated.

**Comment by rowanseymour** [comment]
You should create `settings.py` as a link to an actual file, e.g. to use the default development settings:

```
ln -s temba/settings.py.dev temba/settings.py
```

**Comment by Chelagat** [comment]
I created the symbolic link as suggested, and I still get the same error:
`ImportError: No module named settings`

**Comment by rowanseymour** [comment]
What happens if you open a python shell and run `from temba import settings` ?

**Comment by teehamaral** [comment]
@Chelagat you could copy temba/settings.py.dev to temba/settings.py instead.

**Comment by Benedicte2019** [comment]
@Chelagat you should open temba/settings.py to make sure it has content. If it's empty it means cp temba/settings.py.dev temba/settings.py didn't work. In short do cp --remove-destination temba/settings.py.dev  .That worked for me
