### ISSUE TITLE
PostgreSQL compatibility with create postgis extension command

### ISSUE THREAD

**Issue by Chelagat** [rapidpro/rapidpro#433]
For PostgreSQL versions lower than 9.6, the following error is encountered when creating a postgis extension on the database:
`ERROR: syntax error at or near "PARALLEL"
  Position: 2445`

Upgrade to latest version of PostgreSQL to avoid this.

**Comment by rowanseymour** [comment]
You need to use the right version of the PostGIS extension for your version of Postgres. We use Postgres 9.3 everywhere, and it works with PostGIS 2.1.8
