### ISSUE TITLE
Problem displaying statistics in Analytics

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#442]
Hi guys,

Into the analytics graphs of the type "tower" and "list", the statistics appear with a wrong percentage, however, in the graphs of type "pizza" they appear in the correct form according to which was responded in the flow through the contacts. See below the graphics:

![tower graphic](https://cloud.githubusercontent.com/assets/23530401/22523871/1145f814-e8a8-11e6-9e8f-66bc0b8f6e8e.JPG)

![grafico errado](https://cloud.githubusercontent.com/assets/23530401/22523582/089e2372-e8a7-11e6-98d8-3829b5f5acb2.JPG)

Did you have realized it before, or there is some work done/in progress to solve this? If don´t, please let me know so we can start working on it.

**Comment by nicpottier** [comment]
This style of analytics is no more, replaced by per-flow analytics. Closing.
