### ISSUE TITLE
Enable users to update a contact's highest-priority tel URN via a flow 

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#452]
## Use Case

User wants to update the active contact's phone number (primary tel URN) when the contact reports a number change.  

## Current Behavior

When a contact's 'Phone Numbers' field is updated in a flow via the 'Update Contacts' action, a new tel URN is added to the contact.

**Comment by nicpottier** [comment]
So right now we add new URNs as the lowest priority URN. Part of the reason for that we don't want to change the medium a contact is using to communicate while in a flow. Perhaps the best approach would be to have a way of removing a URN from a contact? Then that would allow them to remove the old URN once the contact confirms the new URN is the right one? Wonder how that would address the various use cases.

**Comment by ycleptkellan** [comment]
👍  A confirmation step would certainly make for a good user exp. 

This request comes from an mHealth context in Kenya where contacts are initially using shared phones, then acquire their own phone and need to continue through the program without losing custom field values/group membership.

**Comment by Hitman23** [comment]
Hi all, was this considered or dropped.
Thank you.

**Comment by nicpottier** [comment]
Still something under consideration and likely to be implemented in the new engine
