### ISSUE TITLE
Size characters limit alert 

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#453]
Hi guys,

Yesterday I got a feedback from France saying that would be good if we could implement a way to alert them when they are exceeding the numbers of characters during a flow construction, for example, the field Category that only allows them to use 35 characters, would be good if we could implement a counter, a red alert or just don´t allow them to write more.

What do you think?

**Comment by nicpottier** [comment]
Doesn't the message dialog already show the number of characters and messages?

**Comment by nelsonlapf** [comment]
I mean here:

![capturar](https://cloud.githubusercontent.com/assets/23530401/22695362/af89220c-ed31-11e6-8121-a3dfbc11e5e9.JPG)

**Comment by nicpottier** [comment]
I think the limit on the Ruleset label is 64 chars.. which I think we do enforce in the UI. (you can't enter longer than that)

Agree the labels should probably have a sane limit as well, perhaps 36 chars.

**Comment by nelsonlapf** [comment]
That´s the point, for "categorize as" the limit is 35 characters, however, it didn´t stop the user while he is typing and allows him to type as much as he wants, and when it goes to U-Report, it didn´t go right.

So would be good to do the same as for "Save result as" and don´t allow the user to type more, or have a kind of alert.
