### ISSUE TITLE
CSS is on Signup page is breaking.

### ISSUE THREAD

**Issue by smn** [rapidpro/rapidpro#454]
v3.0.41 has the following signup screen:

![v3_0_41](https://cloud.githubusercontent.com/assets/1065/22694013/d8948222-ed45-11e6-85fb-f832c3899644.png)

v3.0.42 shows the following:

![v3_0_42](https://cloud.githubusercontent.com/assets/1065/22694901/3aa38bb8-ed49-11e6-99df-80d67e4aa6c5.png)

git bisect tells me commit ff21619a3a04fe521921d8cbfe7a45197f68453d introduced this issue.

**Comment by smn** [comment]
@ericnewcomer I'd issue a PR for this but my CSS foo for this is lacking.

**Comment by ericnewcomer** [comment]
Thanks for this @smn, fix forthcoming.

**Comment by smn** [comment]
thanks!
