### ISSUE TITLE
Improved messaging: user experience

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#459]
Hello guys,

We are trying to improve the messaging model so that the user experience be the best it can be on social networks.
Initially, the solution was to query, for each message, the rules of the next 'waiting for response' box, so that they are sent, after being manipulated, along with the message data to the API channels as follows:

```
step = msg.get_flow_step()
destination = step.get_step()
rule = RuleSet.objects.filter(uuid=destination).first()
rules = rule.as_json()
```

But because of the frequent queries to get the rules of the next message this solution became unfeasible.
Our next attempt was to add the rules in the broadcast since it would be only a single query of them and we would send them in the messages.
Then, we created in the Broadcast model a field that would receive the rules of 'waiting for response' boxes, in the form of serialized JSON, as follows:

```
send_actions, destination = self.get_entry_send_actions()
rule_sets = self.rule_sets.filter(uuid=destination).first()
for send_action in send_actions:
    message_text = self.get_localized_text(send_action.msg)
    # if we have localized versions, add those to our broadcast definition
    language_dict = None
    if isinstance(send_action.msg, dict):
        language_dict = json.dumps(send_action.msg)
    if message_text:
        broadcast = Broadcast.create(self.org, self.created_by, message_text, [], language_dict=language_dict, base_language=self.base_language, rule_sets=rule_sets)
```

We updated `get_entry_send_actions()` to return the destination of the next RuleSet too, and from there, pick up the rules and write to the current broadcast line.
When the message is being sent to Redis in a serialized way, we would add the rules to `as_task_json()` so that in `send_message()` we would have the rules without having to query them again.

```
def as_task_json(self):
    """
    Used internally to serialize to JSON when queueing messages in Redis
    """
    return dict(id=self.id, org=self.org_id, channel=self.channel_id, broadcast=self.broadcast_id,
                text=self.text, urn_path=self.contact_urn.path,
                contact=self.contact_id, contact_urn=self.contact_urn_id,
                priority=self.priority, error_count=self.error_count, next_attempt=self.next_attempt,
                status=self.status, direction=self.direction,
                external_id=self.external_id, response_to_id=self.response_to_id,
                sent_on=self.sent_on, queued_on=self.queued_on,
                created_on=self.created_on, modified_on=self.modified_on, rules=self.broadcast.flow_rules)
 ```

With this, the query to get rules of the next step on database was avoided. But we realized that the creation of the broadcast happens only in the first message of the flow, which when responding would be necessary to consult again in each message, returning to the starting point. Ideally, in the final solution, we wouldn't like to change the Message/Broadcast models, but we are still analyzing all possibilities. Does anyone have any suggestions that can somehow lead to a solution that is scalable?

**Comment by nicpottier** [comment]
So we've chatted about this before. The way we want to solve this is to offer higher level primitives in flows, such that the user can express "I am asking a multiple choice question" and then we do the right thing depending on the channel type. (this would also unify with voice flows for example)

We wouldn't merge an approach that is trying to infer intent from the rulesets.

Since that is basically a huge refactor of flows in general and we are also on the hook to work with the FLOIP group towards flow interoperability, we are trying to address both at once with that refactor. The FLOIP project isn't exactly flying along though, so depending on where we stand in a few months we may just attach that refactor without them.
