### ISSUE TITLE
Expand purge feature on /org/update/

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#460]
Add a purge feature that can be used to delete the entire contents of an account.

**Comment by rowanseymour** [comment]
Currently "is purgeable" means something else - whether we "prune" old data from that org. We maybe should have picked a different word for what we currently call purging, and it seems reasonable that we would have a way to actually purge/delete an account.

**Comment by ycleptkellan** [comment]
Gotcha, yeah, I think such a feature would go a long way for orgs concerned w/ data security. 
A thought: might be good to give this option to user admins, as well an option to 'hard delete' groups of contacts at will. Checks the data security and self-service boxes.

**Comment by nicpottier** [comment]
This is mostly done, though we still need to add a task that does the full release.
