### ISSUE TITLE
'Set preferred channel' action not switching from Nexmo to Twilio when voice-enabled numbers from each service are connected to account 

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#462]
Repro: 

- Add voice-enabled Twilio and Nexmo numbers to your account. 
- Create an IVR flow with a 'Set preferred channel' action that selects the Nexmo number.
- Start your contact in the flow.
- Update the 'Set preferred channel' action to select the Twilio number.
- Start your contact in the flow. 

Nexmo initiates the call despite the contact being mapped to a Twilio channel. 

Additional steps: 

- Remove Nexmo channel from your account.
- Add the Nexmo channel you just removed.
- Start your contact in the flow ('Set preferred channel' should still be selecting the Twilio number). 

Nexmo initiates the call.

**Comment by smn** [comment]
Is this perhaps related to #430?

**Comment by nicpottier** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/1119
