### ISSUE TITLE
Trigger campaign events on custom, non-date contact fields

### ISSUE THREAD

**Issue by bertplunkett** [rapidpro/rapidpro#466]
Hello everyone,

First of all, thank you for the great and hard work you've put into Rapid Pro. We've been using it inside our organization for quite some time already with spectacular results.

However we have a few questions which I'll post as separate issues here.

Is it possible to trigger campaign events on a custom, non date contact field? Suppose I have a numeric custom field called 'ranking', would it be possible to trigger a flow on a contact whenever its ranking value drops or tops a certain threshold?

**Comment by nicpottier** [comment]
You can probably use a dynamic group for this along with campaigns. Perform a query for the condition you want, then create a dynamic group from it. Then base your campaign on that group.
