### ISSUE TITLE
Ability to add metadata to outgoing messages

### ISSUE THREAD

**Issue by bertplunkett** [rapidpro/rapidpro#467]
Would it possible to add certain metadata (say, a few flags) to outgoing messages from the RP UI? Another possibility that could work for us would be to specify an explicit channel to use when sending a message or starting a flow (given that all of our users are available through any of our custom channels).

Edit: by metadata I mean internal data that would not be visible to users on the message body itself but would still be delivered to the appropriate backend channel we use.

**Comment by nicpottier** [comment]
Is the metadata specific to the user/msg or just specific to the channel?

You can specify what channel a contact uses via one of our actions in flows.

**Comment by bertplunkett** [comment]
I have a few different cases but in the simplest and most common one I would want to either specify a certain metadata or use a specific channel (which in either case would be the same for all users) when sending messages and a different set of metadata (or a different channel, again in both cases the same for all users) when participating in a flow.

**Comment by nicpottier** [comment]
Might be slightly goofy but I would probably use your own custom channel then (use the External channel and you can specify whatever you like in the URL in addition the recipient data).

**Comment by bertplunkett** [comment]
Ok, I get what you mean and I'm sorry to keep asking questions, but how could I then specify which channel to use when sending messages and when starting flows? I can't seem to find a way to do that.

**Comment by nicpottier** [comment]
There's a "Set Channel" action you can use in flows.

**Comment by bertplunkett** [comment]
Thank you for your suggestion. However, if I understand correctly, what will happen here is that the *preferred* channel for the contact will be set, which will work for the flow instance. But if I want to target the user with a message later on then the message will be sent through whatever channel was previously set as preferred by the flow, and this in turn takes me back to the root of the problem all over again.

**Comment by nicpottier** [comment]
You could just use flows to send your messages I suppose. Sorry, ya, this isn't a use case really well supported.
