### ISSUE TITLE
Vumi Channel does not send the `in_reply_to` value for USSD sessions.

### ISSUE THREAD

**Issue by smn** [rapidpro/rapidpro#469]
Depending on the interface to the aggregator the value of the `in_reply_to` is important as for both synchronous and asynchronous protocols it is often a requirement to be able to refer to a previous request.

The value of the `in_reply_to` value should be the `message_id` of the previous message that was received to which this is a reply.

**Comment by nicpottier** [comment]
Should be a pretty small change in send_vumi_message in channels/models.py.. We should be tracking the message the response is to so that id is available on the msg dict.

**Comment by smn** [comment]
https://github.com/rapidpro/rapidpro/pull/472 addresses this issue.
