### ISSUE TITLE
Test user session for USSD cause IVR hangup crash in Flow editor

### ISSUE THREAD

**Issue by jpaidoussi** [rapidpro/rapidpro#470]
If there are FlowRun objects for a USSD flow that are:
1.  for a test contact, and
2. have a session ID specified

then this line of code will fail with an AttributeError on `test_call.channel.channel_type` as there is no guard against test_call being a None value:
https://github.com/rapidpro/rapidpro/blob/master/temba/ivr/models.py#L46

I believe this can happen when running through a USSD flow with a test contact.

**Comment by nullcode** [comment]
This bug occurs by using the simulator with no USSD channel added and it's fixed in PR #423

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
