### ISSUE TITLE
Wait for USSD Menu - Character count includes regex

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#471]
When using a regex to specify a menu option, the system counts the expression characters towards the character limit. 

Perhaps the character counter can resolve the regex to determine the length of the resulting string?

Alternatively, perhaps remove the business rule that prevents Save when the character count exceeds the character limit.

![screen shot 2017-02-24 at 3 55 57 pm](https://cloud.githubusercontent.com/assets/10830046/23306500/7a27c266-faac-11e6-9297-0df240876133.png)

**Comment by nicpottier** [comment]
This is the category name (the red box) or the menu name?

**Comment by asseym** [comment]
@RichardHeslopZA is this issue still a show stopper for you?

**Comment by RichardHeslopZA** [comment]
This is not a showstopper. Our workaround is to manually rotate the set of Menu options on a monthly basis so that the correct set of menu options is displayed to the user.

@nicpottier To answer your question: the character limit counts all text in the menu name (i.e. including regex expressions) which will generally exclude (or seriously limit) ability to use regex to dynamically generate menu options. (Perhaps this is an uncommon requirement?) 

The Category Name field appears to limit to input to 36 characters. 

@nicpottier I'm not sure how (if..) the USSD menu character length rule could be changed to accommodate dynamically generated Menu Options (given that the Menu Name string length is only known at runtime).

If it is not possible to dynamically generate Menu Names, then the requirement to accommodate regex in the Category Name field (i.e. longer strings than 36 chars) goes away.

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
