### ISSUE TITLE
@parent is not working with "Start someone in a flow"

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#476]
Hi guys,

I was trying to add multiple users into my organization, however, when I tried to add them through a "Start someone in a flow" and update their information in another flow, it just didn't take the information from the first flow, even though I’m using the **@parent.flow** as in the documentation (http://docs.rapidpro.io/#article_366849). See below:

<img width="897" alt="screen shot 2017-03-01 at 15 14 35" src="https://cloud.githubusercontent.com/assets/5198870/23474306/1919cf16-fe92-11e6-9740-f0101c5c4248.png">
<img width="1051" alt="screen shot 2017-03-01 at 15 15 04" src="https://cloud.githubusercontent.com/assets/5198870/23474317/24728e8e-fe92-11e6-9460-580af2b6c34a.png">
<img width="812" alt="screen shot 2017-03-01 at 15 24 19" src="https://cloud.githubusercontent.com/assets/23530401/23474647/37118db4-fe93-11e6-8ea9-53e0dfd7d051.png">

Let me know if I'm doing something wrong. Thanks in advance for your help.

**Comment by ericnewcomer** [comment]
This is supposed to be ```@parent.name``` not ```@parent.flow.name```.
