### ISSUE TITLE
FlowStepEndpoint isn't handling fields

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#498]
The FlowStepEndpoint isn't handling fields (https://github.com/rapidpro/rapidpro/blob/master/temba/api/v1/views.py#L2802). Would be a contribution welcome here?

**Comment by rowanseymour** [comment]
Not sure what you mean by not 'handling fields' .. not saving values to contact fields?

**Comment by teehamaral** [comment]
It isn't adding fields.

**Comment by rowanseymour** [comment]
Can you provide an example?

**Comment by teehamaral** [comment]
For example, a part of the surveyor app request:

```
{
	"fields": [{
		"key": "mailto",
		"label": "Email address",
		"value_type": "T"
	}],
	"steps": [{
		"node": "6b05d3b7-c4e5-4786-bfd8-9ec39a55485a",
		"arrived_on": "2017-03-21T13:38:20.206Z",
		"left_on": "2017-03-21T13:38:20.216Z",
		"rule": null,
		"actions": [{
			"type": "reply",
			"msg": "What's your code?"
		}],
		"errors": [],
		"flow_uuid": "c947f133-a062-49ff-9441-f94436ae2323"
	},
	...
```

But the fields on `fields` key isn't being added.

**Comment by rowanseymour** [comment]
Ah ok yeah that does seem to be missing on the `FlowStepEndpoint`. You can go ahead and make a PR for that.

Bear in mind that API v1 has been superceded, and we're just keeping the parts of it that we need for backward compatibility with Surveyor clients.

**Comment by teehamaral** [comment]
Could you say if the Surveyor app will have update using API v2?

**Comment by rowanseymour** [comment]
I'm sure it will eventually but the current plan is just to leave the parts of API v1 that it needs.

**Comment by teehamaral** [comment]
I'm closing this issue because there was a mistake, the surveyor app request arrives first in the Contacts API, so it would have to add new fields if they did not exist and not the FlowStep API.
