### ISSUE TITLE
External API channel force UTF8 encoding 

### ISSUE THREAD

**Issue by Haythamamin** [rapidpro/rapidpro#505]
This is supposed to be a flexible channel to allow regions with no access to already supported channels. Enforcing on a type of encoding makes it difficult to integrate other providers who might have different encoding specifications than UTF8. There must be a way to specify the encoding for External API channel to meet provider specs.

**Comment by nicpottier** [comment]
Realize this is old, but can you give us an example provider / use case for this?

**Comment by rowanseymour** [comment]
Closing for now pending more information
