### ISSUE TITLE
Only one of text or attachment can be specified on Facebook Channel

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#512]
> Only one of text or attachment can be specified

The message above is returned when I try to send a message with image using Facebook Channel, so, or text or attachment could be added to payload here https://github.com/rapidpro/rapidpro/blob/master/temba/channels/models.py#L1489

**Comment by norkans7** [comment]
That is fixed in https://github.com/rapidpro/rapidpro/pull/511/files 

in v3.0.86

this PR will be merged soon so closing this issue
