### ISSUE TITLE
Boto3 lib doesn't have the generate_url method

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#513]
The way as boto3 generates urls is different of https://github.com/rapidpro/rapidpro/blob/master/temba/assets/models.py#L85 and it uses `storages.backends.s3boto3.S3Boto3Storage` instead of `storages.backends.s3boto.S3BotoStorage`

**Comment by rowanseymour** [comment]
@teehamaral I'm assuming this is no longer a problem
