### ISSUE TITLE
Create campaign events via V2 API: 320 char limit issue

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#517]
When creating a campaign event via the V2 API and specifying translations with a JSON encoded dictionary as the message content, the character length validation on the message field doesn’t consider that the field may be JSON and will still enforce the max 320 character limit. This obviously isn’t ideal as even with two translations the dictionary will often be over the 320 character limit.

**Comment by rowanseymour** [comment]
The fact that you can currently post `{... "message": "{\"eng\":\"Hello\"}" }` seems like a bug. We should fix this so that either `{... "message": "Hello" }` or `{... "message": {"eng": "Hello"} }` works, and internally it's always stored as a dict of translations.

**Comment by RichardHeslopZA** [comment]
Hi Rowan,

We are struggling to upload campaign events using the V2 API. Could you perhaps provide some guidance as to how exactly we are meant to create campaign events with translations via the V2 API? 

It seems like it should be a dictionary rather than a string? Perhaps the system requires it as just a plain string rather than a json encoded string?

Thanks!

**Comment by rowanseymour** [comment]
Am currently making the change described above. This endpoint should allow:

1. `{... "message": "Hello" }` (internally becomes `{... "message": {"base": "Hello"} }`)
2. `{... "message": {"eng": "Hello", "fre": "Bonjour", ... } }`

The fact that you can currently post post `{... "message": "{\"eng\":\"Hello\"}" }` should be a considered a bug, so don't rely on that behavior continuining.

**Comment by Reobone** [comment]
@rowanseymour, hope you are well. When should we expect the API changes for the Campaign upload to be ready? We would like to start testing as soon as its available on V2?

**Comment by rowanseymour** [comment]
@Reobone I just merged https://github.com/rapidpro/rapidpro/pull/538 so those changes are in rapidpro/rapidpro now.
