### ISSUE TITLE
Carrier reserved keywords aren't being handled properly

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#519]
There are mandated reserved words by law for SMS opt-out: `stop` and `cancel` will block all communication to a given phone, but RapidPro grabs these and continues to attempt to text as if it's just another word, when everything after is clearly failing. Probably indicating in a configuration what words are carrier handled/reserved words for opting in and out would be useful. One reason is so RapidPro can better handle `start` or the equivalent carrier keyword that restores a connection. Right now it's too dumb to understand what happened, so `start` will get thrown into whatever flow was currently running. It's the most frustrating UX I can imagine.

**Comment by rowanseymour** [comment]
Something to bear in mind here is that different countries have different laws on this and different channel types have different mechanisms for opting out. Some carriers will send the stop message, to us, some won't. The way we've dealt with this is to detect opted-out contacts when sending messages - some carriers will send back a specific error code if we try to send to a stopped contact, and that's when we know to stop that contact and pull them out of any active flows.

I can think of two approaches we might take to improve on this:
- have a kind of user trigger specifically for keywords that should take precedence over active flow runs.
- hard code into our channel handlers what keywords should cause a contact to be stopped.

**Comment by nicpottier** [comment]
Reserved words are different everywhere, we can't really have a generic answer for this. The tools are there for flow authors to do the right thing, even in the case of flows that ignore keywords, so closing.

**Comment by putorti** [comment]
For posterity, we elected to have Twilio stop managing these keywords—their default behavior, which solved this problem.
