### ISSUE TITLE
Flow type named "Multimedia".

### ISSUE THREAD

**Issue by leandroneves** [rapidpro/rapidpro#522]
Hi guys,

The communication channels are creating many guidelines to improve the user experience.

We have already discussed that changing the message sent by adapting the guideline according to the channel is not a good practice

Because of that we idealized the creation of a new flow type named "Multimedia".

The modeling structure will look like with the send image that already exist today on the message flow.

With it we have implemented the guidelines and will only work on the channels they support. Just like the SSD or IVR.

Here is an initial mockup. I would like to open this discussion thinking about the best user experience.

https://marvelapp.com/332433j/screen/25753153

**Comment by JPow** [comment]
hey, i love the idea - would be great to be able to send images and get a response via RapidPro, especially given the impact images have had on advocacy efforts recently (think refugees) but also to debunk steroetypes.  It could be very fun for the U-Reporters who now communicate more and more in these mediums and using image to express themselves.

**Comment by nicpottier** [comment]
Note that you can send and receive images today in RapidPro (this was added
a month or so back).

This is more a question on higher order elements, buttons, carousels, etc..

**Comment by ericnewcomer** [comment]
We've put a ton of thought and are underway with some efforts toward how to best support rich experiences over IP channels.  While agreed, things like USSD and IVR don't parallel well, IP channels and text-based channels do to a degree. While one may want to author IP-specific flows to curate that experience, having them gracefully degrade for text-based channels is likely an important tenet of the ultimate design.

I don't think the previous feedback for you guys was that channels shouldn't have a say in how to best present, say a menu over an IP channel, to the contact, but that how that information is provided to the channel needs to be handled further up the stack -- ie, querying rulesets and sending time is not a scalable solution. Our current thinking is more along the line of a declarative blob stored with the outbound message that channels can determine the most appropriate way to deal with.

We're probably a month or two out before we have something to share on this, but we are definitely not ignoring this problem.

**Comment by nicpottier** [comment]
Just to build on what Eric said, we definitely see a need for being able to offer better first class support for IP based messaging, but we don't want it to be a "fork" or a different flow type. The main reason there is that it becomes annoying for users to build multiple versions of the same flow and manage which contacts should be in which.

So the current idea is to ask for intent of the user (is this ruleset a menu of choices?) and then based on the channel that the contact is on build the appropriate representation, either a simple text question or a keyboard response on telegram or menu of options on Facebook etc..

This is all dovetailing with some work on a brand new flow engine as we talked about in Amsterdam which is making good progress now but is a prerequisite before we add these higher order elements.

All that to say, totally agree with this requirement, and I actually think it may make sense in time to have a first class multimedia type flow, but first we just have to do a better job of translating user intent into better experiences for end users automatically.

**Comment by JPow** [comment]
Any updates on the new flow engine Nic/Eric? (happen to be with Facebook right now, discussing using bot features like buttons etc)

**Comment by nicpottier** [comment]
That's all part of a very large refactor which is taking place. Lots of progress being made that will enable us to start adding new features like this, but the integration of that new code and migration of old data is still a ways off. We are hoping to have everybody on the new stuff by end of year but it is a huge amount of work.

**Comment by rowanseymour** [comment]
A lot has changed since this ticket was opened - we have the new engine - and we support things like buttons where different channel types offer that as an experience. Attachments of images, videos and audio are all supported, and I think we're continuing down the path where a single flow translates into slightly different user experiences across different channels.. but it's the same flow. So closing for now.
