### ISSUE TITLE
Flows interrupting & triggering Unhandled message flow

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#528]
Hi,

On our instance, we are seeing the following:
1) a flow interrupts itself during execution (see below)
2) the system triggers the configured event for 'Uncaught message'

![capture 1](https://cloud.githubusercontent.com/assets/10830046/24900311/bf809138-1ea3-11e7-930c-23c1afdc1631.PNG)

We are seeing this pattern of Interrupt & 'Uncaught message' event triggering unexpectedly in contact histories:
![rapidpro_-_visually_build_interactive_sms_applications](https://cloud.githubusercontent.com/assets/10830046/24900337/d57eefd4-1ea3-11e7-9675-8de59e193169.png)

![capture 3](https://cloud.githubusercontent.com/assets/10830046/24900503/5adeeaee-1ea4-11e7-9cb7-7fb581903408.PNG)

![capture 2](https://cloud.githubusercontent.com/assets/10830046/24900611/b5ab4ec2-1ea4-11e7-824b-e536d2ef0a4a.PNG)

This is happening both for 1) standalone Messaging flows (triggered by a keyword)  and 2) Messaging flows that are called from a parent USSD flow.

Is this perhaps caused by the 04dea1e merge commit on PR 423?

Thanks!

**Comment by nicpottier** [comment]
Should only be triggering the unhandled flow if the message isn't handled within the flow itself. There's an empty message in your history there for some reason, wonder if that is the hangup message being generated then handled somehow?

**Comment by smn** [comment]
The empty message is the first message of a new USSD request, is that triggering the the "unhandled message" response?

**Comment by nicpottier** [comment]
Should that be a msg? Seems like that should just be a session start, but ya unless that is handled specially for the USSD case seems like that could be the cause.

`Msg.process_message` is where that happens and I don't see any special casing for USSD in `triggers/models/find_and_handle` which is what would be dealing with the catch-all keyword.

**Comment by smn** [comment]
It arrives as a message with a `session_event` key set with the value of `new`, the content of the message is either `None` or an empty string depending on the aggregator or MNO integration.

**Comment by nicpottier** [comment]
Feels to me like that shouldn't be a real Msg object, just like an incoming IVR call doesn't generate a new Msg. Should create a session and can in turn start a flow but not have a Msg object tied to it.

**Comment by smn** [comment]
Possibly but the way these USSD integrations work is that they need a message_id to refer back to when sending a reply. So if it's not a `Msg` object we'd still need something to stash message_ids on so it can be referred back to when sending a reply.

**Comment by nicpottier** [comment]
Hrmm.. I guess one option would be to add a single nullable field to ChannelSession (this is distinct from the session id I take it?). Do we ever need more than one of these and is using the last received on every not going to work?

Alternatively we can special case this Msg case but I feel like that's going to be more brittle long term.

**Comment by smn** [comment]
After reading through the code this is what I think is happening:

1. First a user starts a USSD session which creates a new ChannelSession object and the user completes the flow.
2. The user returns but this time the existing USSD session is re-used since the date ordinal + from address are used as a session identifier.
3. `USSDSession.handle_session_async()` is called which does a `Msg.create_incoming()` and since `status==PENDING` then the handling of that message is left to `temba.msgs.tasks.process_message_task`. That calls `Msg.process_message()` which loops over the available handlers.
4. The triggers for USSD are in `Trigger.find_trigger_for_ussd_session()` but `TriggerHandler` calls `Trigger.find_and_handle()` which doesn't know anything about the USSD paths.
5. No trigger is matched and then the `CatchAllHandler` does `Trigger.catch_triggers()` for type `Trigger.TYPE_CATCH_ALL` which results in the catch all flow to be run and the SMS to be sent.

**Comment by asseym** [comment]
@smn and @nicpottier I wanted to follow up on this issue. Was this ever resolved?

**Comment by RichardHeslopZA** [comment]
@nullcode It appears that #423 did not resolve this issue; we are still seeing the ' unhandled message' trigger firing at the end of flows in the USSD module:

![unnamed](https://user-images.githubusercontent.com/10830046/29809495-ab0e86d0-8c9c-11e7-817d-38412bd302e0.png)

Is there another Pulilabs PR currently open that is expected to resolve this bug in the USSD module?

**Comment by nullcode** [comment]
@RichardHeslopZA unfortunately no, this is actually the first time I read about this and it has never happened to me before. @smn's breakdown might help to identify and fix this easier, but right now it's not on our agenda nor do I have any estimates for it.

**Comment by RichardHeslopZA** [comment]
@nicpottier We are still seeing this issue in Production.

Regarding Simon's evaluation (^^ on Apr 12) - do you have any feedback/ideas/suggestions as to the approach/nature of a fix for this issue?

**Comment by nicpottier** [comment]
I think my conversation with @smn still stands. That this is a `Msg` smells to me and kind of points to why we are having problems. Handling this somehow in the session (now `Connection`) seems like the better long term fix.

We have no USSD channels or clients on any install, so this really falls on someone who is experiencing this to work through a fix and test it.

**Comment by erikh360** [comment]
@nullcode I had a look at the code, the breakdown from @smn and I followed some sessions on our Prod environment, the initial blank `Msg` object created by `USSDSession.start_session_async` or `USSDSession.handle_session_async`(resume) with a status of `PENDING` and is never changed to `HANDLED`. 

We could mark it as handled in `Flow.start_ussd_flow` after we queue the reply, then another task won't pick it up to process it incorrectly.

Are you ok with this solution?

**Comment by nullcode** [comment]
@erikh360 I have checked the screenshots and that's definitely what's happening here, the check_messages_task() picks up the PENDING messages and tries to handle them. I'm still skeptical if we need that first Msg, but if we do, then marking it HANDLED will probably solve this problem.

**Comment by nicpottier** [comment]
+1 to setting it as handled in `start_ussd_flow`
