### ISSUE TITLE
"anon_org" isn't defined

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#533]
It's causing error on omnibox of send messages when searching contacts and groups.

![screen shot 2017-04-13 at 14 44 03](https://cloud.githubusercontent.com/assets/5198870/25016833/dc1ea14e-2057-11e7-8c95-492af55e0d19.png)

https://github.com/rapidpro/rapidpro/blob/be4479af443fcf1e2bcbc1e75e43367cb6b01259/static/js/omnibox.js#L147

**Comment by nicpottier** [comment]
Pretty sure this is fixed on tip, what version are you on?

**Comment by teehamaral** [comment]
v3.0.85

**Comment by nicpottier** [comment]
Tip is 112 so please see if you still see it there.

**Comment by teehamaral** [comment]
Yeah, I was testing, thanks @nicpottier.
