### ISSUE TITLE
WhatsApp Channel

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#534]
Would be a great social network channel to add if possible.

**Comment by nicpottier** [comment]
Ya, we'd add it in a heartbeat if they ever opened it up. But there is no API and they are super aggressive about putting the kibosh on services that try to hack it.

**Comment by putorti** [comment]
Sorry Nic, thanks for letting me know!

**Comment by xamarindevelopervietnam** [comment]
did they open it up?
