### ISSUE TITLE
Simulator Ignores Text When MMS Attachment Present

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#537]
If an image is attached to a message, the message text body is completely ignored by the simulator, the only output being a photo icon (no copy.) Here's a typical example, happens on all flows I test with.

<img width="311" alt="screen shot 2017-04-20 at 12 23 12 pm" src="https://cloud.githubusercontent.com/assets/82857/25248715/25ee4470-25c4-11e7-95c3-9cabb3edab16.png">

**Comment by nicpottier** [comment]
This should be fixed (and deployed) now.
