### ISSUE TITLE
simulator displays expr error when it encounters an arithmetic expr involving a contact field (null val)

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#548]
e.g. simulator can't increment an 'engagement counter' contact field unless the user updates it to 0 at the beginning of the flow (null + 1 otherwise). 

This can be confusing for users testing their flows (or at least cause some second-guessing). Documenting this for forthcoming simulator work. Perhaps the user is asked to set that field value on the test contact before the simulation begins? IDK

![sim_expr](https://cloud.githubusercontent.com/assets/18295810/25671731/e3244f5a-2fe5-11e7-9cee-52f62205c4f3.png)

**Comment by nicpottier** [comment]
FYI, new flow engine treats null as 0 for cases like this so should be less confusing once that rolls out.

**Comment by nicpottier** [comment]
Discussion on this here: https://github.com/nyaruka/goflow/issues/555

But in the end it was decided that null is indeed the right thing.
