### ISSUE TITLE
Limit of objects in the API response

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#556]
What do you think about the APIs have a parameter to limit the amount of objects in the response?

**Comment by rowanseymour** [comment]
Can I ask why someone would want this? Recently we've been trying to steer API users away from using the API for live viewing of data. For example we don't want people building a dashboard that displays messages and continually fetches hundreds of messages every few seconds. It's a lot better for us if users sync all messages to their dashboard - a lot less API requests to handle and we don't necessarily have to provide really old data.

**Comment by teehamaral** [comment]
For example, on Runs API, what's the best way to get the latest run for a specific contact? So, we want to get only one result instead of default pagination, but not more than that.

**Comment by nicpottier** [comment]
You can filter runs by contact now and that should always be performant. Don't think we really need the limit because of that.
