### ISSUE TITLE
Importing data with date 

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#557]
Hi guys,

I was trying to import an excel file with a date on it (DD/MM/YYYY) as set in the organization, however, the system does not accept this configuration, and only accepts the American format (MM/DD/YYYY).

I think that it should take the org configuration instead of having a standard for it, here in Brazil we do not use (MM/DD) and will be hard to ask our users to always change this before uploading a file.

Can we make it happen?

Example: If you already have a list of contacts with the birthday, we will need to adjust it to American format every time before import.

**Comment by norkans7** [comment]
Hey @nelsonlapf, I checked RapidPro does  the right thing on this.
You just need to make sure the org has the right configuration of date format MM/DD or DD/MM
