### ISSUE TITLE
pull contact's name from FB when they start a convo via messanger

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#558]
Would be great if each new FBM contact's name field was automatically populated with their FB display name. Once the user either taps the 'get started' button or sends your channel a message, their PSID can be used to lookup their name: 

https://developers.facebook.com/docs/messenger-platform/user-profile

**Comment by nicpottier** [comment]
I believe this occurs already for FB for non-anon orgs, have you tried it?

**Comment by ycleptkellan** [comment]
Yep, that's the case. My b!
