### ISSUE TITLE
Duplicate authentication key for TransferTo airtime Top up

### ISSUE THREAD

**Issue by Reobone** [rapidpro/rapidpro#559]
We were processing a lot of airtime transfers and rapdipro is sending duplicate authentication keys and the mobile number and airtime doesn't get created on transferto. This occurred to 34 of our topups, they failed on rapidpro with the following error message: 
Data posted Log
{
  "currency": "ZAR", 
  "delivered_amount_info": "1", 
  "key": "1494868095", 
  "action": "msisdn_info", 
  "login": "praekelt_org", 
  "destination_msisdn": "+27837665039", 
  "md5": "246a42637794ccf5874e2aa837c41766"
}

====================
Responses Log
authentication_key=1494868095
error_code=925
error_txt=Key already used or invalid key value

**Comment by nicpottier** [comment]
Is this running on your own instance? @norkans7 

TransferTo's APIs seem to be a moving target so we are always chasing around changes they make. If you can open a PR with a fix for this that would be much appreciated.

**Comment by Reobone** [comment]
@nicpottier this is happening on our instance (which is the production and the version is ). one of our projects at Praekelt. @nicpottier 

When do you think there will be investigations on this? (is there a way of adding more details/fields on the failed transactions email sent from rapidpro)

**Comment by Reobone** [comment]
This is the version on our instance: Version v3.0.132  @nicpottier

**Comment by norkans7** [comment]
@Reobone First, I think the issue there is that the key is reused 
Also we added some recent fixes for issue related to transferTo 
You need to make sure you have those too https://github.com/nyaruka/rapidpro/pull/1263 https://github.com/nyaruka/rapidpro/pull/1168

**Comment by Reobone** [comment]
@norkans7 we only have nyaruka#1168 in our version and nyaruka#1263 is currently not in our version. I'll try and get that update and see if we'll be experiencing the same issue. 

Thanks for your assistance

**Comment by nicpottier** [comment]
Addressed in goflow.
