### ISSUE TITLE
Contacts API v2

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#561]
The documentation of Contacts API v2 says that we need to send groups as follows:
![screen shot 2017-05-18 at 1 51 03 pm](https://cloud.githubusercontent.com/assets/6073075/26214035/641ec2ec-3bd1-11e7-9076-443e91beed06.png)
It doesn't work in this way, responding an Internal Error, but it works when I use the same way as API v1: `"groups": ["Group Name"]`. 

Is it the correct behavior of API v2 and documentation is wrong?

**Comment by rowanseymour** [comment]
Yeah docs are wrong here (I'll fix as I'm fixing a few other v2 issues) - you can pass either an array of UUIDs or an array of group names
