### ISSUE TITLE
"Send to all contact addresses" doubt

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/rapidpro#570]
Hi guys,

One of our countries was trying to use this option, however, despite it says that will send to all contacts it does the opposite, it removes the users from the flow.

So I would like to know how should we use this option?

![image](https://cloud.githubusercontent.com/assets/23530401/26405402/8df40b1a-406b-11e7-8743-1d08f310283a.png)

Thanks in advance.

**Comment by norkans7** [comment]
A contact can have many addresses like phone number, twitter, telegram, facebook

That checkbox is to make sure the message is sent to all those address for the particular contact.

**Comment by nelsonlapf** [comment]
But by now, it´s removing the user from the flow. Is there a specific way to use it?

**Comment by norkans7** [comment]
I suggest you investigate more on that, I do not think that checkbox remove the user from a flow.

**Comment by ericnewcomer** [comment]
Starting a contact down a new flow will interrupt any existing flow runs. As @norkans7 says, the send to all contact addresses is for the given contact in that flow, this is not how to send to contacts not in that flow.

**Comment by nelsonlapf** [comment]
Hey guys,

we´ve solved the problem updating our database to the most recent one. thanks for the help.
