### ISSUE TITLE
No Send Image Capability on Facebook Messenger

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#575]
We can't return images on Messenger, so our experience doesn't fully work. Need to grab a phone number and send receipts over MMS. Pretty anachronistic.

**Comment by ericnewcomer** [comment]
Interesting, I would have expected that to work. @norkans7 any thoughts on this?

**Comment by norkans7** [comment]
@putorti What version are you running? we support attachments for Facebook channels

**Comment by putorti** [comment]
@norkans7 Where is the version number located?

**Comment by norkans7** [comment]
I mean the Git tag of Rapidpro you are running or the commit?

**Comment by putorti** [comment]
This branch is 19 commits ahead, 136 commits behind nyaruka:master.

**Comment by putorti** [comment]
https://github.com/resistbot/rapidpro

**Comment by nicpottier** [comment]
resist is on v3.0.141 right now.. i'll see about updating it this weeked

**Comment by putorti** [comment]
Thanks @nicpottier just realized we're 23 days out of date.

**Comment by putorti** [comment]
Hey @nicpottier so I guess attachments are supported but this issue was in fact about programmatic attachments, I can't attach the fax receipt in a GUI. Any ideas on when attachments/images can be sent on images generated by API, etc.?

**Comment by putorti** [comment]
>RP could auto-convert messages to MMS, but that might be a lot of analysis. Or they push the decision back to us and give us a send_user_image to parallel send_user_message.

@kentquirk thought maybe this would work

**Comment by nicpottier** [comment]
This is on the roadmap but don't have any set date for it.
