### ISSUE TITLE
Single direction for external channels

### ISSUE THREAD

**Issue by xkmato** [rapidpro/rapidpro#577]
Currently, all channels have to receive and send. This sometimes creates a conflict when you need to use the same urn type (eg Phone number) but need to receive from one channel and respond with a different one.

An example use case:
Currently, we have some automated scripts that read WhatsApp logs and pushes the messages into Rapidpro using an external channel. But since we cannot respond to these people using WhatsApp, this channel is only required for incoming messages. Since we still want to keep the conversations going, we would like to train our users to respond with WhatsApp or SMS when they want but we shall always only be sending them messages via SMS.

**Comment by rowanseymour** [comment]
Curently channels have roles so you can remove the `SEND` role of a channel to make it that we never send using it.

However editing roles isn't exposed in the external channel UI (which is already crazy). Do we feel this feature is sufficiently in demand that it should be in the UI? If not we can close this and let deployments manually do this if/when needed.

@nicpottier?

**Comment by nicpottier** [comment]
Ya, that UI is crazy, but in a way seems natural to allow setting it.
