### ISSUE TITLE
Add support for FB Messenger Conversation Ads 

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#578]
Would be useful for orgs that want to drive usage via Facebook Ads. 

https://developers.facebook.com/docs/messenger-platform/guides/ads

Perhaps this takes the form of a trigger? If so, it would be cool to be able to assign a flow to each ad (as the 'ManyChat' platform allows: https://blog.manychat.com/messenger-marketing-101-how-to-run-facebook-ads-to-messenger-23b245fbd520).

**Comment by nicpottier** [comment]
This is handled via triggers now.
