### ISSUE TITLE
Add Twitter Isn't Working

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#579]
<img width="626" alt="screen shot 2017-06-09 at 1 00 55 pm" src="https://user-images.githubusercontent.com/82857/26992472-afed107c-4d13-11e7-8b4c-f18b8f63a7e7.png">

https://rapidbot.io/channels/channel/claim_twitter/

Is this our local install? https://github.com/resistbot/rapidpro

**Comment by putorti** [comment]
Also the email link is broken: `mailto:?subject=Problem%20using%20&body=Reference:%20e731c18a71234b1a85ffece63c60a846`

**Comment by nicpottier** [comment]
Please don't post resist issues to the rapidpro repo, if you want to use github, post them to the resist rapidpro
