### ISSUE TITLE
Contact search should be smarter about phone numbers

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#584]
We current require normalized E164 numbers.. maybe we should normalize incoming queries to help with this? Guess the problem is it could be a name too, but I'd rather have false positives due to stripping spaces/chars than not matching things that look like phone numbers.

**Comment by jlev** [comment]
It would be great to be able to search contact.tel for a pattern, or at least "starts_with".  In the US, the first three digits of a phone number are (or were) geographically based. In cases where we don't have a full location we'd still like to segment based on what we state we think the user is in.

**Comment by nicpottier** [comment]
You can do containment with `~`, so can do prefix in the US for area code with something like `tel ~ +1206`

**Comment by jlev** [comment]
Thanks, I tried to parse through the lexer code for awhile to figure that out...

**Comment by rowanseymour** [comment]
We now use a regex to determine if something could be a phone number and then clean it up if so
