### ISSUE TITLE
Add support for m.me referrals for Facebook

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#592]
Facebook has added support for shortened m.me links to create links to start a chat with a bot:
   https://developers.facebook.com/docs/messenger-platform/referral-params

Users can add a `?ref=params` to the m.me link and Facebook will notify via the webhook what that referral id was.

Right now we support a few different Facebook referrals systems (see https://github.com/nyaruka/rapidpro/blob/master/temba/channels/handlers.py#L2310), but not this one and it seems to be gaining traction so would be good to add.

Changes needed:
- [ ] Add support for both referral and postback support to handlers.py (https://github.com/nyaruka/rapidpro/blob/master/temba/channels/handlers.py#L2310)
- [ ] Adapt current Facebook referral triggers to make the referral id optional as a catchall (IE, if there isn't a trigger that catches that specific referrer id, then use the trigger with no referrer id, also validate there can only be one) (https://github.com/nyaruka/rapidpro/blob/master/temba/triggers/views.py#L297)
- [ ] When triggered, pass the actual referrer id to the triggered flow in `extra`. This lets a catch all referrer trigger split or save the referrer id for later use. (https://github.com/nyaruka/rapidpro/blob/master/temba/triggers/models.py#L255)

We'll also want to update the Facebook claim page to make sure people subscribe to `messaging_referrals` events so they get passed to us.

**Comment by nicpottier** [comment]
@johncordeiro This would be a great task for you guys to take on!

**Comment by cbunicef** [comment]
Happy to help with testing on this!

**Comment by cbunicef** [comment]
Is it possible to build this as a universal handler for `extra`? There are other uses for information that's sent through postback (from the first message as well as later messages).

eg, FB passes info on ad attribution in the first postback:
https://developers.facebook.com/docs/messenger-platform/guides/ads#adattribution

**Comment by norkans7** [comment]
@johncordeiro any progress on this?

**Comment by johncordeiro** [comment]
@norkans7 next week we will create the PR for this.

**Comment by cbunicef** [comment]
Hi all, any progress on this? We have a few good opportunities to use this coming up, the soonest next week.

**Comment by johncordeiro** [comment]
Hey @cbunicef, it's in progress at the moment: https://github.com/ilhasoft/rapidpro/tree/feature/facebook-ref. The PR is coming ASAP.

**Comment by cbunicef** [comment]
Is this ready to go? If so, how can I use it within RapidPro?
