### ISSUE TITLE
USSD Menu: Change rule to allow saving if above character limit

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#595]
Hi,

The character count for the text pane ("Add text") on a "Wait for USSD Menu" includes characters used in functions e.g. @(DATEDIF("02-26-2015", "02-26-2016", "M")) counts as 43 characters.

In our use cases, this is problematic as we often have insufficient character count to insert the desired menu text with functions.

As possible solution: change the rule on the character count to display a warning when in excess of character limit, but still allow the user to save the inputted menu text.

I'm not sure what the downstream implications would be in the event that a menu is created that exceeds the maximum (after parsing functions).

Thoughts?

**Comment by nicpottier** [comment]
Agree that this should be a warning rather than a hard limit, would take a PR for it for sure.

**Comment by RichardHeslopZA** [comment]
@nullcode Is this something you can possibly include in https://github.com/rapidpro/rapidpro/pull/588 ?

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
