### ISSUE TITLE
Retry failed outgoing calls like we do messages

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#599]
Currently when we receive a failure in sending a message, we retry up to three times with backdowns. The first retry 5 minutes after the initial failure, then 10 minutes later if that fails again, then 15 minutes later.

We do not do any kind of retrying when we receive a callback for an outgoing call, though it seems a similar strategy would be useful. Currently some installs work around this by having their own handler ahead of ours that takes care of doing those retries.

@ericnewcomer any reason you see for not supporting this?

**Comment by ericnewcomer** [comment]
We should think about this in the context of errors vs missed calls. I'm definitely okay with the same sort of backdown for call start failures (the voice provider was unable to connect the call for one reason or another or the api call failed). In the case of a missed call, maybe that is a bit different where the user would need more granular control over how to retry that (if they don't answer trying in 5 minutes might not be as good as waiting an hour).

So maybe in addition to retrying explicit errors, perhaps voice calls could have a "missed call" flow where they can handle how to follow up or something along those lines.

**Comment by dwilkie** [comment]
Thanks for opening this issue. @ericnewcomer just for clarification, Somleng (AKA the TwiML channel) also supports [Twilio's Call-Status Values](https://www.twilio.com/docs/api/twiml/twilio_request#request-parameters-call-status) so you can make use of `completed`, `busy`, `no-answer` and `failed` to distinguish between the different types of flows.

**Comment by nicpottier** [comment]
@dwilkie And to be clear in your use case you care about retries in the `failed` case or are you more trying to trigger redials for the `busy` and `no-answer` cases?

**Comment by dwilkie** [comment]
@nicpottier  yes for now we care more about retries in the `failed`  case, however as @ericnewcomer said, it's probably good to consider different flows for the `busy` and `no-answer` cases, as these may come up in the future

**Comment by nicpottier** [comment]
This is out on the `app.rapidpro.io` servers now.
