### ISSUE TITLE
Create contacts with Facebook profile data

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#603]
Facebook Graph API enables the retrieval of user public profile data (first_name, last_name, profile_pic, locale, timezone, gender). We could fill these information into Contact fields automatically when contacts are created for the first time.

Users could link which contact fields they want to fill in the Facebook Channel settings page (optionally).

**Comment by nicpottier** [comment]
Don't we populate name already for new Facebook contacts?
   https://github.com/rapidpro/rapidpro/blob/master/temba/channels/handlers.py#L2404

For more generic fields I wonder if this might not just be done by a flow using an API call?

**Comment by johncordeiro** [comment]
Yeah, but it would be easier for users to get these generic fields automatically instead of creating triggers and making a webhook call, and RapidPRO already makes this request internally: https://github.com/rapidpro/rapidpro/blob/master/temba/channels/handlers.py#L2410.

**Comment by nicpottier** [comment]
I think we'd want to figure out what a generic way of doing this via a Flow is. Either having a flow that is called when a contact is created (maybe?) or passing these in as extra and leaving it to the flow to set them on the contact or whatnot. In general we don't want to add extra configuration but instead enable more things to happen in flows as that satisfies more general use cases.

So I'd like to have a better story as to how that would work with that paradigm in order to enable this.

**Comment by johncordeiro** [comment]
Some users need to create a "Registration flow" to get basic user data like gender and locale (language), this feature would simplify that. I think that handle these data inside a flow is a good idea, we could pass as `extra` through "Start a conversation" trigger, for example. 

I only worry about how to communicate it to users and not be a hidden feature.

**Comment by JPow** [comment]
Could we make it opt out during the reg flow by giving the user a message that notifies them what we're about to do and they can choose to answer themselves or let us pull it?  We could institute this option across the board at UNICEF.  COs would be very happy saving the user doing it.

**Comment by nicpottier** [comment]
Ya, I think if it is in `extra` then it becomes easy to prompt the user whether they want that stuff copied over then do whatever you'd like from there.

**Comment by johncordeiro** [comment]
hey @nicpottier, can we consider adding the user data on `extra` variable, when a new conversation is started on the Facebook channel and the trigger is called (https://github.com/rapidpro/rapidpro/blob/master/temba/channels/handlers.py#L2644)?

**Comment by nicpottier** [comment]
I think the new way to do this would be `extra` that is available on a trigger, but yes, I still think this is possibly interesting. (other places where it may be used would be the metadata that say Twilio includes in messages) Would be a big task though.

**Comment by johncordeiro** [comment]
This is not supported anymore according to new Facebook policy.
