### ISSUE TITLE
Improve Twilio / TwiML Channel Recording functionality

### ISSUE THREAD

**Issue by dwilkie** [rapidpro/rapidpro#604]
Reading through the [TwiML documentation for Record](https://www.twilio.com/docs/api/twiml/record#attributes-action-parameters) they describe the following for the `RecordingUrl` request parameter.

```
The URL of the recorded audio. The recording file may not yet be accessible when the 'action' callback is sent. Use recordingStatusCallback for reliable notification on when the recording is available for access.
```

However looking at the [implementation](https://github.com/rapidpro/rapidpro/blob/master/temba/ivr/views.py#L93) in RapidPro, it fetches the recording immediately after receiving the `RecordingUrl` request parameter.

We're adding [Record functionality to Somleng](https://github.com/dwilkie/adhearsion-twilio/issues/19) so the current implementation will be an issue for both Twilio and Somleng.

**Comment by nicpottier** [comment]
Looks like we currently try to fetch this 4 times with 250ms sleeps if we get a 404, so ya, current implementation is a bit janky though will work if Somleng writes that file within a second of making the call. The idea case would be to have Somlen guarantee that URL is valid before calling the action URL.

So yes, handling this slightly differently on the RapidPro side would probably be good but I'm guessing this will probably work with your implementation as is.

**Comment by dwilkie** [comment]
@nicpottier thanks for the clarification. I'm going to describe the technical details of how `<Record/>` is handled in Somleng, and why we can't guarantee that the URL is available before calling the Action URL. Hopefully this will help to illustrate why we need RapidPro to implement this according to the Twilio Spec.

When Somleng receives the `<Record/>` verb it sends a command to FreeSWITCH via Rayo to start the recording. The recording is then saved to a file inside the FreeSWITCH docker container.

After the record has finished Somleng receives an event with the recording filename (still stored locally on the FreeSWITCH docker instance). It then notifies the [Twilio REST API](https://github.com/dwilkie/twilreapi) that there is a new recording and crucially it sends a request to the Action URL (in the Record TwiML) with the duration and URL of the recording (which is not yet available).

The last part is important because it's part of the call flow. According to the [Twilio Spec](https://www.twilio.com/docs/api/twiml/record), the TwiML received from the request to the Action URL will be executed. Therefore this cannot be delayed as it would result in a delay in the actual call itself.

A short time later (in another process) the actual recording is synced from the Docker container to S3 (using s3 sync). At this point the Recording URL is available for download.

Finally, a short time after this (in another process) [Twilio REST API](https://github.com/dwilkie/twilreapi) will send a Request to the `recordingStatusCallback` URL (if it exists) indicating that the recording is available for download. This request does not expect a TwiML reply and is not part of the call flow.

The flow above is designed for scale and also adheres to the Twilio Spec.

**Comment by nicpottier** [comment]
So how is it expected for callers to behave differently based on a recording value in this model?

Say we add voice recognition and we want to continue the flow differently based on the recording value, how would that be implemented in your model if the recording will never be available before you make the callback?

**Comment by dwilkie** [comment]
Just to be clear, we're following [Twilio's Specification](https://github.com/dwilkie/twilreapi) which clearly states under the `RecordingUrl` parameter:

The URL of the recorded audio. The recording file may not yet be accessible when the `action` callback is sent. Use `recordingStatusCallback` for reliable notification on when the recording is available for access.

To answer your question though I believe the official way to achieve a call flow which changes based on speech recognition, would be to use the Twilio REST API to modify the live call as described [here]( https://www.twilio.com/docs/api/rest/change-call-state).

**Comment by dwilkie** [comment]
Hi @nicpottier just wanted to reply to @ParthaMoman comment on #647 for his (and other's) benefit.

Somleng follows the Twilio Standard here and implements the `RecordingStatusCallback` as described here https://www.twilio.com/docs/api/twiml/record#attributes-action-parameters which specifically says under the `RecordingUrl` parameter.

```
The URL of the recorded audio. The recording file may not yet be accessible when the 'action' callback is sent. Use recordingStatusCallback for reliable notification on when the recording is available for access.
```

RapidPro's current implementation is to try 4 times sleeping for 250 ms if it gets a 404.

There are technical reasons why we can't and won't change Somleng to wait for the recording to be processed before sending the `action` callback to the client. The purpose of the [RecordingStatusCallback](https://www.twilio.com/docs/api/twiml/record#attributes-recording-status-callback) is to let the client know that the recording is finished and ready for download.

I understand the RapidPro team aren't prioritizing this issue, so I suggest that you consider using [Somleng Simple Call Flow Manager]( https://github.com/somleng/somleng-scfm) as a replacement for RapidPro if this is a problem for you.

**Comment by nicpottier** [comment]
Closing as we retry with extreme prejudice now.
