### ISSUE TITLE
Add action for blocking and stopping contacts

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#607]
So people can build flows and hook up keywords to stop people themselves.

(same thing for block?)

Right now you can sort of do something similar by removing people from all groups which is essentially the same thing, but would be nice to keep this consistent.

**Comment by teehamaral** [comment]
Is there something like in progress now? If not, would be welcome a PR?

**Comment by nicpottier** [comment]
Ya, we've talked about this various times. I think the `stop` case is less clear that it would make sense, as stopping is something the contact does, not the administrator. Blocking is more the type of action that administrators do on a contact if they decide not to send to them, so I think that action could make sense. (unlike stop)

I think the only tricky bit there is thinking through what it means to block a contact that is currently in a flow. It seems to be we would probably want to block someone from adding steps to a flow after they have blocked a contact, as we won't send messages (nor should that contact be able to be in a flow after being blocked)

So this would be more complicated than just adding the action, we'd also need to add the editor tweaks to make sure we didn't allow extending the flow beyond this action.

All that to say yes, we would accept a PR but it isn't as simple as it looks. :)

**Comment by teehamaral** [comment]
Yep, I'll open a PR with an initial code soon, so we can discuss it there, right?

**Comment by nicpottier** [comment]
Yep yep.

**Comment by nicpottier** [comment]
Related: #1241

**Comment by rowanseymour** [comment]
Added as set_contact_status action in engine - part of Update Contact in editor
