### ISSUE TITLE
USSD: Support for resuming interrupted sessions (USSD Pull)

### ISSUE THREAD

**Issue by RichardHeslopZA** [rapidpro/rapidpro#609]
This issue is a follow-on to the discussion in #588 .

Currently, the system does not contain functionality to allow a user to resume an interrupted session on a USSD pull channel. The expected user flow would be:
1) Contact is active in a USSD pull flow
2) Contact's session times out or otherwise ends
3) Contact redials USSD number 
4) System detects that Contact was active in a flow (i.e. has not completed most recent flow)
5) System displays a menu offering the option to Continue the flow, or restart the flow (see attached screenshot for example)

![phone](https://user-images.githubusercontent.com/10830046/28659092-6f6a6d7c-72ae-11e7-8818-0cf285029f25.png)

**Comment by nullcode** [comment]
@RichardHeslopZA implemented in #620

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
