### ISSUE TITLE
Invitation Codes Re-Used

### ISSUE THREAD

**Issue by mracter** [rapidpro/rapidpro#615]
Invitation links to the same email address and the same organisation were re-used. Once an invitation link had been used to register an account, the same link will be re-used if the same email address is removed and re-added, or reinvited to the same organisation.

Although the impact of this vulnerability is mitigated by invitation links only being valid if it is associated with a pending invitation, the re-use of invitation secrets do increase the temporal attack surface of an invitation link. Attackers could use this knowledge to guess the static invitation code associated with an organisation and an email, and race the legitimate recipient of the invitation to registering an account on an organisation, thereby gaining access to sensitive information.

The impact of this vulnerability could be further augmented by the fact that an invitee could enter an email address for their RapidPro account that is different from the email address on which they received the invitation. If the invitation code is compromised, this would allow a threat actor to use the invitation code to register using their own email address.

This issue was found in RapidPro v3.0.136p4 during a routine security assessment.

**Comment by ericnewcomer** [comment]
Interesting find @mracter, would you guys be willing to provide PR with a fix for this?
