### ISSUE TITLE
Put error body into @extra for further processing on endpoints that return helpful failure detail

### ISSUE THREAD

**Issue by chris-erickson** [rapidpro/rapidpro#616]
Looking to find a solution for hitting endpoints that don't always return a 200, yet that 4XX is actionable within flows.  For example, hitting the endpoint with missing keys in the query string parameters technically should not return a 200 with a dictionary indicating a failed status/error message.  We've essentially done this, but it breaks the web and results in mistakes as developers try to _Do The Right Thing_ when building endpoints for RapidPro.

I think that the logging of the error needs to begin [here](https://github.com/rapidpro/rapidpro/blob/3d9008da2eaddbf6010dd73e177781e3ccd3682c/temba/api/models.py#L328-L331) but I'm not sure how one would go about sticking the response into `@extra`.

Appreciate the help!

/cc @nicpottier @putorti

**Comment by norkans7** [comment]
@chris-erickson that is the right direction to update the @extra values you will need to use `FlowRun.update_field` as done [above]  (https://github.com/rapidpro/rapidpro/blob/3d9008da2eaddbf6010dd73e177781e3ccd3682c/temba/api/models.py#L322) in the 200 status code case, the 400 response should have a valid JSON response body

**Comment by putorti** [comment]
Any luck on this one?
