### ISSUE TITLE
Invalid file error when importing campaigns

### ISSUE THREAD

**Issue by codenonprofits** [rapidpro/rapidpro#618]
An invalid file error is returned by importing the JSON of the campaigns that send text messages on organizations that have more than one language.

![screen shot 2017-08-15 at 22 55 07](https://user-images.githubusercontent.com/30082655/29344243-d12ceb94-820c-11e7-97ef-de9cb18a41fc.png)

JSON example:
[sandbox.json.zip](https://github.com/rapidpro/rapidpro/files/1226858/sandbox.json.zip)

**Comment by codenonprofits** [comment]
Did anyone can to reproduce this issue?

**Comment by Hitman23** [comment]
This is the error that I get from my logs.

Please call analytics.init(secret) before calling analytics methods.
ERROR 2018-09-21 12:47:17,877 views 17301 140150909101888 Exception on app import: Must include translation for base language
Traceback (most recent call last):
  File "/var/www/rapidpro/temba/orgs/views.py", line 502, in form_valid
    org.import_app(data, self.request.user, self.request.branding['link'])
  File "/var/www/env/rapidpro_prod/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/www/rapidpro/temba/orgs/models.py", line 388, in import_app
    Campaign.import_campaigns(data, self, user, same_site)
  File "/var/www/rapidpro/temba/campaigns/models.py", line 136, in import_campaigns
    base_language=base_language)
  File "/var/www/rapidpro/temba/campaigns/models.py", line 287, in create_message_event
    flow = Flow.create_single_message(org, user, message, base_language)
  File "/var/www/rapidpro/temba/flows/models.py", line 253, in create_single_message
    flow.update_single_message_flow(message, base_language)
  File "/var/www/rapidpro/temba/flows/models.py", line 1138, in update_single_message_flow
    raise ValueError("Must include translation for base language")
ValueError: Must include translation for base language

**Comment by nicpottier** [comment]
This sounds like it is importing a newer flow into an older installation, which is not really supported. Please reopen with the import file and the version of RapidPro being imported into if not.

**Comment by cromulus** [comment]
Hey, so... I just upgraded my rapidpro instance, and the migration failed. Since it wasn't the first time that's happened to me, I exported the flows before upgrading and discovered that the flows aren't compatible across versions...

**Comment by rowanseymour** [comment]
@cromulus older exports/imports should always be importable in a newer installation - you just obviously can't go the other direction and import a newer export into an older installion. We have migrations which should bring any export forward to the latest (non-new-editor) version which is 11.12. If that's not working then maybe you've run into a bug but it certainly should work.

**Comment by nicpottier** [comment]
Just to make sure, @cromulus when you say export you mean flow definitions or exporting your raw DB?
