### ISSUE TITLE
USSD: subflows shouldn't start new sessions

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#622]
I'm not sure if subflows are supported in USSD flows as there doesn't appear to be a test for it - but it seems that a subflow ruleset will cause a new USSD session to be created rather than spawning a child run in the same session.

example flows: [ussd_subflow.json.zip](https://github.com/rapidpro/rapidpro/files/1253013/ussd_subflow.json.zip)

**Comment by nullcode** [comment]
@rowanseymour this might be the test you are looking for https://github.com/rapidpro/rapidpro/blob/1c4434b32ca06adad5e0739c0cd8a57d6d5f4b00/temba/ussd/tests.py#L753

**Comment by rowanseymour** [comment]
@nullcode that's triggering a contact in a different flow (if I recall right it's not even a USSD flow). So it's an example of where we'd expect to spawn a new session anyway. What we don't have is a subflow test which runs the same contact through a subflow and back into the parent.

**Comment by nullcode** [comment]
@rowanseymour oh, I see, I think I wasn't familiar with the concept of subflows then. Can it be that it was introduced later than the USSD functionality?

**Comment by rowanseymour** [comment]
@nullcode I don't think so. It's the difference between `StartFlowAction` and `TriggerFlowAction`, and I guess we've made it this long without support for `StartFlowAction` because there's a limited number of users using USSD.

**Comment by nullcode** [comment]
@rowanseymour interesting, well I dont see it in my first sketches of the actions and rulesets when I started working on USSD in April 2016 and as I see from commit timestamps subflows started appearing August 2016 which might be the reason it slipped through my radar.

**Comment by rowanseymour** [comment]
@nullcode my recollection of subflow history is sketchy but StartFlowAction has definitely been around for a while. Perhaps that newer subflow stuff was the ability of rulesets to spawn subflows? That's arguably the more useful subflow case because it allows the parent flow to be properly resumed and split on the exit type of the child flow.

**Comment by nullcode** [comment]
@rowanseymour yeah, that's what I think. I'm not sure how hard it is to add support for this (doesn't sound so difficult), but first maybe we could filter out this ruleset type and then address the issue later in a PR?

**Comment by rowanseymour** [comment]
Yeah let's definitely disable these kind of rulesets on USSD flows for now.

**Comment by RichardHeslopZA** [comment]
@rowanseymour We are currently in a situation where our USSD flows are becomingly unmanageably large & complex within a single flow. We had hoped that we could improve this situation by splitting the oversized USSD flow into multiple child flows and calling the child flows when needed.

If I follow this thread correctly: this functionality does not currently work? I.e. we cannot currently use USSD subflows from a parent USSD flow with the active contact?

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
