### ISSUE TITLE
RTL support in editor and compose boxes

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#63]
Text input in the flow editor which uses variable substitution within RTL languages can end up with improper ordering. We need to detect when the current language is RTL and apply the appropriate dir attribute for the input.

**Comment by rowanseymour** [comment]
Moved to https://github.com/nyaruka/floweditor/issues/413

**Comment by rowanseymour** [comment]
Re-opening this to track for next milestone
