### ISSUE TITLE
Chatbase failures shouldn't cause message sending failure

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#634]
Currently if sending logs from sending messages to Chatbase fails, an exception is thrown which causes the message sending to appear to have errored. RapidPro then retries the message 3 times until it's marked as failed.

We should just log the chatbase error and ensure it doesn't cause the message to fail

cc @teehamaral

**Comment by teehamaral** [comment]
Ok, we'll fix it and a PR will be sent soon.

**Comment by rowanseymour** [comment]
Chatbase integration now occurs in https://github.com/nyaruka/courier
