### ISSUE TITLE
Currency values, e.g. '$250', aren't parsed to numbers by numeric response rules

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#636]
Currently, something like '$250 > 200' resolves to false.

**Comment by ericnewcomer** [comment]
What about:

@flow.amount > 200

Where "Amount" is a has a number rule that captured $250?

**Comment by ycleptkellan** [comment]
Sorry, the '$250' operand in my comment above is a flow field. Separately, the 'has a number' rule doesn't capture $250 though it would capture something '$ 250'.

**Comment by ericnewcomer** [comment]
Okay, so I built a repro case to show that the number extraction is indeed not working in this case. See attached.

<img width="1104" alt="screen shot 2017-09-18 at 12 25 07 pm" src="https://user-images.githubusercontent.com/211652/30555207-93b1102c-9c6c-11e7-8d8d-f53bce99a697.png">


[monies.json.zip](https://github.com/rapidpro/rapidpro/files/1311602/monies.json.zip)

**Comment by ycleptkellan** [comment]
Ah, thanks @ericnewcomer! Didn't think to ZIP the flow, good to know for future issues 👍
