### ISSUE TITLE
Recordings for multi-language IVR not imported

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#64]
When exporting a multi-language IVR flow with localized recordings, the recordings are not pulled in on import. We do import the primary language, so this issue applies specifically to multi-language flows only.

It's important to note that audio recordings are not guaranteed to come across between exports / imports as the original recordings can be removed at any time by the flow owner and the recordings themselves are not embedded in the export. However, if they are still available at the time of import, they should be pulled in.

**Comment by nicpottier** [comment]
I believe this is fixed via having absolute URLs in new imports.
