### ISSUE TITLE
Contacts interacting w/ Twilio channels are no longer placed in the reserved 'Stopped' group when they opt-out

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#640]
To reproduce, add a Twilio channel and have your contact send one of STOP, STOPALL, UNSUBSCRIBE, CANCEL, END or QUIT. Send the contact another message.

**Comment by nicpottier** [comment]
I don't think we add them to the stop group until we try to send to them.

**Comment by ycleptkellan** [comment]
Sorry, updated that first comment. In my case, the contact isn't being added to that group when sent a message from a flow or broadcast.

**Comment by nicpottier** [comment]
Ah shoot, that's a courier regression, let me try to push a fix.

**Comment by nicpottier** [comment]
Fixed in https://github.com/nyaruka/courier/pull/49
