### ISSUE TITLE
Flow editor not loading

### ISSUE THREAD

**Issue by bertplunkett** [rapidpro/rapidpro#648]
Hi all,

I've used RapidPro in the past, however recently I installed it from scratch and the flow editor is not working because of a JS error. Tried it on different browsers (Safari, Chrome, Firefox), all latest versions, under macOS High Sierra (10.13). The logged error message varies from browser to browser but they all refer to the same thing:

Safari:

	[Error] Error: Attempted to assign to readonly property.
	fetch@http://localhost:8000/sitestatic/CACHE/js/services.e0e911588885.js:1736:19
	init@http://localhost:8000/sitestatic/CACHE/js/controllers.d5ed049b6923.js:193:26
	$parseFunctionCall@http://localhost:8000/sitestatic/bower/angular/angular.js:12404:23
	pre@http://localhost:8000/sitestatic/bower/angular/angular.js:22468:20
	invokeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:8258:15
	nodeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7747:23
	compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7117:23
	compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:24
	compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:24
	compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:24
	publicLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:6996:45
	http://localhost:8000/sitestatic/bower/angular/angular.js:1457:27
	$apply@http://localhost:8000/sitestatic/bower/angular/angular.js:14565:28
	bootstrapApply@http://localhost:8000/sitestatic/bower/angular/angular.js:1455:21
	doBootstrap@http://localhost:8000/sitestatic/bower/angular/angular.js:1453:20
	angularInit@http://localhost:8000/sitestatic/bower/angular/angular.js:1367:14
	http://localhost:8000/sitestatic/bower/angular/angular.js:26304:16
	fire@http://localhost:8000/sitestatic/bower/jquery/jquery.js:2913:35
	fireWith@http://localhost:8000/sitestatic/bower/jquery/jquery.js:3025:11
	ready@http://localhost:8000/sitestatic/bower/jquery/jquery.js:398:24
	completed@http://localhost:8000/sitestatic/bower/jquery/jquery.js:93:15 – 
		"<div ng-controller=\"FlowController\" ng-show=\"flow\" ng-mousemove=\"mouseMove($event)\" ng-init=\"init()\" id=\"ctlr\" class=\"ng-scope\">"
		(anonymous function) (angular.js:8596)
		invokeLinkFn (angular.js:8260)
		nodeLinkFn (angular.js:7747)
		compositeLinkFn (angular.js:7117)
		compositeLinkFn (angular.js:7120)
		compositeLinkFn (angular.js:7120)
		compositeLinkFn (angular.js:7120)
		publicLinkFn (angular.js:6996)
		(anonymous function) (angular.js:1457)
		$apply (angular.js:14565)
		bootstrapApply (angular.js:1455)
		doBootstrap (angular.js:1453)
		angularInit (angular.js:1367)
		(anonymous function) (angular.js:26304)
		fire (jquery.js:2913)
		fireWith (jquery.js:3025)
		ready (jquery.js:398)
		completed (jquery.js:93)

Chrome:

	TypeError: Assignment to constant variable.
		angular.js:11655
		at Flow.fetch (http://localhost:8000/sitestatic/CACHE/js/services.e0e911588885.js:1736:18)
		at ChildScope.$scope.init (http://localhost:8000/sitestatic/CACHE/js/controllers.d5ed049b6923.js:193:21)
		at $parseFunctionCall (http://localhost:8000/sitestatic/bower/angular/angular.js:12404:18)
		at ChildScope.$eval (http://localhost:8000/sitestatic/bower/angular/angular.js:14466:28)
		at pre (http://localhost:8000/sitestatic/bower/angular/angular.js:22468:15)
		at invokeLinkFn (http://localhost:8000/sitestatic/bower/angular/angular.js:8258:9)
		at nodeLinkFn (http://localhost:8000/sitestatic/bower/angular/angular.js:7747:11)
		at compositeLinkFn (http://localhost:8000/sitestatic/bower/angular/angular.js:7117:13)
		at compositeLinkFn (http://localhost:8000/sitestatic/bower/angular/angular.js:7120:13)
		at compositeLinkFn (http://localhost:8000/sitestatic/bower/angular/angular.js:7120:13) 
		<div ng-controller="FlowController" ng-show="flow" ng-mousemove="mouseMove($event)" ng-init="init()" id="ctlr" class="ng-scope">

Firefox:

	Error: invalid assignment to const `Flow'
		angular.js:11655:18
		fetch@http://localhost:8000/sitestatic/CACHE/js/services.e0e911588885.js:1736:13
		$scope.init@http://localhost:8000/sitestatic/CACHE/js/controllers.d5ed049b6923.js:193:16
		$parseFunctionCall@http://localhost:8000/sitestatic/bower/angular/angular.js:12404:15
		$eval@http://localhost:8000/sitestatic/bower/angular/angular.js:14466:16
		pre@http://localhost:8000/sitestatic/bower/angular/angular.js:22468:9
		invokeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:8258:9
		nodeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7747:11
		compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7117:13
		compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:13
		compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:13
		compositeLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:7120:13
		publicLinkFn@http://localhost:8000/sitestatic/bower/angular/angular.js:6996:30
		bootstrapApply/<@http://localhost:8000/sitestatic/bower/angular/angular.js:1457:11
		$eval@http://localhost:8000/sitestatic/bower/angular/angular.js:14466:16
		$apply@http://localhost:8000/sitestatic/bower/angular/angular.js:14565:18
		bootstrapApply@http://localhost:8000/sitestatic/bower/angular/angular.js:1455:9
		invoke@http://localhost:8000/sitestatic/bower/angular/angular.js:4203:14
		doBootstrap@http://localhost:8000/sitestatic/bower/angular/angular.js:1453:5
		bootstrap@http://localhost:8000/sitestatic/bower/angular/angular.js:1473:12
		angularInit@http://localhost:8000/sitestatic/bower/angular/angular.js:1367:5
		@http://localhost:8000/sitestatic/bower/angular/angular.js:26304:5
		fire@http://localhost:8000/sitestatic/bower/jquery/jquery.js:2913:10
		fireWith@http://localhost:8000/sitestatic/bower/jquery/jquery.js:3025:7
		ready@http://localhost:8000/sitestatic/bower/jquery/jquery.js:398:3
		completed@http://localhost:8000/sitestatic/bower/jquery/jquery.js:93:3
		<div ng-controller="FlowController" ng-show="flow" ng-mousemove="mouseMove($event)" ng-init="init()" id="ctlr" class="ng-scope">

I tried the version currently on [textit.in](https://textit.in) and it's working properly (as well as our older setups). Someone on the discussion group recently posted the same issue (https://groups.google.com/forum/#!topic/rapidpro-dev/4yWN6iiH25E).

Any idea? conflicting versions of JS components maybe?

**Comment by idevsoftware** [comment]
This seems to be an issue with the latest version of CoffeeScript available on npm (2.something). Try downgrading to an earlier version, the one currently available on Debian 9 (CoffeeScript 1.10.0) works correctly.
