### ISSUE TITLE
Add call forwarding as an option in IVR flows

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/rapidpro#65]

**Comment by citizenrich** [comment]
I want to revisit this. There needs to be some flexibility to forward calls, for example to other Twilio numbers, such as to use call queues for agent handling of calls and other as yet unsupported IVR/voice features.

**Comment by nicpottier** [comment]
Definitely no argument that the ability to "call out" to another number makes a lot of sense.

**Comment by citizenrich** [comment]
I'm just going to reiterate that if this eventually makes it on a roadmap it would be great. It can provide for directing calls to call center agents, or conference calls, or to join live audio events.

**Comment by rowanseymour** [comment]
6 years later.. we added this!

**Comment by citizenrich** [comment]
Thanks @rowanseymour! It seems that if you wish hard enough that GitHub issue dreams do come true. We (IntraHealth) work regularly with RapidPro, so hope to try it out at some point.

**Comment by nicpottier** [comment]
All it takes is enough hope! Hope you are well Richard!
