### ISSUE TITLE
Inconsistent Migration History

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#654]
This commit https://github.com/nyaruka/rapidpro/commit/1d7a9cc566e96d2af0d27cf6e8b08dc2e0327798 is causing error on django migrations:

`django.db.migrations.exceptions.InconsistentMigrationHistory: Migration orgs.0030_install_triggers is applied before its dependency channels.0080_fix_sql_func on database 'default'.`

**Comment by rowanseymour** [comment]
Is this on a clean database or particular branch of yours? We haven't had this problem on our boxes or building clean databases.

**Comment by teehamaral** [comment]
I'm using a particular branch, I'm going test in a clean database

**Comment by teehamaral** [comment]
In a clean database, it works well. But once `0030_install_triggers.py` already was ran, why to put `channels.0080_fix_sql_func ` and `msgs.0076_install_triggers` as dependence? I think that was causing inconsistency on django migration.

**Comment by rowanseymour** [comment]
Yeah good point - can you try https://github.com/rapidpro/rapidpro/pull/656 and see if it fixes it for you

**Comment by teehamaral** [comment]
@rowanseymour Yes, this PR #656 fixes it.

**Comment by rowanseymour** [comment]
Ok great - have merged that

**Comment by teehamaral** [comment]
Thanks!
