### ISSUE TITLE
Skype for Business channel

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/rapidpro#657]
Will need to review the MS docs in more detail to confirm, but would be neat to support Skype for Business. At UNICEF HQ, we've ditch all of our POTS phones in favor of SfB and most of our other offices will likely follow suit.. making SfB an attractive channel for engaging UNICEF staff

https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview
https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-overview

**Comment by rowanseymour** [comment]
Work started on a Skype bot channel at https://github.com/rapidpro/rapidpro/pull/646

**Comment by ewheeler** [comment]
@rowanseymour yup! awesome to see that contribution! 

just wanted to put a separate issue for S4B as I suspect Skype For Business will (at least) need a different claim flow than Skype.. specifically the process around a Tenant Administrator registering the bot via powershell cmdlet (?!) which presumably won't be necessary for non-enterprise Skype

https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#adding-a-bot-to-skype-for-business

**Comment by ewheeler** [comment]
Closing because Microsoft has announced end of life for S4B

https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Skype-for-Business-Online-to-Be-Retired-in-2021/ba-p/777833

**Comment by nicpottier** [comment]
Hah, does that mean that Skype will finally mean Skype again?

**Comment by ewheeler** [comment]
Perhaps? If we are unlucky, maybe Skype will mean Teams now?

FYI- Here is an excellent overview of MS product terminology:
https://news.ycombinator.com/item?id=14160809
