### ISSUE TITLE
Can't delete Contact

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#663]
This is the error thrown:
```
raven.min.js:2 Uncaught TypeError: Cannot read property 'attr' of undefined
    at HTMLAnchorElement.<anonymous> ((index):3817)
    at HTMLAnchorElement.e (raven.min.js:2)
    at HTMLAnchorElement.dispatch (jquery.js:4676)
    at HTMLAnchorElement.elemData.handle (jquery.js:4360)
    at Object.trigger (jquery.js:4594)
    at Object.e.event.trigger (jquery-migrate.min.js:2)
    at HTMLAnchorElement.<anonymous> (jquery.js:5119)
    at Function.each (jquery.js:590)
    at e.fn.init.each (jquery.js:237)
    at e.fn.init.trigger (jquery.js:5118)
```

To replicate, launch a brand new rapidpro instance, create a contact, and attempt to delete the contact.

The same error is thrown when you attempt to delete a flow as well.

**Comment by ericnewcomer** [comment]
Would be helpful to see the underlying error here. This stacktrace looks like an unconfigured sentry instance failing to report what is the actual issue.

**Comment by cromulus** [comment]
The error is that there is no href on the delete button and it fails here:
```$("a.posterize").click(function(event){
    event.preventDefault();
    event.stopPropagation();

    var href = $(this).attr("href");
    var url = $.url(href);

    $("#posterizer").attr("action", url.attr("path"));

    for (var key in url.param()){
      $("#posterizer").append("<input type='hidden' name='" + key + "' value='" + url.param(key) + "'></input>");
    }
```

this is in base.html:34 and frame.haml:370

The offending delete button lives here:  contact_read.haml:210
```%a#delete-form.posterize{href:'{% url "contacts.contact_delete" contact.pk %}'}```

My guess is that this is related to the fact that jquery.url.js is included at /js/libs/jquery.url.js in both frame.haml and base.html but doesn't exist in the repository and throws a 404.

**Comment by cromulus** [comment]
and yes, I'm going to try to get raven stacktraces in JS as well. Need to define both the private DSN and public DSN and then expose the public one to JS....
See this branch for progress: https://github.com/cromulus/rapidpro/tree/raven-config
