### ISSUE TITLE
IVR leave a recording/audio stream

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#665]
Could be used as a voicemail or as a way to pass the audio on to a voice recognition platform

**Comment by ericnewcomer** [comment]
There is a capture recording action you can use in IVR flows, are you referring to something different?

**Comment by cromulus** [comment]
Correct. I'd like the ability to forward that recording to a service in
order to receive back text

**Comment by ericnewcomer** [comment]
Yup, that can be done, you can access the url for the resulting recording (ie, @flow.my_recording) and include that in a webhook call.
