### ISSUE TITLE
Use Facebook NLP

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#672]
Seems useful if RapidPro could use whatever is being passed over by this:

<img width="929" alt="screen shot 2017-11-03 at 12 19 12 pm" src="https://user-images.githubusercontent.com/82857/32392000-391af058-c091-11e7-8f0c-0af91ca4cbbb.png">

**Comment by cromulus** [comment]
I currently just webhook out to [wit.ai](https://wit.ai) or my own [duckling](https://github.com/facebook/duckling) instance when I need NLP

**Comment by putorti** [comment]
Ask @ericnewcomer we can’t afford to make webhook calls out with our volume, if Facebook already provides data “for free”, it would be especially helpful to us to be able to use it.

**Comment by nicpottier** [comment]
I think the current thinking is probably plugging in providers such as wit.ai, but agree maybe this would be interesting too, just a lot less generically useful as having full NLP integration like #832
