### ISSUE TITLE
Move used credits to be a SquashableModel

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#674]
Calculating number of credits on a TopUp gets expensive as it is a count on the Msg table. Currently we work around this by caching the TopUp that is currently having credits deducted from it in Redis, but for various reasons this can drift.

We solve the problem of big counts elsewhere in the system by using a SquashableModel pattern that Rowan added. Basically we do a single row insert per count we want to manage, then squash these periodically into larger counts. This allows for high frequency, unblocking management of number of counts while retaining fast queries for the sum. (an example of this is `FlowRunCount`)

Let's move credits to use the same model.

**Comment by ericnewcomer** [comment]
@dodobas happy to pair on this when you have a chance

**Comment by dodobas** [comment]
this was already a SquashableModel, however, related bugs were fixed by https://github.com/nyaruka/rapidpro/pull/1575
