### ISSUE TITLE
Branding in Django settings - settings post_processing

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#678]
When using branding we need to do updates to ALLOWED_HOSTS in order to accept requests for domains/hosts defined by brand configuration. At the moment we expect the user to be aware of this during the deployment, since user is the one who defines brand configuration.

Ideally we should make this automatic, and one way to do it is to perform any post_branding configuration changes in a settings file by splitting settings file in multiple files. For example: settings.py is the main file that would build (import) settings from all other files:
base_settings -> common_settings -> user_settings -> post_processing -> settings.py

Initially the user_settings file could be empty, but still included in the *build settings pipeline*. the *post_processing* settings file could also do all sorts of sanity checks before building settings.

**Comment by nicpottier** [comment]
Closing as I think the real solution here is to implement branding at a code level, not a configuration level.
