### ISSUE TITLE
USSD channel duplicated on channel claim template

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#679]
Probably a wrong merge has caused this error

1 - https://github.com/rapidpro/rapidpro/blob/master/templates/channels/channel_claim.haml#L263
2 - https://github.com/rapidpro/rapidpro/blob/master/templates/channels/channel_claim.haml#L281

**Comment by norkans7** [comment]
This has been fixed on Nyaruka fork https://github.com/nyaruka/rapidpro/commit/4dc7d494d0afbeafdbbe4653a359b4fa8c2c7477#diff-da3f6aba36b8090d5b965f792c3d4518

**Comment by rowanseymour** [comment]
We'll try to get our fork upmerged today hopefully

**Comment by rowanseymour** [comment]
Fix should be merged in now
