### ISSUE TITLE
Remove from All Groups Action

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#68]
It may be nice to have an action that removes a user from every single group without having to enumerate them one at a time. This is especially true in cases where groups are actually dynamic.

See: https://textit.uservoice.com/admin/tickets/404

**Comment by ewheeler** [comment]
@nicpottier are you thinking that this would be a separate action? or some kind of button on the existing 'Remove from Groups' dialog and an additional execution mode for [```DeleteFromGroupAction```](https://github.com/rapidpro/rapidpro/blob/master/temba/flows/models.py#L3750) that selects all ```ContactGroup```s for the org?

**Comment by nicpottier** [comment]
Could be part of the same action, though the UI seems slightly tricky since we use an omnibox there I think.
