### ISSUE TITLE
Shouldn't send topup expiration email if topups remaining

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#687]
Currently we send an email before a topup expiring regardless of whether the user will have credits after that topup expires.

We should:

1) not send that email if their service won't be interrupted
2) not talk about how many credits are expiring because that's irrelevant

**Comment by dodobas** [comment]
In which cases do we want to send an email about expiring topups? Never ?

also noticed that text and html email templates have diverged a bit, https://github.com/rapidpro/rapidpro/blob/master/templates/orgs/email/alert_email.txt and https://github.com/rapidpro/rapidpro/blob/master/templates/orgs/email/alert_email.html, html checks for `allow_signups` should we update the text email template ?

**Comment by nicpottier** [comment]
I think the case we want to avoid is creating alarm when there is no need for one. So if the expiration will not cause their service to be interrupted (because there is another topup that has credits with an expiration farther in the future) then we don't send the email.

Yes, those two templates should be the same.

**Comment by nicpottier** [comment]
Fixed.
