### ISSUE TITLE
Double check that we are using select_related on the orgs__country and not loading gemetry fields if we don't need

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#689]
* loading a geometry field can be expensive as it needs to parse large binary blobs

**Comment by nicpottier** [comment]
@dodobas can you double check this?

**Comment by dodobas** [comment]
this is done, the default manager on AdminBoundary is `NoGeometryManager` that defers `geometry` and `simplified_geometry` (https://github.com/nyaruka/rapidpro/blob/0af99cecaa6e0c0b4e8184f8c3a9c839f5ea9624/temba/locations/models.py#L69)

**Comment by nicpottier** [comment]
👍
