### ISSUE TITLE
Consider whether we should more aggressively end flows when someone joins another flow

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#69]
Currently being part of a flow masks the previous flows you were in (until you expire from them).

It may be clearer to end users if we explicitly remove users from flows when they are started down another one, at least for the trigger and broadcast case. (perhaps current behavior is ok for the case of "Start Flow" action)

**Comment by ericnewcomer** [comment]
We now exit flows when starting new ones unless they are initiated by a subflow ruleset.
