### ISSUE TITLE
Adding a non-existent custom field fails silently

### ISSUE THREAD

**Issue by alexmuller** [rapidpro/rapidpro#690]
When I create a contact with a custom field that doesn't exist:

```
POST /api/v2/contacts.json
{
  'urns': ['tel:+123456'],
  'fields': {'new_field': 'true'}
}
```

I get a successful response but with the field ignored:

```
{
  'uuid': '123',
  'urns': ['tel:+123456'],
  'fields': {}
}
```

It would be much more clear if this returned a 400 Bad Request indicating that the field doesn't exist.

Thanks!

**Comment by rowanseymour** [comment]
It definitely looks like it should be validating fields: https://github.com/rapidpro/rapidpro/blob/master/temba/api/v2/serializers.py#L407

Maybe contact.set_field(..) is failing for some other reason - can you check on that?

**Comment by alexmuller** [comment]
Ah, in that case this is probably related to the fact that I can't get the field to save even when I provide it correctly: https://groups.google.com/d/msg/rapidpro-dev/7gYkPNgJs2U/75bftzABBAAJ

I'll try and have a look at what's going on here, thanks!

**Comment by cromulus** [comment]
Having the same issue...

**Comment by ericnewcomer** [comment]
I was not able to reproduce this. I know the create logic around fields changed since this was filed. If you see this happening still, feel free to reopen.

Using the included example, the api returned the following:
```
HTTP/1.0 400 Bad Request
{
    "fields": [
        "Invalid contact field key: new_field"
    ]
}
```
