### ISSUE TITLE
Adding a contact via API doesn't save urns

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#693]
```
POST /api/v2/contacts.json
{
 'name':'Ben Haggarty',
  'urns': ['tel:+123456'],
  'groups':[]
}```

results in:
``
{
  'uuid': '123',
  'name': 'Ben Haggarty',
  'urns': [],
  'fields': {}
}

Any thoughts?

**Comment by dodobas** [comment]
URNs are stripped if the Org is anonymous, can you check if your Org is anonymous ?

**Comment by cromulus** [comment]
I don't know what that means... Where would I check if my Org is anonymous?

Seems strange that the API would just drop the most important element of a request silently... if anonymous orgs aren't supposed to be able to create contacts via the API, it should, well, be a bit come explicit about that.

**Comment by cromulus** [comment]
Ahh, found it, have to log in as administrator and it's in the org's configuration.

No, none of my orgs are set to anonymize the phone numbers of contacts within it.

**Comment by cromulus** [comment]
here's the API result from `GET /api/v2/org.json`
```
{"languages"=>[], "credits"=>{"used"=>208, "remaining"=>2157484439}, "timezone"=>"America/New_York", "name"=>"MyOrg", "primary_language"=>nil, "country"=>"US", "date_style"=>"day_first", "anon"=>false}
```

**Comment by cromulus** [comment]
FYI, I am on v3.0.135. Switching to master now and will see what happens.

**Comment by rowanseymour** [comment]
Could be something to do with invalid URNs? `tel:+123456` should be rejected but maybe there's a bug that prevents that coming back as an error response.

**Comment by cromulus** [comment]
upgrading to the latest master branch fixes this issue. I'm going to close this out, but probably means it might be time for a new release? 😉

**Comment by cromulus** [comment]
Just FYI, it breaks with valid phone numbers, just used +123456 as an example.
