### ISSUE TITLE
Audit and manually control database ForeignKey constraints creation

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#694]
When we have high resource contention on the database (many clients, many queries) we get a lot of `ACCESS SHARE` locks which are triggered by SELECT statements which try to read a related table (https://www.postgresql.org/docs/9.4/static/explicit-locking.html)

In order to reduce `ACCESS SHARE` locks we manually removed FK constraints to the problematic table. 

This behavior can be controlled by Django (https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.db_constraint) and we should audit which FK constraints are actually useful and remove the ones which are not.

**Comment by nicpottier** [comment]
I think we are correct on our usage here, some of those locks were red herrings on resist due to misconfiguration of their db.
