### ISSUE TITLE
All flows empty

### ISSUE THREAD

**Issue by rafaelhbrasil** [rapidpro/rapidpro#697]
Hi guys!
I used to have a dev server of rapidpro and it worked fine for a few months. However I had to rebuild my VM and the issue started.

I can open the home page, register a new user and log in. When I access the flows page, there are 3 or 4 example flows. When I open any of them, it's empty! nothing there. no components of my flows...
I've also tried to load a backup from textit and is still empty. The simulator (blue buttom) in the right edge of the page also does nothing. No errors in the logs. 

I've passed over and over through all steps to reconfigure, recreated the VM using both Debian 8, Ubuntu 14 and Ubuntu 16, installed all dependencies and it still doesn't work.
Using last version of postgresql and redis-server (installed through apt-get)

It sems to be an issue on new installations only. Anyone able to reproduce it?

**Comment by rafaelhbrasil** [comment]
Hi!
The doc of rapidpro says the following libs are required (among others):

lessc, the Less compiler.
coffee, the Coffee script compiler.
bower, package manager for javascript libraries.

The problem is that it does not say which version of each one.

using a "npm list"  command inside the rapidpro folder shows the missing versions.

**Comment by JoseCage** [comment]
@rafaelhbrasil I solved this problem installing the dependencies inside the project.

Command 
```bash
npm install
```
