### ISSUE TITLE
Want to have a variable who gives the number of week Between 0 and 52

### ISSUE THREAD

**Issue by AmirSmarty** [rapidpro/rapidpro#698]

**Comment by ycleptkellan** [comment]
e.g. `@(WEEK(date.now))`

**Comment by rowanseymour** [comment]
FYI this was being worked on at one point https://github.com/rapidpro/expressions/pull/7. Would happily merge a working PR for this

**Comment by nicpottier** [comment]
@rowanseymour this seems like a missing piece in goflow expressions that would be an easy add.

**Comment by rowanseymour** [comment]
Agreed. Moved issue there
