### ISSUE TITLE
Feature Request: Call External WebServer/Webhook Post JSON objects

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#702]
Hi!
I would love to be able to POST json objects to an external server. The header options are great, but I don't have the ability to use expressions in them. It would be wonderful to have a little text area that I could use to write expressions to populate the data field of a json request.

Usecase: I want to know how many people are in a household, then the ages for each person in the household, and then populate a json object to send to a web service API which then determines that household's eligibility for benefits.

Creating that json object right now is, as far as I can tell, impossible in the additional headers options.

Thanks!

**Comment by nicpottier** [comment]
Ya, this is crummy. We will be shipping a `v2` version of webhook bodies which will be a more sane JSON body in a week or so.

Plan for v2 engine is to allow arbitrary payloads of json/form encoded/whatevs.. That's implemented but ya, has to wait for that to ship which is a ways out still.

**Comment by cromulus** [comment]
🕺 

Amazing. Thanks!
