### ISSUE TITLE
Feature request: Force directed layouts of flows and/or multi-select of flow objects

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#703]
On occasion, when we haven't quite planned out our flows well, we need to add another object into the middle of a relatively complex flow. This makes the flow either complex and hard to understand or it means we have to individually move elements in order to make the visual display for the flow more comprehensible.

Two potential options:
1) be able to drag the cursor selecting multiple flow objects and move them together as a group.

2) have an "auto-layout" button that would clean up the layout of a flow, using a force directed graph style layout engine: https://bl.ocks.org/mbostock/4062045

Thanks!

**Comment by nicpottier** [comment]
Our new flow editor implements 1) actually and also relays out if you drop something on a node.

We might still do 2) eventually.

New editor is still a ways out, but ya, this is done. :)

**Comment by cromulus** [comment]
Amazing.

I was going to take a stab at the force directed graph auto-layout. If you all think that's a worthwhile endeavor, I'd be happy to take a look.

**Comment by nicpottier** [comment]
Probably not something we'd accept in the short term, let us ship the new editor first and we can revisit. :)

**Comment by cromulus** [comment]
Makes perfect sense.

**Comment by nicpottier** [comment]
New editor takes care of multi-select. Believe @ericnewcomer added some code to do auto layout when we have no layout at all, so may be fairly easy to add that if someone has interest.

**Comment by ericnewcomer** [comment]
Should we close these issues on rapidpro? Seems anything for the editor should be tracked over at https://github.com/nyaruka/floweditor.
