### ISSUE TITLE
Feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#704]
Particularly for handling large tabular data, like messages/contacts, etc.

Could be rather easy to implement and would radically speed up the UI for power users while being totally transparent for everyone else.

**Comment by ycleptkellan** [comment]
agreed, shift-selecting multiple checkboxes would be helpful

**Comment by cromulus** [comment]
Any other thoughts?

I may have some bandwidth to take a crack at this in the next month or two. I was thinking [gmail style keyboard shortcuts](https://support.google.com/mail/answer/6594?co=GENIE.Platform%3DDesktop&hl=en), unless anyone else has strong feelings otherwise.
