### ISSUE TITLE
Update groups blocked by max limit

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#705]
![screenshot](https://user-images.githubusercontent.com/5198870/33720284-3f444f9e-db42-11e7-9267-b351c2dcaf82.png)

When we try to edit a group and there's more than 250 contacts group, we're getting this alert, but I think that the update of the group should be allowed even that exists more than limit.

And just to know a little bit more, why was added a limit to 250 contact groups? What's happen when there's a flow that creates groups dynamically?

Thanks in advance.

**Comment by rowanseymour** [comment]
@teehamaral flows can no longer dynamically create groups - they can still match existing groups by a name expression. The problem with flows creating groups on the fly is that it's too easy for users to accidentally create a new group for every single contact.

We can make the max number of groups configurable if you want to increase it, but you should understand that there are lots of places in the codebase where its assumed that the total number of groups per org is a relatively small number. Increasing it may have performance and UI implications.

**Comment by nicpottier** [comment]
Closing this (with apologies) as I think current behavior is right. We do have some ideas to address the use cases people use that involve tons of groups, will add that issue in a bit.
