### ISSUE TITLE
QuickReplies invisible on Firefox

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#707]
When typing in the QuickReplies input fields on Firefox, the text does not echo. Something goofy with the styling there.

<img width="530" alt="screen shot 2017-12-12 at 9 58 28 am" src="https://user-images.githubusercontent.com/211652/33891168-1f27d0d4-df23-11e7-885a-c30bedf69a90.png">

**Comment by ericnewcomer** [comment]
@teehamaral have you seen this?

**Comment by teehamaral** [comment]
@ericnewcomer Oh, I just saw this now, we'll send a PR fixing it soon.
