### ISSUE TITLE
Prevent contacts being started on multiple runs at same time

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#710]
For example, customer can hit the flow_starts API endpoint with two simultaneous requests and start a contact twice in the same flow (have found an example of this in our logs).

Since we added the new trigger on run.path which disallows changing path on an inactive run, this blows up because creating the second run in Flow.start will deactivate the first run, but the first run will continue to be executed in a different thread.

**Comment by rowanseymour** [comment]
This problem also applies to campaign events. We have an example in RapidPro where there are 2 campaign events scheduled for exactly 1 hour after someone registers.

**Comment by nicpottier** [comment]
This is no longer possible with mailroom / goflow
