### ISSUE TITLE
Allow flows to specify behavior for reconnections on session based flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#712]
We currently have two types of flows which are session based, IVR (voice) and USSD. Both of these share the same problem in that calls can be disconnected halfway through a call due to bad connections or timeouts and we want to allow contacts to reconnect and continue where they left off.

An attempt was made to address this by @nullcode in https://github.com/rapidpro/rapidpro/pull/620, but it was determined that the approach used was incompatible with the way RapidPro flows work. (involved rewinding of flows and history)

As a community we want to come up with what our story is for handling resumptions of session based flows, some general requirements:

1. The solution should maintain the current flow paradigm of waits and explicit behavior. IE, resumption and disconnects should be treated explicitly in a flow and behavior should be defined by the author.

2. Though we should strive in making RapidPro easy to use, our bias should be towards the best experience for the contacts which there are many more of rather than optimizing for authors. This means having a solution which introduces new nodes and connections is acceptable if it allows for more flexibility in an ideal experience for a contact.

3. The solution should work using the same concepts for IVR and USSD so as not to require any special casing in the flow engine across those session types.

Opening this up for discussion for the time being, I'll follow up with some ideas we've been thinking along in the past when discussing this.

@ewheeler @ericnewcomer @rowanseymour

**Comment by asseym** [comment]
Thanks @nicpottier for starting this off. I am also inviting @RichardHeslopZA and team to contribute any ideas that may be important for this design discussion.
