### ISSUE TITLE
Date parsing should be much stricter

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#713]
```
>>> str_to_datetime("4", pytz.UTC)
datetime.datetime(2017, 12, 4, 19, 20, 15, 76353, tzinfo=<UTC>)
>>> str_to_datetime("1", pytz.UTC)
>>>
```

Need to agree what dates we want to parse and keep RP and GoFlow consistent

**Comment by nicpottier** [comment]
I think only format we should support is the "friendly format" for an org and ISO8604. GoFlow introduces them being able to specify their own format so that covers the other cases.

**Comment by rowanseymour** [comment]
This was addressed in https://github.com/nyaruka/rapidpro/pull/1673
