### ISSUE TITLE
Celery Setup and Branding

### ISSUE THREAD

**Issue by jlev** [rapidpro/rapidpro#714]
Trying to get this working on Heroku, and basing the Procfile on ansible settings. (WIP at https://github.com/fightforthefuture/rapidpro/tree/heroku-setup)

To run celery, the supervisor_tasks in ansible/vars.yml references `python manage.py celery worker`, which does not appear to be present without djcelery (which was removed in 3a372d88c890429124946e6a517b25846245ba2a).

I can run still bin/celery, but that does not appear to pick up my DJANGO_SETTINGS_MODULE with a redis broker and custom branding. An email to invite a new user was sent out with the default BRANDING and links from settings_common, not my changes to settings_fftf.

Is there a recommended way to keep celery and Django settings in sync?

**Comment by jlev** [comment]
Resolved by starting celery with the -app flag

Procfile now includes:
```
web: gunicorn temba.wsgi:application --log-file -
worker: celery -A temba worker --beat -Q flows,msgs,handler,celery -c 2
```

**Comment by jlev** [comment]
Well, sort of. The celery worker now runs on the redis broker, but the branding and links are still the defaults from settings_common, not my overrides in settings_fftf. 

I had to manually change the Org model to have the correct brand, since the default rapidpro.io was still in place.

**Comment by nicpottier** [comment]
That is the right way to start celery, so on that front you are good. (though you'll want lots more workers at scale)

Are you sure the Org wasn't created before you made these changes? Branding on an org sticks around after you change settings (as you saw it is org specific, not specific just to an install) But once you have your branding set up correctly NEW orgs should be whatever the default org is. (or whatever host the user is on when they create the org)
