### ISSUE TITLE
Webhook call on Contact update

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#715]
I'd love to make a webhook call to my service whenever a contact is updated: group, custom field, name, urn, etc.

Right now, we have unidirectional contact info sync from my service to rapidpro, but the reverse would be fantastic. Right now, we implement this with a webhook, so when the contact's group changes, we add another step in the flow to call a webhook, but that's a bit clunky.

I looked around for documentation on resthooks, which look like it is exactly the solution I want, but I couldn't seem to find any... Any thoughts?

**Comment by rowanseymour** [comment]
Generally we'd like to move away from non-flow based webhooks. We currently support webhooks for certain message events but not a lot of users use these and we'd prefer to make flows be the sole way to call out to external services. 

If you need to keep contacts up to date in another system, you can poll the contacts API endpoint which returns contacts as they are modified. We use this with https://github.com/rapidpro/casepro to keep its list of contacts in sync with RapidPro's.
