### ISSUE TITLE
Code that will never run

### ISSUE THREAD

**Issue by eltonplima** [rapidpro/rapidpro#718]
The [conditional code in this line](https://github.com/rapidpro/rapidpro/blob/e333ea50a5ebf8ec51e5e4367c2291e0a06a998c/temba/flows/models.py#L4979) will never be executed, because the uuid arg is mandatory.

Generally when doing this type of validation is recommended to lock a default value for the argument. This is only a recommendation of good practice. Hope it helps with something.

Who call the function can pass None as param, but, he must to do this always.

**Comment by rowanseymour** [comment]
I think it can be called with `None` from https://github.com/rapidpro/rapidpro/blob/e333ea50a5ebf8ec51e5e4367c2291e0a06a998c/temba/flows/models.py#L5555
