### ISSUE TITLE
Support Facebook Messenger Extensions SDK over IP Channels

### ISSUE THREAD

**Issue by IanLawrence** [rapidpro/rapidpro#721]
Would be very useful for payments and basically anything else moderately complex to do in a text interface. 
Hope to open a discussion on the best way to do this or even if it is desirable - not asking for someone to do it

**Comment by nicpottier** [comment]
As a start.. Is there an API for say payments over messenger? Can you point us to that?

**Comment by IanLawrence** [comment]
There is something here https://developers.facebook.com/docs/messenger-platform/reference/messenger-extensions-sdk/PaymentRequest. The request for a payment basically needs to conform to the  W3C standard Payment Request API (https://w3c.github.io/payment-request/)

More generally it is support for the Messenger Extension SDK. This JS SDK allows you to call some of the Messenger functionality within a web page if opened from the Messenger app. Two of the key features are 1) retrieving user identity, and 2) closing the webview container. Here’s how it might work in practice:

You send a message with a URL button that has the extension flag on
A person taps the button and opens a webview without leaving Messenger
Using the SDK, you retrieve the user ID, potentially personalize the page, capture user input
When done, you send a message back to the thread if needed and this is available to use in textit

**Comment by nicpottier** [comment]
Don't think we are likely to add this, now that webhooks support full headers etc, most things are possible that route. Closing.
