### ISSUE TITLE
Trackable Links

### ISSUE THREAD

**Issue by NelsonCCL** [rapidpro/rapidpro#722]
Hey guys. 
Our company has been doing some work using the RapidPro code and we developed a feature that you might get interested, a feature to track links. Here are some mockups (see attached) showing how we are developing it. If you have any questions or feedback on our approach, please let us know.

Just to explain a little bit, we add a new tab "trackable link", where the user can create the links that will be trackable, also a ruleset "shortened url" (it´s important on our case as our clients use SMS and we want to save characters). After that, the user just need to send the shortened link with a "send message" calling the flow step. Once the user clicked on the link (every user get a different link related to its UUID), we count its click, and list its name into the trackable link.

![main page clickable link](https://user-images.githubusercontent.com/35786132/35365960-c9dc4aec-0155-11e8-8639-9673f6211395.PNG)

![inside traceable link](https://user-images.githubusercontent.com/35786132/35365962-cbf2cd88-0155-11e8-8e39-1644de52e549.JPG)

![create clickable](https://user-images.githubusercontent.com/35786132/35366031-0e05c9f0-0156-11e8-85a5-721875cc6b1f.JPG)

![flow step](https://user-images.githubusercontent.com/35786132/35365975-d404510e-0155-11e8-9bb6-c2eef1ac850d.JPG)

![ruleset](https://user-images.githubusercontent.com/35786132/35365977-d541b93a-0155-11e8-869a-c7f4bfdb0688.JPG)

**Comment by nicpottier** [comment]
Hi Nelson!

Definitely an interesting idea. Can you share your branch where you have this implemented?

I think we'd have to chat about the design for this, not positive about this being done with a ruleset. Also would have to consider how this scales to people sending hundreds of millions of these. We have heard this as a desirable feature in the past, so may not be opposed to rolling it into the platform.

**Comment by teehamaral** [comment]
I’ll open a PR soon with the branch where the code is implemented, sounds good?

**Comment by nicpottier** [comment]
No promises to merge as I mentioned we aren't positive on the approach, but sure would like to see the code path taken.

**Comment by teehamaral** [comment]
Hey @nicpottier, I didn't open a PR because I think that we have some features beyond that Unicef needs like a flow step to shorten URL, export contacts that clicked on the trackable link and so on. So the link of the branch that we're working is https://github.com/greatnonprofits-nfp/rapidpro/tree/feature/trackable-links, if you want we can remove this features that I mentioned and based on your master we can open the PR.
