### ISSUE TITLE
Add support for typing indicators on Facebook Messenger

### ISSUE THREAD

**Issue by IanLawrence** [rapidpro/rapidpro#725]
Both webhooks and zaps can take a long time to process. Having typing indicators would help. It would be implementing sender actions
 https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions

**Comment by nicpottier** [comment]
I could see value there. Would be interesting to figure out which other IP channels (WhatsApp, Viber, Twitter for starters support these).

**Comment by IanLawrence** [comment]
@nicpottier WhatsApp does not allow for bots (they have business channels but that is not what we need here). Twitter does (https://twitter.com/twitter/status/773913816740409345) as does Twilio (https://www.twilio.com/docs/api/chat/guides/typing-indicator). Slack and Skype both have support for them too

**Comment by nicpottier** [comment]
WhatsApp does have bots, it is just a closed beta right now.

**Comment by IanLawrence** [comment]
@nicpottier difficult then to know if they will support them or not - i would suggest its quite likely however. 
Typing indicators would also be useful if you needed to insert a message delay to prevent messages that contain images/videos from being sent out of order.

**Comment by nicpottier** [comment]
WhatsApp doesn't. :)

Not arguing utility of this, not entirely clear how it fits into the current model but we'll consider it. Seems it could be something done automatically / universally for supported channels once we receive a message and while we are running a flow in response to it.

**Comment by IanLawrence** [comment]
Automatically would be ok I think as long as it can be turned off.  Current model - you mean models.py or business model? I am trying to plan for up coming work which needs the great multi tenant features of rapid pro but also IP channel stuff like Extensions, NLP etc principally on Facebook.

**Comment by nicpottier** [comment]
Current model as in architecture of flows, is this an action or something automatic etc.. there are a lot of details of how this is communicated to courier for example, who is responsible for doing it, how users decide whether they want it or not etc..

If you have a specific use case you are probably better off just doing it on your fork unless you want to think through all those specifics and work through a PR with us.

**Comment by IanLawrence** [comment]
My gut feeling is that working through a PR is the correct way to do it. Looking ahead there will probably be a bunch of other stuff we need to add coming up which will more likely make it upstream if this is done

**Comment by nicpottier** [comment]
This kinda sorta fits in with #875 and I think those two would probably fit together. No idea still what exactly that strategy would be but just grouping them.
