### ISSUE TITLE
RapidPro Development | SuperUser Account

### ISSUE THREAD

**Issue by deldesir** [rapidpro/rapidpro#731]
I have been able to install RapidPro for testing. Now I am stuck with the superuser account as I have no clue why dashboard doesn't load and why I don't have any access to menus / pages (other than these two limited ones: users and orgs) that would help me following tutorials found at https://community.rapidpro.io/videos/.

**Comment by rowanseymour** [comment]
@deldesir it's best if you use the [rapidpro developers mailing list](https://groups.google.com/forum/#!forum/rapidpro-dev) for these kinds of questions. Also you'll need to give us some more information if we're going to be able to help you. For example are you seeing any error messages? Have you tried creating an org?
