### ISSUE TITLE
Closing dialog boxes on iOS Safari

### ISSUE THREAD

**Issue by mattcrum** [rapidpro/rapidpro#734]
The flow editor has some issues with touch devices, main being it doesn't respond with a dynamically created div on a mobile browser (iOS Safari in particular... ).  I realize this may not be a priority to fix, so I did some digging and built the project and hopefully came up with something that may be a start to a solution.
Basically there's an issue with ng-click not firing on mobile as described here:
https://stackoverflow.com/questions/25032237/ng-click-on-firing-on-mobile-or-tablet-devices/44560612#44560612 
and here: https://stackoverflow.com/questions/34575510/angular-ng-click-issues-on-safari-with-ios-8-3/34579185#34579185

So basically adding the following directive to flows/directives.coffee
```coffeescript
app.directive 'ngMobileClick', [ "$parse", ($parse) ->
  (scope, elem, attrs) ->
    elem.bind 'touchstart click', (e) ->
      e.preventDefault()
      e.stopPropagation()
      scope.$apply ->
        $parse(attrs.ngMobileClick) scope, $event: e
        return
      return
    return
 ]
```
and in the flow_editor.haml file, all divs that were generated dynamically would need to be adjusted to ng-mobile-click instead of ng-click

This will enable touch for this device in this instance. With that being the case, we now have a new issue. Once the box is touched, it activates a click as expected, but the hover hasn't been activated (cause touch) so it will not be able to activate the icon that will allow us to remove a actionset or ruleset.  I'd imagine this can be solved in a few ways: initially I'm thinking after activating the ruleset or action set, it will set that particular node's iconset as active, then once the user clicks off the modal the icon set.  There may be a better way.  I'm not a big mobile developer but there may be better ways, I just wanted to go ahead and share this to see if folks will be open about increasing compatibility before I continue down this route.

**Comment by mattcrum** [comment]
I got some time to take another look at the issue, and scratch some of what I said before, even though ngMobileClick directive did actually work, it introduced some new tricky issues.

I now am leaning towards the root being ng-click isn't being fired perhaps due to nodes being draggable set in the directives.  Once I take the draggable functions out, it works okay. Trying to think through some other options to solve this problem.  https://groups.google.com/forum/#!topic/jsplumb/J143LTDUNfc Is a good discussion on this. @ericnewcomer can you take a quick glance through and give any thoughts?

**Comment by ericnewcomer** [comment]
One tricky thing to consider with click events and dragging with respect to jsPlumb is that the click event completes before the drag event is done. So the only way to know the difference between a click and a drag on these nodes that defer to jsPlumb for dragging is to monitor mouseDown and mouseUp. The other option is not deferring to jsPlumb for dragging, but that's really a non-starter in my mind since it needs to be aware of draggable elements (and their nested children which may have endpoints to update).

For example, we do this in the new editor by managing the click ourselves: https://github.com/nyaruka/floweditor/blob/581eb869807b54f015f6d2fe5b1c5cca504532c6/src/utils/index.tsx#L152

**Comment by mattcrum** [comment]
@ericnewcomer thanks.  The new editor works well with iOS (outside of the use of hover, but if I touch where the x should be, even though the x doesn't appear, it'll activate properly). 
Is the current implementation of jsplumb using jQuery UI? In that thread I linked above, they are implying that vanilla jsplumb and perhaps use of mottle solves the issue, but I'm not sure how to clearly tell if you've got jQuery UI tied to it. I see it in the grunt file but not sure if jsplumb is integrated with it or if it's used for something else independently.

**Comment by ericnewcomer** [comment]
Both editors use vanilla jsPlumb, though the old editor uses jQuery all over the place. Hover is definitely something that needs to be rethought on mobile.

**Comment by nicpottier** [comment]
Closing as I think new editor addresses this.
