### ISSUE TITLE
Allow searching by contact number in 'Start Flow' modal omnibox

### ISSUE THREAD

**Issue by ycleptkellan** [rapidpro/rapidpro#735]
contacts could have the same name, contact may not yet have a name/group, or the user may only know the contact's number

**Comment by norkans7** [comment]
I think using random urn was removed because it was slow to make sure a contact is not started twice in the flow

**Comment by ycleptkellan** [comment]
ah ok thanks. @nicpottier do you think this is something we'll want to re-implement in the future?

**Comment by nicpottier** [comment]
I can't recall why we removed it, but at first blush it doesn't SOUND like it would be much harder than resolving a URN to a contact then just adding it to the contact list in FlowStart. It was years and years ago though, so I may be forgetting exactly why we removed it.
