### ISSUE TITLE
Consider adding Swagger file for API

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#744]
Would let people more easily build libraries:
  https://swagger.io/specification/

Looks like there's some people who have build this on Django Rest Framework:
  https://github.com/axnsan12/drf-yasg/

**Comment by citizenrich** [comment]
It would be nice to try to use a Swagger definition as a way to generate proto definitions for code generation in Go, JS, and other languages without maintained API clients.

See https://github.com/NYTimes/openapi2proto

**Comment by cromulus** [comment]
100% this.

**Comment by bkimondiu** [comment]
I am reopening this issue to see if the request below can be implemented in the coming days. Please let us know if that will be viable.
> Would let people more easily build libraries: https://swagger.io/specification/
> 
> Looks like there's some people who have build this on Django Rest Framework: https://github.com/axnsan12/drf-yasg/
