### ISSUE TITLE
Issues with compression

### ISSUE THREAD

**Issue by mekjr1** [rapidpro/rapidpro#750]
I am having trouble with the Modax object creation, my modals are not working, it seems to be caused by  temba.js no being loaded 
![image](https://user-images.githubusercontent.com/17961065/39846317-37d9a114-53fb-11e8-8c6d-5b06103f9071.png)

**Comment by nicpottier** [comment]
This looks like a collectstatic issue, where the generated hashes at runtime aren't the same as they are when running `collectstatic`. These are a pain to debug, but that's definitely what is occurring on your side. Are you running collect static?

**Comment by mekjr1** [comment]
Yes. I did run it

![image](https://user-images.githubusercontent.com/17961065/39878119-d9f3903c-5477-11e8-919b-bca2ef3c903f.png)

**Comment by nicpottier** [comment]
Is your web server set up to serve /sitestatic? Are the files referenced above and which are getting 404s actually present?

**Comment by mekjr1** [comment]
yes. I am using nginx to serve the static files and all the files getting 404 are in the CACHE folder

**Comment by nicpottier** [comment]
Sounds like a NGINX configuration issue then. This isn't a RapidPro problem.

**Comment by mekjr1** [comment]
With COMPRESSION_ENABLED set to False, this is what I get

![image](https://user-images.githubusercontent.com/17961065/39880442-1e7dd57c-547e-11e8-8956-71d46735ad65.png)
if it was a NGIX problem would it fail for other JS and CSS?

I only discovered the issue when I was trying to test the flow feature ( trying to create one),
this is the address http://35.185.19.5:8000/

**Comment by nicpottier** [comment]
You have a problem with your compression, you need to debug why things are not the same when you run collect static and when you are actually running your server. That isn't a RapidPro problem, that's a problem in your customizations or templates.
