### ISSUE TITLE
FilterError at /  Your JavaScript runtime does not support some features used by the coffee command. Please use Node 6 or later.

### ISSUE THREAD

**Issue by seppibrown** [rapidpro/rapidpro#751]
hi everybody  when i try to set up Rapidpro in my loczal vmware workstation : i have this at the end !!!!!

![image](https://user-images.githubusercontent.com/26435158/39867925-352d9570-544f-11e8-9c6d-066fbcd4b5bd.png)
Any suggestions? Thanks!

**Comment by FlorentinCONGO** [comment]
hi @seppibrown, you can try to reinstall node js with version 11. 
```
apt autoremove nodejs -y
apt remove nodejs
deb https://deb.nodesource.com/node_6.x xenial main
sudo apt-get install curl python-software-properties
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
node -v
sudo apt-get install nodejs
node -v
```

**Comment by nicpottier** [comment]
Make sure you are using latest coffeescript. Closing.
