### ISSUE TITLE
Add action for sending airtime using http://www.transfer-to.com/

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#76]
Various requests for this at various times.. Would be nice if transfer-to made it a bit easier for people to create accounts adhoc, then we could do something similar to Nexmo and Twilio where we ask for API keys and automate the sending.

Still a pending question as to how reliable they are in actually delivering the cash as well.

**Comment by citizenrich** [comment]
In the process of setting up an account to test this if anyone wants to follow-up with me later.

**Comment by ericnewcomer** [comment]
Oh nice. Are you testing this in Afghanistan? Definitely interested to hear
if they perform reliably there.

**Comment by citizenrich** [comment]
Will probably test this elsewhere too, but also in Afghanistan. If there
are other providers of such services then I can also approach them.

**Comment by ericnewcomer** [comment]
Adding @norkans7 as he is currently in progress of implementing this.

**Comment by ericnewcomer** [comment]
See here: https://github.com/nyaruka/rapidpro/pull/742
