### ISSUE TITLE
Generated external channel configuration has wrong content-type for JSON

### ISSUE THREAD

**Issue by idevsoftware** [rapidpro/rapidpro#762]
Hi,

When a new external channel is created its configuration stored in the database is slightly wrong. The Content-Type field is set to `json` when it should read `application/json`. I know it's a minor issue but it prevented the channel from properly working with a rather strict (and old) SMS GW software.

If you can point me where to make the necessary changes I would do so gladly and submit a PR.

**Comment by idevsoftware** [comment]
Ok, so changing the stored config field for the channel in the postgresql db solved the issue of the correct header being sent on HTTP requests, but I am now getting the inverse problem: when trying to view the channel details I get a KeyError:

```
  File "/var/lib/rapidpro/rapidpro/temba/channels/types/external/type.py", line 46, in get_configuration_context_dict
    context["example_content_type"] = "Content-Type: " + Channel.CONTENT_TYPES[content_type]
KeyError: 'application/json'
```

I manually changed [this line](https://github.com/rapidpro/rapidpro/blob/7acb45e4168e1c6601e6647038e422ce20ebcac7/temba/channels/models.py#L340) to read as follows instead:

`    CONTENT_TYPE_JSON = "application/json"`

This seemed to solve both issues but I'm not sure it's the right fix.

**Comment by norkans7** [comment]
It is true the DB value should be `json` and https://github.com/rapidpro/rapidpro/blob/7acb45e4168e1c6601e6647038e422ce20ebcac7/temba/channels/types/external/type.py#L46 will look up the right value from https://github.com/rapidpro/rapidpro/blob/7acb45e4168e1c6601e6647038e422ce20ebcac7/temba/channels/models.py#L343

**Comment by idevsoftware** [comment]
Right @norkans7, but that's not what I'm seeing at all. The HTTP request made by courier still has the `Content-Type` header set with a value of `json` instead of `application/json`:

![screen shot 2018-06-19 at 9 07 09 am](https://user-images.githubusercontent.com/356357/41599392-02834d24-73a1-11e8-8fbd-06e7b5ade2a6.png)

Which, in this case, is making the request to fail.

**Comment by norkans7** [comment]
@idevsoftware ahh right, then that is a bug in courier which should be making a lookup the same way

**Comment by nicpottier** [comment]
This should be fixed here: https://github.com/nyaruka/courier/pull/161
