### ISSUE TITLE
Enable AdminBoundary upload per Org

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#763]
* we need to enable Orgs to manage their own set of boundaries
* original set of boundaries are going to be copied/cloned to per org boundaries in a data migration

* leverage existing OSM /Nyaruka datasource and add support for GADM source
  * we will hardcode attribute mapping (i.e. NAME_1 -> name, ...)

* management per country
  * administrators are able to upload/replace lower level boundaries for a country

# Discussion

* `osm_id` is used as a boundary identifier when accessing data over the API (used by UReport, for example)
  * maybe we should deprecate `osm_id` with `geom_id` or something similar
  * add an upstream source attribute to track the original source of data

* hierarchical relationship of the boundaries is defined by attributes
  * for OSM boundaries exported by Nyaruka, we maintain the relationship when exporting the data after simplification process
  * GADM data has a link to the parent boundary through one of the attributes
  * we should also check if the boundary is geographically contained within the parent boundary

* when importing/updating data if the parent cannot be found (text/geographical comparison)
  * we don't import/update that row
  * we show the user which rows have not been imported

* do we want to keep previous versions of the data
  * some service downstream might still require a 'previous' dataset version
  * how do we manage data updates, how do we announce data updates
  * do we allow users to delete/hide ('deactivate') data

* do we use fields `lft`, `rght` that are in the database relation, but not defined in the model

**Comment by nicpottier** [comment]
I don't think we allow updating children of boundaries.. It's all or nothing. We aren't building a boundary editing tool, just giving people a way of uploading their own boundaries for their org.

I also don't think we need a concept of platform vs org, we should just have org only and leave it at that. No reason to have two ways of doing things.

**Comment by dodobas** [comment]
Ok, then we will only have one type of the boundary, at the OrgLevel.

Do we migrate(copy) existing boundary data per org, for every org that uses at least one Location field?

**Comment by nicpottier** [comment]
Ya, I think  migration path is copying those all into org specific ones.

**Comment by dodobas** [comment]
Updated the main comment, maybe this should have been discussed as a wiki article, seems cumbersome to update the comment all the time

**Comment by nicpottier** [comment]
Ya Google docs are nice from a commenting point of view really.
