### ISSUE TITLE
Call Webhook: Dynamic Value in Header Value

### ISSUE THREAD

**Issue by qoda** [rapidpro/rapidpro#770]
Is it possible to use a dynamic value in the Header value. I.e. I call a authentication endpoint in my API to retrieve an auth token. The token is than used for subsequent webhook calls.

<img width="658" alt="screen shot 2018-06-27 at 09 28 17" src="https://user-images.githubusercontent.com/125271/41959168-81b88eaa-79ec-11e8-9d36-aa34c613197b.png">

**Comment by rowanseymour** [comment]
Not currently possible but can't think of a reason we shouldn't add support for this.

**Comment by qoda** [comment]
@rowanseymour will look into it and see if I can submit a PR for your consideration, it would be exceptionally useful to me.

**Comment by qoda** [comment]
@rowanseymour I looked at the code last night to see if this would be possible, but have little to no clue where to even start. Will use a default token and see if the same can be achieved. I'll try and look at it again, but for now... deadlines. You can tag this as a feature request if you like.

**Comment by rowanseymour** [comment]
All flow execution now happens in https://github.com/nyaruka/goflow which implements this feature
