### ISSUE TITLE
Begginer question NGINX uwsgi multiple issues.

### ISSUE THREAD

**Issue by markotitel** [rapidpro/rapidpro#772]
Hi,

I am trying to figure out how to run rapidpro behing Nginx using uwsgi.

At the moment I can successfully use the APP with `python manage.py runserver`.

Once I want to use UWSGI `uwsgi  --socket 0.0.0.0:8080 -w temba.wsgi` I have issues with Nginx serving "wrong" `content-type`.

I know the problem is on my side and lack of knowledge in deploying Django with Nginx and Uwsgi, but I am searching two days now on how to figure this out.

This is Nginx conf.
`server {

        # Running port
        listen 80;
            root /home/ubuntu/rap;

        # Settings to by-pass for static files
        location ^~ /sitestatic/  {
            alias /home/ubuntu/rap/sitestatic/;
        }

        # Serve a static file (ex. favico) outside static dir.
        location = /favico.ico  {

            root /app/favico.ico;

        }

        # Proxying connections to application servers
        location / {

            include            uwsgi_params;
            uwsgi_pass         127.0.0.1:8080;

            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;

        }
    }
`
Any clue appreciated.

**Comment by markotitel** [comment]
Here is an image of what I get served.

![2018-06-29-121358_521x176_scrot](https://user-images.githubusercontent.com/5695612/42087271-f2a70f1a-7b95-11e8-88df-29a483a55cf4.png)

**Comment by markotitel** [comment]
No need to confirm that the problem was in my knowledge.

I did not have mime types included for Nginx.

**Comment by FlorentinCONGO** [comment]
Hi @markotitel, i deployed Rapidpro with apache and wsgi. Now i want to use it with nginx and uwsgi. Could you help me with your config files? 
Thanks.
