### ISSUE TITLE
More consistent Msg export columns

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#776]
We should make this more consistent with our contact exports and our flow exports.

Messages export columns should be Date, Contact UUID, Name, URN, URN Type, Direction, Text, Attachment, Status, Channel, Labels

Note that this should be the same format as is used for the "Messages" tab in flow result exports.

**Comment by norkans7** [comment]
You mean also include all these on the "Messages" for the results?  @nicpottier

**Comment by nicpottier** [comment]
Seems we should, apart from maybe labels I think we have all this data no? (I'd be ok leaving labels out of flow exports)

**Comment by norkans7** [comment]
Okay

**Comment by norkans7** [comment]
We get the message from events 

	"events": [{
		"msg": {
			"urn": "tel:+12076661212",
			"text": "hola",
			"uuid": "cf05c58f-31fb-4ce8-9e65-4ecc9fd47cbe",
			"channel": {
				"name": "1223",
				"uuid": "bbfe2e9c-cf69-4d0a-b42e-00ac3dc0b0b8"
			}
		},
		"type": "msg_created",
		"step_uuid": "659cdae5-1f29-4a58-9437-10421f724268",
		"created_on": "2018-01-22T15:06:47.357682+00:00"
	}]

So we can not get all those fields I leave the results exports as they are now

**Comment by rowanseymour** [comment]
this was fixed
