### ISSUE TITLE
Run a Flow in USSD Exits

### ISSUE THREAD

**Issue by qoda** [rapidpro/rapidpro#782]
I'm attempting to break up a complicated USSD application by with "Run a flow" however it exits out of the application rather than serving the user with the menu as layout out in the flow I point to. I may be missing something or is this not supposed to work for USSD?

Please see simple example below. The linked flows run without issue on their own.

<img width="1679" alt="screen shot 2018-07-18 at 08 53 47" src="https://user-images.githubusercontent.com/125271/42864860-255bd8c4-8a68-11e8-9c36-7f480ef73447.png">

**Comment by nicpottier** [comment]
USSD no longer supported, closing.
