### ISSUE TITLE
Facebook access tokens fail

### ISSUE THREAD

**Issue by Hitman23** [rapidpro/rapidpro#785]
I was trying to add a facebook channel to rapidpro and it kept failing with an internal server error. 
After turning on debug mode I, the error points to the access token being longer than what is expected.

`DataError at /channels/claim/facebook/
value too long for type character varying(64)
Request Method:	POST
Request URL:	https://mydomain/channels/claim/facebook/
Django Version:	1.11.2
Exception Type:	DataError
Exception Value:	
value too long for type character varying(64)
Exception Location:	/var/www/env/rapidpro_prod/local/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 65
Python Executable:	/var/www/env/rapidpro_prod/bin/python
Python Version:	2.7.6`

I think it is the database field that stores the access token.

Has anyone faced this?

**Note: Facebook access tokens are always of varying length. Not sure what determines the length though.**

**Comment by nicpottier** [comment]
Yep, that was indeed an issue, but was fixed a good while back. You can do a local patch to just remove the length validation if you like or update to the latest version. (make sure to read the release notes, 4.0 has lots of changes)

**Comment by Hitman23** [comment]
Thank you very much for this information and a timely response.
