### ISSUE TITLE
Releasing a channel shouldn't both deactivate and archive its associated triggers

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#795]
Deactivates them on https://github.com/nyaruka/rapidpro/blob/master/temba/channels/models.py#L1146

Archives them on https://github.com/nyaruka/rapidpro/blob/master/temba/channels/models.py#L1152

Correct behavior should be verified in `ChannelTest.test_delete`

**Comment by ericnewcomer** [comment]
These links aren't against sha's so not super useful. What is the desired behavior here? Seems we should just archive but keep is_active true which is "deactivated" from a user's perspective.

**Comment by rowanseymour** [comment]
Take 2...

Deactivates: https://github.com/nyaruka/rapidpro/blob/a2a3200f9f7918ecabbf0b33d8d99ab7b5a2e435/temba/channels/models.py#L1081

Archives: https://github.com/nyaruka/rapidpro/blob/a2a3200f9f7918ecabbf0b33d8d99ab7b5a2e435/temba/channels/models.py#L1090

I think triggers only have channels in the case of "New Conversation trigger".. and it's non-optional. So the problem with just archiving is that you have a trigger now referencing a channel that no longer exists... so I think we gotta deactivate those triggers completely.. or not let the channel be released until the user explicitly removes the triggers.

**Comment by ericnewcomer** [comment]
Seems removing new conversation triggers when the conversation enabled channel is deleted is appropriate. So is the fix here to just not also archive them? Which I guess makes this more of a cleanup task than a bug since it's not really affecting anything.

**Comment by nicpottier** [comment]
Seems deletion is probably the right thing. Archiving implies you can unarchive them. Not sure why doing both is considered wrong though. But ya, agree this is more cleanup than anything, retagging.

**Comment by rowanseymour** [comment]
I think I just assumed it was a mistake because it's archiving things that are already deleted.. if that's the correct behavior then maybe it just needs a comment

**Comment by nicpottier** [comment]
Ya, not sure, to some extent it feels to me like archiving means "execute this" and active means "this thing is deleted".. and that when you move to the deleted state then maybe you should move out of the executing state? But can see arguments either way for sure.

**Comment by nicpottier** [comment]
Anyways, going to close this, certainly not doing any harm.
