### ISSUE TITLE
Parse date from variable in @extra blob within Filter by Expression field

### ISSUE THREAD

**Issue by gabrielosorio** [rapidpro/rapidpro#796]
Hi!

I'm currently trying to have a "Filter by Expression" node compare dates passed in the data when starting the flow.

What I'm trying to implement is a simple way to check for expiration within a timeframe. A Filter by Expression that checks a date sent along with the flow start.

```
If the expression: @(NOW() < DATEVALUE(@extra.flow_start_date) + TIMEVALUE(@extra.flow_start_time) + TIME(4, 0, 0))
```

Where `flow_start_date` and `flow_start_time` are strings resembling `"08-29-2018"` and `"13:04"`, respectively. Where the date format matches the format configured for the Org, in case this makes a difference.

So if the answer comes after four hours of the flow start, it will be treated as having expired.

Is there there something I'm simply doing wrong here, or should I be using a Call Webhook component instead?

Appreciate any insight!

**Comment by rowanseymour** [comment]
Inside an expression you shouldn't be putting `@` in front of variable names. Also the best place for questions like this is probably the mailing list https://groups.google.com/forum/#!forum/rapidpro-dev
