### ISSUE TITLE
Editor overwrites field names potentially losing changes made via Manage Fields

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#800]
1. Open a flow in the editor the sets a contact field value
2. In a different window open Manage Fields and change the field name
3. Do anything in the editor window that causes a flow save
4. Field has old name again

**Comment by norkans7** [comment]
I believe that was fixed with https://github.com/nyaruka/rapidpro/pull/2118

**Comment by nicpottier** [comment]
Yep, fixed.
