### ISSUE TITLE
Inconsistent constants for expired on FlowRun and FlowSession

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#810]
FlowSession uses 'X'
FlowRun uses 'E'

Should probably change session to 'E' since changing runs would break API compatibility.

**Comment by rowanseymour** [comment]
flow runs actually use `completed|interrupted|expired` in API

**Comment by nicpottier** [comment]
Oh right. Well fewer rows to update with session then!

**Comment by rowanseymour** [comment]
Both use 'X' for expired since 'E' is used elsewhere for errored
