### ISSUE TITLE
Switch org level SMTP settings to be single config value SMTP_SERVER

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#812]
URL in format:
 `smtp://user:password@host:port/[?from=from]`

Note that from and user must be URL endoded.

Should replace the various config variables we already have `SMTP_HOST`, `SMTP_USER` etc..

TLS will be upgraded by default so may not need that setting. (but can put in the query as `tls=true` for historical purposes)

**Comment by nicpottier** [comment]
We'll need a data migration for this.

**Comment by norkans7** [comment]
Fixed in https://github.com/nyaruka/rapidpro/pull/2161
