### ISSUE TITLE
Need a field on EventFire to mark why an event didn't fire

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#813]
We can now skip over a fire when a user is active in another flow. Right now we still mark the event as fired, but we probably should also have a field showing that it was skipped and display that slightly differently in the contact page UI.

Perhaps a `fired_result` field on event fire? (that can be one of `F` for fired or `S` for skipped?)

@rowanseymour @ericnewcomer

**Comment by norkans7** [comment]
In this case we need remove the batch start and pass the event fire to the flow starts?

**Comment by nicpottier** [comment]
On the django side they are currently being set as fired ya? If so, lets just leave it that way, but still add a field that mailroom can populate so we can add more clarity to the contact page. So for this can you add a migration to add the new field then tweak the contact page to display those event fires differently?

**Comment by norkans7** [comment]
Addressed in https://github.com/nyaruka/rapidpro/pull/2167
