### ISSUE TITLE
Foot gun prevention for trigger flow and send broadcast

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#814]
Problem:

RapidPro has the ability to send a lot of messages and start many many people in flows very quickly. Two of our actions, broadcast and trigger flow, take parameters that are groups. Although rare, occasionally user get confused and use these actions incorrectly, and say start a group of users in a flow which then triggers a broadcast to the same set of users. For a group of 500 users, that then creates 500^2 messages, which is obviously troublesome.

These features however are useful. It is often useful to cause a group of people to be notified when some event occurs and these actions enable that.

We currently have a very rough heuristic to try to detect these cases, but it is imperfect. Essentially looking for the same action occurring on the same set of user within a period and not performing the action if so, but it occurs to me that we could maybe make this simpler.

My proposal would be that any time we see one of these actions when starting a flow in a bulk, then they are ignored. IE, if you start a flow on 500 contacts, then any trigger flow action or broadcast action that operates on a group is ignored. If however the same flow is run on a single user, either through a start or due to a trigger, then those actions work as expected.

What do we think about this as a way forward to deal with the upcoming foot-bazooka that is mailroom/goflow and these actions? It would be easy to apply that heuristic within the framework we have there (ignoring all actions on groups on batch starts). Ideally perhaps we could catch this even earlier, say when starting a flow, but even then we would still want some rules as to when we honor these actions.

Thoughts? @ericnewcomer @norkans7 @rowanseymour @dodobas

**Comment by norkans7** [comment]
I think we could look at if the current run is in the group then we sent to that contact only but if the group the broadcast is going too does not include the run contact then we send to the group.

I think user make that mistake when the mean send to this run contact.

I think we still need to support a way to have contacts in Group A started in a flow at some point to notify some others contacts in Group B

**Comment by nicpottier** [comment]
I think testing whether the current contact is in the group may be useful but likely isn't enough to know that a mistake has been made.

I'm just not sure we have a lot of cases where people do a big start and in that start they are either broadcasting to a group or triggering a flow for a group and that is the intended behavior. Note I'm only talking about disallowing this on whatever actions are run in the first "sprint" of a batch start, replies etc can still trigger these.

**Comment by norkans7** [comment]
by first "sprint" you mean only ignore that for the first actionset only?

**Comment by nicpottier** [comment]
until the first wait, ya

**Comment by rowanseymour** [comment]
Some thoughts and no answers. We currently have two levels of loop detection in goflow:

 1. You can't re-visit the same node in a flow within the same sprint
 2. You can't re-visit the same flow within the same sprint

So I think what we're trying to figure out here is a 3rd type of loop detection.. this time across sessions. 

- It doesn't seem enough to base this on whether starts are bulk or not - because you can envisage a flow which has a single trigger flow action that starts contact A. What happens when we start contact A in that flow?
- It also doesn't seem enough to say you can't trigger yourself. Flow A might start contact B in flow B and flow B might trigger contact A in flow A and so on. Ping pong.

So I think the only viable solution is detecting a problem has occurred after the fact.

**Comment by nicpottier** [comment]
The infinite case is indeed another one we need to think about, though subtly different.

This isn't that case, this is the case when a group action is taking place in a group start. There doesn't need to be any kind of loop to cause millions of messages to be sent. (IE, it can just be a broadcast to the same group that is being started for example)

We should maybe start a new issue for the trigger causing another trigger case though.

**Comment by ericnewcomer** [comment]
I think both of those things are true. The case Rowan is describing I believe is a current vulnerability that is just a lot harder to execute. While I agree with Nic, highly, highly doubt there is a valid use case of group starting a group, perhaps we should be thinking about the wider scope here.

**Comment by ericnewcomer** [comment]
Fine with that being a separate issue. The broadcast case is surely going to be a different solution.

**Comment by nicpottier** [comment]
Ya, seems like Rowan's case is one we can address by adding a bit more to the `RunSummary` passed into the FlowActionTrigger. But ya, groups starting groups is another. Can chat about it on call.

**Comment by nicpottier** [comment]
Mailroom deals with this now by basically disallowing sending to groups or starting groups in a start that is on a group. That seems to be working well for us, closing.
