### ISSUE TITLE
Duplicated contacts once started by Facebook referrer trigger.

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#819]
Once a new person starts to chat by clicking a Facebook ad/referrer URL RapidPro holds the action of creating that new contact, like if it's expecting for some message to arrive. Then after the person sends the first message RapidPro creates one contact for the situation where that message came and, right away, it also creates another contact to the referrer that was on hold.
That issue is making contacts to be duplicated, and worst, as both contacts created uses the same Facebook URN, the last one created (referred) will take over the URN and the first one will just be a trash contact with the first message the person sent.

**Comment by nicpottier** [comment]
Thanks for the report. If this is a bug, it is probably on the Courier side as that is what is in charge of catching these events and creating the contact. I will see if I can glance at it over the next few days and get a repro case.

**Comment by nicpottier** [comment]
@norkans7 can you see if you can build a repro case for this in Courier?

**Comment by norkans7** [comment]
This has been addressed in https://github.com/nyaruka/courier/pull/192
