### ISSUE TITLE
Installation of rapidpro on windows is not working

### ISSUE THREAD

**Issue by nitesh-hurchand** [rapidpro/rapidpro#824]
I am trying to install rapidpro on windows environment but I am not able to make it run.  Is windows supported? If you have any guide please share.

**Comment by norkans7** [comment]
We have tested it on OSX and Ubuntu and the guide is on http://rapidpro.github.io/rapidpro/docs/development/

**Comment by norkans7** [comment]
It might however we recommend Ubuntu
