### ISSUE TITLE
Docker create  super user

### ISSUE THREAD

**Issue by mymanga** [rapidpro/rapidpro#826]
Anyone who has an idea how to create super user in the docker rapidpro? 
I tried it by running
` docker exec -it mycontainer /bin/sh`
`./manage.py createsuperuser`
I get the following error
`No module named 'django.`

**Comment by dodobas** [comment]
RapidPro does not have an official Docker image.

**Comment by rowanseymour** [comment]
@mymanga sounds like the virtualenv hasn't been built or hasn't been activated. Maybe create an issue at https://github.com/rapidpro/rapidpro-docker if can't get that working.

**Comment by mymanga** [comment]
Solution;
# docker exec -it rapidpro sh
# cd /
# venv source/bin/activate
# rapidpro/manage.py createsuperuser
