### ISSUE TITLE
Is it really necessary to have hardcoded characters replacement for l=1 and o=0?

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#828]
I noticed that there's a replacement action to the characters **l** (L) and **o** (O) at:
https://github.com/rapidpro/rapidpro/blob/79b0721b05fcba5fc1432b19bcfa8627b5bb13ab/temba/flows/models.py#L8343

Is that really supposed to be hardcoded like this? The reason I'm submitting this issue is that some languages will probably be in trouble with it! EG. portuguese (pt_BR)

Categorizing a contact response with "has a number" can have the user replying, for example:
**O número é 500.**
Which means "The number is 500."
But in that case, instead of 500, the value taken would be 0 (zero). This behavior drove me a bit crazy before I found out that it was hardcoded! 'xD 

Could that line be removed/refactored?

Appreciated.

**Comment by rowanseymour** [comment]
I could definitely be persuaded we shouldn't be so clever here and ditch substituting characters altogether...

**Comment by nicpottier** [comment]
That'd probably be my preference, we could add an Excellent function that does this kind of substitution if we wanted to allow that in the future, but would satisfy not doing unexpected things that can't be turned off.

**Comment by rowanseymour** [comment]
Fine with that - I can remove it on the goflow side

**Comment by WilliamTales** [comment]
Can I submit a PR to remove that code line also from current RapidPro?

**Comment by nicpottier** [comment]
Yep yep.
