### ISSUE TITLE
Normalize keywords with diacritics

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#83]
We likely shouldn't allow different keywords to exist for the same latin characters differing only by accents.

**Comment by ericnewcomer** [comment]
Saw an instance today with cyrillic i vs latin i not matching today. Perhaps we could consider using a transliteration library for this.

One to look at?
https://github.com/barseghyanartur/transliterate

**Comment by nicpottier** [comment]
I think instead of doing magic here that could potentially remove people from flows users can create multiple keywords here.
