### ISSUE TITLE
It's not being possible to create contact's group starting with the letter "c"

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#833]
https://github.com/rapidpro/rapidpro/blob/c055fa8637328c281f339bf99ca291e198a42ef0/static/coffee/flows/widgets.coffee#L568

For new groups' name, when the codes verify if starts with g- = groups or c-= contacts, prevents from creating groups with names starting with "c".

This bug happens only at the flow editor, at the contacts tab is perfectly possible to create groups with any names - starting with word chars.

**Comment by nicpottier** [comment]
Hah, funny, well that's an easy fix (at least to bring it to look for `c-` and `g-`)

I don't think the new editor has the same bug but maybe @ericnewcomer can verify that.

**Comment by ericnewcomer** [comment]
Can confirm new editor doesn't relay on c- g- stuff which is there to support select2.
