### ISSUE TITLE
Orgs alert's emails improvement.

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#836]
https://github.com/rapidpro/rapidpro/blob/79b0721b05fcba5fc1432b19bcfa8627b5bb13ab/temba/orgs/models.py#L2842

Instead of just taking the first admin's email to send Alert messages, wouldn't be more relevant to provide a support email account to receive these? Or make alerts arrive at all org's admin accounts?

**Comment by nicpottier** [comment]
Agree that these should probably go to all admins, happy to take a PR for that.

**Comment by nicpottier** [comment]
Fixed, closing.
