### ISSUE TITLE
msgs.Msg.high_priority: (fields.E110) BooleanFields do not accept null values.

### ISSUE THREAD

**Issue by Kirembu** [rapidpro/rapidpro#843]
https://github.com/rapidpro/rapidpro/blob/f7b6010cf7a56631fb6a6b1fd2764ba8333dfb32/temba/msgs/models.py#L818

Getting the following hint bellow:

    HINT: Use a NullBooleanField instead.

Below is a patch for the change, it will require the migrations generated to be attached to the new commit.

```

diff --git a/temba/msgs/models.py b/temba/msgs/models.py
index de5078ded..9e4a8c4e5 100644
--- a/temba/msgs/models.py
+++ b/temba/msgs/models.py
@@ -815,7 +815,7 @@ class Msg(models.Model):

     text = models.TextField(verbose_name=_("Text"), help_text=_("The actual message content that was sent"))

-    high_priority = models.BooleanField(
+    high_priority = models.NullBooleanField(
         null=True, help_text=_("Give this message higher priority than other messages")
     )
```

Django documentation link about the NullBooleanField:

https://docs.djangoproject.com/en/2.0/ref/models/fields/#nullbooleanfield

**Comment by Kirembu** [comment]
False alarm. Looks like this does not affect Django 2.1.X which was in this commit:

 https://github.com/rapidpro/rapidpro/commit/21cb567ee67d4ea0a67c6a5ca180f11f974623d3#diff-47b63b60c2b715596002079a340836b6

Closing this issue because it was better to upgrade Django from 2.0.9 than to have any changes. And the NullBooleanField is likely to be deprecated in a future version of Django..

**Comment by rowanseymour** [comment]
You shouldn't be creating any messages without this field set - other parts of RapidPro require it
