### ISSUE TITLE
Flow migration to replace StartFlowActions that cross flow modalities

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#845]
We allow users to start an IVR flow from a messaging flow, but this should be considered starting a new session (it will in the new engine) so should be replaced with a `TriggerFlowAction` using `@contact` to start the current contact. Allowing `StartFlowAction` in this case makes it look like a subflow but engine doesn't handle it as such. 

Also editor should be updated so that `StartFlowAction` only shows flows of same type.

**Comment by rowanseymour** [comment]
Complication here is whether the TriggerFlowAction should probably be terminal so we don't get into a race condition with the new flow session we're triggering.

But then that has the potential to leave orphan nodes in a migration, e.g (child is of different modality).

<img width="642" alt="captura de pantalla 2019-01-25 a la s 16 56 26" src="https://user-images.githubusercontent.com/675558/51774992-2ea7bd80-20c2-11e9-9083-18d2fd2dce28.png">

Unrelated note: need to update editor as well to prevent creation of StartFlowAction and Subflow rulesets crossing modalities.

**Comment by ericnewcomer** [comment]
Shouldn't starting a session require a recipient (contact, group, etc)? Also, can you expand on the race condition? Is the state not a snapshot at the point of triggering? 

The only oddity with not being terminal is when acting on the same contact which should terminate the current run once they are triggered in the new flow. That not happening instantly I don't necessarily see as a problem. Seems like the same contract as it is for starting anybody in a flow (ie, they get in the start queue and the start interrupts them if necessary when that start occurs).

**Comment by ericnewcomer** [comment]
Also, another thought is I think starting the current contact (directly or as a member of a group) is an anti-pattern. Perhaps we should disallow that altogether or disable it by default as a property of the action.

**Comment by nicpottier** [comment]
Ya.. I think in the mailroom case essentially the actions after the start will take place, that person will be at a wait, then they will be interrupted by the start of the new session. Which I think is correct.

Agree this may be seen as slightly weird but its needed for the cross modality case and it may be more confusing to have that be an exception rather than being consistent even in the same modality case.

**Comment by ericnewcomer** [comment]
Ah yes, cross-modality is the acceptable use case that started this, so disregard my second comment above.

**Comment by rowanseymour** [comment]
Ok so I think we agree then it's ok for the parent to keep running to the next wait, then mailroom will most likely interrupt them before they resume... tho there's always a chance they reply before that.. and as Nic mentioned there's also the possibility for all sorts of weirdness if they've been triggered multiple times.

I feel triggered just thinking about all this.

Definitely feels complicated to allow same contact for TriggerFlowAction depending on flow modality
