### ISSUE TITLE
Flow migration to find and remove invalid node destinations

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#846]

**Comment by nicpottier** [comment]
@rowanseymour is this done?

**Comment by rowanseymour** [comment]
No - we just ignore invalid node destinations when migrating old flows.. so the new flows will be valid

**Comment by rowanseymour** [comment]
I think we can close this and let the goflow migration just ignore the invalid exits. Even if we make a flow migration, the legacy editor is still most likely going to be creating new invalid exits.

**Comment by rowanseymour** [comment]
Closing as these aren't causing any problems because they are migrated away
