### ISSUE TITLE
Remove created_by, make modified_by nullable on Contact

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#849]
Another vestige of Smartmin models on some basic models. `created_by` doesn't make a whole lot of sense as the vast majority of contacts are created by courier (which currently just shoves in user id 1 I think). I would argue keeping modified_on is probably worth it (as nullable) because it can server a useful auditing purpose when users delete contacts.

**Comment by rowanseymour** [comment]
Tricky part here is that we lean `SmartModel` stuff for imports, tho probably not getting that much value from it

**Comment by norkans7** [comment]
`created_by` can be made nullable and imports use task.created_by to set that which is what is currently happening to be compatible with smartmin. Exports are not affected by created_by at all
