### ISSUE TITLE
ChannelLog list using old counts after logs deleted

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#855]
At last that's what I'm guessing having not had had time yet to dig into this. We override the count on the queryset at https://github.com/rapidpro/rapidpro/blob/dccecd5ef6e181f13befd7edf132d51bf53cf552/temba/channels/views.py#L1994

<img width="1200" alt="captura de pantalla 2019-01-16 a la s 15 44 06 copy" src="https://user-images.githubusercontent.com/675558/51278196-f1e41400-19a7-11e9-9361-e28eec7de469.png">

**Comment by nicpottier** [comment]
Need a better repro for this, looking at the code I don't see how these would get out of sync. I do remember seeing weird behavior here as some point but its been a while since I've seen it. All the accounts I can look at appear correct. Closing until we see it again.
