### ISSUE TITLE
Move to absolute URLs in flow definitions

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#857]
Currently flow definitions have relative URLs (e.g. `attachments/1/2/4646...`) and when they are executed by the engine and we're saving a `Msg` then they become absolute. GoFlow could do likewise if something it its environment told it where files were hosted, or Mailroom could do it when saving messages... but I think the right thing is actually having absolute URLs in the flow definition.

**Comment by nicpottier** [comment]
Not sure it is a plus or minus (leaning towards plus) but this would also help with import/exports across installations.

**Comment by nicpottier** [comment]
This is done ya @rowanseymour ?

**Comment by rowanseymour** [comment]
Engine is agnostic about URLs but when we migrate legacy flows we absolutify media URLs and AFAIK the new editor only deals in absolute URLs

**Comment by ericnewcomer** [comment]
Correct, new editor uses absolutes.
