### ISSUE TITLE
Remove retry failed calls option

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#859]
Currently we have these options for IVR flows:
![ivr flow 2019-01-23 07-35-24](https://user-images.githubusercontent.com/168067/51618060-5fc99780-1ee2-11e9-855b-2d56cd3a9c58.png)

I'd like to propose removing the "failed calls" option and changing the text for the "retry call on busy / no answer" to "retry call if unable to connect". I don't think the distinction of the two is particularly useful to users (when does a call fail? why wouldn't I always retry?) and there's no big cost to the user or to us to retry all calls on failures. (failures in the Twilio world happen with bad / unreachable numbers or other much less common reasons, in the Somleng world can happen if there are no available lines or other unspecified reasons)

So proposal is to always retry calls 3 times with the configurable timeout if we are unable to connect.

@dodobas @ericnewcomer  thoughts?

**Comment by nicpottier** [comment]
PS. We added this in https://github.com/nyaruka/rapidpro/pull/2154

**Comment by ericnewcomer** [comment]
Agree with this distinction not being worth its widget weight

**Comment by nicpottier** [comment]
That's a channel setting, not a flow setting. I think until that becomes a use case we see in more than one org that being a hidden channel attribute is just fine.

**Comment by dodobas** [comment]
there are some issues,
* AFAICT mailroom has no support for handling Somleng specific case (a.k.a local throttling)
* IVR tasks in the temba project were recently gated (`settings.TESTING`), but not sure if maliroom IVR support is feature complete, nor how it actually handles call retries
* are there any tests for IVR call retries in mailroom, could not find anything

**Comment by rowanseymour** [comment]
AFAIK (@nicpottier can clarify), mailroom is doing IVR now and the IVR code that still exists in RapidPro is only to 1) create pending calls for mailroom to handle 2) make unit tests pass

**Comment by nicpottier** [comment]
Mailroom does handle throttling, that's done here:
  https://github.com/nyaruka/mailroom/blob/master/ivr/ivr.go#L222

Retries are done here:
  https://github.com/nyaruka/mailroom/blob/master/ivr/cron.go#L50

Testing is somewhat spurious in Mailroom for sure, but that shouldn't affect us removing the above.

Poking around I think in truth we already retry every call including failed calls:
  https://github.com/nyaruka/mailroom/blob/master/ivr/ivr.go#L603

So I guess we really just need to remove that checkbox because it is a lie anyways. (we always retry)
