### ISSUE TITLE
Django views should return http_status 400, if a mandatory request param is not defined

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#861]
(Sentry issue: https://sentry.io/nyaruka/textit/issues/859601328/)

Some views, like `https://textit.in/channels/channellog/` require a mandatory request parameter, i.e. `channel` ... https://github.com/nyaruka/rapidpro/blob/67664cec9da5e4c64041198bdd8ad13d2fade20e/temba/channels/views.py#L1967

At the moment we simply 'blow up', and we should check if mandatory parameters are defined before actually processing a request. In the case mandatory parameters are not defined then we would render a standard Http400 (Bad Request)

**Comment by rowanseymour** [comment]
As @nicpottier mentioned on call - this is probably best handled with a custom regex/path like `https://textit.in/channels/channellog/1234-34567-2345/` so Django returns a 404 and we can also use `reverse` to generate URLs for it.
