### ISSUE TITLE
Support not-equal operator on contact fields of type text

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#868]
- previous search backend used EAV relation to store and query contact data - `values_value`, and the *not-equal* operator was not supported due to poor performance
- we could reevaluate the performance and add support for not-equal operator on contact fields of type text
- we would use `!=` operator

**Comment by nicpottier** [comment]
I *think* this makes sense and is easy to support with elastic now. Would need to update the goflow engine appropriately but that shouldn't be too big a deal.

**Comment by ericnewcomer** [comment]
goflow piece: https://github.com/nyaruka/goflow/issues/625
