### ISSUE TITLE
Contact Fields shown on Contact Page should follow field preference

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#869]
We currently show a selection of contact fields on the Contact page, but we don't sort these by the same order as the fields we show on the list page.

<img width="332" alt="nic pottier voice 2019-02-12 17-30-38" src="https://user-images.githubusercontent.com/168067/52672470-f4c11e80-2eeb-11e9-8f7f-51e3d3808fbf.png">

Seems we could honor the exact same things as list page.. IE, if you have it shown on the list page, it is shown on the Contact page by default and in the same order.

**Comment by dodobas** [comment]
a few notes/questions:
- we only display fields that have a value, should we maybe display all fields that are *featured* (visible on the contact list page) even if the field has no value
- should we display ALL fields even if those don't have a value?
- there are some 'system' fields like Language (Created_On is not shown on that page, should it be?) which are added to the regular contact fields, maybe we could move those out of the current _contact-fields_ div

**Comment by nicpottier** [comment]
I *think* showing featured fields even if they don't have a value makes sense. @ericnewcomer thoughts there? I think only question is whether we think the list page and contact pages are similar enough that people will be satisfied with those two options being the same. (that is that you can't select which are shown on the contact page and list page independently) But I think as a first take, honoring the order and showing all featured makes sense, gives the user some control.

I think showing fields with no value is probably a bit much for orgs that have a ton of fields which may be only related to some contacts. I suppose that's an argument against showing them above as well for consistency though I could convince myself those are different.

`created_on` is a field in the context now, so showing it probably isn't the worst idea. I think language also should be shown, even when it isn't set. Showing them distinctly likely makes sense. Eric may have thoughts there.

**Comment by ericnewcomer** [comment]
I think honoring list page settings for featured and order on the contact page makes sense as a next step. If it’s a featured field, showing empty makes sense. If it’s not lets not show it. Too many contact fields that exist out there just for flow operations that only some contacts touch (counters, etc).
