### ISSUE TITLE
Substitute ' and " characters that Word inserts with normal ASCII versions when authoring messages so that they don't get sent as UNICODE.

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#87]
Those are just two, but common ones when people author messages in Word or the like, then copy/paste into RapidPro.

**Comment by ewheeler** [comment]
related but perhaps deserves a separate issue: should the message length counter switch from 160 to 70 whenever a non-ASCII character is entered?

**Comment by rowanseymour** [comment]
Moved to https://github.com/nyaruka/floweditor/issues/802
