### ISSUE TITLE
ContactFields Management Page

### ISSUE THREAD

**Issue by dodobas** [rapidpro/rapidpro#870]
ContactFields Management Page is basically a standard List page.

Users can:
* add a ContactField (label, type)
  - by clicking an `Add` button above table
  - form opens in a modal
* update a ContactField (label, type, show_in_table)
  - by clicking a row in a table
  - form opens in a modal
  - *Delete* button is positioned on the modal

The list page is split into two tables: *Featured ContactFields* and *All ContactFields*
* *Featured ContactFields* table enables users to reorder the ContactFields by priority by dragging the field 
  - only FeaturedCFs are orderable by priority
  - the priority is used to order CFs on the Contacts List Page and on the Contact Details Page
  - no pagination, all featured CFs are displayed
  - clicking on the table row opens Update CF modal
* *All ContactFields* table enables users to manage all fields
  - this table is paginated
  - users can search for a CF based on *label* and *key*
  - clicking on the table row opens Update CF modal

Related to #821

**Comment by nicpottier** [comment]
I think combining these without pagination makes sense.

I do think sorting should only happen for featured fields, rest should be alphabetical. (not sure on the wording `featured` but I like the concept) I would guess then in the future we could let users pick how many /featured/ fields to show on list vs contact page. (perhaps thats even a user setting)
