### ISSUE TITLE
RP keeps trying to send messages to Facebook's blocked contacts

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#871]
# How to deal with contacts who blocked the FB page used as the RP channel

It's very common to have contacted who blocked the FB page used as the RP channel from sending messages to their profile.
That has already been addressed in #373 but no further action was taken. 

I will share my experience using a test FB profile and I really think contacts who blocked the page should be stopped (like done for Viber app) or give the workspace administrator a way to sort all contacts with failed messages and take actions, like removing/adding from/to a contact's group.

## Messages log 
A successful message sent logs a 200 POST request:
![image](https://user-images.githubusercontent.com/35577716/52874095-5de4a400-312f-11e9-9b88-d43c52deea67.png)

While a failed (due to blocked page) logs a 400 POST request:
![image](https://user-images.githubusercontent.com/35577716/52874528-9769df00-3130-11e9-8766-f913f1c9135d.png)

On the failed message log is also possible to see why hasn't been delivered to the contact:
![image](https://user-images.githubusercontent.com/35577716/52874476-6d182180-3130-11e9-9e95-348069e051ef.png)

Would be possible to have one of that log's data to create a RP feature to sort those contacts? That would be very helpful to avoid situations like this:
![image](https://user-images.githubusercontent.com/35577716/52874817-6c33bf80-3131-11e9-97c7-1090458cace9.png)

**Comment by nicpottier** [comment]
Ya, the problem here is that the error message that FB returns is not conclusive, they will return that error in other cases. I think at some point we did some calculations that if we got five of those in a row, then we could probably reliably determine that the contact has blocked us, but that then becomes an expensive query. That's probably ok though as its a fairly rare thing. Happy to look at a Courier PR if you want to put one together.

**Comment by WilliamTales** [comment]
Hey @nicpottier it tries for three times and drops (default behavior for all non-delivered messages), which makes it even worse.
I'm not an advanced developer with the required skills to make a solution like this xD
I'm more likely a RapidPro heavy user who analysis issues like this with technical details.

@edudouglas and @johncordeiro I think you could gimme a hand (or two) 8)

**Comment by nicpottier** [comment]
That's retrying a message, which is the right behavior, as I said, that error message can mean other things, it doesn't necessarily mean the contact has blocked you.

Looking at a wide range of data it was determined that if the last five messages for a FB contact end up failing then we should consider that contact as blocked. (they will then be added to the blocked group, removed from all groups, etc..)

So the work is on Courier to look at last five messages for a contact on a permanent failure if a FB contact and trigger a contact blocked event in that case.
