### ISSUE TITLE
Support for WhatsApp Templates

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#873]
WhatsApp requires outbound messages outside the 24hour contact window to be in the form of a pre-approved template.

RapidPro needs to incorporate the concept of templates to allow this to work for those workspaces with WA channels.

**Comment by johncordeiro** [comment]
I've read the doc about Template Messages and I see a challenge in the way how RapidPro would support it, given that textual flows are used for multiple channels that behave differently as WhatsApp to initiate conversations.

We could have a configuration page for WhatsApp Channel inside RapidPro, that I could manage Template Messages (using expression syntax of RapidPro) in multiple languages. These messages would be listed with its respective approval statuses.

Once WhatsApp is configured in the workspace, the flow could be created/edited exactly in the same way as it is today, however, when users try to "Start Flow" (just when WhatsApp channel is connected), it would be required to select one Template Message already approved by WhatsApp to initiate the flow to these contacts in the same dialog. I believe that it can avoid touching the flow engine that was designed for multiple channels.

![whatsapp templates](https://user-images.githubusercontent.com/6073075/53109763-53078600-3518-11e9-9162-08a92c74ec85.png)

Actually, I think that's difficult to explain the `Template Messages` capability to RapidPro users.

**Comment by nicpottier** [comment]
So a few issues I see there is that there flows can start with any number of things, splits etc, the first message for example could be a set of different templates based on some split that happens right at the start of the flow, we don't know it is always the same message. Even if we only had a single first message there would also have to be some crazy hacks to make the flow engine not send the first message but instead send this template instead. You can't do it all at the channel level because the channel needs the parameterized fields in order to forward the template on correctly. You also run into the super weird case that the flow definition will say one thing about the first message but what actually happened is something else entirely for WhatsApp users.

So you really need to have this integrated in the flow itself.

I think the approach we are going towards is introducing the idea of a message template at a top level in RapidPro. A `template` is just like any other RapidPro message which can contain variables in it.  Fields on a template would be:
 * id
 * slug
 * message (dictionary with keys per language)
 * fields (derived from message, but contains the map of field name to expression for substitution)
 * org_id
 * is_active

We would also introduce a `channel_template` model which would essentially be the many to many for a channel syncing the template above to its backend. Channel types would have to advertise whether they have the capacity to "sync" a template, and then would be charged with syncing those and creating the `channel_template` rows as necessary. `channel_template` is roughly:
 * template_id
 * external_id
 * status
 * modified_on

So users can create templates and depending on what channels they have picked these will get synced for approval etc..

Tricky bit here will be languages. As contact languages are ISO639-3 and WhatsApp expects a subset of country-code/ISO639-1. This may have to be a mapping defined at the org level where users select languages in general, though we may be able to auto-populate the most common options.

In a flow, you can select to "Send a Template", which lets you pick from available templates. At flow execution msgs are created with real text message as determined by the flow engine and template content but `metadata` is also populated with the template name and substituted fields. Channel implementations in Courier can look at metadata when appropriate and take the right action.

So from the user's perspective, they have a new template management section in the interface where they can create / delete templates. And in flows they have a way of sending a template. When a user tries to start a flow and they have a template enabled channel they will be warned if their first action is not a template or their template is not synced, they can continue anyways if they want (they may know they are not in the 24 period).

We'll need to create API endpoints for at least the listing of templates on an org for U-Partners use. We'll also need to augment the `broadcast` API endpoint to allow the specification of an optional template to send.

Finally we'll need to change CasePro to use above endpoints to get available templates and make them available as responses when appropriate.

**Comment by nicpottier** [comment]
Note this is all a bit more complicated than we originally thought because the set of languages supported by WhatsApp is actually quite limited, and they do not support all country-code / 639-1 combinations. So we have to decide what to do in those cases.

@smn this issue is also up your alley, any comments on direction?

**Comment by smn** [comment]
@nicpottier yeah, the language issue is not great. They're not supporting an official list or standard and not all of the languages we're supposed to support in South Africa are part of the list they're maintaining. I'm talking to them to find out what can be done. I'll be sure to let you know as I learn more.

Just a heads up that at some point much of this stuff will likely be automate-able. It doesn't solve the language issue but it is something to keep in mind. Happy to discuss further in separate channels.

**Comment by nicpottier** [comment]
By automate-able you mean the beta API to create these or something else?

**Comment by nicpottier** [comment]
So @rowanseymour and I pow wowed about this some more on how this all fits into new engine and how languages are treated.

Since the set of supported languages by WhatsApp is a constant, that's going to be tied to the scheme (`whapsapp`). When a `send_template` action is encountered in a flow, goflow fill first determine if the contact's language is supported by the scheme it is sending to (other schemes will support all languages), then look at whether the template has been translated to that language. If either of those is false, then the org's base language will be used.

Goflow then does the substitution into the template in that language so that mailroom can write the physical message to the DB, but also includes the language that was picked (ISO 639-3 still), the variables that were substituted and the template slug. The latter three items are stuffed into metadata for the msg and passed to courier. Courier channel types do what they will with that when sending, most will just send the physical message, but WhatsApp implementations will translate the ISO 639-3 code to the country/ISO 639-1 code and send the template onwards appropriately.

There are doubtless some devils in the details here but that seems fairly clean. The big assertion here is that the org primary language MUST BE one of the supported WhatsApp languages and that all templates must have a translation to that language.

**Comment by nicpottier** [comment]
So as we've dug into this more I think our thinking is changing a bit due to a few different factors:

1. Managing templates completely within RapidPro is looking more and more like a WhatsApp specific thing. Even other WhatsApp providers such as Twilio and Nexmo don't provide APIs for managing these and seem to push users to the Facebook / Whatsapp console for management. I think this combined with the UI for managing rejection status, resubmitting etc, makes is clearer that taking this on is just an exercise in futility. So I don't think we are going to have RapidPro specific management of templates, rather RapidPro will sync the available templates.

2. We don't want the UI for sending and receiving templates to be confusing to users, so I think we are going to make templates be an attribute of a `reply` action instead of a new action itself. If you have a WhatsApp channel connected, then you will see a tab on that action to set a template for your message that will let you select one of your approved templates to send and the substitutions you want to make into that template. This also simplifies the problem of what message to send to people who aren't on WhatsApp, they get the normal reply action text as expected.

  From a goflow perspective this then becomes a series of steps. First we check if the URN we are going to send to is WhatsApp, if not, they get a normal message back. If so, we see if there is a template, if not, they receive a normal message. If so, then we figure out the best language to use based on that template (templates are still assets) and that is included in the `msg_created` event along with the raw text of the message.

3. We still want to warn users when doing a flow broadcast with a connected WhatsApp channel. In those cases they will still be warned if their starting reply actions do not have templates set on them.

**Comment by smn** [comment]
@nicpottier yeah, with automate-able I did mean the beta message template API, wasn't sure how public that information was.

We've just launched an internal API for managing these message templates but it's extremely limited in what it can do. We've decided to just mimick the message template API itself but have made authentication a bit simpler.

Right now only a create operation is supported by FB and we poll the API endpoints at regular intervals to see if any of them templates created have had a change in their approval status. We also validate any outbound messages against the list of known message templates and reject any API calls for templates that aren't recognised.

What further complicates things is the limited language set that is currently possible which forces everyone to maintain their own mapping of actual languages used to languages supported but likely not used.

I think your suggested approach of making a template an attribute of a reply makes sense for normal flows. One edge case to keep in mind is that message templates do not allow for any kind of media attachments like images or audio files. If you're linking these to a reply rather than making them a separate action then perhaps that's something to alert the user about if message templates and attachments are used in the same reply.

How are you thinking of tackling this with campaigns? Is your thinking that if people want to use a campaign with message templates they'll always have to use a flow for that campaign even if it's a single bit of text content needing to be sent?

**Comment by nicpottier** [comment]
Good point on attachments, will have to warn of that case as well.

I think trying the wrap the API around template management is just a fool's errand, at least right now while there's still so much in flux and their policies will change. IE, once I started thinking through what the use case would look like if a template was rejected, resubmitting, etc, then it all seemed a crazy thing. (not to mention support tickets from users asking why WE rejected their template and expectations around that) That Twilio made this same choice of punting and making people manage templates through the WhatsApp/Facebook page kind of settled it for us.

One way sync is also way more sane.

Campaigns are already flows internally (even for the simple message case) but yes, campaigns on WhatsApp enabled accounts will need to be explicit flows for the user to configure templates as well.

**Comment by smn** [comment]
Not sure if this is relevant information but what we were considering doing to address this was to provide a webhook endpoint for RapidPro for each message template we know of.

This endpoint could be configured in the UI to provide a mapping of `{{1}}` style placeholders to named variables from a flow's context. To submit a message template from a flow one would need to provide the URL for that message template in a webhook action. The full context of the flow is posted to the endpoint and it would then resolve the variables to placeholders and send the message template.

The obvious downside to this is that the burden of ensuring the variables are correct and the language mapping works between two systems is pushed to whoever's maintaining the flows.

**Comment by nicpottier** [comment]
Hrmm? I must be missing something here. Why this approach? Isn't this just an action in a flow that says how the user wants these substituted? (and then metadata on the message?)

**Comment by smn** [comment]
Sorry should've clarified, this was our thinking of how to go about working with message templates in RapidPro before you opened this ticket. We had not yet started work on that and your proposed way forward is much better.

**Comment by nicpottier** [comment]
This is done, closing.
