### ISSUE TITLE
Paging to page 201 in ES search fails

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#876]
Fetching page 201 of a contact search blows up with the following:

> TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [10050]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')

Sentry error:
https://sentry.io/nyaruka/textit/issues/899727966

Ticket:
https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/155984/conversations/20908596934

**Comment by dodobas** [comment]
Do we know a use-case for users to open page 200 in the contact list page ? Maybe we could turn this limit into a "feature" of the platform?

- we are using standard ElasticSearch result which is by default capped at 10000 results
  - the limit is that users can only browse 10000 results, (from, size params), 200 pages
  - pagination is compatible with Django Pagination (ES-DSL uses Python slices to specify *from* and *size*)
  - users can jump to a random page

- options:
  - limit view to max 200 pages (a.k.a. don't do anything, just don't crash)
    - we don't expect normal users to manually click through Pagination and check every page in order to find a contact
    - users can export contacts and use other tools to search for a contact
  - increase ES **"index.max_result_window"**
    - this is not recommended, uses more heap memory and takes longer to access each following page
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings
  - use ES *scroll* method
    - scroll method is optimized for accessing large datasets
    - ordering in not supported by default - can be activated but it's going to slow down the search
    - paging is not supported - we always get **ALL** of the dataset
    - should not be for 'real time user requests'
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html
  - use ES *search after* method
    - recommended for "deep pagination"
    - not possible to jump to a random page - ideal for 'endless scroll/pagination' pages
    - every search result has a 'pointer' to the next result set - `search_after` parameter
      - not possible to simply jump at page 30 without getting a result set search for page 29
      - a 'page' is defined by `size` and `search_after` parameters
    - integrating with current Django pagination might not be simple 
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

**Comment by nicpottier** [comment]
Thanks for the clear enumeration of options. I personally don't think we need to paginate that far and would support just turning it off after 20 pages.

Worst case the user can create a dynamic group and page that right?

**Comment by rowanseymour** [comment]
I'd be fine with the UI giving users a warning that we only show the first 200 pages of results.

Don't we use ES with contact exports? That is a little more awkward to limit to 10,000 results... tho again they can create a dynamic group. Just need to be clear about that limit.

**Comment by nicpottier** [comment]
I think exports are fine, you can use scrolling for that. Problem here is the skipping around I think.

**Comment by ericnewcomer** [comment]
Ya, and same for dynamic group creation. Basically anything other than paging searches is non interactive. Do those currently blow up today in the same way or are they already scrollling?

**Comment by dodobas** [comment]
We do the right thing and use *ES scan* for exports and dynamic group reevaluation, it works as expected ... https://github.com/nyaruka/rapidpro/blob/master/temba/contacts/models.py#L750

@nicpottier yes, a user can create a dynamic group and then paginate to a random page. We will read contacts from the DB (*contacts_contactgroup_contacts* relation) as long as `search query` is undefined.

This *feature* is only enabled for users that use search query and want to open page 201. :)
