### ISSUE TITLE
Add a set preferred scheme action

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#881]
We currently have a `set_channel` action. Although this is occasionally used to force use of a particular channel with the same scheme (IE, force using a shortcode instead of a long code or vice versa) it is more often used as a way to set the contact method to a contact to an IP channel. (say Telegram of Facebook)

In these cases, the specificity of the `set_channel` action is a detriment, as it actually creates a very fragile flow that will likely only work in the org it was authored in. Either adding a new action that allows setting the preferred channel based on scheme or changing this action to allow specifying either the scheme OR uuid would help make flows more interoperable.

**Comment by rowanseymour** [comment]
This seems to serve the same purpose as https://github.com/rapidpro/rapidpro/issues/452 but I think would be easier to use

**Comment by rowanseymour** [comment]
Tho it wouldn't allow changing of priority between URNs of same type (two tel numbers).. so maybe not? I can't imagine that's nearly as common as wanting to switch a tel contact to an IP channel

**Comment by matthaikin** [comment]
Different use-case but similar functionality.

We have a network we are working with, and they use a mix of SMS and WhatsApp - some have just one channel, but same communicate with us using both (depending on data/airtime I imagine).

So we have, for example contact NAME who has both a telephone number and a WhatsApp URN in their contact.

I cannot see any way to choose how to communicate with them - the Send Message seems to default to WhatsApp (not sure about this as it doesn't indicate), but we need to be able to:
 - sometimes, manually select to send a SMS or send a WhatsApp
 - often, send a message/flow to a group, and understand how it will choose a 'preferred' channel, and be able to change this preferred channel on a per-user basis

Hope this use-case helps in scoping the solution

**Comment by nicpottier** [comment]
This is something you can definitely do now by using the "update contact" -> "channel" action to either the WhatsApp or SMS channel, but yes, being able to pick the scheme instead would be more convenient.

**Comment by matthaikin** [comment]
Ah yes thats helpful - different use-case from adjusting the individual users default channel, but I can see a few ways we might want to use that.

Is there any easy way to work out what the CURRENT channel is (I assume it defaults to.... last-used, or last-channel-added or there is a persistent heirarchy or something, but couldn't see any way to identify this in the UI).

**Comment by nicpottier** [comment]
Ya, this isn't super well exposed in the UI, because it is a bit more complex than you first think.

Each URN has its own preferred channel, because not all channels can talk all schemes and not all channels can even send. So it is really more about the highest priority URN first, then the channel that is set on that URN.

As you guess, we change the preferred URN based on how the contact last communicated with us. IE, the assumption is that the contact wants to receive a response on the same channel/URN they last used. That works correctly and without surprise 99% of the time, but ya, there are use cases where it doesn't.

If the contact is brand new, then yes, we then look for the oldest channel that can reach that URN, with some additional magic for telephone channels where we try to find the channel that has the largest prefix overlap with the address of the contact. This tends to be helpful in cases where say your channels are long codes on particular carriers and you would prefer to use the same carrier as the contact to send the message. (in many developing countries number porting isn't really a thing and carriers have set prefixes)

**Comment by rowanseymour** [comment]
In expressions in flows you can access the result of that calculation @nicpottier is describing as `@contact.channel` - you can think of that as _the channel we will use to send to that contact_.
