### ISSUE TITLE
Support Viber Welcome Messages

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#883]
Viber allows channels to advertise "sticker packs" and when they are downloaded they trigger a `conversation_started` callback.

https://developers.viber.com/docs/api/rest-bot-api/#SendingWelcomeMessage

Trick is that the `conversation_started` callback does not permit you to send a message in the usual way, instead in the same HTTP response of their call you may include a "welcome message" encouraging them to reply in some way, at which point you can converse with them as usual.

We don't currently have any way of dealing with these though they are very similar to other events from Facebook etc.. the challenge here is that the response must be synchronous.

Some options:

1. We could hack in a message in the channel config that is hard coded and just reply with that. IE, on the Viber channel page you get a dialog where you can set your "welcome message". Courier then sends that back for any `conversation_started` event.

   Only complicated bit is that Courier really doesn't create outbound messages today, only incoming, and doesn't assign topups to them either. So we'd have to teach Courier how to insert outbound messages and teach Courier how to assign topups to them. This will keep the contact history accurate.

   This also doesn't fit into the natural way we do things in RapidPro (IE, this feels a lot more like a Trigger than some channel config)

2. Courier could synchronously hand the message to a HTTP Mailroom endpoint for "handling" and we deal with the response and pass it back. This could essentially start the contact in a flow based on that event and get a response.

   Downsides here are that there are some restrictions that are probably confusing to the user. You can only send one message for example in the flow you trigger. Since you can't initiate messages to the contact until they reply, any timed actions such as timeouts / campaigns etc, won't work properly either.

   From a technical perspective having Courier call an HTTP endpoint for Mailroom also sounds a bit nuts.

   Upside is that creation of the outgoing message, assigning a topup etc, is all handled within Mailroom today anyways, and you do get to do all the usual contact manipulation you want / expect to be possible.

**Comment by norkans7** [comment]
Something like the campaign messages that are flows in the background and not edited modified on the flow editor.
So the messages is added on the channel form and saved as a system flow and the option 2 is used.

**Comment by rowanseymour** [comment]
Don't like the idea of courier having to learn about creating outgoing messages and topups etc... but really struggling to think of a solution I do like.

Wonder if it's time to think about "classes" of flows and how you communicate to the user that a flow meets some criteria to be considered a certain class of flow. For example in the past we've talked about "worker" (?) flows which don't have any waits or sends. Maybe another class of flow is the a "welcome" flow which has to start with a single send message followed by a wait.

**Comment by nicpottier** [comment]
The other way to look at this is this is a fringe feature of a fringe feature (we don't have many Viber channels and we don't have many sticker packs being created for Viber channels).  So maybe we should just take the dirty hack way (maybe we don't even create the outgoing message, just send it for the welcome event) and revisit when we see greater usage and or another similar use case on another channel?

**Comment by ericnewcomer** [comment]
That there isn't a model of this from any of the myriad channels we support I wholeheartedly support a quick and dirty solution here with plan to revisit if things change.

**Comment by rowanseymour** [comment]
Yeah... I'd say go full dirty for now and don't even create the msg

**Comment by ericnewcomer** [comment]
Never go full dirty

**Comment by nicpottier** [comment]
I'm slightly appalled at how fast you guys went full dirty hack on me, but ya, I think that's the way forward until we see this again.

**Comment by nicpottier** [comment]
Ok, @norkans7 can you drive this?

Seems like we need:

1. A way to set a welcome message on a viber channel, can just be a simple message that is added to the channel config
2. Update courier to react to that event by replying with that welcome message if configured
3. We should still create a channel log and channel event for these cases, which will help a bit from an auditing perspective

**Comment by norkans7** [comment]
For 3 We add a new type `WelcomeMessageSent` event to make is distinct to the `newConversation` one we have now? @nicpottier

**Comment by nicpottier** [comment]
Sure, that sounds like an ok middle ground.

**Comment by johncordeiro** [comment]
hey @nicpottier, I talked with my team and we totally agree with the middle ground solution, and we would like to help on it. PR welcome here? (planning to start the Sprint next Tuesday)

**Comment by norkans7** [comment]
@johncordeiro This is already in progress 

https://github.com/nyaruka/rapidpro/pull/2347

https://github.com/nyaruka/courier/pull/222

**Comment by paradoxxjm** [comment]
Hey @nicpottier @norkans7 can you create a documentation page that provides context on how this can enabled. We have a team that is using this feature in a campaign and we would like test it with them. Nothing has been added yet to the Help Center.

**Comment by nicpottier** [comment]
Sure, can you have them open an issue on the RapidPro site and we can give
them a hand and make sure an article gets created?

**Comment by nicpottier** [comment]
This was added, closing.
