### ISSUE TITLE
Use consistent terminology in UI

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#884]
For example the thing which stores a user configurable attribute on a contact is referred to a "field", a "contact field", a "custom field" or a "custom contact field". Context does matter and they don't necessarily have to be exactly the same (e.g. in the context of looking a contact, it might be ok to say just "field"),  but we should make a glossary document that defines such rules.

Examples in the UI:

<img width="357" alt="captura de pantalla 2019-03-06 a la s 09 38 16" src="https://user-images.githubusercontent.com/675558/53889161-e8fcdf80-3ff3-11e9-87c5-6f87d731ba2a.png">
<img width="577" alt="captura de pantalla 2019-03-06 a la s 09 35 08" src="https://user-images.githubusercontent.com/675558/53889164-e9957600-3ff3-11e9-93d3-773770a3bdd2.png">
<img width="427" alt="captura de pantalla 2019-03-06 a la s 09 40 17" src="https://user-images.githubusercontent.com/675558/53889169-ec906680-3ff3-11e9-838b-5110b161f7c8.png">
<img width="713" alt="captura de pantalla 2019-03-06 a la s 09 38 51" src="https://user-images.githubusercontent.com/675558/53889171-edc19380-3ff3-11e9-82c8-04ce08145e40.png">

In help docs:

<img width="678" alt="53832739-ceffc600-3f3b-11e9-9611-fef52cae074a" src="https://user-images.githubusercontent.com/675558/53889244-16e22400-3ff4-11e9-84e2-bcb430ad7260.png">

**Comment by nicpottier** [comment]
Definitely useful to hash this out. I don't think we are *too* bad here though.

A contact field may be something "custom" or built in. ie, `created on`, `language` and `name are contact fields, but `age` is a custom contact field right? At least that's how they are treated in the flow editor for example.

So I think if we are talking about you updating a value on a contact (that isn't a URN) then using "Contact Field" is ok. If we are talking about someone creating a new field, then using "Custom Contact Field" is also correct.

"Field" may be appropriate depending on the context, IE, if you are already in a sentence talking about contacts, then using the term "field" there I think is also acceptable.

Totally down for discussion on all that but that's how I see it.

**Comment by rowanseymour** [comment]
FYI this comes from https://github.com/nyaruka/rapidpro/pull/2337#discussion_r262092997
