### ISSUE TITLE
Merge flow path counts for rules that become merged exits

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#885]
When we migrate a flow from the legacy format to the new format, multiple rules with the same name can end up being a single exit. The old editor takes care of merging the path counts from multiple rules into a single exit, but once we convert the definition permanently we lose information about which rules became which exits

**Comment by nicpottier** [comment]
Do we still need this for v5 @rowanseymour ?

**Comment by rowanseymour** [comment]
yes.. anyone upgrading a flow right now which has merged exits is going to see potentially wrong path counts
