### ISSUE TITLE
Update documentation of API definitions endpoint, warn accounts using it about flow spec changes

### ISSUE THREAD

**Issue by norkans7** [rapidpro/rapidpro#891]
with the new editor, what the flow definition is available on the API?

**Comment by norkans7** [comment]
This is needed by U-Report

**Comment by ericnewcomer** [comment]
What precisely does U-Report need from the definition? It will need to operate on the new format for sure. Ultimately there will be no old format. This endpoint is private ya?

**Comment by norkans7** [comment]
It is public, It uses it so get the poll questions, I guess then that will be a V3 API endpoint and all flows will have that so U-Report can switch to use that new endpoint

**Comment by ericnewcomer** [comment]
Oh shoot. Didn’t realize that was a published endpoint, it sure is. Problem with versioning is the v2 endpoint will cease once we flip to the new editor. We may just have to see who (if anyone) is using it and change it over.  If UReport is the only customer we can start that switch now.

**Comment by rowanseymour** [comment]
It's also used by Surveyor but it's now updated to support either format. TBH I don't feel like the contract of this API endpoint was to always return flows with the same schema internally. We should send something to the dev list to warn people that the flow format is going to change, but I think U-Report just has to be able to accept either format.

**Comment by ericnewcomer** [comment]
Dev list I’m less concerned about. We need to identify if any of our customers are using it.

**Comment by nicpottier** [comment]
Agree we should track down who is using it, but ya, I don't think endpoint changes. Flow definition format changing is no different than us migrating it in the past, flow format has always been a moving target on this endpoint.

**Comment by norkans7** [comment]
I saw we include the flow version, so we can allow a GET parameter to specify with version to return

**Comment by rowanseymour** [comment]
I think the only useful usecase there would be getting a migrated (12.0) version now from a 11.x flow so you can test parsing a 12.0 flow in UReport. Going forward, picking a flow spec version on this endpoint isn't going to make any sense.

**Comment by nicpottier** [comment]
Agree we likely don't want to make this a parameter.

If we include the version number in the export I guess we should be able to test U-Report and make it work with both versions, there will just need to be some good testing on the U-Report side so we know it will work as flows flip to 12 a little by little.

Norbert think you can get enough test cases  just using the assets endpoint for the time being to make sure this works well when we flip to 12? (we will also be able to test by creating these manually once we allow native authoring in 12 (soon!))

**Comment by nicpottier** [comment]
Closing.. U-Report now uses flow metadata for what it needs.
