### ISSUE TITLE
Replace engine level loop detection with a limit on number of steps in a sprint

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#893]
Currently...

1. the editor detects loops within the same flow
2. `Flow.update` looks for loops within the same flow
3. the engine errors if it visits the same node more than once in a sprint
4. the engine errors if enters a flow more than once in a single sprint

Maybe for simplicity we just put a limit on the number of steps you can take in a single sprint (100 ?). If you hit that limit, the session is errored, and mailroom doesn't send messages or apply other events.

Downside is engine would have still performed things like webhook calls.

I think the editor would still try to prevent intra-flow loops?

**Comment by nicpottier** [comment]
I like this better than trying to detect cycles ourselves which is essentially impossible to do without being either too strict or too loose. Do agree for the time being editor should discourage / disallow loops but engine should just limit number of steps.

**Comment by rowanseymour** [comment]
Ok so immediate implications are that the engine's flow validation won't include loop detection - I need to remove that on the RP side soon as RP won't know about the internal workings of flow definitions.

**Comment by rowanseymour** [comment]
Added in engine with https://github.com/nyaruka/goflow/pull/574
