### ISSUE TITLE
Triggers won't work for non latin script languages

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#898]
# Description

Keyword's trigger takes no action when the word set is in non latin language.

## Example

ยกเลิก
> Thai word

বাতিল
> Bengali word

ထွက်သွား
> Burmese word

https://github.com/rapidpro/rapidpro/blob/aa18fac9d2c0ffa5eceb0a3c812d9cca20dda7af/temba/triggers/models.py#L364

**Comment by norkans7** [comment]
It seems those are not words rather multiple words

https://regex101.com/r/GXRALg/1

**Comment by nicpottier** [comment]
Hard to say, don't speak any of these but google translate says the Burmese means "Augustine", the Bengali means "Cancel", and the Thai means "Canceled" so probably a valid argument that these should be able to be used as triggers.

**Comment by norkans7** [comment]
https://github.com/rapidpro/expressions/pull/34

**Comment by nicpottier** [comment]
Nice Norbert. @rowanseymour what's the story with `utils.TokenizeString` do we do the right thing there in goflow?

**Comment by norkans7** [comment]
Nope, I am making a PR, however that means ℹ️ will no longer match i

**Comment by nicpottier** [comment]
I think I'm ok with that. :)

**Comment by norkans7** [comment]
https://github.com/nyaruka/goflow/pull/586/

**Comment by norkans7** [comment]
Fixed in https://github.com/rapidpro/rapidpro/pull/900
