### ISSUE TITLE
Listing all workspaces account's access

### ISSUE THREAD

**Issue by WilliamTales** [rapidpro/rapidpro#904]
# Description
At https://rapidpro.../org/manage/ there's a list of all accounts granted access to that workspace. 
![image](https://user-images.githubusercontent.com/35577716/55362327-0b2d3480-54b0-11e9-9a94-98cf9a7e940c.png)

Would it be possible to have the same feature for accounts page? https://rapidpro.../users/user but listing all workspaces that account has access and its role.
![image](https://user-images.githubusercontent.com/35577716/55362648-fd2be380-54b0-11e9-844b-61ccc8a7ef31.png)

**Comment by nicpottier** [comment]
I think we'd be fine with this and happy to accept a PR for that change.
