### ISSUE TITLE
Agent user role

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#909]
Role that can view contacts and flows but can't edit them. What sets them apart from viewers is they can send messages and interact with contacts.

**Comment by rowanseymour** [comment]
This plus a few tweaks to contact read pages would allow RP to be used like a basic ticketing service.

Where it might get tricky is that orgs are going to want different levels of permissions for this user class - you can imagine some orgs wanting agents have free reign to interact with any contact, whereas others would want something more like CasePro where agents are typically external and should only be allowed to access to tickets that they've been assigned to.

**Comment by rowanseymour** [comment]
We added this as part of initial work for internal ticketing
