### ISSUE TITLE
New engine: expiration not being set/updated in revision definitions

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#913]

**Comment by nicpottier** [comment]
Fixed in https://github.com/nyaruka/mailroom/commit/3655e38cd5757b7ad0d758c34c3df781e28565cd

Mailroom now always honoring flow setting and overriding definition.

Open question is whether we want to remove the flow setting entirely and ONLY store it on the definition. That makes RapidPro have to know about flow formats though. (it kind of does already as it creates an empty flow definition on new flows)

Leaving this open for discussion.

**Comment by nicpottier** [comment]
Note the same issue exists with the name of flows.. that are also double represented in the flow definition itself and our flow model.

Again, can change mailroom to override that, but is that the right approach?

@rowanseymour any thoughts?

**Comment by rowanseymour** [comment]
Same with UUID. I'm ok with RP knowing about a few fields at the root level of a flow definition. And it makes sense from a querying pov to pull some things out of the definition and save on flow itself.

**Comment by nicpottier** [comment]
Ya, feel like the right approach is probably do both things. IE, update the definition based on name / expiration / uuid changes but also have mailroom always defer to DB as well when building defs.

I can take care of that.
