### ISSUE TITLE
Contact field creation not honoring is_active

### ISSUE THREAD

**Issue by ericnewcomer** [rapidpro/rapidpro#916]
Repro steps:

1. Create field
2. Delete that field
3. Create that field again (or create it again from the flow editor)

**Comment by dodobas** [comment]
can you think of any issues if we reuse/duplicate the key? 

User deletes a field (label="Age", key="age") and then recreates that field with same label (key will be generated from the label), this "new" age field does not have any relation to the old one, it has a completely new uuid.

The other potential problem is that we use `ContactField.get_or_create` to access and create fields, and let's say that someone is using the API to update contacts. Even if the field is deleted, if the payload contains `"fields": {"age": 83}` a new field will be created with the same label and key, is this what we want?

**Comment by rowanseymour** [comment]
Engine knows nothing about field UUIDs so no problem there. 

Certainly can't force the user to pick a new key just because there was once a field with that key, so re-using seems correct.
