### ISSUE TITLE
"Starting Someone in Flow" creates an Improperly formatted new Account

### ISSUE THREAD

**Issue by LisaBinIL** [rapidpro/rapidpro#921]
Our INVITE flow is creating an account for the newly invited user.  But then when that new user responds, another new record is created.  This is a new behavior.  In the past, the new user would simply be on the account where they were originally contacted.

I've recreated a simple version of this in Textit.
This user https://textit.in/contact/read/d6c828e0-3e54-4285-a04e-0c8aac1bc39b/ "invited" a cell phone.  
The `invite` flow created this user: https://textit.in/contact/read/6b5c31c6-c9c1-4330-a324-f49b7e8502f3/ and then ran `hi to user`
However, when the new user responded, a new account was created: https://textit.in/contact/read/5c3a9020-2ddc-4dc3-926e-b7680c8397ab/

I then tried `invite` again and formatted the phone number with the 1 prefix to see if that would make a difference, but it did not.  Another new account was created: https://textit.in/contact/read/e327a676-cc30-4b10-a2cd-4bb5ba17c71e/
This is particularly troublesome because the account technically already existed (twice actually), so now I've got 3 records for one cell number.

FYI the cell number used for testing _is_ receiving all of the "hi" texts regardless of the formatting.

**Comment by LisaBinIL** [comment]
FYI... it seems if the user doing the "inviting" puts the "+1" on the number rather than just the 10 or 11 digits, then it works like it originally did.
See this user:
https://textit.in/contact/read/9f71f834-0015-4663-ac88-8881aa4bfc24/

The text from https://textit.in/contact/read/d6c828e0-3e54-4285-a04e-0c8aac1bc39b/  and the reply of "thanks" is all in the same account rather than separated into 2 account as detailed above.

**Comment by LisaBinIL** [comment]
Also, entering the phone number like this (xxx) xxx-xxxx does not seem to work at all (and it definitely used to).  See log of:
https://textit.in/contact/read/d6c828e0-3e54-4285-a04e-0c8aac1bc39b/
No contact was created for that last number.

**Comment by rowanseymour** [comment]
I think this is fixed by https://github.com/nyaruka/goflow/pull/672 (latest mailroom has this) but I don't think I can update that in resistbot.

**Comment by nicpottier** [comment]
Closing as its been addressed.
