### ISSUE TITLE
Remove docs for account-level webhooks

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#922]
![image](https://user-images.githubusercontent.com/82857/57237103-7f4d8180-6ff4-11e9-8ddf-7e2aa3ef7a3a.png)

According to [RapidPro documentation](https://app.rapidpro.io/webhooks/webhook/):

>Your web service should return a 200 or 201 status code to mark acceptance of the event. If a 400 or 500 status code is returned then RapidPro will retry delivering the event up to three times. You can view a log of recent events through your API Log when logged in.

I haven't seen any retries in our logs. Is this a setting? Is this a bug? Or are the docs incorrect?

**Comment by rowanseymour** [comment]
That documentation is for non-flow webhooks - i.e. account level webhooks that we make in response to a message being received etc. In-flow webhooks have never done retries because they need to be synchronous.

However we've been removing non-flow webhooks ensuring orgs that don't already have them can't create new ones.. so we're probably ready to delete these docs. All webhooks now need to be done via flows.

**Comment by cromulus** [comment]
Any reason why? We need to send every single sent/received message to another service. We were using web hooks for that. 

How do we go about doing that now?

**Comment by nicpottier** [comment]
It wasn't really maintainable. People start flows with millions of users and then get surprised that they get browned out, expect us to retry etc..

Either using flow webhooks on the things that really matter or polling one of the API endpoints is how this is done going forward.

**Comment by cromulus** [comment]
Hmm... seems like a premium feature to me!

For the rest of us, especially those of us who host an instance ourselves, this functionality is tremendously valuable.

**Comment by cromulus** [comment]
For what it's worth, my use case is being able to jump into a flow with human if need be, as well as having both automated rapidpro flows and person to person communication over the same channel.

Real time webhooks are less crucial for the first, but essential for the second.

**Comment by nicpottier** [comment]
Removed in upcoming upmerge. (cleaning up issues beforehand) Closing.
