### ISSUE TITLE
Telegram MMS Failure

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#926]
Just started happening today, can't really figure out why. URL is valid. Works on other channels. If its Telegram, apologies and please close out. Has been happening all day.

```
400 POST https://api.telegram.org/bot375322948:AAE2uZQVS4Bt3fFiyufTqYfT2n8H6WroRsQ/sendPhoto
POST /bot375322948:AAE2uZQVS4Bt3fFiyufTqYfT2n8H6WroRsQ/sendPhoto HTTP/1.1
Host: api.telegram.org
User-Agent: Courier/1.2.138
Content-Length: 382
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

caption=Here%27s+a+letter+someone+near+you+wrote+a+day+ago.+Want+to+see+another+one%3F&chat_id=424985247&photo=https%3A%2F%2Fresistbot-scribe.s3.us-west-2.amazonaws.com%2Fc7bb8e19-9fa0-463a-933f-af7e1ea66c9b.png&reply_markup=%7B%22resize_keyboard%22%3Atrue%2C%22one_time_keyboard%22%3Atrue%2C%22keyboard%22%3A%5B%5B%7B%22text%22%3A%22Yes%22%7D%2C%7B%22text%22%3A%22No%22%7D%5D%5D%7D
HTTP/1.1 400 Bad Request
Content-Length: 99
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
Connection: keep-alive
Content-Type: application/json
Date: Tue, 14 May 2019 21:28:28 GMT
Server: nginx/1.12.2
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

{"ok":false,"error_code":400,"description":"Bad Request: wrong file identifier/HTTP URL specified"}

Error: received non 200 status: 400
```

<img width="870" alt="image" src="https://user-images.githubusercontent.com/82857/57733709-258d2d00-766e-11e9-8749-5d48dbde6fbc.png">

**Comment by nicpottier** [comment]
I would give that photo URL a test and make sure that's valid. Pretty sure this has nothing to do with RapidPro.

**Comment by putorti** [comment]
That was the first thing I did, it works fine, and works in the other platforms: https://resistbot-scribe.s3.us-west-2.amazonaws.com/c7bb8e19-9fa0-463a-933f-af7e1ea66c9b.png

**Comment by nicpottier** [comment]
Ya, don't know, all those parameters look right. Maybe that file wasn't available on S3 yet at the time or maybe Telegram doesn't like that specific file. They seem somewhat arbitrary:
  https://core.telegram.org/bots/api#sending-files
