### ISSUE TITLE
Allow anon orgs to see channel logs

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#929]
Currently we disallow administrators on anonymous orgs from seeing channel logs because those logs may contain phone numbers in them. This is a bummer because there's a lot of self-servicing around WhatsApp and Facebook that could take place if they could see them.

It seems like we could filter out those numbers dynamically when we render that page for anonymous orgs, by looking at the URN that was sent to and masking out that phone number. This would retain anonymity but allow people to see details as to how a message was sent or failed. Could all be done in the views that show those logs.

**Comment by rowanseymour** [comment]
Added in https://github.com/nyaruka/rapidpro/pull/2410
