### ISSUE TITLE
Use a TextArea for URL field on  Add External Service page

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#93]
See: https://textit.uservoice.com/admin/tickets/683/

**Comment by knightsamar** [comment]
Ticket details cannot be accessed :) Asks for login details and signing in with Google account doesn't work. Can you please copy-paste the details here ?

Thanks.

**Comment by nicpottier** [comment]
Hi there,

The issue is essentially just that the URL provided on the webhook dialog (in a flow, on a ruleset, select "webhook") can't be easily copy/pasted.

Having a way (perhaps a link) to copy it to the clipboard is probably the most elegant solution.

**Comment by bbbb99** [comment]
thank you
