### ISSUE TITLE
Cross org credit-transfers should use newest topup

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#930]
Currently when transferring credits between a parent org and child org, we use the oldest valid topup to transfer from. This leads to confusion especially around renewals because they transfer credits that will expire in just a little while.

Which we transfer from is pretty arbitrary really, but it seems like it would generally be less confusing to users if we used the newest topup instead of the oldest to prevent that behavior.

**Comment by dodobas** [comment]
when transferring credits between orgs we use `decrement_credit` method that is used in normal case, decrementing a credit for sending/receiving messages. In that case we **do** want to decrement credits from the oldest topup (https://github.com/nyaruka/rapidpro/blob/689bc0f8e81f06f724c6403c1e98a77a97459f21/temba/orgs/models.py#L1618).

in the case when transferring credits, we use a loop to iterate over valid topups and decrement credits until we collect all the required credits (https://github.com/nyaruka/rapidpro/blob/689bc0f8e81f06f724c6403c1e98a77a97459f21/temba/orgs/models.py#L1506). Even if we change traverse order of valid topups we still might get to the same problem when a topup, that will expire soon, has to be used to transfer credits to a suborg.

what if we would set the `topup.expires_on` for the new created topup (org -> suborg transfer) to the same value as the *newest* topup of the parent org? This effectively 'extends' the credit validity, which is probably not what we want?

or we simply don't send topup expiry emails to suborgs?

**Comment by nicpottier** [comment]
Not sending emails? How does that solve things?

Extending validity is basically giving money away, so would rather not do that.

Apart from it being work, what's the arguments against having different traversal rules for when decrementing topups for sending msgs vs assigning to sub-orgs?

**Comment by dodobas** [comment]
well, if suborgs can't add topups for themselves, is there a reason for suborgs to get emails about something that they can't control?

there are no arguments against having different traversal rules for assigning topups to suborgs, but we will eventually have to use a topup that is going to expire soon because there is not enough transferable credits on most recent valid topup, and that would still trigger confusing emails (although probably not so often)

**Comment by nicpottier** [comment]
Suborgs usually have some organizational (in meat space) connection to their parent, so yes, getting an email is important, it is warning them that their service is about to stop working and they should bug their parent for more credits.

Yes, obviously if the parent has only near-expiring credits then the child will as well.
