### ISSUE TITLE
Webhook Simulator missing URI.js

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#931]
Can't test web hooks here `/webhooks/webhook/simulator/` due to this error: 
```
ReferenceError: Can't find variable: URI
simulator.js:1572
```

Probably just need to include this library:
https://github.com/medialize/URI.js

**Comment by nicpottier** [comment]
PR welcome.

**Comment by cromulus** [comment]
Sweet! 

Don’t currently have the bandwidth, but will in July. 

Thinking just a simple Boolean feature flag set by superuser on orgs to enable webhooks. Sound good?

**Comment by nicpottier** [comment]
These aren't a thing anymore, closing.
