### ISSUE TITLE
Request to add UUID to Broadcast

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#932]
Currently, each message has a unique ID, which is an INT. Integers are great for internal representation, but once you start operating across multiple systems, they can get messy insofar as you may need to create a lookup table to uniquely identify a message across systems.

Currently, contacts, groups, campaigns, and flows have a UUID, which enables them to be easily coordinated with other systems. 

Could we potentially do the same with messages and broadcasts?

**Comment by nicpottier** [comment]
Messages have UUIDs now.

Broadcasts don't. Not necessarily opposed to them having UUIDs though note that they are becoming more transient in the world, only really being used to tie together a bunch of messages that went out together. (IE, they are now deleted after 90 days, though archived messages refer to them by id so you can group them that way)
