### ISSUE TITLE
Trigger flow action via query

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#953]
Related to https://github.com/rapidpro/rapidpro/issues/952 but possibly enabling even more would be the ability to trigger a flow for a set of contacts based on a query.

This would address a longstanding request / limitation on notifying a set of contacts say associated with a health clinic, which isn't really possible to model today due to limits on groups etc..

Would fall out pretty easily after implementing: https://github.com/rapidpro/rapidpro/issues/952

**Comment by ericnewcomer** [comment]
See https://github.com/nyaruka/floweditor/pull/703
