### ISSUE TITLE
First order setting of parameters to subflows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#959]
For more complicated flow systems it becomes useful to start using subflows as function calls of sorts, where you set some results on your current flow then call a subflow that expects those parameters to exist.

An example might be a flow that formats a particular string, lets say a blackjack hand represented as "10C 7S" and turns it into something prettier. 

This is certainly made easier in v5 due to being able to set a result directly in an action, but we can probably do even better.

We could figure out what results a child flow expects the parent to set (via inspection) and then add a tab to the "start subflow" action to let you set these according to your context. In the engine these would be regular "set_result" actions, but it would really make subflows way easier to reason about.

Another piece to think about would be the inverse.. making it easier to take what the child flow set and put it in the current context, but I think that's a less common case and can come later, big win is knowing which parameters need setting and making that easy to do.

Note: we have stalled on this in the past because we have treated this a strong contract which then creates crazy knock on effects when you change the child flow (IE, all parent flows would then be updating) I think perfect is the enemy of good on this one and we should start with something better and then see where we go from there.

**Comment by IanLawrence** [comment]
Is there any reason this is limited to subflows? Being able to pass multiple variables into a flow (like the ref=<something>)  would be very useful for us

**Comment by nicpottier** [comment]
Can you talk more about your use case? You can already pass in parameters to any flow you start via the API using the `extra` parameters (which turn into `@triggers.params` in the flow). Are you talking about manual starts?

**Comment by IanLawrence** [comment]
Here is what we are doing currently. I am sure its not the best way and its a bit manual:
User JoeBloggs starts the default flow called 'Sign Up'. Variables are saved against JoeBloggs. We then manually copy a 'Followers' template and rename it joebloggs (lower case). We then add a trigger with a referrer id of the joebloggs to start this joebloggs flow. This joebloggs flow updates the contact with the variables collected against JoeBloggs and then kicks off another flow (the main flow).  We then send a message to JoeBloggs saying that his followers can follow him at https://m.me/<botname>?ref=joebloggs

**Comment by nicpottier** [comment]
Well for one I think you should be able to get the referrer id, that should be part of the trigger. Not sure that really helps though. Without seeing your whole account and what you are trying to do hard for me to really brainstorm on what a better way to do this is though.

**Comment by IanLawrence** [comment]
Yes I understand. 
Basically what we want is to automate a process whereby a specific users flow results configures other flows for users.So something like 'create a new flow passing in these variables which we already collected from some user'

**Comment by nicpottier** [comment]
Ok, noted, but not likely something we would add, at least that is way way off in some distant land of feature creep that I hope to never reach. Authoring flows via the API will probably be our answer there.

**Comment by IanLawrence** [comment]
> Authoring flows via the API will probably be our answer there.
That would be just fine :) We could link it up with zapier and be away! Thanks for letting us know its not something you would add. We might depending on how annoying / time consuming it is for us to do manually as useage increases

**Comment by nicpottier** [comment]
Yep, yep. Just note that it is not only something we wouldn't add ourselves but probably something we would not accept a PR for. That kind of meta-meta programming is just not something we want in the platform.

**Comment by rowanseymour** [comment]
Associated goflow issue at https://github.com/nyaruka/goflow/issues/822

**Comment by rowanseymour** [comment]
PR to save and expose keys of parent results referenced in a flow as "parent_refs" on flows endpoint https://github.com/rapidpro/rapidpro/issues/1123

**Comment by ericnewcomer** [comment]
PR for the flow editor side: https://github.com/nyaruka/floweditor/pull/796
