### ISSUE TITLE
Catch flow start loops and interrupt

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#960]
We try to catch some kinds of foot-guns, such as starting a group of contacts in a flow and in that flow starting the same group of contacts, but we still have some others.

One I just saw was a campaign set up to fire on a particular date and the flow setting that date to `@(NOW())` as the first action in the flow. That causes the flow to be rescheduled and refired immediately which isn't great. 

Problem of course differentiation the things that are done on purpose from those that are done by mistake.

So some ideas:
 * Can we detect campaign starts that immediately reschedule the same campaign event for the same time? Problem here is what constitutes "same time". It is obviously going to drift a little bit as it takes some time to start a flow. So knowing what is mean to be vs what is a mistake seems difficult.
 * Can we track flow start loops for contacts? This would be more high level, but say if a contact has been started in a flow more than `n` times in the past five minutes, then fail? That would be a more generic solution, but again could be falsely triggered.

Any other ideas?

**Comment by rowanseymour** [comment]
We solved this for `start_session` actions in the engine, and decided the campaign scenario *could* be solved in a similar manner but isn't critical
