### ISSUE TITLE
Simulator: context explorer

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#961]
It would be nice to give the user a nicer way of knowing what is in the context. We've talked of having a basic "tree view" of the context available in the simulator that would let you see the value of everything in the context at your current step in the flow. This is fairly low hanging fruit for us so would be something neat to add.

**Comment by rowanseymour** [comment]
Time to start hashing out some details here...

**Mailroom/goflow**

Already in goflow you can ask for the context as a giant object and serialize that as JSON. Could either..

- Have an explicit endpoint to get the context. You pass it a session blob, it loads it, it returns the context blob that would be used for expression evaluation.
- Change the simulate endpoint to always include the context blob? It's typically "not that" big (see http://app.rapidpro.io/mr/docs/completion.txt)

**Editor**

- Does it require a wait? I think it does since we're trying to show the context _that would be used at a specific point in time_, and there's no other way to stop a run at a specific point in time... so maybe this is only something the user can view, when the simulator is waiting?
- How do users get to this thing? I've always imagined it as something that appears to the left of the simulator, but I've not really thought it thru
- What is it? A tree of expandable nodes? ➕➖? Is it searchable?

**Comment by ericnewcomer** [comment]
In my mind, this would be returned with each sprint, so ya, always returned and requires a wait. 

On the editor front, I'd like it to be an expandable tree with a box that lets you enter an expression to evaluate (do we have an endpoint for evaluating a single expression?)

**Comment by rowanseymour** [comment]
> do we have an endpoint for evaluating a single expression?

No but that would be fairly straightforward to add - you pass it a session blob and an expression. It loads the session, evaluates the expression and returns the result.

**Comment by nicpottier** [comment]
Being able to evaluate an expression would be extra credit (technically part of issue https://github.com/rapidpro/rapidpro/issues/962) but ya, these are related. But we may want to just bite off the explorer first and ship that then expand to the expression tester.

Otherwise agree with everything here (evaluated on waits etc..)

**Comment by rowanseymour** [comment]
Engine side is done and the context is now returned with any waiting simulator sessions ( see https://github.com/nyaruka/mailroom/pull/216)

One thing to note which I just thought of as I pressed merge is that the context blob doesn't include explicit defaults on non-leaf parts of the context. Maybe it's useful to show the user that `@contact` evaluates to name.. but less easy to show that `@results` evaluates to multi-line dict, and that other have implicit defaults in the form of giant stringified objects..

**Comment by nicpottier** [comment]
Hrmm, not sure where I land there. On one hand, explicit values are less fragile in general, on the other, we would really rather train people to say use `@results.foo` rather than `@results.foo.value`, so do feel the implicit values should be represented somehow. Can we have a `__default__` key?

**Comment by rowanseymour** [comment]
> would really rather train people to say use @results.foo rather than @results.foo.value

I personally always use the the latter cuz it's clearer what it means.. even I can't remember if the default is the value or the category.

**Comment by nicpottier** [comment]
If you are confused as to what it evaluates to, then all the more reason we should endeavor to include it in the context explorer no?

**Comment by rowanseymour** [comment]
I just don't get the aversion to users being more explicit.. for me a little bit more verbosity is worth extra readability and being absolutely sure of user intention. I'm not arguing against including defaults, just that this wouldn't be the reason for me.

**Comment by nicpottier** [comment]
Probably not super useful to argue whether full paths are preferences or not, totally fine for us to disagree on our preference there. But they are supported and since the point of a context explorer is to, well, let you see what the context it, seems to me they should be included.

**Comment by ericnewcomer** [comment]
I think we definitely want to show the default evaluation, ie, context explorer looking something like:

```
contact         Rowan Seymour
   first_name   Rowan
   name         Rowan Seymour
   ...
```

I'm not sure I fully understand the downside of letting them explore what we'd return at each node.

**Comment by rowanseymour** [comment]
I'm not averse to including defaults. Just need to think how you render things that have a default which a multi-line blob, or whether implicit defaults (e.g. `@trigger` warrant being in there too)

It certainly makes sense when the default is the only way to get a particular value - for example `@results` formatted as key/values on new lines.

**Comment by ericnewcomer** [comment]
Ya, for blobs, those keys/values would show up as children under `results`, so in that case, it wouldn't be providing any extra value in the explorer.  For those (anything that is a blob of its children), I'm not sure it makes sense.

**Comment by ericnewcomer** [comment]
https://github.com/nyaruka/floweditor/pull/783
