### ISSUE TITLE
Simulator: add init flows

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#963]
A common thing that comes up, especially when in complex systems is being able to simulate all parts of a flow due to a contact's state or the state of a parent flow.

Right now the ugly hack is to create the actions you need to set up your state so that in simulation your flow goes down the path you are testing and then disconnecting those before launching but that is a dirty hack and especially problematic for live systems.

One thought we've had on this front is to allow setting up an "initialization" flow for your simulation. This would be a flow like any other that you could build that would get run BEFORE you enter the current flow in simulation.

That would let you:
 * set attributes on the contact as you see fit (add URNs, languages, fields)
 * set parent attributes as you see fit (since this flow is run before you, its values would be in `@parent`)

The reason we like this is it follows the general paradigm that "everything is a flow" and uses tools that people are already familiar with.

Most complicated bit is probably the management of where these flows live and figuring out what limits to put on them etc.. (IE, can they have waits in them, webhooks etc.. my bias is yes, but its complicated)

**Comment by nicpottier** [comment]
Doesn't that already happen when looking at a flow with a specific language?

**Comment by nicpottier** [comment]
(if not maybe that needs its own issue)

**Comment by rowanseymour** [comment]
It appears not.. but I guess it *could* work like that. Maybe the simulator needs to say something at the start of the flow to explain what it's doing as it might get confusing if there are set_lang actions within the flow or the user is using an init-flow to set language.

**Comment by ericnewcomer** [comment]
Agree with @rowanseymour, I don't think we should conflate language editing and simulation language. Setting your Spanish language contact (using an init flow) and running a simulation in the default view (say in English), I would expect the language to be in Spanish.

That said, I feel init-flows is the far better option than just setting language in the simulator. There's a lot that can go into a test profile even for simple cases. We had talked at one point of showing these init flows differently in the UI. Then we could also maybe create default ones for them when they add a language.

**Comment by nicpottier** [comment]
Really? I feel if you are looking at the Spanish translations for a flow, then automatically changing the test contact to have a language of Spanish is the most obvious (and helpful) thing. It is no more arbitrary than us setting the default contact language in the first place.

No doubt having init flows lets you do far more but for the super common case of testing translations we don't want to force people to use that.

**Comment by ericnewcomer** [comment]
So what happens when they set an init flow? Is there a precedence? Does it always set the language first on the contact then run the init flow?

**Comment by nicpottier** [comment]
Seems to me it would be an attribute of the simulator contact, so would happen before init flows. My bad on language. I guess kinda the same as telephone number then?

**Comment by ericnewcomer** [comment]
Not wild about mixing the two, but okay proceeding with that. I'll open an issue on that over at nyaruka/floweditor.

Also, trying to think how these might dovetail with unit tests (saved from simulation runs) which I still really love as a feature. Guess that's getting ahead of myself.

To get us back on topic.. I think we are in agreement on init flows being a thing. Do we see those as distinct flow types? ie, can they only be used for simulation, so can't be used in triggers or subflows and get their own place in the ui?

**Comment by nicpottier** [comment]
Lots to discuss here still but I think we should do *something* along these lines for 5.4. Perhaps it is even allowing user to manually populate contact fields in a simulator tab but implementing that via an init flow? That could then let us introduce the full power of init flows later.

**Comment by rowanseymour** [comment]
TBH I do have some small lingering doubts about whether init flows strikes the right balance of covering usecases vs complexity of use.. simply because it seems 99% of use cases will be covered just by making the `contact` blob used by the simulator editable in easy some way. You can even imagine `_simulation` being another key in the definition like `_ui` so there's a super easy way to associate a certain simulator contact profile with a given flow - that works with exports/imports. And for the 1% who need to do something more complex.. well you can already create another flow that calls the flow you want to test.

So if there's anyway we can start to explore that sort of thing.. before committing to the idea of separate init flows in the database... that would get my vote.

**Comment by ericnewcomer** [comment]
To play a little bit more on @rowanseymour's point, one bit, and perhaps its only an advanced concern, is simulating a flow that operates as a subflow only (relying on @parent.results). Some sort of profile with a masaged context is interesting. I suppose you could have a separate init flow that created results without interaction, but maybe we take a stab toward context exploration first. I could maybe see maybe editing / snapshotting the context to be another way to approach this.

**Comment by nicpottier** [comment]
Do not question the *EVERYTHING*IS*A*FLOW* dogma! We found it on buried tablets and it is the golden word from our ancestors!

But yes, totally agree with should make that decision with eyes wide open. Though you /can/ test a flow by creating a fake parent, it is pretty awkward because you can't see the child flow steps etc, during simulation, you are just interacting with it. Maybe that's good enough though.

One possible argument towards init flows is that it is probably less work. IE, we already have a UI that users are familiar with on how to edit a contact, add it to groups, add URNs, etc.. We would have to build a UI to do that if we went down the path of first order simulator contacts while that could be optional if we just punted and said there were special types of flows. (then you just have a drop down of "init flows" in simulation and that's the only UI that needs to be built)

I guess the answers here partly depend on:
 1. what class of user generally needs custom simulator contacts
 2. could they make the leap to init flows, or will they need an "edit simulator contact" UI?
 3. how often do user need help editing subflows that operate on parent vars?
 4. can they make the same leap?

Usecase 3) is super awkward right now sadly, which is a shame because subflows are by far the best way to organize a big system.

**Comment by nicpottier** [comment]
>  I suppose you could have a separate init flow that created results without interaction

I think that's the primary argument for int flows actually, in that it addresses both the test contact case and this one. Two birds, one stone etc..

Other approaches require two separate solutions.

**Comment by ericnewcomer** [comment]
To me the biggest argument for init flows is it solves scenarios we aren't thinking about. That, and, dogfooding flows for other uses means we get those gains every time flows themselves improve. To be clear, I'm very much in the init flow camp, but I'm trying to consider the cost/benefit of this as an alternative.

**Comment by rowanseymour** [comment]
(I also feel like someone needs to play devil's advocate here so if you wanna start arguing against init flows at any point i'm happy to take over arguing for them!)

So my intuition about _what users really want™_:

 1. Users want to test sessions as complete things whether that's a single flow or more
 2. Users building complex flow hierarchies are already testing those hierarchies together, i.e. I don't think they think in terms of unit testing a subflow (tho maybe they should!)
 3. Sessions start with a clean slate regarding results... but they start with contact state.. and that's the thing that users really need to be able to edit.

**Comment by nicpottier** [comment]
Wait all I have to do is disagree with you to have you agree with me? :)

I'd say 2) was super annoying when building Blackjack, to the point that I used my leet flow skills to test on results being not present and populated them manually to get around it. You really need to be able to see the flow you are in to understand what is going on and it gets really tiring testing a subflow that takes 4 or 5 interactions to get to from the parent, the test cycle is just terrible.

@chris-erickson @putorti You guys maintain some of the more complicated flows out there. What are your thoughts here?

**Comment by ericnewcomer** [comment]
I would echo the concerns with 2 above. I did the same thing with defaults to set some data to test with as I built out my functional subflows. This one feels a bit like our discussion a ways back of having more clearly defined parameters to subflows, treating that more like functions (which you could see changing the approach for testing this quite a bit). I still feel initializing a simulation run with a flow is going to be necessary since that offers flexibility we may need anyways (ie, it may need to call a webhook or who knows..)

**Comment by putorti** [comment]
I can't say I understand everything here, but I'll say by necessity, I already need a flow that runs on every single trigger we have, in order to handle things like the SMS compliance message, new user field and group initialization, pairing new non-SMS accounts for existing SMS users, etc. I probably suggested _that_ as a feature at some point (have all triggers start with an init flow). So for my purposes, I already have a flow today that I would pick for simulator runs.

Having a setting to run it first on simulator, would more accurately simulate how Resistbot works. However, I can simply ignore what simulator runs first and type the trigger. So, for me personally, this doesn't solve a big problem, I also only run an English bot.

**Comment by rowanseymour** [comment]
I guess I need to clarify what I'm arguing against/for here. When we say init-flows, are we talking a custom UI for editing contact fields and parent results, which saves a special init-flow in the background? And then only advanced users are ever going touch that flow themselves?

Or if we don't have that special UI.. then it's just a drop down on the simulator right? I'm not even sure it makes sense to define a new class of flows. Seems more straightforward to just let users pick any flow.

The latter option is definitely tempting from a _we can implement that this afternoon_ approach.. tho I guess it still leaves me wondering if that's the best we can do for the 90% case which is probably just setting a language and a few field values.

**Comment by chris-erickson** [comment]
My perspective as a developer who can barely build a flow, is that _testing ideas_ is my biggest problem.  I'm glad to see that my current strategy of testing how to interact with a parent flow by creating two, and call the first with a keyword and have it call the second is not completely nutty.  I would really like a way to prepare the context for a flow in-simulator so I don't need to mess around with some of that stuff.

I've also long wondered how we could sort of unit test these things - my incomplete ideas included triggering a flow remotely, somehow mocking out URLs for endpoints, those endpoints return faked data, then assert that the result somehow makes sense (URL A called, then B with some dependent data, then user contact state = X).  Maybe this allows that to be easier, by actually preparing the flow context when it's a "unit test" with urls or whatever.  Kind of thinking outlaid, but I think what Rowan has just proposed seems to be a decent bit of value for me right off.

My knowledge gaps could just as easily be the bigger problem, though.

**Comment by ericnewcomer** [comment]
I don't think it's a terrible user experience to select a flow to "prep" the session. It may be cumbersome to have to go to another flow to edit that flow, but you could see some simple curation of common states being reused.

That said, it doesn't get at the heart of what @chris-erickson is saying here either -- that sounds closer to context editing/snapshotting mentioned a little further up. That sounds quite complex though and I'd have a hard time saying that's where we should start here. It definitely more closely aligns with unit testing which is another ball of incredibly valuable wax.

Also, as an aside, language for the contact in simulation is currently based on the language being shown in the editor.

**Comment by nicpottier** [comment]
Note that setting language isn't something being addressed here, that has already been addressed  based on the language you are viewing. (that was https://github.com/nyaruka/floweditor/issues/635)

This is addressing contact fields / urns and parent values.

**Comment by ericnewcomer** [comment]
So @putorti you don't find yourself editing a subflow that relies on some things being present outside of your master initialization flow? With resist's call stack, I assumed there were lots of little functional flows that would benefit from having some parent results set for them when testing. Not actually running that flow, but prepping the state of simulation with some non-interactive results, fields, etc normally coming from somewhere in the middle of that call stack.

**Comment by nicpottier** [comment]
Just to be clear this issue is about setting up the context and contact for use during simulations. 

Unit testing can be talked about here: https://github.com/rapidpro/rapidpro/issues/1090

**Comment by chris-erickson** [comment]
My guess is that preloading some context would really tighten the feedback loop of testing out a flow, and could lead to more "one-thing-well" sort of structuring.  Would be cool if you could somehow preserve "sample" data in the Sim so you could set up multiple scenarios that would be reusable by other people ie.  "user without state districts" or "has no address".  Just thinking out loud.

**Comment by putorti** [comment]
@ericnewcomer Now that I think about it, the limitations of simulator are why I don't use it often, I find myself testing in Telegram most of the time and then exporting flow runs to the session explainer to find bugs. My workflow involves Telegram, a browser tab for my log, and tabs for flows. We built a 'test mode' very early on so we could use live channels but wouldn't actually send letters to Congress or do anything that would mess up production data.

As for testing small function-style child flows, I would just test their parents, or use a trigger. I've been using RapidPro so much for so long that I probably have just adapted to what's missing. If you guys want more general usability information on testing/simulator, Lisa is another good person to ask off this thread.

**Comment by nicpottier** [comment]
Right, so that's some interesting insight. In that because of all the hooks and you guys generating emails / faxes you need a contact to be marked as a "test" contact via a particular field. And being able to easily set that before simulation would let you use the simulator more as I gather it.

**Comment by nicpottier** [comment]
After seeing some brand new users use the platform a bit more I think the priority may be to make an expression tester / console more than doing this. IE: https://github.com/rapidpro/rapidpro/issues/962

After that I think a context explorer would probably be next:
  https://github.com/rapidpro/rapidpro/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+simulator

And only then do I think doing init flows would make sense. Going to shuffle things around for 5.4 accordingly.

**Comment by nicpottier** [comment]
(reversed the ordering, actually think context explorer would be the biggest win for the most users)

**Comment by nicpottier** [comment]
Rereading all this now I think realistically expression tester does make sense as the next highest value item, then I think init flows. If we find init flows are too confusing for people we should try to work on that UI some more but in the worst case we can circle back and do something contact specific.
