### ISSUE TITLE
Allow translation of subject and body in email action

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#971]
- [x] https://github.com/nyaruka/goflow/issues/707
- [x] https://github.com/nyaruka/floweditor/issues/638

**Comment by ericnewcomer** [comment]
One thought on this, if they are sending the email to the contact it makes total sense, but I don't think I've ever seen that used that way. Usually the person getting the email is somebody else so using the language of the contact might not be desirable or be confusing.

**Comment by rowanseymour** [comment]
I think in that case the user could just not translate the action and we assume the base language of the flow matches what the user understands.

**Comment by nicpottier** [comment]
This was a customer request FWIW.

**Comment by nicpottier** [comment]
(and they were sending an email to the contact)

**Comment by ericnewcomer** [comment]
Sure sure, was just wanting to weigh in that while I've seen lots of email actions, I hadn't seen one to the active contact yet.

**Comment by ericnewcomer** [comment]
As a followup to this, was working with a customer today who wanted localizable emails but on further discussion, didn't fully understand the connection with the contact language active in the flow and and the language of the email sent. After explaining it to him, he used two email actions depending on the language of the two fixed recipients.

Once this is added in goflow it's super easy to add it to the editor, but of course needs to be done in that order. Adding this would have definitely confused the guy I just helped, but that's just one data point.

**Comment by ericnewcomer** [comment]
@nicpottier I believe the feature work is done end to end for this to list as a 5.2 feature
