### ISSUE TITLE
Cleanup CSS styles

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#973]
Our styles are a bit out of control, would be nice to revisit, perhaps with a fresh (CSS) slate to make sure our styles are consistent and proper on all our pages. Slight UI refresh along the way is probably overdue as well.

**Comment by nicpottier** [comment]
Current thinking is adopt a utility based framework like Tailwind CSS so we stop fighting boostrap everywhere. Overall look and feel will remain the same just be tightened up and be made more consistent. Adding for 5.4

**Comment by nicpottier** [comment]
We are going to retarget the site reskin for 6.0

**Comment by rowanseymour** [comment]
it happened!
