### ISSUE TITLE
Unable to select text on new engine post-it note

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#982]
If I try to select a bit of text on a post-it note in the new flow engine, it will instead drag the note. A single click and the keyboard is required in new engine to select text. Old flow editor has a more expected behavior where a click and drag on the edges only will move the note. Title bar off of the text would also be what I normally expect in GUIs.

**Comment by ericnewcomer** [comment]
Moved to here: https://github.com/nyaruka/floweditor/issues/655
