### ISSUE TITLE
Android app not connecting to local Rapid pro server

### ISSUE THREAD

**Issue by nathansiafa** [rapidpro/rapidpro#988]
I have downloaded and setup Rapid pro on my computer following instructions from this site: https://rapidpro.github.io/rapidpro/docs/development/
I also have the android app installed on my phone and I am now trying to configure it to work with the Rapid pro server on my computer, but it is not working...

I followed the doc by tapping 11 times to unlock advanced settings, and also enter my computer's IP, but nothing is working...
Also, I look at this thread(https://github.com/rapidpro/rapidpro/issues/214) hoping to find some solutions. @ericnewcomer suggested to ask such questions in the following groups:

1.https://groups.google.com/forum/#!forum/rapidpro
2.https://groups.google.com/forum/#!forum/rapidpro-dev 

I'm being told by google that those groups doesn't exists or I don't have permissions to view them. Can anyone please help me resolve this issue I'm having? Thanks in advance...........

**Comment by rowanseymour** [comment]
The https://groups.google.com/forum/#!forum/rapidpro-dev group is open to anyone, and that would be where this sort of question belongs.
