### ISSUE TITLE
Git pre/post commit hook scripts leave behind .commit file

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#989]
Looks like https://github.com/rapidpro/rapidpro/issues/938 introduced a new issue with the pre/post commit git hooks where they leave behind a `.commit` file. To reproduce:

 1. Commit something that will fail flake8, e.g. unused import
 2. After commit is rejected, correct the flake8 error
 3. Recommit

Result:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    .commit
```

You have to then `git add` that and `git commit --amend`

**Comment by dodobas** [comment]
hmm, the only way one could get that git status would be if `.commit` was actually added to the index/staging, probably by a `git add .` or something similar
