### ISSUE TITLE
Update mailroom and courier nginx configuration examples in documentation

### ISSUE THREAD

**Issue by cromulus** [rapidpro/rapidpro#996]
The nginx configs here:
http://rapidpro.github.io/rapidpro/docs/mailroom/

and here:
http://rapidpro.github.io/rapidpro/docs/courier/

Are in conflict with each other. For instance, a twilio IVR inbound url will look like:
https://example.com/mr/ivr/c/UUID/inbound

Depending on the order of your nginx config, you'll either send that to courier or mailroom.

Instead, the regex for the location should specify that we are pattern matching for the beginning of the location:
```
# all courier URLs go to courier
  location ^~ /c/ {
    proxy_set_header Host $http_host;
    proxy_pass http://courier_server;
    break;
  }
```
and 
```
# all Mailroom URLs go to Mailroom
location ^~ /mr/ {
  proxy_set_header Host $http_host;
  proxy_pass http://mailroom_server;
  break;
}
```

**Comment by nicpottier** [comment]
I think that's right, can you submit a PR?

**Comment by nicpottier** [comment]
This was updated, thanks!
