### ISSUE TITLE
Airtime Transfers in new engine

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/rapidpro#997]
Need to discuss future of TransferTo support in the new world. Current state of things:

* Goflow: airtime transfer support is untested https://github.com/nyaruka/goflow/issues/461
* Mailroom: no handling of airtime_transfer events so no creation of Airtime transfer db models
* Floweditor: no airtime transfer node support

**Comment by nicpottier** [comment]
I don't think there's any plans to remove support so 2 and 3 should be filed as bugs.

**Comment by rowanseymour** [comment]
I think tho we might need to discuss how we want to architect this. We've chatted about stuff like this but not yet committed ourselves to a particular direction for this any future functionality that leans on third party APIs.

There's a few different ways to approach this and it's worth thinking about whether there's a general model that would work for things like email, NLP, airtable etc.

1. TransferTo is just part of our flow spec. Goflow defines an airtime transfer action which is hardcoded to use the TransferTo API and its configuration is passed through the environment.
2. TransferTo is an _extension_ to the flow spec (what we've currently done). Goflow allows extensions and they can add actions and events etc tho their implementations still live in the Goflow repo. Extension configuration is passed via an extensions section in the environment.
3. TransferTo is a _provider_ for an airtime action. Goflow defines a generic airtime transfer action but it's up to the caller (mailroom) to configure a provider which contains the implementation. On the RP side, an org picks a single provider to be the thing that handles all their airtime flow actions.
4. TransferTo is a new type of _asset_ that can do transfers. Flows can contain airtime transfer actions but they need to reference a transferer asset. On the RP side, an org can add transferers like they add channels and reference as they please in flows. 

I like 3 because it avoids adding more external references to flow definitions which always make things like import/export more difficult, and it doesn't bind us to the TransferTo API forever. But it does limit users to one service per thing.. and maybe that's not going to work for other things like email and NLP.

**Comment by nicpottier** [comment]
I don't think 1. and 2. are approaches we would take for NLU, so maybe we can just disqualify those.

I think 4) seems the most flexible but does make the flow specs more fragile which I really think we should avoid if possible, even at the cost of flexibility.

I really really want it to be 3) but I don't think that is feasible for NLU, I think there will have to be hard references similiar to message templates for WhatsApp. Specifically you will need to say WHICH classifier you are using, so that's going to have to be a reference of some kind.

I think really what we want is 3) but for NLU that is ALSO going to require you to reference a classifier which is an asset. So goflow will use some interface that mailroom has which says, classify this using this classifier reference. And the classifier references will be represented in the flow definition and managed by RapidPro etc..

**Comment by rowanseymour** [comment]
> I don't think 1. and 2. are approaches we would take for NLU, so maybe we can just disqualify those.

Agree, I just mention those for complete-ness

> Specifically you will need to say WHICH classifier you are using, so that's going to have to be a reference of some kind.

Have we thought about how this would work from the user POV? You configure a classifier in a third party website. How do you get that into RP, and does the editor have access to things like the list of classifications and it sets those up as router categories automatically? Or do you just provide the name of the classifier and then add categories yourself? Maybe that's more flexible?

@ericnewcomer?

**Comment by nicpottier** [comment]
> Have we thought about how this would work from the user POV? You configure a classifier in a third party website. How do you get that into RP, and does the editor have access to things like the list of classifications and it sets those up as router categories automatically?

Hadn't thought through the categories side of things, but list of classifiers yes. I think NLU providers on the RapidPro side will need to sync the available classifiers periodically (or perhaps those are added manually by the user at the org level). Knowing possible categories sounds like another nice side-effect there.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/goflow/pull/778 and https://github.com/nyaruka/mailroom/pull/183
