### ISSUE TITLE
Triggers sometimes duplicated on Triggers page

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro#999]
Guessing this is related to a related model query without a unique clause.

<img width="657" alt="Screen Shot 2019-07-24 at 9 26 36 AM" src="https://user-images.githubusercontent.com/168067/61810924-363beb00-adf5-11e9-8207-3508a15deff4.png">

Org 13455 on TextIt is an example.

**Comment by rowanseymour** [comment]
Aren't those different? `helo` vs `hello` ?

Was wondering recently if we should allow those to be same trigger https://github.com/rapidpro/rapidpro/issues/979

**Comment by nicpottier** [comment]
Hah, so they are, was thrown off by that account having Arabic triggers as well which were only different with a tiny dot. Doh.

However, we do seem to be doing something goofy with new conversation triggers:
![Screen Shot 2019-07-24 at 2 06 07 PM](https://user-images.githubusercontent.com/168067/61828775-53d07b00-ae1c-11e9-8f8f-1994f4da6d61.png)

**Comment by nicpottier** [comment]
Oh, well NM, those are actually different channels with the same name.

I am the only bug!
